### ISSUE TITLE
Create a swimlane instead of a partition

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1003]
### Is your feature request related to a problem?

Yes, but no

### Describe the solution you'd like

When creating a partition and adding additional partitions, it becomes mentally challenging to understand what it's happening.

![image](https://user-images.githubusercontent.com/8182138/133726333-8d5ac9b9-60c6-43cf-835b-ba82063984d2.png)

When I select the swimlane (and I see there partition) it has a name (First partition) but when I change the name of the first partition's name, it changes the name. I understand what's happening but that's definitely not what I want.

### Describe alternatives you've considered
Instead of a partition, I would like to create actually a swimlane, which owns one or multiple partitions. 

When selecting a swimlane, i would like to add partitions to the swimlane. Both swimlane has a model name, and every partition it contains shall have a model name as well.

![image](https://user-images.githubusercontent.com/8182138/133726266-11193241-9645-458a-8232-407642a93ace.png)

**Comment by amolenaar** [comment]
I agree that "swimlane" would be a more descriptive, since that's how we tend to refer to what in UML is called an ActivityPartition.

I'm pretty sure the partitions should be relabeled as swimlanes. You create an Activity and add Swimlanes to it (like in a swimming pool). Not as depicted in the second image.

**Comment by sz332** [comment]
UML Spec 2.5.1 page 408 

An ActivityPartition is notated with two, usually parallel lines, either horizontal or vertical, and a name labeling the 
partition in a box at one end. Any ActivityNodes and ActivityEdges placed between these lines are considered to be 
contained within the partition. This notation for an ActivityPartition is colloquially known as a **swimlane**, as shown in
Figure 15.66(a). 

I just checked the metamodel (page 406) and I see why it is implemented like the current way, but will check how other modeling tools do that on metamodel level.

**Comment by sz332** [comment]
![image](https://user-images.githubusercontent.com/8182138/133819409-c38c4a17-cd9d-4803-bbff-2c861e534ceb.png)

**Comment by sz332** [comment]
The way magicdraw does is that for each Activity Partition, there is a model element. On the diagram, there is a graphical element, which does not have a name (only an id) and some properties.

![image](https://user-images.githubusercontent.com/8182138/133819819-b27c5f4a-e536-48ab-9b10-d91880fb6839.png)

**Comment by sz332** [comment]
[swimlane.zip](https://github.com/gaphor/gaphor/files/7186972/swimlane.zip)

**Comment by amolenaar** [comment]
@sz332 Can you have a look at #1013? I think it addresses this issue.

**Comment by sz332** [comment]
@amolenaar sure, i am trying it out

**Comment by sz332** [comment]
@amolenaar added a comment to the pull request. Was it the correct place for it?

**Comment by amolenaar** [comment]
@sz332 Thanks! Much appreciated 🙏

**Comment by danyeaw** [comment]
Closed by #1013. Thanks @sz332 for the suggestion and @amolenaar for this fix!
