### ISSUE TITLE
Moving a new interaction model element causes scroll issues

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1004]
### Describe the bug

When moving an "interaction" model element on a diagram upwards, the scrollbar starts growing downward. 

### To Reproduce
1. Create a diagram
2. Add new interaction
3. Select interaction
4. Start moving it downwards
5. Start moving it upwards
6. Check scrollbar

### Expected behavior

It should be possible to move the selected component upwards thus removing the space and the scrollbar.

### Screenshots
![image](https://user-images.githubusercontent.com/8182138/133726931-62b38976-cae2-4202-bb38-712a447b6702.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.5.1

**Comment by amolenaar** [comment]
This is an effect of auto-scrolling, implemented recently. I'll dive into this. Basically it makes no sense to scroll the window if there's only one item on the canvas.

**Comment by amolenaar** [comment]
I did some testing. I can not reproduce this precise behavior. I found that the scroll(bar) behavior is a bit flaky though. I fixed in in Gaphas 3.1.9.

**Comment by sz332** [comment]
https://user-images.githubusercontent.com/8182138/134763166-5179bc0f-7ffb-432b-acd7-ef73f508b680.mp4

@amolenaar I added a video, reproducing the issue after pulling the latest code.

**Comment by amolenaar** [comment]
Thanks!

This has to do with the "infinite" canvas in Gaphor. It gets even weirder when you move the item upwards and then close and reopen the diagram. The canvas will be located at it's origin (0, 0). When you move towards the model element the scroll bars het bigger -> your canvas get smaller. 

I'll figure out something to improve the UX.

Thanks again for helping out. You already got a special mention in the 2.6 release blog at https://gaphor.org 👏.

**Comment by sz332** [comment]
> Thanks again for helping out. You already got a special mention in the 2.6 release blog at https://gaphor.org 👏.

@amolenaar Wow, thank you so much! 🙏

Do you think we should write down the requirements / test cases for the infinite canvas so that it might be checked against it?

**Comment by amolenaar** [comment]
Solved by gaphor/gaphas#343.
