### ISSUE TITLE
Automatically add execution specification when adding a message

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1005]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

When drawing a sequence diagram, and adding a message from one lifeline to another, I would like to have an execution specification automatically added to the selected lifeline.

**Comment by amolenaar** [comment]
This is a tricky one, since lifeline items also act as object nodes (for collaboration diagrams). That seemed logical at the time, because both representations are backed by the same model element.

**Comment by amolenaar** [comment]
I'd like to close this ticket, because of the double usage of lifeline elements in both Sequence and Collaboration diagrams.
