### ISSUE TITLE
Adding a new message shall be horizontal

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1006]
### Describe the solution you'd like

When drawing a sequence diagram, the default behavior shall be when a new message is drawn from a lifeline to another is that the line shall be horizontal, with the same y coordinate where I started to draw the line.

**Comment by amolenaar** [comment]
Yes! This is on my wish list for a while, although I did not bother creating a ticket.

Thanks for bringing it up!

**Comment by amolenaar** [comment]
@sz332 I think this issue as been resolved in Gaphor 2.7, right?

**Comment by sz332** [comment]
@amolenaar tested, works as expected, great work, thank you! The issue can be closed.

**Comment by amolenaar** [comment]
@sz332 Thanks 😀 I'm pretty happy with how it turned out.
