### ISSUE TITLE
Moving a message during drawing a sequence diagram

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1007]
### Describe the solution you'd like

Moving a message from one lifeline to another is very painful. There should be a simple mode for selecting the line and moving it upwards or downwards.

**Comment by amolenaar** [comment]
Can you elaborate?

I suspect to mean that, if you want to move a message up or down, you have to grab one side of the handle, move it and repeat for the second handle.

Related to #1006.

**Comment by sz332** [comment]
A standard action in case of sequence diagram when you want to move the line representing the message up or down. Most modeling tool do it the following way: you select the line, you press the button, start dragging up or down, which moves both endpoints of the line up or down, with the same y coordinate, so you don't need to move one and, and then the other.
