### ISSUE TITLE
Interaction is not removed after deleting elements from the diagram

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1008]
### Describe the bug

Interaction is not removed after deleting all the elements from the diagram.

### To Reproduce

1. Create a diagram
2. Add a lifeline
3. Remove lifeline
4. Interaction remains in model
5. Select interaction
6. Delete is not working

### Expected behavior

Either interaction shall be removed when all of it's parts are removed from the diagram, or there should be a way to delete model elements from the model.

### Screenshots

![image](https://user-images.githubusercontent.com/8182138/133727956-61a682c7-587a-4814-95c0-b249e284b718.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.5.1

**Comment by amolenaar** [comment]
Given the interaction is created automatically, it should also be removed automatically when it's:
* not displayed in any diagram
* has no owned elements
