### ISSUE TITLE
Context menu support

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1011]
### Describe the solution you'd like

In order to support quick modeling we shall minimize the mouse movements of the user. Currently for example to add a new object flow between two actions requires to go to the menu, select the object flow, select the items, etc. Instead of this it would be nice to have a floating menu item displayed besides the element with the possible actions. 

MagicDraw does it this way:

![image](https://user-images.githubusercontent.com/8182138/133879910-1058fe98-faed-4ac4-9b16-0f291eae2538.png)

Visual Paradigm does it this way:

![image](https://user-images.githubusercontent.com/8182138/133879937-d583d4d1-5388-42cb-a86e-b531dc628cfe.png)

**Comment by danyeaw** [comment]
MagicDraw does a lot of things and there are many ways to create objects. We have keyboard shortcuts to reduce clicking around. Do we really need a toolbox and a context menu?

**Comment by amolenaar** [comment]
> We have keyboard shortcuts to reduce clicking around. Do we really need a toolbox and a context menu?

I think we should keep it simple, for both users and developers. Keyboard shortcuts will do the trick, IMHO.
