### ISSUE TITLE
Add new action: pusher and magnet to toolbar

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1012]
### Is your feature request related to a problem?

In case of working with a big diagram, making space is not always easy with selecting items, and moving them around.

### Describe the solution you'd like

MagicDraw has a very useful tool for this problem, called pusher/magnet. (Visual Paradigm calls this sweep/magnet). It works the following way:

Pusher (make space):

- User selects pusher from the toolbar
- User presses left mouse button and keeps it pressed, and
- Starts moving the mouse to the right
  - A vertical line is shown
  - Every element to the right of the vertical line are pushed to the right (farther from each other)
- Starts moving the mouse downwards
  - A horizontal line is shown
  - Every element below of the horizontal line are moved downwards (farther from each other)

Magnet (remove space):

- User selects magnet from the toolbar
- User presses left mouse button and keeps it pressed, and
- Starts moving the mouse to the left
  - A vertical line is shown
  - Every element to the right of the vertical line are pushed to the left (closer to each other)
- Starts moving the mouse upwards
  - A horizontal line is shown
  - Every element below of the horizontal line are moved upwards (closer to each other)

**Comment by sz332** [comment]
https://user-images.githubusercontent.com/8182138/135477321-bc31a1c6-d321-48ad-8c09-5b5e3dfe50c0.mp4

**Comment by danyeaw** [comment]
Maybe you could combine it if you always made right to left and down to up close space (magnet), and the opposite open space (push). I am not sure how intuitive that would be though since I have only played with them as separate tools, but might be worth a try to play with.

**Comment by danyeaw** [comment]
Closed by #1208 which includes pusher and magnet support :+1:
