### ISSUE TITLE
Can not run 

### ISSUE THREAD

**Issue by ilikui** [gaphor/gaphor#1019]
### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor:

### Additional information
![屏幕截图 2021-09-21 204139](https://user-images.githubusercontent.com/11962397/134172276-e672996d-e808-45f0-babb-86632c2d25e5.png)

When I download and  install this software,and it is the issure.
![图片](https://user-images.githubusercontent.com/11962397/134172512-9f9d6239-b6f5-41c7-84e6-59f62531aeff.png)

**Comment by amolenaar** [comment]
Is this the same startup problem as #1001?

**Comment by danyeaw** [comment]
@ilikui This issue doesn't have enough information to help us troubleshoot, since you submitted a screenshot without the full traceback. It is also likely a duplicate as @amolenaar pointed out above.
