### ISSUE TITLE
Hungarian not showing

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1024]
### Describe the bug
Hungarian translations on [Weblate](https://hosted.weblate.org/projects/gaphor/gaphor/) are at 100%; however, Hungarian is not shown in the Gaphor GUI.

### To Reproduce
1. Download Gaphor Flatpak from [Flathub.org](https://flathub.org/apps/details/org.gaphor.Gaphor) using Linux Mint's Software Manager.
2. Open Gaphor.
3. Gaphor GUI is in English, not Hungarian.
4. See screenshot.

### Expected behavior
The Gaphor GUI should be in Hungarian, not English.

### Screenshot
![kép](https://user-images.githubusercontent.com/17465872/134587879-c118ea6d-c8cf-4676-a683-66ed1c31128a.png)
Image shows Gaphor (incorrectly in English) with the follow 2 programs (correctly in Hungarian): [Video Downloader](https://flathub.org/apps/details/com.github.unrud.VideoDownloader) and [Video Trimmer](https://flathub.org/apps/details/org.gnome.gitlab.YaLTeR.VideoTrimmer).

### OS
- [X] [Linux Mint](https://linuxmint.com/) [20.2 Cinnamon](https://linuxmint.com/rel_uma_cinnamon.php)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.0

### Additional information
https://github.com/gaphor/gaphor/issues/943

Thank you

**Comment by danyeaw** [comment]
@milotype are you getting Croatian to show up?

**Comment by ovari** [comment]
Croatian doesn't work here either. Please see image below with Video Trimmer which is in Croatian.

![image](https://user-images.githubusercontent.com/17465872/134604571-140a8f6a-6e19-432c-98cb-5df60b957c8e.png)

**Comment by milotype** [comment]
> @milotype are you getting Croatian to show up?

Sorry, I can’t test ...

**Comment by amolenaar** [comment]
I think I experience the same for Dutch. Invoking `LANG=nl_NL gaphor` still shows everything in English.

**Comment by danyeaw** [comment]
Closed by #1025.

**Comment by ovari** [comment]
Thank you for fixing @amolenaar

@danyeaw has the About dialog been fix for Linux Mint too? Cf. [Fixed closing of about dialog](https://github.com/gaphor/gaphor/commit/eccffa11894c5b5bd308334646a04ef19e6c5825)

Thank you once again

**Comment by danyeaw** [comment]
@ovari It should work, if not please submit a new issue 😀
