### ISSUE TITLE
Hungarian not showing followup

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1027]
Thank you @danyeaw and @amolenaar for the 2.6.1 release.

Here is the Gaphor localisation followup.

### Describe the bug
Hungarian translations on Weblate are at 100%; however, Hungarian is not completely shown in the Gaphor GUI.

### To Reproduce
https://github.com/gaphor/gaphor/issues/1024

### Expected behavior
Not all strings are showing in Hungarian.

### Screenshots
1. `Open`
2. Popups: `New diagram`, `Show/Hide Editor`, `Undo`, `Redo`, `Zoom In`, `Zoom 100%`, `Zoom Out`, 
3. `No item selected` and the rest of the right panel
![kép](https://user-images.githubusercontent.com/17465872/134790937-4912186c-7e53-4c7c-a243-8f8d9b24a969.png)

1. `Preferences` (`Preferences` button has no popup, should the popup be added to the `Preferences` button)
2. `Preferences` and the rest of the right panel
![kép](https://user-images.githubusercontent.com/17465872/134791025-c2e4d928-8d43-4218-b95b-c7404cb2153d.png)

1. When adding a `Class` or `Package`, the default name is `NewClass` or `NewPackage`, respectively. Can the default name please be translatable? And the strings be added to [Weblate](https://hosted.weblate.org/projects/gaphor/gaphor/)
2. The right panel
![kép](https://user-images.githubusercontent.com/17465872/134791219-6cfe63f1-41bc-4ac6-808c-0c830a9fded3.png)

1. `Gapor is the simple modeling tool written in Python`
2. `Fork me on GitHub`
3. `Copyright © 2001-2021 Arjan J. Molenaar and Dan Yeaw`
4. The About dialog heading shows `Gaphor névjegye` when it should show `A Gaphor névjegye`
![kép](https://user-images.githubusercontent.com/17465872/134791251-bab00e23-e4f0-4e40-8117-c6a0c524c13c.png)

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.1

### Additional information
https://github.com/gaphor/gaphor/issues/943

**Comment by ovari** [comment]
1. `All Gaphor Models`
![kép](https://user-images.githubusercontent.com/17465872/134791419-38b892bc-9bff-4bb8-96cc-be99d777e3df.png)

**Comment by ovari** [comment]
1. `Console` in the menu
2. `Gaphor Console` in the window title
3. Console text
```
Gaphor Interactive Python Console
3.9.7 (default, Nov 10 2011, 15:00:00) 
[GCC 11.2.0]
Type "help" for more information.
```
![kép](https://user-images.githubusercontent.com/17465872/134791483-584a6920-c0a0-4cb1-b949-f1b125f2d706.png)

**Comment by amolenaar** [comment]
Thanks.
It looks like nothing from the UI files is translated (`profil: UML` is defined from the Gaphor Python code).

The catch is that the gettext module in python is actually a pure-Python module. Hence, Gtk.Builder and friends are not aware of ouw language setting (they need to know the should fetch the messages from the `gaphor` domain in our own locale directory.

I'll look into this.

**Comment by ovari** [comment]
Thanks.

Can you also look at adding default names like `NewClass` and `NewPackage` to Weblate?

Thank you once again.

**Comment by amolenaar** [comment]
Found it: https://docs.python.org/3/library/locale.html#access-to-message-catalogs.

If we use the `locale` library, instead of `gettext` we get access to the C gettext library (libintl). I learned something new :D.

I'll check if we still miss some text for translation. (No guaratees: in Dutch we tend to stick with English terms every now and then ;) )

**Comment by ovari** [comment]
> I'll check if we still miss some text for translation. (No guaratees: in Dutch we tend to stick with English terms every now and then ;) )

Having the option to enable translation of all the strings would be beneficial for an improved user experience. If in Dutch you want to stick with the English terms you can; and, if in another language you want to localise the strings you can. It would also be helpful in languages that do not use the Latin script.

What do you think?

Thank you once again.

**Comment by amolenaar** [comment]
@ovari there is a fallback on English for all translations, so we should be fine there.

I create #1031, which will fix translations for good :smiley:

**Comment by ovari** [comment]
Thank you @amolenaar.

**Comment by ovari** [comment]
Can you please advise when the version with this patch will be published on [Flathub](https://flathub.org/apps/details/org.gaphor.Gaphor) to enable testing? Thank you

**Comment by danyeaw** [comment]
@ovari We may be able to release a new version this weekend
