### ISSUE TITLE
New icons are less readable in dark mode

### ISSUE THREAD

**Issue by mskorkowski** [gaphor/gaphor#1028]
### Describe the bug
I'm using gnome with dark mode (Adwaita dark). Old white icons where much more readable.

### To Reproduce
1. Switch to gnome dark theme for applications
2. Open Gaphor

### Expected behavior

Icons should have white lines in dark mode instead of black

### Screenshots

![Screenshot from 2021-09-26 06-58-02](https://user-images.githubusercontent.com/90662755/134794327-43d75a96-537a-49fb-b634-120d7ae7e645.png)

### OS
- [x] Linux Fedora 34 via flathub
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.1

**Comment by amolenaar** [comment]
Crap! I simplified the creation of icons for Gaphor 2.6.1, but I did not check dark mode.

**Comment by danyeaw** [comment]
Thanks @mskorkowski for the bug report! Thanks to @amolenaar this will be fixed in the next release soon. :+1:
