### ISSUE TITLE
Emblem missing in About dialog

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1043]
### Describe the bug
Gaphor emblem missing in `About` dialog

### To Reproduce
In English locale, open Gaphor's About dialog.

### Expected behavior
Gaphor emblem should show in `About` dialog

### Screenshots
![image](https://user-images.githubusercontent.com/17465872/135731646-743a53be-d711-407c-a601-dbfcc03fc1e2.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2 from Flathub.org

Thank you

**Comment by danyeaw** [comment]
Thanks @ovari for the report. Closed by #1042.
