### ISSUE TITLE
Localize all occurrences of `All Gaphor Models`

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1044]
### Describe the bug
`Save As` dialog `All Gaphor Models` drop-down not localized.

### To Reproduce
1. Menu with 3 horizontal lines
2. Save As
3. Dialog box drop-down has English string (red box draw in image)

### Expected behavior
`All Gaphor Models` drop-down should be localized like in the `Open` dialog box.

### Screenshots
![Save As Dialog](https://user-images.githubusercontent.com/17465872/135731932-7e21863d-11fb-485c-89dd-c36a32c38bf0.png)

![Open Dialog](https://user-images.githubusercontent.com/17465872/135732070-fa62d057-c77d-47f7-9203-73bae03e96e8.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2

### Additional information
https://github.com/gaphor/gaphor/issues/1027#issuecomment-927217878

Thank you

**Comment by amolenaar** [comment]
Nice catch! I fixed it.

**Comment by danyeaw** [comment]
@all-contributors please add @ovari for bug
