### ISSUE TITLE
Enable the default names to be localized, like `Swimlanes`

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1045]
### Describe the bug
The default name `Swimlane One` is localized. Please allow the default names for all other object, activities, actions, etc. to be localized, for example:
1. Activity
2. NewAction
3. NewActivityFinalNode
4. NewDecisionNode
5. NewFlowFinalNode
6. NewInitialNode
7. NewArtifact
8. NewClass
9. NewComponent
10. NewDataType
11. NewEnumeration
12. NewInteraction
13. NewInterface
14. NewNode
15. NewPackage
16. NewPrimitiveType

Above the names of some items there are other items that should be translated, for example:
1. interface
2. dataType
3. enumeration
4. primitive

### To Reproduce
1. Add component, object, etc on the canvas.
2. The names are incorrectly in English. The only correct object is `Swimlanes`.

### Expected behavior
It would be good if there was consistency by having all items can be localized. It would also be helpful for languages which do not use the latin script.

### Screenshots
![kép](https://user-images.githubusercontent.com/17465872/135734493-6cdbf0af-6620-4d27-8fe1-24b6acf0b499.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2

Thank you

**Comment by amolenaar** [comment]
I created #1053. I already have all stereotypes translatable. However, the new elements names are a bit more tricky. Currently they are constructed from the class name of the underlaying model element. Obviously this does not translate well ;).

**Comment by amolenaar** [comment]
I only just noticed @danyeaw opened #1049. I'll rebase my changes on top of Dan's work.
