### ISSUE TITLE
Column heading `Name` not localized for `Swimlanes`

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1046]
### Describe the bug
Column heading `Name` not localized for `Swimlanes`

### To Reproduce
1. Hungarian locale
2. Add a Swimlane
3. Column heading `Name` not localized
4. See image (red rectangle around English string)

### Expected behavior
Column heading `Name` should be localized for `Swimlanes`

### Screenshots
![Swimlanes Name in Hungarian](https://user-images.githubusercontent.com/17465872/135734627-03c1e15a-44fe-4a90-b56e-44758d77c874.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2

Thank you

**Comment by danyeaw** [comment]
Closed by #1049.

**Comment by amolenaar** [comment]
Fixed by #1049.

@ovari Thanks a lot for helping out with translations. I know how annoying it is to work with partially translated applications (but I'm lazy and switched to English for everything instead :see_no_evil: ).

BTW Have you considered [joining the chat](https://gaphor.org/discuss.html)?

**Comment by ovari** [comment]
> Thanks a lot for helping out with translations. I know how annoying it is to work with partially translated applications (but I'm lazy and switched to English for everything instead).

Thank you @danyeaw and @amolenaar for all your work in supporting complete translations. People whose native language is not English will be able to use your program more effectively.

> BTW Have you considered [joining the chat](https://gaphor.org/discuss.html)?

Don’t have Matrix or Gitter; however, do have [Jami](https://jami.net/).

Is there something you wanted to talk about?

Thank you once again.

**Comment by ovari** [comment]
Weblate for Hungarian is at 100%. Can you please look at the Weblate comments? Thank you
