### ISSUE TITLE
About dialog window title hu locale

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1047]
### Describe the bug
About dialog window title in Hungarian (magyar) locale should have `A ` at the beginning of the string.

### To Reproduce
1. Set system to hu (Hungarian - magyar) locale
2. Open About dialog
3. Dialog title should be changed from `Gaphor névjegye` to `A Gaphor névjegye`

### Expected behavior
In the hu (Hungarian - magyar) locale, the About dialog window title should be `A Gaphor névjegye`

### Screenshots
![Gaphor About dialog](https://user-images.githubusercontent.com/17465872/135735925-beec1754-a3f7-4ba1-b56c-74c4bd7d2d51.png)

![Firefox About dialog](https://user-images.githubusercontent.com/17465872/135735969-03e1c26b-3e52-49e3-99e3-27f14515ccef.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2

### Additional information
Hungarian locale

Thank you

**Comment by danyeaw** [comment]
Thanks @ovari, this should now be fixed! :tada:

**Comment by ovari** [comment]
Thank you

**Comment by amolenaar** [comment]
That's odd (the dialog on Linux does not have a title header).

The menu entry looks okay, right?

![image](https://user-images.githubusercontent.com/96249/137974978-15606caa-96c6-4639-95b5-aa3587b8ff79.png)

**Comment by amolenaar** [comment]
I had a look at video-trimmer (really nice app, btw :) ). I can not find any difference.

When I open the about dialog with the `LANG=hu_HU`, this is the window I get:

![image](https://user-images.githubusercontent.com/96249/140800487-a8526e94-9159-4d61-a382-d23c8cf0abcf.png)

It looks like the Mint theme is messing up the styling.
