### ISSUE TITLE
Consistent default names with spaces

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1048]
### Describe the bug
Inserting a Class on the canvas create an object with the name `NewClass`. Should a space be added so the default name of the object is `New Class`?

Inserting a Swimlane, the default name is `Swimlane One`, which has a space.

Can all default names please have spaces?

Having spaces would make translation easier as `Swimlane One`’s Hungarian translation is `1. sáv`, i.e. it also contains a `.`.

### Expected behavior
Consistent default names with spaces

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.2

Thank you

**Comment by danyeaw** [comment]
Closed by #1049.
