### ISSUE TITLE
Undo/redo Causes Namespace tree view to become out of sync

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#106]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Python errors when using the Undo keyboard shortcut and different GTK errors when hitting the undo button.

### Expected behavior
No undo errors and a correct Navigation (treeview)

### Minimal reproduction of the problem with instructions
Add a class to a diagram. Press Ctr+Z and you get the following error:
```
gaphor.ui.namespace ERROR Exception in <function NamespaceModel._on_element_delete at 0x7fc4ed913378>. Try to refresh the entire model
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/namespace.py", line 66, in catchall_wrapper
    func(*args, **kwargs)
  File "/home/dan/Projects/gaphor/gaphor/ui/namespace.py", line 254, in _on_element_delete
    path = self.path_from_element(element)
  File "/home/dan/Projects/gaphor/gaphor/ui/namespace.py", line 138, in path_from_element
    return self.path_from_element(ns) + (n.index(e),)
ValueError: <gaphor.UML.uml2.Class object at 0x7fc4ed8b6b00> is not in list
```
Use the Undo button in the toolbar and you get a different error:
```
(gaphor:10885): Gtk-CRITICAL **: 20:14:38.451: ../../../../gtk/gtktreeview.c:5573 (gtk_tree_view_bin_draw): assertion `has_next' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.
```
Also the Navigation highlights and unhighlights with mouse over, and shows too many elements:
![Screenshot from 2019-03-21 20-17-22](https://user-images.githubusercontent.com/10014976/54792902-8112df80-4c16-11e9-9e98-03a09f3dca7f.png)

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by amolenaar** [comment]
This issue already exists in Gaphor 0.17.2
