### ISSUE TITLE
Please see comments on Weblate

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1060]
### Describe the bug
Is/Are there a reason/reasons why some strings do not have a space/spaces ` `?

Should `call()` be translated? For example, in Hungarian it is `hívás()`

### Version
Version of Gaphor: 2.6.2

### Additional information
Please see Weblate comments.

Thank you

**Comment by amolenaar** [comment]
> Is/Are there a reason/reasons why some strings do not have a space/spaces ?

What do you mean?

> Should call() be translated? For example, in Hungarian it is hívás()

Yes!

**Comment by ovari** [comment]
> What do you mean?

![image](https://user-images.githubusercontent.com/17465872/136101376-efec155e-37ff-48e4-92c7-f4e7af5c5a2e.png)

Examples include:
* `New DecisionNode`
* `New FlowFinalNode`
* `New AcceptEventAction`

**Comment by ovari** [comment]
> What do you mean?

Are you able to view the comments on Weblate?

**Comment by danyeaw** [comment]
The comments about RAAML should reference the spec:
https://www.omg.org/spec/RAAML/1.0/Beta1/PDF

This is tough, I agree that AND is for example an AND Gate, but the spec just calls it AND. Should we stick to what the spec says exactly, or improve the translatability by deviating from the spec some?

**Comment by ovari** [comment]
The heading may be `AND`, but the description in the spec does say `AND gate`.

![image](https://user-images.githubusercontent.com/17465872/136128875-4ea6219a-a435-4b3b-a2c1-70f043eb16ff.png)

See no problem calling it `AND gate`; only improvements in translatability and for screen readers for vision impaired users.

**Comment by ovari** [comment]
If it is a `beta` spec, perhaps you can send an upstream request to call it an `AND gate`?

**Comment by danyeaw** [comment]
@ovari I did talk to one of the RAAML spec leads on Friday, thanks @blippost. I think we can go ahead and name things on the GUI to maximize translation while keeping the data model true to the spec. I'll take on updating the strings that you commented on in Weblate.
