### ISSUE TITLE
Changing description/name of Person when copied from existing Person seems to change name for both Person objects.

### ISSUE THREAD

**Issue by ambersariya** [gaphor/gaphor#1061]
### To Reproduce
Steps to reproduce the behaviour:
1. Change to "C4 Model" profile
2. Add Person, drag and drop from left pane
3. Double click and give the Person a name
4. Select person, Ctrl + C and Ctrl + V to add another person
5. Change name on newly added Person
6. Name on older person object changes as well.

### Expected behavior
Expect Person 1 to not have their name changed when Person 2 name is changed

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.4

**Comment by amolenaar** [comment]
Hi,

Welcome :)

Gaphor is a modeling tool. Copy/paste will copy the presentation element, not the underlaying model element. We already have an issue related to this: #791 . We can continue discussing it there.
