### ISSUE TITLE
Diagram specific menu items not shown

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#107]
When opening a diagram, the menu should be updated with diagram specific items, such as zoom and select-all. Also, the toolbar should be updated.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

No diagram specific actions are shown in menu and task bar.

**Comment by danyeaw** [comment]
Closed by #116 :+1:
