### ISSUE TITLE
Lines hide behind other model elements in a diagram

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1073]
### Describe the bug

Depending on the order on which lines and elements are added to a diagram, lines can become invisible if they hide behind some other element.

### To Reproduce
1. Create a line
2. Create a Class
3. Drag one line end, see it hide behind the class

### Expected behavior

Lines should be drawn on top of the elements.

### Screenshots

![image](https://user-images.githubusercontent.com/96249/136968940-7a993e87-d147-4406-b2fe-4ad7b15370d5.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.4

### Additional information

Reported by [@joshmikow on Matrix/Gitter](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$02bju60jACSypeC5mtV2xNA0HBkcbAccwnERaxH3HAk?via=matrix.org&via=gitter.im).

There could be two rules in play:
- an item (line or elements) should be drawn later than an element it is connected to (e.g. a dependency should draw after a Class item it's connected to).
- Any Line-like item (which we can identify, since it inherits from `gaphas.Line`) should be placed on top of any other element.

I'll try the second option first.

**Comment by danyeaw** [comment]
Closed by #1084. :shipit:
