### ISSUE TITLE
Association end properties are missing from editor pane

### ISSUE THREAD

**Issue by Mek101** [gaphor/gaphor#1075]
There's no obvious way to set the multiplicity in any association.

Graphor 2.6.4 from Flathub

**Comment by amolenaar** [comment]
Hi,

Multiplicity is set by editing the association end property in the editor on the right or by double clicking the association end directly. To set multiplicity, provide it after the name in square brackets, like this:
```
name[1..*]
``` 

![image](https://user-images.githubusercontent.com/96249/137592142-40bb8896-92be-4920-8386-968bf4e64e06.png)

I see that the editing option in the editor is missing!

![image](https://user-images.githubusercontent.com/96249/137592193-6f0af4c5-b1f0-446a-968f-a227fa6c9250.png)
