### ISSUE TITLE
Spaces (` `) to include in English source strings and more translations to add to Weblate

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1090]
### Describe the bug
1. Should some source English string have some spaces ` ` added?
2. Should some strings be translatable?

### To Reproduce
See image below with red added indicating strings which should be translated into Hungarian.

### Screenshots
![kép](https://user-images.githubusercontent.com/17465872/137869338-1921415c-0ead-4cd3-9dcf-b059344a21e0.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.6.5

### Additional information
Did you want a list of all the strings that still need translating as the image is not complete?

Thank you

**Comment by ovari** [comment]
> Please note that the order of `from Új modell` in Hungarian is `Új modellből`, i.e. the `ből` is `from`. In Hungarian `from` changes depending on the noun it attached itself to as the following all are from: `tól`, `től`, `ból`, `ből`, `ról`, `ről. Also, from is written at the _end_ in Hungarian, while in English from is written at the _start_. Thank you

Another option is to change `from New Model` to `source: New Model` then the Hungarian can be `forrás: Új modell`. Improvements in this en source string update include:
1. No need for the variations in the ending for languages like Hungarian; and
2. Should make it easier to translate into other languages.

What do you think?

Thank you

**Comment by amolenaar** [comment]
@ovari I think it's fair to translate `from New Model` to `forrás: Új modell`. The meaning is still the same, although it does not translate literally, which is not a problem IMHO. As you said: it avoids the problem with the Hungarian suffixes.

**Comment by amolenaar** [comment]
@ovari is any more action required or can we close this issue?

**Comment by ovari** [comment]
> @ovari is any more action required or can we close this issue?

@amolenaar waiting for the strings to be available to translate on Weblate. Do you know when they will arrive? Thank you

**Comment by ovari** [comment]
1. Could you please merge the Hungarian translations from Weblate as they should be complete?
2. Could not see `ordering` in Weblate (cf. point 3 in https://github.com/gaphor/gaphor/issues/1090#issuecomment-946473346). Has this been reworded?

Thank you

**Comment by ovari** [comment]
Thank for fixing. 

Weblate's Hungarian translation is complete again.

1. Should `upperBound` have a space ` `?

2. Can you do a global search for `fstring` to see if there are anymore instances that need fixing?

3. Can a 2.6.6 be created on Flathub so we can test again with the complete translations before 2.7.0 is released?

Thank you once again.
