### ISSUE TITLE
Wrong user data dir

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#110]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

Gaphor is using `GLib.get_user_data_dir()`, which is refering to `~/.local/share` by default (on MacOS at least). Since we place multiple files in the user data dir, it should be a Gaphor specific one, such as `~/.gaphor` or `~/.local/share/gaphor`.

According to the XDG spec, the files should be written in a config dir, `$XDG_CONFIG_HOME`, which would even be better.

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
Closed by #111.
