### ISSUE TITLE
Notify users of new versions

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1151]
### Is your feature request related to a problem?

Users on Windows and macOS are often not aware a new version is out. 

Linux users use Flatpak a lot, which already has an auto=update feature. AppImage users we probably want to notify.

### Describe the solution you'd like

Let Gaphor check for new versions every now and then. If one is found, notify the user and point them to the latest version.

### Describe alternatives you've considered

Provide Gaphor via the Windows app store?
Provide Gaphor via the Apple app store? (will probably be declined, since the UX is quite different from macOS native)

### Additional context

For Flatpak, this feature is not really needed. For PyPI and AppImage it may be needed, though.

Do we know if Gaphor runs in a Flatpak? Check for `'FLATPAK_ID': 'org.gaphor.Gaphor'`.

**Comment by danyeaw** [comment]
One additional option is we could package Gaphor for brew and choco.

**Comment by amolenaar** [comment]
If it can be done automatically...

**Comment by danyeaw** [comment]
Would we make this version check be part of the greeter, a popup that opens separately, part of the about dialog, or a separate option in the hamburger menu to check for a new version?

**Comment by amolenaar** [comment]
A banner in the greeter would be nice I suppose. At the top or bottom. A [Gtk.InforBar](https://developer.gnome.org/hig/patterns/feedback/info-bars.html) or Gtk.ActionBar.

I'm not sure to which extend we should provide extra permissions to the macOS or windows versions.

**Comment by amolenaar** [comment]
The brew version has been kept up to date for the past versions :+1: (wasn't me). Really nice. It's a seamless way for me to upgrade Gaphor on my macbook.

**Comment by amolenaar** [comment]
I'm closing this issue. We have this covered for macOS with Brew. Most environment require extra (network) permissions for this feature to work. A permission not strictly necessary for the functioning of Gaphor.
