### ISSUE TITLE
This file does not contain a valid Gaphor mode

### ISSUE THREAD

**Issue by LordSinSentido** [gaphor/gaphor#1152]
### Describe the bug
I saved a work for the school and when I wanted to open the file it showed me the error: "This file does not contain a valid Gaphor model" 

### To Reproduce
1. Save your Gaphor project
2. Close Gaphor
3. Try to open your saved file
4. You go it

### Expected behavior
That open the file, I need to present the diagrams 

### Screenshots
![Captura de pantalla de 2021-11-24 10-25-28](https://user-images.githubusercontent.com/57022857/143277017-1a27f7cf-11b0-441d-b6fd-bd1517cae258.png)

### OS
- [X] Linux (Fedora Linux 35)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.6.5

### Additional information
I attach the file in question:
[file.zip](https://github.com/gaphor/gaphor/files/7597259/file.zip)

**Comment by amolenaar** [comment]
Hi @LordSinSentido,

Thanks a lot for reporting this issue. When I open the model, I get the following exception on the console:

```
Traceback (most recent call last):
  File "/home/arjan/Development/gaphor/gaphor/transaction.py", line 151, in _transactional
    return func(*args, **kwargs)
  File "/home/arjan/Development/gaphor/gaphor/diagram/tools/connector.py", line 73, in connect
    connect(handle, sink.port)
  File "/home/arjan/Development/gaphor/gaphor/UML/interactions/interactionsconnect.py", line 212, in connect
    connect_lifelines(line, send, received)
  File "/home/arjan/Development/gaphor/gaphor/UML/interactions/interactionsconnect.py", line 98, in connect_lifelines
    order_lifeline_covered_by(received)
  File "/home/arjan/Development/gaphor/gaphor/UML/interactions/interactionsconnect.py", line 60, in order_lifeline_covered_by
    lifeline.subject.coveredBy.order(keys.get)
  File "/home/arjan/Development/gaphor/gaphor/core/modeling/collection.py", line 164, in order
    self.items.sort(key=key)
TypeError: '<' not supported between instances of 'NoneType' and 'float'
gaphor.storage.storage WARNING file b'/home/arjan/Downloads/file/modelos.gaphor' could not be loaded ('<' not supported between instances of 'NoneType' and 'float')
> /home/arjan/Development/gaphor/gaphor/core/modeling/collection.py(164)order()
-> self.items.sort(key=key)
```

**Comment by amolenaar** [comment]
I did some analysis on this issue. The issue occurs when messages (occurrences) are ordered on a life line. The occurrences and their order are determined by the _y_ position. However, 3 our of 4 occurrences are connected. Then, when ordering, one occurrence has no corresponding y coordinates, thus `None` is returned. Hence the error: float and None do not compare.

A fix seems quite simple, but it will require a new release. It's not an issue in the model itself.

BTW. Those are some really nice diagrams, @LordSinSentido! Really nice! :+1:

**Comment by amolenaar** [comment]
@LordSinSentido We're workring on a new release, so you can open your models again.

**Comment by danyeaw** [comment]
@all-contributors please add @LordSinSentido for bug

**Comment by amolenaar** [comment]
@LordSinSentido Gaphor 2.7 has been released. It contains a fix so you can open your model again :)

**Comment by LordSinSentido** [comment]
Thank you very much guys for fixing the error! I hope I haven't caused any inconvenience with my request, you solved it so quickly that I even feel bad if I took away part of your time giving importance to my problem. u.u

Either way, **I thank you again** for your support! :D

> @LordSinSentido Gaphor 2.7 has been released. It contains a fix so you can open your model again :)

**Comment by amolenaar** [comment]
Hi @LordSinSentido,

This issue needed a fix :wink:. We appreciate it very much that you reached out.

Happy modeling!
