### ISSUE TITLE
Add predefined viewpoints for the C4 model

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#1157]
### Is your feature request related to a problem?
A user opens Gaphor and changes profile to the C4 model.
The user now is unclear on how to proceed, on what to do.

### Describe the solution you'd like
Add the 4 predefined C4 viewpoints.
- Level 1: Context diagrams
- Level 2: Container diagrams 
- Level 3: Component diagrams
- Level 4: Code diagrams

So that the user can quickly get a grasp of C4 and have a starting point.

**Comment by amolenaar** [comment]
A similar issue has come up with SysML, where you want different layers defined in the starting image. We probably need something like templates to accommodate different modeling styles.

**Comment by vanillajonathan** [comment]
Yes, templates would be give a huge increase in usability by providing guidance and laying the foundation to guide proper usage of the modeling language,

**Comment by amolenaar** [comment]
I've been looking for examples. I think the create-project plugin of GNOME Builder is a nice example.

![image](https://user-images.githubusercontent.com/96249/144808702-86544884-aaba-4159-b0e6-47313c33969d.png)


* https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/src/plugins/create-project/gbp-create-project-template-icon.ui
* https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/src/plugins/create-project/themes/shared.css

**Comment by amolenaar** [comment]
... How are we dealing with templates? Will we define a fix numer of templates in Gaphor? Can we make it extensible by users, and if so, how?

**Comment by danyeaw** [comment]
Probably the simplest way to do that is we could publish gaphor models with some initial diagrams and views setup so that users just have to go and edit them. We could ship the models with gaphor, or make them available separate on our website. This wouldn't require any changes to Gaphor to make it happen, only some modeling.

**Comment by vanillajonathan** [comment]
@amolenaar I only think it is important with a set of predefined templates for the standards modeling notations.

I personally don't think they need to be extensible by users. The standards already exist, end-users have no need to edit templates, just needs to to pick a notation and be confined to the scope of that notation.

**Comment by amolenaar** [comment]
Any ideas for what templates we might need?

1. C4 model, with packages as defined above
2. Something SysML-ish?
3. Does RAAML have it's own template?

**Comment by vanillajonathan** [comment]
I think templates is most useful for the C4 model, since for UML and SysML the user can create the type of diagram they desire, but for the C4 the user is suppose to follow the C4 model by implementing the 4 predefined views.

**Comment by danyeaw** [comment]
@vanillajonathan Template support is now merged in after an outstanding implementation by @amolenaar. Right now, the template has a package and diagram for each level. We would be glad to have help extending the template model to include elements in the template diagrams and other template scaffolding.

**Comment by danyeaw** [comment]
@all-contributors please add @vanillajonathan for idea
