### ISSUE TITLE
Restrict symbol usage to diagram type

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#1158]
### Is your feature request related to a problem?
A junior developer haven't read thick books of a thousand pages and hence doesn't understand all the intricacies of the modeling language. He improperly creates a diagram with symbols from different diagram types, violating model language constraints which results in a semantic mess that makes no sense at all.

### Describe the solution you'd like
Prevent semantic abuse by restricting the symbol usage to one diagram type.
So when you create a component diagram, you can only use component diagram symbols, you cannot use symbols that belong to other diagram types such as the state diagram.

### Additional context
Gaphor already uses language profiles which prevent using symbols from different modeling languages. Preventing using symbols from different diagram types is the next logical step.

**Comment by amolenaar** [comment]
I think this request is identical to #973.

**Comment by vanillajonathan** [comment]
You're right, I think so too. My bad.

> 1. The tool can simplify or collapse parts of the toolbox based on the type of diagram open, and add the gray out guidance.
> 2. We could add the diagram frame with the info in the upper left which provides additional context for someone else viewing your diagram.

I like your ideas.
