### ISSUE TITLE
Numpad Enter key does work on rename

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#1159]
### Describe the bug
The numpad <kbd>Enter</kbd> does work to commit a change when renaming symbols in a diagram.

### To Reproduce
1. Add a UML component (example node or device) to the diagram.
2. Press the <kbd>F2</kbd> key to rename.
3. Press the <kbd>Enter</kbd> on the numpad.

### Expected behavior
I expected the numkad <kbd>Enter</kbd> to work the same way the normal <kbd>Enter</kbd> works.

### OS
- [x] Linux (Ubuntu)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.0

### Additional information
GDK have different key codes for the different keys. See `Gdk.KEY_Return` and `Gdk.KEY_KP_Enter`.

**Comment by amolenaar** [comment]
Thanks @vanillajonathan,

Indeed, I would expect the same behavior. Do you want to create a PR or shall I?

**Comment by vanillajonathan** [comment]
Please create a PR you.
