### ISSUE TITLE
Some strings showing in English and are not localized

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1162]
### Describe the bug
Some strings are still showing in English.

### To Reproduce
Hungarian locale. Seems that the variable `New {Name}` (or could be `New [Name]`) is not _always_ working correctly (`New Database` is working correctly).

### Expected behavior
That the following strings be localized:
* None
* Profile
* Enumeration
* Stereotype
* ControlledProcess

### Screenshots
![kép](https://user-images.githubusercontent.com/17465872/143723252-7c89a5dc-558d-4036-91b5-ed47cf9a5d1b.png)

### OS
Linux Mint 20.2 Cinnamon

### Version
Version of Gaphor: 2.7.0

Thank you

**Comment by amolenaar** [comment]
> Seems that the variable New {Name} (or could be New [Name]) is not always working correctly (New Database is working correctly).

**Comment by amolenaar** [comment]
This is better, right?

![image](https://user-images.githubusercontent.com/96249/144758693-809229cb-8730-457b-b7db-02a0825cb29c.png)

**Comment by amolenaar** [comment]
`None` is also translated in the tree view now. I updated the translations.

**Comment by ovari** [comment]
> This is better, right?

Yes, thank you

**Comment by amolenaar** [comment]
> Yes, thank you

@ovari And thank you as well. Your persistence is a great help to make Gaphor fully localizable. :clap:

**Comment by ovari** [comment]
> Your persistence is a great help to make Gaphor fully localizable.

Seems that all you now need in Gaphor is a `Language Preference Setting`
https://git.jami.net/savoirfairelinux/jami-project/-/issues/1342#note_31741

**Comment by ovari** [comment]
Haven't been able to test; however, trusting `None` has been fixed.
