### ISSUE TITLE
Language Preference Setting

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1176]
Please see image (screenshot from [FreeTube App](https://freetubeapp.io/)) below

![Language Preference Setting from FreeTube App](https://user-images.githubusercontent.com/17465872/144813020-2bfb7664-b570-4214-8cef-dbd7020eb662.png)

[Thunderbird](https://www.thunderbird.net/), [LibreOffice](https://www.libreoffice.org/), [Firefox](https://www.mozilla.org/firefox/new/) have this option too.

Thank you

https://git.jami.net/savoirfairelinux/jami-project/-/issues/1342#note_31741
https://github.com/gaphor/gaphor/issues/1162#issuecomment-986528125

**Comment by ovari** [comment]
Please ensure that you have a `System default` as the first entry and that `System default` is translatable.

Hope you can have this issue ready in the next release of Gaphor.

Thank you once again.

**Comment by amolenaar** [comment]
Hi @ovari,

Every OS has system language settings. Currently we're using this. Why should Gaphor provide a different means to set the language?

**Comment by ovari** [comment]
> Every OS has system language settings. Currently we're using this. Why should Gaphor provide a different means to set the language?

Your choice. Closing as WONTFIX.

**Comment by cloud-erik** [comment]
When working in a internation environment, it would be helpfull if its possible to set laguage of exported drawings different from loacal laguage.
E.g., you aggreed that project laguage is English but team is globaly distributed it would be nice if Language (at least for export) could be set independend from system language.
Other used case would be, if translation in local laguage is not suficient.

**Comment by danyeaw** [comment]
@cloud-erik this should be moved to a new enhancement request with more details on what you would expect to show up as translated. Thanks!

**Comment by cloud-erik** [comment]
@danyeaw Thanks, will create new request.
