### ISSUE TITLE
Feature Request - Support vsd/vsdx Format

### ISSUE THREAD

**Issue by dtantono** [gaphor/gaphor#1177]
### Is your feature request related to a problem?
We know VSD/vsdx format is an industry standard and many FOSS apps supports it. 

### Describe the solution you'd like
I hope we can open and save file in VSD/vsdx format

### Describe alternatives you've considered
nothing so far

**Comment by amolenaar** [comment]
Hi @dtantono,

Thanks for your suggestion. VSD is the Visio file format, right? 

What do you want to use it for? Do you want to edit the diagrams in Visio?

I'm not aware of any open source apps that support it. Are there libraries that help create such files?

**Comment by dtantono** [comment]
yes, some kind of an app to create and edit diagram/flowcharts like visio and I heard Libreoffice Draw (https://github.com/LibreOffice) or drawio (https://github.com/jgraph/drawio) or Inkscape https://gitlab.com/inkscape/inkscape are good FOSS apps for now that support it.

**Comment by amolenaar** [comment]
What do you want to use it for? What do you want to do that you can not do with Gaphor directly?

**Comment by dtantono** [comment]
I hope I can make flowcharts and diagrams with Gaphor. But, since gaphor does not support vsd/vsdx format and it is an industry standard. it is quite dealbreaker for me

**Comment by danyeaw** [comment]
Thanks for the suggestion. Gaphor is not a diagramming tool, it is for modeling. I could see where exporting a picture would be useful, and exporting a model as a XMI. I don't think creating a visio pictures is our focus.

**Comment by amolenaar** [comment]
You can make flow charts (activity diagrams) with gaphor. Really nice ones, if I say so myself. I agree with @danyeaw: I see no benefit in exporting to Visio. Better stick with open standards, such as SVG.

If you feel you really need it, you can always build a plugin that supports it. The current export features are also build [as a plugins](https://github.com/gaphor/gaphor/blob/master/gaphor/plugins/diagramexport/__init__.py). Gaphor is really extensible in that regard. https://gaphor.org/tutorials/plugins.html
