### ISSUE TITLE
Cancel Button on Quit Confirmation Closes Gaphor

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#118]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
1. Edit a diagram
1. Go to File -> Quit
1. Hit Cancel
1. Gaphor closes

or

1. Edit a diagram
1. Go to File -> Quit
1. Hit Save
1. On the save dialog, hit Cancel
1. Gaphor Closes

### Expected behavior
Gaphor should remain running

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Fixed in 78ec0b772027d
