### ISSUE TITLE
Please make Gaphor installable with Homebrew on macOS

### ISSUE THREAD

**Issue by yonkeltron** [gaphor/gaphor#1184]
### Is your feature request related to a problem?

It is harder to automatically install Gaphor on macOS devices if distributed solely through a DMG. This is in comparison to competing tools which allow installation with [Homebrew](https://brew.sh/), the de-facto package manager for macOS. Although Homebrew isn't the same as a "true" package manager like apt or its equivalents, it'd certainly make Gaphor more accessible to folks who primarily use macOS.

### Describe the solution you'd like

By creating a cask formula for Gaphor in the [primary Homebrew Cask tap repo](https://github.com/Homebrew/homebrew-cask), macOS users could install the application with `brew install --cask gaphor` and it would be upgraded to newer versions on subsequent invocations of `brew upgrade` or equivalent.

### Describe alternatives you've considered

Right not the only installation is manual installation involving drag-and-drop workflows. While there are other package managers for macOS, such as [MacPorts](https://www.macports.org/), Homebrew is what I use so I'm submitting for that one first.

### Additional context

While I have written cask Formula for private taps, I haven't ever written one for Homebrew's primary repository. Still, I am happy to consult on any questions folks might have regarding this process. Please let me know if I can help, especially for testing.

Thanks,
+Jonathan

**Comment by amolenaar** [comment]
Hi Jonathan,

Would you like to create such a cask? By looking at it, most casks are installed from a DMG (right?).

If we can upgrade it from our release workflow (github actions) that would be really neat :wink:.

(See also #1151)

**Comment by danyeaw** [comment]
@all-contributors please add @yonkeltron for idea

**Comment by yonkeltron** [comment]
I would love to help. Let me think this through and get back to you. Happy to pair up with someone also since they might know more.

**Comment by yonkeltron** [comment]
Ok would anyone be interested in pairing with me on this one so that I can both teach how to do this as well as ask some questions?

**Comment by amolenaar** [comment]
Hi @yonkeltron, we can meet on Gitter/Matrix. That's probably faster than this issue. https://gaphor.org/discuss.html

**Comment by amolenaar** [comment]
@yonkeltron Are there any Python based GUI apps casked? (preferably GTK based)

**Comment by amolenaar** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/116693.

**Comment by amolenaar** [comment]
You can now pour Gaphor from a [Homebrew cask](https://formulae.brew.sh/cask/gaphor).

Out [download page](https://gaphor.org/download.html) has been updated as well.

**Comment by yonkeltron** [comment]
Omigosh I am so grateful and happy. I apologize for not contributing more
to this effort. Cannot wait to share the good news with others.

Thanks,
+Jonathan

**Comment by amolenaar** [comment]
@yonkeltron No problem. It was quite easy: I only had to follow the tutorial. I also did a small tweak to our website, so the latest version can easily be retrieved: https://gaphor.org/latest.txt.

I added a `livecheck` block. Not sure if it will update automatically or if we still have to submit pull requests when a new version of gaphor is released.

**Comment by yonkeltron** [comment]
Marvelous, I will test it out immediately upon my return to work. I'll also
keep my eyes open for upgrades and make sure those work also. Not sure how
you build and sign apps for macOS but lots of products actually maintain
their own update feeds and stuff. However most of them can do that because
they auto update anyway on account of sparkle.

Looking forward to sharing Gaphor more widely in 2022 and please let me
reiterate my gratitude for this project and all of your efforts.

Thanks,
+Jonathan
