### ISSUE TITLE
Closing Keyboard shortcuts dialog closes the whole app

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1193]
### Describe the bug

When you close the keyboard shortcuts dialog, the whole application closes

### To Reproduce
1. Open _Keyboard Shortcuts_ from the hamburger menu
2. Close it by clicking on the _x_ in the header
3. See Gaphor quit

### Expected behavior

Dialog should be closed.

### OS
- [x] Linux - Fedora 35 / Flatpak / Wayland
    - Works fine in dev environment X11 (XWayland from vscode) and Wayland
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1

### Additional information
Need to test behavior on Windows and macOS as well.

**Comment by danyeaw** [comment]
I can't reproduce this in openSUSE Tumbleweed / Flatpak / Wayland.

**Comment by amolenaar** [comment]
After an update and a restart I can not reproduce this issue either. Phew ;)
