### ISSUE TITLE
Diagram background should be white

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#122]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

Background is the same as the default widget background.

### Expected behavior

Should be white, like a drawing canvas.

### Minimal reproduction of the problem with instructions

Open the application on Linux.

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Fixed in c23fd5c5c06a385514c36b6e71ea7f27cd2e1f8a

**Comment by danyeaw** [comment]
@amolenaar That commit broke the build :grinning:

**Comment by danyeaw** [comment]
@amolenaar we are getting test failures with Linux:
```
    def construct(self):
        """
        Create the widget.
    
        Returns: the newly created widget.
        """
        assert self.diagram
    
        view = GtkView(canvas=self.diagram.canvas)
>       view.set_css_name("diagramview")
E       AttributeError: 'GtkView' object has no attribute 'set_css_name'
```

**Comment by amolenaar** [comment]
Argh! The version of GTK+ is too old. set_css_name is added in GTK+ 3.20.

**Comment by amolenaar** [comment]
Fixed 😃
