### ISSUE TITLE
Stereotype information is not editable

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#123]
### I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

Editor is shown, but Stereotype block is empty

### Expected behavior

I would expect that I can add and edit stereotypes in the editor window.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/96249/55503781-ac062600-564f-11e9-8898-2fdd168e2be5.png">

### Minimal reproduction of the problem with instructions

Open gaphor/UML/uml2.gaphor
Go to a diagram, e.g. Classes/Kernel/DataType
open the editor

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by danyeaw** [comment]
Closed by #125.
