### ISSUE TITLE
Linking associations to actors in use cases can cover the text names for the actors

### ISSUE THREAD

**Issue by hamishmb** [gaphor/gaphor#1231]
Thanks for this excellent tool.

### Describe the bug
As in title. Can make diagrams hard to draw - if not linked then much more manual manipulation is needed when things move around.

Might be more an enhancement than a bug.

### To Reproduce
1. Create a new actor.
2. Create a new association line.
3. Link it to the bottom of the actor.
4. Observe that the actor's name is now unreadable as it is underneath the association line.

### Expected behavior
When an actor has a name, the outline should be enlargened so that association lines can be linked without overlapping the actor name and making it unreadable.

### Screenshots
Probably not needed but will provide on request.

### OS
- Linux Mint 20.2 x86_64 (Ubuntu 20.04 LTS base)

### Version
Version of Gaphor: 2.7.1 (flatpak)

### Additional information
Not sure if anything else is needed, but will provide extra information if needed.

**Comment by danyeaw** [comment]
@hamishmb Thanks for the issue report :heart: 

I am able to reproduce this behavior, I think you mean something like this:
![image](https://user-images.githubusercontent.com/10014976/147371112-755b7c1d-39be-4e11-886c-9e1738e4e1d9.png)

Any thoughts on a preferred solution? Should we move the name to the side automatically to try to avoid the associations? Should we make the association connection underneath the name by extending the bounds of the actor to include the name as well?

@all-contributors please add @hamishmb for bug

**Comment by hamishmb** [comment]
I would prefer extending the bounds of the actor to include the name as well - if there are many associations, moving the text might just obscure a different association.

**Comment by amolenaar** [comment]
I like to close this issue. You can always place the association end on one of the sides of the actor.

If you disagree, please feel free to reopen this issue.

**Comment by hamishmb** [comment]
Ideally yes, you can. In practice, bearing in mind that (IIRC) all model elements have this issue with the text, trying to do that can be an exercise in frustration, especially if you're trying to make the model fit on an A4 page.

I don't think I have the ability to re-open this, but it'd be great if someone else could.

**Comment by amolenaar** [comment]
@hamishmb reopened, as you requested. Your remark made me realize this could become an issue, especially if we add auto-layouting.

**Comment by hamishmb** [comment]
Thanks! I would add some examples I made that demonstrate the issues for A4, but they were for university so I'm not sure I'm allowed to share them - I'd lean towards probably not, to be safe.

**Comment by hamishmb** [comment]
Cheers!
