### ISSUE TITLE
Multiplicity support for associations

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1239]
### Is your feature request related to a problem?

Yes, during modeling I wanted to specify the multiplicities for assocations but I could only as part of the name of the association.

### Describe the solution you'd like

As a modeler, for associations, I would like to be able to set the multiplicity for each association ends. I would like to do it a way that it shows that the multiplicity is not part of the name of the association end but a separate attribute.

**Comment by amolenaar** [comment]
I do not see the problem.

* For an attribute, you can define the multiplicity in one go: `attr[1..*]`
* For operations, the multiplicity can be added to the method signature: `square(n: int[2]): int` / `method(foo: str[*]): int[*]`
* For association ends, the name/multiplicity can be defined in the property editor (right pane), or by opening an editor by clicking near the end of an association. Multiplicity can be defined simply by typing `*` or `0..1`. You can also define the association name and multiplicity in one go: `end[0..1]`.

All these methods have in common that they work in a similar way. If you know how to define an attribute (explained in the tooltip) you can handle all cases.

**Comment by sz332** [comment]
Do we have a tooltip?

**Comment by amolenaar** [comment]
Ah :smile:. It's there for attributes and operations, not for association ends :facepalm:.

![Screenshot from 2021-12-28 18-34-22](https://user-images.githubusercontent.com/96249/147594187-583c48cc-064e-438e-9cec-abd63a89b0b8.png)

Would it make sense to make it more prominent (e.g. as an information :information_source: icon?)

**Comment by sz332** [comment]
Oh, yes, an information icon or something similar would be helpful because it is not really user friendly (well, if we know how it works it's okay but how would a user know how it works?)

**Comment by amolenaar** [comment]
Agreed. Let's update the "property pages" for association end, attribute and operations to have an informatio icon. It wil open a `Gtk.PopOver` with explaination and examples. Extend the examples with a multiplicity.

**Comment by amolenaar** [comment]
Fixed by #1242.
