### ISSUE TITLE
Greeter Recent Model Button Not Working

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1245]
### Describe the bug
If you have recent models showing on the greeter window, pressing Recent Model doesn't do anything.
If you have no recent models, pressing Recent Model go to the Create New Model window.

### Expected behavior
Since the Recent Models are already displayed in the window, can we remove the button entirely?

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: master branch

**Comment by danyeaw** [comment]
I can take on fixing this, but I wanted to get alignment on the expected behavior first. :+1:

**Comment by amolenaar** [comment]
I also noticed that when I start Gaphor without any recent models, it's still precenting this page. It should show the new model page.

Indeed, the button can be removed completely. I hadn't thought of that.

**Comment by amolenaar** [comment]
Fixed by 3e569856a65c6cb0ea24738d0a2de6cd425380f1.
