### ISSUE TITLE
a join node looses its size after close and reopen of the program on linux

### ISSUE THREAD

**Issue by deifemu** [gaphor/gaphor#1246]
### Describe the bug
a join node looses its size after close and reopen of the program on linux

### To Reproduce

- draw a join node with connections
- save
- close 
- open

### Expected behavior
stay the same

### Screenshots
![image](https://user-images.githubusercontent.com/81991548/147817481-9c2d9455-b133-42c4-be84-8e29a6ac5d46.png)
![image](https://user-images.githubusercontent.com/81991548/147817510-cd7b8088-8b88-4279-8562-f809cec5dec0.png)

### OS
- [x] Linux (Please put in notes the specific distro)
Linux Mint 20.2, installed with flatpack

- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1

**Comment by amolenaar** [comment]
Hi @deifemu,

Thank you for reporting. I can reproduce this issue. 

@all-contributors please add @deifemu for bug

**Comment by danyeaw** [comment]
@deifemu Thanks again for submitting the issue, this will be fixed in version 2.8.0 which we are getting ready to release soon.
