### ISSUE TITLE
Fixing stereotype support

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1248]
### Is your feature request related to a problem?
The current stereotype function lacks the actual functionality: assigning stereotypes to model elements. I opened this ticket to start a discussion about the possible iterations we can progress.

### Describe the solution you'd like

 To have this functionality we shall fix our basic functionalities, namely the following:

- The place of profiles in the current system
- Metaclass definition for stereotypes
- Ability to assign a stereotype to a model element based on metaclass
- Ability to set the stereotype properties assigned to a model-element
- Stereotype can exists only as part of a profile 
  - This also might mean that the whole add item only as part of a diagram is really a valid concept

### Additional context

UML 2.5.1 specification, chapter 12.3, Profiles

**Comment by amolenaar** [comment]
This is how it work already https://gaphor.readthedocs.io/en/latest/stereotypes.html

* Create a metaclass
* extend with a stereotype
* Create a normal model element of the type of the metaclass, e.g. 'Class'
* The stereotype can be assigned from the right panel.

**Comment by amolenaar** [comment]
Do we need to do anything for this issue?

**Comment by amolenaar** [comment]
I think we can close this issue. With stereotype inheritance implemented our story is pretty complete IMHO.
