### ISSUE TITLE
Use Official OMG Logos and Document Trademarks

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1256]
### Is your feature request related to a problem?
We are currently using unofficial logos for UML and SysML. We never mention that UML and SysML are registered trademarks of OMG.

### Describe the solution you'd like
1. Follow the [OMG Trademark Guidelines](https://www.omg.org/legal/tm_guidelines.htm)
1. Use the official logos on the New Model from Template Window and our website. These official logos are attached with permission to use them.
1. Add a blurb in our about page that UML, SysML, and RAAML are either registered
trademarks or trademarks of Object Management Group, Inc. in the United States and/or other countries.
1. Use the registered symbol for UML/SysML and TM symbol for RAAML the first time we use them on the website

### Describe alternatives you've considered
Status quo of using unofficial images and not mentioning trademarks.

### Additional context
![UML-logo](https://user-images.githubusercontent.com/10014976/148002005-32649ccd-d69e-4ad4-a2bd-a66ffb0d27a0.png)
![OMG-SysML-logo](https://user-images.githubusercontent.com/10014976/148002006-669fa763-7b78-476d-8789-25467172b641.png)
I also have files in eps format that I can't attach to this issue.

Hello Dan,
 
Your request has been approved.  Please keep this email for your records.
 
The logos are attached.
 
Best regards,
 
Lana
 
Lana Orlova
Senior Webmaster
Boston, MA, USA UTC-05
+1 781 444 0404; 129
lana@omg.org 

From: Bill Hoffman <hoffman@omg.org> 
Sent: Monday, January 3, 2022 12:04 PM
To: info <info@omg.org>; trademarks@omg.org
Subject: Re: Request to Use OMG Trademarks
 
ok
 
Best regards, 
 
Bill 
 
Bill Hoffman
Boston, MA, USA UTC-04

From: info@omg.org <info@omg.org>
Sent: Monday, December 27, 2021 8:09 PM
To: trademarks@omg.org <trademarks@omg.org>
Subject: Request to Use OMG Trademarks
 

_1_Organization_Individual_req: Gaphor Project

_2_Description_Licensee_req: Open source UML, SysML, and RAAML Modeling Tool

_3_Trademark_Logo_req: Use of UML, SysML, and RAAML Trademarks and Logos

_4_Comment_req: Gaphor is an open source modeling tool at https://gaphor.org

We would like to use the UML, SysML, and RAAML trademarks to:
-  Explain on our website that the tool supports these modeling languages
- Allow users to pick one of these profiles for use in the tool, using a drop-down that reconfigures the tool for the language being used

Additionally, we would like to use the SysML, UML, and RAAML logos while selecting a starting template in the tool. For example, if a user is selects to create a new project using a template, they would select the SysML logo if they want to start a SysML project.

We will use the proper trademark notices, and the legal notice in our About page in the tool.

**Comment by amolenaar** [comment]
Awesome. I think we can convert the EPS files to SVG using Inkscape.

**Comment by danyeaw** [comment]
@blippost I was able to get the official logos from OMG for SysML and UML. Is there a RAAML logo in svg or eps format?

**Comment by blippost** [comment]
OMG is in process for releasing the official RAAML logo.  It should be soon.

**Comment by danyeaw** [comment]
We created our own svg of the RAAML logo to hold us over until the official one is released. #1258 and #1279 will close this, and then we can add in the released RAAML logo later.
