### ISSUE TITLE
Application shortcuts bugs in zoom, copy and paste

### ISSUE THREAD

**Issue by h8672** [gaphor/gaphor#1260]
### Describe the bug
The application shortcuts found in top right corner hamburger menu mostly work, but these few may have issues:
- Ctrl_+ doesn't zoom in (Zoom out and reset works though, buttons for zooming work flawlessly).
- Ctrl_C & Ctrl_P pastes the copied element association, so editing changes both new and old element.

#### Zoom In bug
1. Press Ctrl_- to zoom out few times.
2. Press Ctrl_+ to zoom in.
- Zoom in doesn't work.
##### Expected result
Zoom in works.

#### Copying for new element
1. Select element in diagram.
2. Press Ctrl_C to copy it.
3. Press Ctrl_V to paste new element.
4. Change new element.
- Both copies get changed.
##### Expected result
Expected the copied element to be a new element.

### Additional information
Perhaps add a shortcut for copying an element which keeps association to old element?
Like Ctrl_Shift_C or just Ctrl_D for duplication.

Using finnish keyboard layout, Corsair K55 keyboard with ckb-next keyboard application.

### OS
- [x] Linux (Pop OS 21.10)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1 (flatpak)

**Comment by amolenaar** [comment]
Hi @h8672,

Thanks for pointing this out. I'll fix the zoom shortcut for the next version.

Regarding the copying, it is indeed only copying the diagram item, not the underlaying model element. 
I changed the phrasing to "Copy diagram item". I hope that's more clear.
There is already a ticket about that: #791.

**Comment by amolenaar** [comment]
@all-contributors add @h8672 for bug.

**Comment by amolenaar** [comment]
Fixed by #1262
