### ISSUE TITLE
Cannot open previously saved model with multiple packages

### ISSUE THREAD

**Issue by KhazAkar** [gaphor/gaphor#1272]
### Describe the bug
My model is git versioned, can be found at my repository in autorok project.
Locally, after trying to open a previously saved project, which contains multiple packages, gaphor shows me this error message:

### To Reproduce
1. Create pure UML project which contains multiple levels of packages, several use cases etc 
2. Save it
3. Put at your git repository
4. Try to open it
5. ????
6. Fail.

### Expected behavior
Gaphor model should always be able to be opened, or at least recovered

### Screenshots
![Gaphor opening file error](https://user-images.githubusercontent.com/12693890/148657739-952aacc4-a937-40b4-82eb-1f60a7f05e05.png)

### OS
- [X] Linux
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1, Flatpak version

### Additional information
openSUSE Tumbleweed, the latest updates installed

**Comment by amolenaar** [comment]
Hi @KhazAkar, thanks for the bug report. I'll look into it.

@all-contributors add @KhazAkar for bug.

**Comment by amolenaar** [comment]
Hi @KhazAkar 

I found the issue with your model. In one of the use case diagrams, an association exists without association ends. They may have been removed accidentally. Do you recall something like moving an association end property on the diagram and then deleting it? We've added some safeguards for the next version. I'm just hoping we catch this case properly.

The highlighted association in the tree view has no associated association ends. There were also a few other associations that were lacking an association end property.

![image](https://user-images.githubusercontent.com/96249/148661679-5ca030d8-a9df-4a8f-9b60-165699321683.png)

I'll create a PR for you with the fixed model tomorrow.

**Comment by KhazAkar** [comment]
> Hi @KhazAkar
> 
> I found the issue with your model. In one of the use case diagrams, an association exists without association ends. They may have been removed accidentally. Do you recall something like moving an association end property on the diagram and then deleting it? We've added some safeguards for the next version. I'm just hoping we catch this case properly.
> 
> The highlighted association in the tree view has no associated association ends. There were also a few other associations that were lacking an association end property.
> 
> ![image](https://user-images.githubusercontent.com/96249/148661679-5ca030d8-a9df-4a8f-9b60-165699321683.png)
> 
> I'll create a PR for you with the fixed model tomorrow.

Hi @amolenaar ,
Thanks a lot for this exhaustihe explaination.
About your question: it's possible, since when I tried to move things like : GatherDevices out of "root view" on left panel, on the top, to appropriate "package", I was not able to do so. Then I just moved those to blank diagram page and deleted them. Do you think this action caused this to malfunction?
Thank you also for this PR, after it will be made I will check it and merge it, my first attempts at AMDD (Agile Modeling Driven Development) development method :)

**Comment by amolenaar** [comment]
Hi @KhazAkar, I added a [PR](https://github.com/KhazAkar/autorok/pull/1) to fix the model.

If you run into any other problems, please don't hesitate to raise an issue :smiley:
