### ISSUE TITLE
Connectors Won't Connect to Proxy Ports

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1277]
### Describe the bug
Connectors won't connect to proxy ports, they always snap to the boundary of a part property instead.

### To Reproduce
1. Create two part properties
2. Add proxy ports to each one
3. Create a connector and try to connect them to the proxy ports

### Expected behavior
Connectors should snap to proxy ports and move when the proxy port is moved.

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: master

**Comment by liavaag95** [comment]
I experienced the same on Windows today following the same procedure as specified above.

**Comment by amolenaar** [comment]
Fixed by #1403.
