### ISSUE TITLE
Actions Won't Wrap Text

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1278]
### Describe the bug
When trying to resize an action so that the text wraps, it always goes back to its original width.

### To Reproduce
1. Create an Action and name it with a few words like Determine Actuator Command
2. Try to resize it by dragging the bottom right handle so the width is smaller
3. The width always reverts to the original width

### Expected behavior
Width is able to be changed, and the words wrap to the width.

### Screenshots
![image](https://user-images.githubusercontent.com/10014976/148693357-b32eeba9-773f-401e-8805-8a83c985e6ab.png)

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: master

**Comment by ghillebrand** [comment]
I notice this issue with States as well, in version 2.21, running on Windows 10
The width of a state can be changed, and the text wraps whilst changing the width, but then jumps back to all-on-one-line as soon as the mouse stops moving.
Happy to open a new issue if that is more helpful.

**Comment by danyeaw** [comment]
Hi @ghillebrand, thanks that would be really helpful if you could open a new issue!
