### ISSUE TITLE
Remove setup.py

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#128]
Right now pyproject.toml and setup.py have a lot of redundant content and it would be really nice to get rid of setup.py and rely only on the pyproject.toml. We are currently dependent on setup.py for packaging:
1. Packaging for macOS with Briefcase
2. Packaging for Windows with MSYS2

If we were to remove the setup.py we would need to contribute upstream to Briefcase to add support for pyproject.toml. Also MSYS2 Python is very broken right now, so we would need to work to push changes upstream to get Poetry to work there.

### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

**Comment by amolenaar** [comment]
Also, there are a couple of custom build commands:

* Generate the `uml2.py` file from `uml2.gaphor`
* Gettext internationalization (i18n) (`.pot` and `.mo` files)

**Comment by amolenaar** [comment]
I changed the commands a while back, so they can execute independently. We should have a good look at i18n. Currently no translations are packaged with the application.

**Comment by danyeaw** [comment]
I agree that the packaging issues are no longer there, so it look like i18n might be the final thing we need to support.

**Comment by amolenaar** [comment]
Let’s do that for 1.2.0.

**Comment by amolenaar** [comment]
i18n: #220
