### ISSUE TITLE
UML template is empty

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1291]
### Describe the bug

Start a new model from the UML template and you'll end up with an empty workspace.

### Screenshots

The model is actually empty:

```xml
<?xml version="1.0" encoding="utf-8"?>
<gaphor xmlns="http://gaphor.sourceforge.net/model" version="3.0" gaphor-version="2.7.1"/>
```

### Version
Version of Gaphor: master

**Comment by danyeaw** [comment]
Fixed by 0a00d2218d7a730d656f58b9f11d119ed5786002 :+1:
