### ISSUE TITLE
Fix CD Pipeline for Windows and Linux

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#130]
Currently the CD pipeline has issues with Windows and Linux:

- [ ] Windows - each stage is only taking seconds, and no exe files are actually uploaded.
- [X] Linux - we need to find a way to upload to PyPI on a tagged version. I would like to be able to use Poetry to accomplish this, but we may have to use twine since that is what seems to be supported by azure pipelines. Also we could create a linux package using Briefcase and upload it to the release as well.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

**Comment by amolenaar** [comment]
This is fixed, right?

**Comment by danyeaw** [comment]
Windows scripts are now working, however pytest is failing in MSYS2. This is the next thing that needs to be resolved.

**Comment by danyeaw** [comment]
Pytest is working now in Windows by setting the PY_IGNORE_IMPORTMISMATCH environmental variable. The final step is to get the PyInstaller team to merge my PRs, or I need to patch the changes downstream in MINGW packages.

**Comment by amolenaar** [comment]
Can I upvote the patches?

**Comment by danyeaw** [comment]
Your upvote must have worked, because my PR is now merged :smile:
