### ISSUE TITLE
Improve Greeter Interface to Update Buttons and Title on Stack Change

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1300]
### Is your feature request related to a problem?
The current greeter, which although is a really great addition, was implemented as a Window Stack which changed the middle of the stack, but not the action bar or titlebar. This results in a selection buttons not doing anything on certain screens and the title can sometimes be confusing. This was also reported by @vanillajonathan in https://github.com/gaphor/gaphor/issues/973.

For example, on the recent model Window, the Recent Model... doesn't do anything. The title bar says Open a Gaphor Model instead of Recent Models:
![image](https://user-images.githubusercontent.com/10014976/149662793-78c962c2-0f64-4fb0-a47a-904829e0bc81.png)

On the Create Model Window, the Create New Model... button doesn't do anything. The title bar says Open a Gaphor Model instead of Create New Model:
![image](https://user-images.githubusercontent.com/10014976/149662910-9efa1005-dd11-4bc8-9e8e-fdb8eca31146.png)

This is also evident when selecting Open a Model or New Model from the hamburger menu, since the same window stack opens.

### Describe the solution you'd like
Here are a couple of mockups:

![Screenshot from 2022-01-16 09-06-59](https://user-images.githubusercontent.com/10014976/149663589-c8baaf3f-c61d-4136-9c04-e0e6c91aec14.png)

![Screenshot from 2022-01-16 08-51-24](https://user-images.githubusercontent.com/10014976/149664763-9308f5ec-eb92-4284-b618-40307a7ce281.png)

Would Open Other Model... or just Open Model... be better than Existing model? I wasn't sure about that or not.

I can submit a PR once we are aligned on improvements :+1:

**Comment by amolenaar** [comment]
Solved by #1301
