### ISSUE TITLE
Please enable `Create a New Model` to be translatable

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#1308]
### Describe the bug
Please enable `Create a New Model` to be translatable.

### To Reproduce
1. Set system to the Hungarian locale
1. Open Gaphor
2. Please enable `Create a New Model` to be translatable

### Screenshots
![kép](https://user-images.githubusercontent.com/17465872/150207902-863123cd-30ce-4f4e-91c9-85ebb1acc8f4.png)

### OS
- Linux Mint 20.3 Cinnamon

### Version
Version of Gaphor: 2.8.1

Thank you

**Comment by ovari** [comment]
Please enable `supplier` to be translatable.

![kép](https://user-images.githubusercontent.com/17465872/150208436-5af891bd-9f28-4600-92fb-1720c4c8f717.png)

**Comment by ovari** [comment]
Please enable `general` to be translatable.

![kép](https://user-images.githubusercontent.com/17465872/150208588-ab6c0927-7e6a-4d5d-bf41-c930c5fba2fb.png)

Thank you

**Comment by ovari** [comment]
Please enable `date` to be translatable.

![kép](https://user-images.githubusercontent.com/17465872/150208763-a9e085a8-9a88-4080-a889-561d34a85194.png)

Thank you

**Comment by ovari** [comment]
Please enable `String` to be translatable.

![kép](https://user-images.githubusercontent.com/17465872/150208856-382bf916-8c45-44f5-ad56-225761042b4a.png)

Thank you

P.S. Should `String` and `date` both start with a capital letter or both start with a lowercase letter for consistency as they seem to indicate the type?

Thank you once again

**Comment by danyeaw** [comment]
Hey @ovari, thanks for the report. I fixed the `Create a New Model` with c800e8d.

For the others, they are translations in the model itself and I am not sure how we would translate that. @amolenaar, any ideas?

**Comment by ovari** [comment]
It seems that the current convention is to have the program name at the end of the window title.

Should the strings with `Gaphor - ...` be changed so that `... - Gaphor` is at the end?

Examples of programs which have the name of the program at the end:
* [Thunderbird](https://www.thunderbird.net/)
![Thunderbird](https://user-images.githubusercontent.com/17465872/150282131-84f39203-3a8a-4fec-9824-0a40024693e0.png)
* [LibreOffice](https://www.libreoffice.org/)
![LibreOffice](https://user-images.githubusercontent.com/17465872/150282216-d184c8b0-3292-4b39-baeb-97ff21c6726b.png)
* [GNU Image Manipulation Program (GIMP)](https://www.gimp.org/)
![GIMP](https://user-images.githubusercontent.com/17465872/150282350-9eb803c4-54e9-49c7-8de5-a5833631e367.png)
* [Xournal++](https://xournalpp.github.io/)
![Xournal++](https://user-images.githubusercontent.com/17465872/150282440-d3dda596-e809-4fcf-9e19-4527be12c413.png)

Perhaps `Gaphor` is not required in the translatable part of the string as it can be reused from the program name?

What do you think?

Thank you

**Comment by danyeaw** [comment]
@ovari None of those are GNOME Apps. I looked in the GNOME Human Interface Guidelines and I don't see that it actually mentions what to put in the title, however I looked at a few GNOME Apps like Nautilus, Polari, Music, Text Editor, Clocks, Weather, Maps, and Builder. Not a single one of them contains the app name in the title at all. So I think we should follow the other apps and take it off the greeter windows.

**Comment by ovari** [comment]
@amolenaar are `supplier`, `general`, `date`, `string` translatable?

**Comment by danyeaw** [comment]
@ovari supplier and general should now be translatable for you. `date` and `string` are part of the template models themselves. I am not sure how we would translate those to be honest because they aren't part of Gaphor the program, they are model files.

**Comment by ovari** [comment]
1. `supplier`, etc are not showing on Weblate.

![image](https://user-images.githubusercontent.com/17465872/151141066-d5df2420-3a21-4146-a316-bf8960b0d2e8.png)

2/ The English has `String` and `date`. Should `date` be with a capital letter, i.e. `Date`? Should the types be consistent? Or perhaps `String` should be written with a lowercase letter, i.e. `string`?

Thank you

**Comment by danyeaw** [comment]
I reset weblate and capitalized date, we should be all set now. :+1:

**Comment by ovari** [comment]
Hungarian strings should be at 100% on Weblate now, ready to import into your code.

**Comment by danyeaw** [comment]
Thanks @ovari !
