### ISSUE TITLE
Modernize Docs for Version 1.1.0

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#131]
The docs need a thorough review and update to bring them up to the latest version of Gaphor.

- Technical editing improvements
- New screenshots and updated user manual
- Updated installation and development instructions

### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [X] Documentation issue or request

**Comment by danyeaw** [comment]
I want to start working on this. I think we should split up our documentation in two parts:

1. User Focused - Documentation about how to install and use Gaphor. We could also add some getting started with UML tutorials that focus on the key concepts while using Gaphor.
2. Contributor Focused - Documentation for contributors to understand how to setup a development environment, make a contribution, and understand Gaphor's architecture and other design aspects.

For the user focused part, I suggest we create a separate website (gaphor.org). For this we can use a static site like Pelican, Lektor, or Nikola, or it might be a chance for me to learn Django on a hosted site. For the contributor focused part, I think we can continue to use readthedocs.

Any thoughts on splitting things up this way?

**Comment by amolenaar** [comment]
This sounds like an excellent idea. Having a proper user focused web site could attract a lot more users.

I would stick with a static site, unless we reallt need dynamic features (which I doubt).

**Comment by danyeaw** [comment]
https://www.gaphor.org is now live. Time to move user focused stuff to that website, and then we can start to update the technical docs.

**Comment by danyeaw** [comment]
The docs have been updated. I think they are to a point where we have a good foundation of documentation, we can continue to improve them over time.
