### ISSUE TITLE
Update README with New Functionality

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1310]
### Describe the bug
The README needs to be updated:

1. We now have more than one diagram type
2. The description that Gaphor loads a new diagram immediately needs to be updated because we now have the Greeter dialog that appears
3. Instructions on creating a new diagram should talk about the new diagram button

**Comment by Texopolis** [comment]
Hi @danyeaw -can I work on this?
Not entirely clear on the new instructions you want to add but I will install Gaphor and see if I can come up with something
Thanks!

**Comment by danyeaw** [comment]
@Texopolis That would be great! If you have any questions feel free to ask here or come chat with us on Gitter.

**Comment by danyeaw** [comment]
Closed by #1320
