### ISSUE TITLE
Keyboard Shortcuts aren't Working in Windows

### ISSUE THREAD

**Issue by Viicos** [gaphor/gaphor#1329]
### Describe the bug
Can't find the settings panel in the application. According to the keyboard shortcuts, <kbd>Ctrl</kbd> + <kbd>,</kbd> should open settings but it appears that the shortcut isn't working.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows 10 x64

### Version
Version of Gaphor: 2.8.1 x64

**Comment by danyeaw** [comment]
Hi @Viicos, the settings panel can be accessed by pressing the wrench on a page icon in the upper right:
![image](https://user-images.githubusercontent.com/10014976/151713596-82d7ddea-3b32-4376-a616-36a6e3087900.png)

I can reproduce that none of the keyboard shortcuts are working in Windows. If you agree, I can rename the issue to get that fixed.

**Comment by Viicos** [comment]
Ah sorry thought there were more options available in the preferences thus I did not see them at the first place. I was trying to change the theme to dark mode because even if it is activated on my Windows system, Gaphor does not seem to apply it accordingly (maybe another bug?). You can rename the issue, thanks a lot!

**Comment by danyeaw** [comment]
@all-contributors please add @Viicos for bug

**Comment by Viicos** [comment]
@danyeaw thanks for the fast PR. Any ideas on why I'm unable to get the dark mode?

**Comment by danyeaw** [comment]
Could you please submit a separate issue with details on how you have dark mode setup and what you were expecting so that I can try to reproduce the issue? Thanks!

**Comment by Viicos** [comment]
Yes I'll do that!

**Comment by danyeaw** [comment]
@Viicos Are the keyboard shortcuts working now or do we need to keep this issue open?
