### ISSUE TITLE
Dark mode not working on Windows

### ISSUE THREAD

**Issue by Viicos** [gaphor/gaphor#1335]
### Describe the bug
Hey there,
even though dark mode is activated on Windows (`Settings` -> `Personalization` -> `Colors`), Gaphor doesn't seem to detect it and still uses the default clear theme.
Do not hesitate to ask for additional details as I don't really know where it could come from.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.8.1

**Comment by amolenaar** [comment]
hi @Viicos,

This issue [has come up before](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$96rf2S68ucxdHkLsz5vqY86G0Zr4EL_BeZlsA5mL068?via=matrix.org&via=gitter.im). One way is to set an evironment variable `GTK_THEME` to `Adwaita:dark` (or just `:dark`).

However, I do not think this is a story we can keep up for long: as a user you expect this to *just work* in 2022.

See:
 * https://stackoverflow.com/questions/65294987/detect-os-dark-mode-in-python
 * https://pypi.org/project/darkdetect/
 * https://stackoverflow.com/questions/42881112/pygtk3-how-to-change-application-theme
