### ISSUE TITLE
To be able to freely move an association end label

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#1341]
### Is your feature request related to a problem?

When making a class diagram, and when creating an association between two classes, currently Gaphor is always automatically placing the label at each end of the association. While this is a nice feature: it has some problems:

- Sometimes Gaphor puts labels in front of existing elements (classes, associations, other labels, etc.)
- Sometimes labels are so close that it's hard to tell which association end they are for

### Describe the solution you'd like

I would like to be able, if needed, to manually move around the label at the and of an association. Maybe this possibility should be enabled manually in the association properties, so that automatic placement remains the default, but could be disabled on a per case basis.

### Describe alternatives you've considered

Improve the automatic placement of labels − but that would require some very smart heuristics!

**Comment by danyeaw** [comment]
@all-contributors please add @ebousse for idea

Thanks @ebousse for submitting the improvement suggestion :+1:

**Comment by amolenaar** [comment]
I expect manual placement to make label placement considerably more complicated. 

> Sometimes labels are so close that it's hard to tell which association end they are for

In my experience manually moving the labels does not fix this issue.

How to deal with a label location when the endpoint is moved? The current automatic placement is simple and predicable in that sense.

I like to close this issue.

**Comment by amolenaar** [comment]
As I stated before, I personally think our handling of text at association ends, or any other text for that matter, is pretty okay. Models can be made in a way in accordance to the current text placement rules.

I'm closing this issue. If anyone disagrees, feel free to reopen it.

**Comment by ebousse** [comment]
Hi there, sorry to come back on this matter, but I have a question: should I open an issue when I observe a case where the automated placement produces something unreadable, with the idea that the automated placement should eventually be improved as much as needed to avoid such issues?

For instance I encounter this case:

![image](https://user-images.githubusercontent.com/5868014/213745857-3264727c-e8ec-440f-9fdd-c9ec28e1e96d.png)

It's hard to see, but at the bottom part of the association there is a label with `*`. I believe this label should not be drawn atop the arrow end in such case?

**Comment by amolenaar** [comment]
Please open a new issue.

I created one for you: #2025.

**Comment by ebousse** [comment]
> Please open a new issue.

OK, sorry I was not sure.
 
> I created one for you: #2025.

Thanks!
