### ISSUE TITLE
App crashes when action taken to save

### ISSUE THREAD

**Issue by GregJohnStewart** [gaphor/gaphor#1355]
### Describe the bug
The app completely crashes when you go to save the project.

### To Reproduce
1. Open up a new UML diagram project
2. Go to save the project (`ctrl+s`, `Save` through the ui)

### Expected behavior
App doesn't crash, lets you save the project

### Screenshots

Not a screenshot, but an error from console:

```
(gaphor-exe:25031): GLib-GIO-ERROR **: 21:57:34.821: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)
```
Side note, on program init:
```
Gtk-Message: 21:57:17.430: Failed to load module "canberra-gtk-module"
```

### OS
- [ x] Linux (Ubuntu 20.04.3)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: `2.8.2`

**Comment by amolenaar** [comment]
Hi @GregJohnStewart,

This is an odd error. 

* How did you install Gaphor? Flatpak/appimage/python package?
* What type of desktop environment are you using? GNOME/KDE/XFCE/...?
* Does this issue only happen with Gaphor, or do other (GTK based) applications exhibit the same issue?

A search for the error message on google gives a bunch of hits. You're probably not the first person to run into this issue :wink:.
(e.g. https://unix.stackexchange.com/questions/549741/gtk-filechooser-causes-crashes-in-several-programs).

The `canberra-gtk-module` warning is not a problem.

@all-contributors add @GregJohnStewart for bug.

**Comment by GregJohnStewart** [comment]
Confirmed that `gnome-logs` shows me a file select screen when I hit "Export Logs to File"

**Comment by danyeaw** [comment]
I can reproduce this issue for the segfault, I don't get the missing canberra-gtk-module error though.

**Comment by GregJohnStewart** [comment]
Just checked, this is still an issue with 2.9.2. Is the fix still waiting to make it into a release or does this mean it wasn't quite the fix?

**Comment by danyeaw** [comment]
@GregJohnStewart You are right, I just tested it and I can reproduce the issue again. I am not sure what happened there, I tested PR #1364 and everything was working fine. I'll have to look in to it more.

**Comment by GregJohnStewart** [comment]
Just tested on Fedora 35, getting the same issue.

**Comment by amolenaar** [comment]
@danyeaw @GregJohnStewart Is this still an issue with Gaphor 2.10?

**Comment by GregJohnStewart** [comment]
Looks like it's fixed for me, thanks a bunch!
