### ISSUE TITLE
feature request:import python code

### ISSUE THREAD

**Issue by ghost** [gaphor/gaphor#1363]
Hi

 Would like to request a feature: importing python code that is converted into uml automatically by reading the classes.
Also class relations (inheritance, composition) can be created.

Thanks

**Comment by amolenaar** [comment]
Hi @pygamedev,

Indeed this would be a nice feature. Do you know of any (Python) library capable of doing so?
One thing we probably also want then is a way to lay out the elements in a diagram. So far I have not been able to find a proper library for diagram layout.

**Comment by amolenaar** [comment]
Options:

* Pyreverse: https://github.com/PyCQA/pylint/tree/main/pylint/pyreverse
* PyNSource: https://github.com/abulka/pynsource (can do layouting too)

**Comment by vanillajonathan** [comment]
You would build an abstract syntax tree (see the [ast](https://docs.python.org/3/library/ast.html) module), then you iterate over that tree to create a diagram from it.

**Comment by danyeaw** [comment]
Thanks for the feature request. We have updated the README to make it more clear that this isn't one of our goals for the project.
