### ISSUE TITLE
Select items overlayed by another item

### ISSUE THREAD

**Issue by Octopizza** [gaphor/gaphor#1368]
Hi great tool!
However I am missing one feature:
I would like to be able to select and edit entities by selecting them in the tree view.

^Why would I like to do this? E.g. because if I put a block on top/over my use cases I cant access the use cases any more in the diagram (I will only be able to edit the block unless I move the block out of the way before trying to edit the Use case Note/remarks)

**Comment by danyeaw** [comment]
@Octopizza Thanks for the idea. I have noticed this before when putting a use case on a block. I think in this case, the use case should be nested in the block, and you should be able to click on it without having to move it out of the block. Would that be the right solution?

**Comment by amolenaar** [comment]
I'm also thinking about something along those lines. When creating or resizing a block (box/rectangle), it should automatically try to contain all elements that are under the block. It would be good if there's a visual queue something is underneath the block, e.g. by graying it out.

**Comment by amolenaar** [comment]
I've been giving it some more thought. Currently the topmost item with a distance of 0 (zero) is considered the the target for a mouse action. This does not play well if you overlay (for example) a Class with a Box.

What I propose is to introduce a _negative distance_:

* negative distance is calculated as the distance within an element to it's closed boundary
* negative distance (inside ) is always preferred over a positive distance (outside of the element)
* to find the right element, find the item with the highest negative distance (e.i. closest to 0)

The distance is provided by the `Item.point()` method (from Gaphas). We can always provide the current behavior for elements that need it, e.g. for _ProxyPort_.

I think that this allows us to work with diagrams, without caring about the item hierarchy.

@danyeaw What do you think?

**Comment by danyeaw** [comment]
This sounds like a good approach to me.

**Comment by amolenaar** [comment]
Fixed in Gaphas 3.6.0 (included in `main`).
