### ISSUE TITLE
Shortcut not work on linux

### ISSUE THREAD

**Issue by yantaozhao** [gaphor/gaphor#1376]
### Describe the bug
shortcut not work on linux, for example key `c` to create Class.

### OS
- Linux (Ubuntu 20.04LTS)

### Version
Version of Gaphor: 2.8.2

**Comment by amolenaar** [comment]
Hi @yantaozhao,

Thank you for the feedback. Did you try to click on the diagram once before hitting the shortcut? These currently only work if the diagram has the input focus.

Technical reason: the shortcuts interfered with text editing in Gaphor.

**Comment by yantaozhao** [comment]
yes, the diagram is in focus when pressing the shortcut key.

since the _appimage_ bundle version would crash when saving file, I install `gaphor` using _flatpack_ under ubuntu.
both the _appimage_ and _flatpack_ version are not responsible to shortcut for creating diagram element.

**Comment by danyeaw** [comment]
Interesting, I can't reproduce using flatpak version 2.8.2 or the latest version from source using openSUSE Tumbleweed. I can try to boot up a Ubuntu 20.04 LiveCD and see if it is something to do with the older distro.

**Comment by danyeaw** [comment]
I used a LiveCD version of Ubuntu 20.04 and then installed Gaphor from Flathub. I launched Gaphor and hit the c button. A class was created immediately. I am still unable to reproduce this issue.

Are keyboard shortcuts working for other GNOME apps? Which desktop environment are you using?

**Comment by danyeaw** [comment]
@yantaozhao and @juleswh Which desktop environment are you running?

**Comment by yantaozhao** [comment]
Ubuntu 20.04.3 LTS
OS Type: 64bit
GNOME version: 3.36.8
Windowing System: X11
