### ISSUE TITLE
Support right mouse dragging the diagram canvas, and shortcut to scroll left/right

### ISSUE THREAD

**Issue by yantaozhao** [gaphor/gaphor#1377]
Feature requests:

1. As the right mouse is not defined yet, how about use it to drag the canvas instead of using middle mouse? Or perhaps an application setting option to decide using middle/right mouse to drag?

2. now, it is lack to scroll canvas left/right, besides the default scroll up/down with a normal middle mouse scroll. Adding such as `Shift+MiddleMouseScroll` to do so is appreciated.

**Comment by amolenaar** [comment]
Hi @yantaozhao,

Thank you for the suggestions.

I'd like the application to behave similar to Inkscape, when it comes to shortcuts. We _could_ use the right mouse button for dragging the canvas for now, until it's assigned another purpose. In Inkscape `shift`+right button can be used for scrolling.

I like the suggestion of the `shift`+scroll wheel to support horizontal scrolling. It works similar in Inkscape.

Do you think you can help out implementing those features? :relaxed: 

@all-contributors Add @yantaozhao for bug and idea.

**Comment by ebousse** [comment]
Hi there, just wondering if you will eventually consider the first item of the original post? By that I mean the possibility to drag the canvas with either the right or the middle mouse button?

I'm personally in favor of being able to drag the canvas with the middle mouse button, as it seems to be quite standard in drawing tools nowadays (eg. GIMP, Inkscape or Draw.ui do it). In fact I got so much used to move around the canvas in this fashion in other tools that I feel quite slow in Gaphor currently :smile:

**Comment by danyeaw** [comment]
Hi @ebousse, could you please submit a new issue for this?
