### ISSUE TITLE
Ctrl_- both zooms out and moves attributes up in list

### ISSUE THREAD

**Issue by Holzhauer** [gaphor/gaphor#1411]
### Describe the bug
Pressing Ctrl_- when an attribute is selected, the selected attribute is moved up in the list and the canvas zooms out at the same time. Besides, I find it strange that Ctrl_- moves an attribute up and Ctrl_+ moves it down (although this might make sense in terms of indices).

### To Reproduce
1. Select a class with attributes
2. Select an attribute
3. Press Ctrl_-

### Expected behavior
For both actions not the same shortcut should be assigned.

### Screenshots
-

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.8.2

### Additional information
ubuntu 20.10

**Comment by amolenaar** [comment]
Moving elements up and down works without holding the Ctrl key. It would make sense to check for `not Ctrl` when reordering attributes.

**Comment by danyeaw** [comment]
@all-contributors please add @Holzhauer for bug
