### ISSUE TITLE
Ctrl_+ does not zoom in

### ISSUE THREAD

**Issue by Holzhauer** [gaphor/gaphor#1412]
### Describe the bug
Ctrl_+ does not zoom in

### To Reproduce
1. Press Ctrl_+

### Expected behavior
Ctrl_+ should zoom in

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.8.2

### Additional information
ubuntu 20.10
The bug has been reported in #1260 but only the other issue in that report was resolved.
Also note the potential conflict with moving attributes down (see #1411)

**Comment by amolenaar** [comment]
We've been using Ctrl_= to zoom in. It saves hitting the shift key. Maybe we should support both Ctrl_= and Ctrl_+?
