### ISSUE TITLE
KeyError: 'event_manager'

### ISSUE THREAD

**Issue by probonopd** [gaphor/gaphor#1413]
### Describe the bug

```
Traceback (most recent call last):
  File "gaphor/ui/__init__.py", line 118, in app_startup
  File "gaphor/application.py", line 64, in __init__
KeyError: 'event_manager'
Traceback (most recent call last):
  File "gaphor/ui/__init__.py", line 131, in app_activate
AssertionError
```

### To Reproduce
1. Run `Gaphor-2.9.2-x86_64.AppImage` from the command line
2. See error

### Expected behavior
Runs

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows
- [x] FreeBSD helloSystem 0.7.0 with Debian bullseye runtime
 
### Version
Version of Gaphor: Gaphor-2.9.2-x86_64.AppImage

### Additional information
FreeBSD with Debian bullseye runtime may or may not have a part in this.

**Comment by amolenaar** [comment]
This is a new one. It looks like no entry points are loaded. It already breaks on application init:

https://github.com/gaphor/gaphor/blob/master/gaphor/application.py#L64

**Comment by danyeaw** [comment]
Ya, that's an interesting one @probonopd. I can't reproduce it in Linux. This sounds like a pretty unique setup, any thoughts on how we would troubleshoot this?

**Comment by probonopd** [comment]
Thanks for checking. 

It this can't be reproduced in Linux then I'd say the fault may well be on the FreeBSD/helloSystem side and I really don't waste your time on what is a miniscule edge case.

Is there any tracing/debugging built in that I could use to increase verbosity and produce useful outputs on this quite unique system?

**Comment by danyeaw** [comment]
@probonopd We are using https://github.com/pyinstaller/pyinstaller to package up the app with all the needed libraries for the AppImage. PyInstaller has its own bootloader. The bootloader creates a temporary Python environment such that the Python interpreter will find all imported modules and libraries in the folder. Although it is possible to `pip install pyinstaller` with FreeBSD and build a bootloader, I wouldn't expect that an app packaged for Linux would be able to be run in FreeBSD, we would probably need to repackage it for FreeBSD.

**Comment by amolenaar** [comment]
You can also try with a Python virtual environment and install Gaphor in there. It should "just work".
