### ISSUE TITLE
Support UML communication diagrams

### ISSUE THREAD

**Issue by ruimaciel** [gaphor/gaphor#142]
### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

### Current behavior

It would be nice if Gaphor allowed users to draw UML Communication diagrams ([see example here](https://www.uml-diagrams.org/communication-diagrams.html).

UML Communication diagrams are essential to document communication protocols and workflows, particularly envolving service-oriented architectures.

Currently Gaphor allows users to draw class and sequence diagrams, but it doesn't provide users with a drawing object that represent messages flowing between classes (preferably classes without any compartment) in a specific order.

### Expected behavior

It would be nice if Gaphor allowed users to:

* add classes without any compartment, and with lifeline name and selector
* represent message flows between classes (line connector)
* allowed users to add messages, sequence expressions and guards to message flows

**Comment by danyeaw** [comment]
Thanks for this suggestion and for #143. We will add this to a longer term plan to support. If anyone is interested in helping to implement this it is up-for-grabs. @all-contributors please add @ruimaciel for ideas.

**Comment by danyeaw** [comment]
@all-contributors please add @ruimaciel for ideas

**Comment by danyeaw** [comment]
@all-contributors please add @ruimaciel for ideas

**Comment by ruimaciel** [comment]
Thanks! Sorry for the delay.  I hope I can chip in with a few suggestions.

**Comment by amolenaar** [comment]
A basic form of communication diagrams are already present in Gaphor:

![image](https://user-images.githubusercontent.com/96249/75591759-dd19f100-5a80-11ea-93f9-69ca8233715c.png)

Instead of connecting messages to the life line, one can connect messages to the box element, which will make them look like communication messages.

@ruimaciel Would this be sufficient for your needs?

**Comment by amolenaar** [comment]
Fixed by #273
