### ISSUE TITLE
Model Compatibility issues

### ISSUE THREAD

**Issue by mashua** [gaphor/gaphor#1424]
### Describe the bug
I had created a C4 model with the Gaphor-2.7.1-x86_64 version, updated to Gaphor-2.9.2-x86_64 version and it seems that the latest version does not offer backward compatibility.

### To Reproduce
1. Try to load a .gaphor file created with a previous .appimage version.

### OS
- [ ] Linux ( Debian Testing )

### Version
Version of Gaphor: Gaphor-2.9.2-x86_64

**Comment by danyeaw** [comment]
@mashua Thanks for the bug report. Would you be able to share the model file?

**Comment by mashua** [comment]
@danyeaw , the specific one unfortunately not, but I'll try to reproduce it with a share-able one. Will post here when I'll have it.

**Comment by amolenaar** [comment]
@mashua Have you been able to reproduce this issue?

**Comment by danyeaw** [comment]
I am going to go ahead and close this one. Please open a new issue if you have an example we can reproduce.
