### ISSUE TITLE
Overreaction to touchscreen scrolling

### ISSUE THREAD

**Issue by CoderThomasB** [gaphor/gaphor#1425]
Overreaction to touchscreen scrolling

### Describe the bug
When a touchscreen is used to scroll around in the view window it overreacts to the input and scrolls further than expected.

### To Reproduce
Steps to reproduce the behaviour:
1. Create or open a diagram.
2. Select the mouse tool.
3. Try using a touchscreen to scroll in the view window.

### Expected behaviour
The Area that is first taped remands under the finger as the finger moves.
The note-taking apps Rnote and Xournal++ do touchscreen scrolling correctly.

### Screenshots
https://user-images.githubusercontent.com/47554072/159789158-abc48e01-1464-41eb-88a2-e986f9fe638e.mp4

### OS
Linux (Arch flatpak)

### Version
The version of Gaphor: 2.9.2

**Comment by amolenaar** [comment]
Hi @CoderThomasB,

Thanks for the feedback. Indeed it would be best if the scroll behavior is in sync with a touch screen move.
Are you able to fix the scroll speed?

It should be pretty easy to define a `speed` attribute to the `scroll_tools()` call.
https://github.com/gaphor/gaphor/blob/main/gaphor/diagram/tools/__init__.py#L65

**Comment by amolenaar** [comment]
@CoderThomasB,

I tried this on Windows. There zooming works as expected, but for scrolling it works differently: when I place one finger on the touchscreen and move it slightly upwards, the diagram starts scrolling down. If I move it slightly downwards, the diagram starts scrolling up until I move my finger back to the starting position, or lift my finger.

Not exactly the behavior I expected. Is this what's happening with you too?

BTW. changing the scroll speed has a side effect that scrolling with the mouse middle-button hardly moves the diagram.

**Comment by danyeaw** [comment]
@all-contributors please add @CoderThomasB for bug

**Comment by amolenaar** [comment]
Found it: it works fine if we leave the scrolling to ScrolledWindow. The diagram should not care about that.
