### ISSUE TITLE
Add execution specification in UML sequence diagrams

### ISSUE THREAD

**Issue by ruimaciel** [gaphor/gaphor#143]
Currently Gaphor offers some support for interaction diagrams.  However, it doesn't provide a way to add [execution specifications](https://www.uml-diagrams.org/sequence-diagrams.html#execution) in sequence diagrams.  

Therefore, although Gaphor enables users to represent lifelines and messages, it does not offer the user a way to represent where the control flow is executing and which lifeline is waiting for synchronous messages.

**Comment by amolenaar** [comment]
I start working on this one. 

It's a nice case to work a bit with Gaphor. I'm updating the Interaction model to UML 2.5. And fixing some odds and ends in Gaphor itself

**Comment by amolenaar** [comment]
@ruimaciel 
![image](https://user-images.githubusercontent.com/96249/75111856-8eaec180-563e-11ea-9b6e-48ed4537c49e.png)

A lot still has to be done, but the item is at least on the canvas.

**Comment by amolenaar** [comment]
@ruimaciel @danyeaw 
![image](https://user-images.githubusercontent.com/96249/75592182-ec4d6e80-5a81-11ea-9250-e5cf64258513.png)

Almost there.

**Comment by amolenaar** [comment]
Fixed by #273
