### ISSUE TITLE
Can I have multiple Level 1 Packages?

### ISSUE THREAD

**Issue by LeoLeoHu** [gaphor/gaphor#1431]
### Is your feature request related to a problem?
No. new feature request.
In one model, I'd like to create multiple Level 1 packages.
![image](https://user-images.githubusercontent.com/29404176/160243337-264ad137-1e4f-4b8c-bf6b-5bb17f1e64b8.png)

**Comment by amolenaar** [comment]
Yes you can. Either create a diagram in your "1" package, or select the "1" package, right click and select "new package".

**Comment by LeoLeoHu** [comment]
> Yes you can. Either create a diagram in your "1" package, or select the "1" package, right click and select "new package". You can also drag packages around.

Thank you @amolenaar for the reply.  But this does not help.  This will create a new Level 2 package under "1".
Can you help me create one package out of the "1"?  Is this possible?
BTW, I am using version 2.9.2.

![image](https://user-images.githubusercontent.com/29404176/160263545-099d2704-1f9a-4c87-8d32-3dc2fce46fe7.png)

**Comment by amolenaar** [comment]
You mean a toplevel package? A sibling of "1"?

**Comment by LeoLeoHu** [comment]
> You mean a toplevel package? A sibling of "1"?

Yes, correct.  Is that possible?

**Comment by danyeaw** [comment]
@LeoLeoHu I am use to the top level package being called the model package that everything for a model is under. Do you have a different use case?

**Comment by LeoLeoHu** [comment]
> @LeoLeoHu I am use to the top level package being called the model package that everything for a model is under. Do you have a different use case?

OK, then I got it.  You regard **the only one** Level 1 package as the ROOT, like this:
![image](https://user-images.githubusercontent.com/29404176/160323161-7ed65cef-7711-427d-813c-442fd05dea4e.png)

So that's to say, there is no support to add multiple level 1 packages, currently.

Thank you for the reply, I will try your workaround.

**Comment by amolenaar** [comment]
You can do that by dragging a package in the tree view. It takes some skill though, since the tree view in GTK only shows a small green line.

**Comment by LeoLeoHu** [comment]
> This used to work. I see now that when I move an item in between two others (it shows only one green line), the item is not dragged to that level.
> 
> I think this is a regression with the latest changes to make drag/drop more generic.
> 
> @LeoLeoHu Thanks for reporting. I'll look into this.

Thank you.

**Comment by amolenaar** [comment]
It was a tricky bug, but it's fixed now:

![image](https://user-images.githubusercontent.com/96249/160769244-450c0fd9-d809-4d25-b711-c1a1f6be4bac.png)
