### ISSUE TITLE
Unable to Launch macOS App

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#144]
@stevenliu216 reported that he is having issues launching version 1.0.0 macOS app.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Steven, could you give us more information about the issue you are having?

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by stevenliu216** [comment]
### I'm submitting a...
* [x]  Bug report
* [ ]  Feature request
* [ ]  Documentation issue or request

### Current behavior
![Screen Shot 2019-04-16 at 10 39 18 PM](https://user-images.githubusercontent.com/1274417/56257180-5e4edc00-6099-11e9-8ad8-d3db1145dafa.png)

### Expected behavior
Expect the app to launch.

### Minimal reproduction of the problem with instructions
I installed with the .dmg file, and was able to pass the security settings. Opening Gaphor.app results in the above message.

### System Information
OS: MacOS Mojave 10.14.1

* [ ]  Linux (Please put in notes the specific distro)
* [x]  MacOS
* [ ]  Windows 10
* [ ]  Windows 7

NOTES:

I was later able to launch from command-line via `python -m gaphor` after I git cloned and `brew install` + `source .venv`. After installing dependencies that way, I find I can also launch Gaphor.app normally. 

Probably the .dmg installer is a good place to start investigating.

**Comment by amolenaar** [comment]
Indeed, the required libraries are not found in the binary:

```
$ find . -name 'lib*'
./Contents/Resources/app/setuptools/__pycache__/lib2to3_ex.cpython-37.pyc
./Contents/Resources/app/setuptools/lib2to3_ex.py
./Contents/Resources/python/lib
./Contents/Resources/python/lib/python3.7/lib-dynload
./Contents/Resources/python/lib/python3.7/test/libregrtest
./Contents/Resources/python/lib/python3.7/config-3.7m-darwin/libpython3.7m.a
./Contents/Resources/python/lib/python3.7/lib2to3
./Contents/Resources/python/lib/libpython3.7m.a
./Contents/Resources/app_packages/setuptools/__pycache__/lib2to3_ex.cpython-37.pyc
./Contents/Resources/app_packages/setuptools/lib2to3_ex.py
./Contents/Resources/app_packages/libfuturize
./Contents/Resources/app_packages/libpasteurize```

(I would have expected libglib, libgtk, et al to be in this list)

Should we dive into Briefcase and see what goes wrong?

I have a project (https://github.com/amolenaar/gaphor-osx-bundle) that I used to make MacOSX Bundle files for Gaphor. It does need a bit of love, though.

**Comment by amolenaar** [comment]
I had a peek at the dmgbuild code, which is actually performing the packaging. I can not find a hook anywhere to add (binary) libraries to the project.

**Comment by danyeaw** [comment]
I thought Briefcase was making the .app with all of the metadata, files, and libraries, and then Briefcase is making use of dmgbuild for just wrapping it in to a disk image that can be installed.

**Comment by danyeaw** [comment]
I built a Gaphor.dmg manually by running `python setup.py macos -b` on the 1.0.1-release branch. If I try to run gaphor directly I get the following error:
```
Traceback (most recent call last):
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/pkg_resources/__init__.py", line 2442, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'gaphor.services.actionmanager' has no attribute 'UIManager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 161, in app_startup
    self.init()
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 55, in init
    self.load_services(services)
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 79, in load_services
    cls = ep.load()
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/pkg_resources/__init__.py", line 2444, in resolve
    raise ImportError(str(exc))
ImportError: module 'gaphor.services.actionmanager' has no attribute 'UIManager'
Traceback (most recent call last):
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 166, in app_activate
    main_window = self.get_service("main_window")
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 122, in get_service
    raise NotInitializedError("First call Application.init() to load services")
gaphor.application.NotInitializedError: First call Application.init() to load services
Traceback (most recent call last):
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 178, in app_shutdown
    self.shutdown()
  File "/Users/user915375/gaphor/macOS/Gaphor.app/Contents/Resources/app/gaphor/application.py", line 130, in shutdown
    for name, srv in self.component_registry.get_utilities(IService):
AttributeError: 'NoneType' object has no attribute 'get_utilities'
(Gaphor) 74-80-250-219:MacOS user915375$ 
```

**Comment by amolenaar** [comment]
It’s still looking for the UIManager service, which has been removed. How?

**Comment by danyeaw** [comment]
Briefcase is not pulling in GTK so that is what is causing the error message. I have updated the README to require homebrew GTK as an installation pre-requisite. At some point we need to get a packaged version which includes GTK itself.

**Comment by danyeaw** [comment]
@stevenliu216 Would you mind testing this new installer? @amolenaar redid all of the macOS packaging.


https://github.com/gaphor/gaphor/releases/download/untagged-b728780c0522853e3399/Gaphor-1.0.0.post2.dmg

**Comment by stevenliu216** [comment]
After uninstalling the dependencies I installed with brew, I downloaded the latest .dmg and re-installed. It launches on the 1st try now!

**Comment by danyeaw** [comment]
@stevenliu216 Thanks for testing! :tada: 
@amolenaar Nice work on getting this working :+1:
We'll release a new version soon!

**Comment by danyeaw** [comment]
@all-contributors please add @stevenliu216 for bug
