### ISSUE TITLE
Association direction arrow overlapping with name

### ISSUE THREAD

**Issue by HighKingofMelons** [gaphor/gaphor#1451]
### Describe the bug
Direction arrow on associations overlapping name

### To Reproduce
1. Create two classes next to each other
2. Create association from left to right
3. Give association a name
4. Toggle display direction of association

### Expected behavior
Arrow would appear on the opposite side of the association compared to the name, or better yet the arrow being attached to the front or back of the name fx. '◂ Name', '▾ Name', '▸ Name' or '▴ Name' 

### Screenshots
![arrowhas](https://user-images.githubusercontent.com/27958428/161728172-28c98805-c88b-4063-8509-38ffe62b7b03.png)

### OS
Linux

### Version
Version of Gaphor: 
2.9.2, Flatpak from flathub

### Additional information
Using Fedora 35

**Comment by amolenaar** [comment]
![image](https://user-images.githubusercontent.com/96249/176018248-1872c37d-4a4f-4b05-938f-b3b0622bbafa.png)

This is better. I moved the arrow a bit and it now remains on the same side. I also added a bit more padding to the property text at the association ends, as suggested by @Toorero. There are still a few angles where the text is overlapped by a few pixels, but it remains readable.

**Comment by danyeaw** [comment]
@all-contributors please add @HighKingofMelons for bug
