### ISSUE TITLE
Reopening a file moves things around

### ISSUE THREAD

**Issue by Seppli11** [gaphor/gaphor#1467]
### Describe the bug
When saving and reopening a file, some elements shift a little.

I also think some classes were moved out of their packages, but maybe that was just me being sloppy and not noticing it. On the second pair of pictures, they stay in the package. Maybe this is connected.

### To Reproduce
I haven't found a way to reliably reproduce this bug.
1. Launch Gaphor
2. Create a new package with some classes in them
3. Save the file
4. Close the application and reopen it

### Expected behavior
The elements should be at the same place

### Screenshots:
Before reopening it
![Screenshot from 2022-04-17 00-34-34](https://user-images.githubusercontent.com/9285506/163705694-a84852c8-fb1a-4239-9c61-e6e6b91cd09f.png)

After reopening it:
![Screenshot from 2022-04-17 00-34-55](https://user-images.githubusercontent.com/9285506/163705685-55d426f1-5ac8-473b-a6d1-4914fc3da59a.png)

A simple example, before reopening it:
![Screenshot from 2022-04-16 23-24-58](https://user-images.githubusercontent.com/9285506/163705710-366d66be-ed8f-4617-b18c-be22ace47f71.png)

After reopening it:
![Screenshot from 2022-04-16 23-25-13](https://user-images.githubusercontent.com/9285506/163705713-ba5c9786-a359-4a3e-be38-6899a030432b.png)

### OS
- [x] Linux (Arch Linux - Gnome 42)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.9.2 and the main branch (5de066454712162d3575330427a4c0a1b2d271d0)

### Additional information
A friend opened a file on his Windows 10 machine and everything was misaligned as well.

**Comment by Seppli11** [comment]
This is the file were I first noticied it.
[ziped uml gaphor file.zip](https://github.com/gaphor/gaphor/files/8501201/ziped.uml.gaphor.file.zip)
It had looked like this:
![uml](https://user-images.githubusercontent.com/9285506/163705956-ecbcc99d-3018-4bb1-9ee6-a9d6534289b1.svg)

If I open the file in the zip, it lookes like this:
![missalligned uml](https://user-images.githubusercontent.com/9285506/163706010-a5cf2111-93a5-427c-86a5-d5902ad940d2.svg)

**Comment by amolenaar** [comment]
Hi @Seppli11,

Thank you for creating this issue.

I'll have a look at it.

**Comment by amolenaar** [comment]
@Seppli11 I'm not able to reproduce your second example. Is there a certain order in which you add the elements? Can you share that model as well, maybe?

**Comment by amolenaar** [comment]
@all-contributors Add @Seppli11 for bugs.

**Comment by amolenaar** [comment]
I think I found the issue: the position of the top-left handle was not saved. Hence, elements that were resized in the left/top direction would load wrongly.
