### ISSUE TITLE
Add functionality to align (left, center, middle, top, right, etc.)

### ISSUE THREAD

**Issue by noblevirk** [gaphor/gaphor#1476]
### Is your feature request related to a problem?
Today one can manually move the blocks in the white space. It would be nice to have some functionality to align them.

### Describe the solution you'd like
A set of buttons similar to what is available in LibreOffice that operate on selected items.
![image](https://user-images.githubusercontent.com/5385824/164494609-55226fc7-393d-4af6-b460-6365d9a6d037.png)

### Describe alternatives you've considered
Guide lines helps in alignment, but it is a pain to repeatedly perform and as items get added/removed the operation needs repetition.

**Comment by amolenaar** [comment]
Hi @noblevirk,

Thank you for the idea. We only need to find a proper place to put the icons. I suppose the pane on the right, only when multiple items are selected. Any ideas?


@all-contributors add @noblevirk for ideas.

**Comment by sz332** [comment]
Required functions:

- align left, right, top, bottom
- center horizontally and vertically
- space evenly (horizontal, vertical)

This might be part of the same feature, or a separate one:
- same width, height, and size

Location of the icons:

To remove noise I agree with @amolenaar that those icons shall be visible only if they are available. Now the question of where the user should move his mouse and what he actually needs to do.

Random ideas to start brainstorming:

1, Add a new category above General with icons
2, Create a new panel inbetween a tree and actions and add it there (probably does not make much sense)
3, Add a panel on top of the canvas, and the buttons there
4, Somewhere on the right panel

![image](https://github.com/gaphor/gaphor/assets/8182138/76d60fd7-6c19-4638-ac7c-c55a13ff2b0c)


@amolenaar @danyeaw @noblevirk  what do you think?

**Comment by sz332** [comment]
I am kind of stuck with this one. I was able to create a new Category (Below general, see picture above) but I was not able to solve the problem to just execute a custom code when the tool is being selected. Any idea what could be an approach that does not require rewriting the existing codebase?

**Comment by marek-piirikivi** [comment]
@sz332 I think utilizing property page space for multiselection options makes sense. This area shows options/details about a single selection. I think it should do so with multiselection as well. For me, it seems like a consistent behavior and is expected.

**Comment by sz332** [comment]
I reached a point where we have this functionality but only in the hamburger menu / Tools. A better place would be on the left side (under the tree) or the right side (properties).

- Left side problem: the menu items are tightly bound to item factory (it is optimized for the workflow of select an icon, click on diagram, create something). I can hack it around probably in a reasonable time, but later we need to do a major refactor.
- Right  panel problem: the properties panel is designed to handle only single selected elements. It would require a major rewrite to support multi selection at this point.

**Comment by danyeaw** [comment]
Closed by #1476.

**Comment by danyeaw** [comment]
Thanks again @noblevirk for the feature idea. The initial implementation adds the options in the tools menu and we can follow up with adding a special toolbar if we think that is necessary.
