### ISSUE TITLE
SysML Enumerations Should Also be ValueTypes

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1485]
### Is your feature request related to a problem?
In the RAAML profile, we need to be able to make an enumeration show up as values for a Block. For example, Controllability has enumerations (C0, C1, C2, C3) and needs to be a value of AccidentScenario.

![image](https://user-images.githubusercontent.com/10014976/164979943-e881da17-a667-4030-870f-d1d35bae7a1f.png)
![image](https://user-images.githubusercontent.com/10014976/164979971-269fe81f-41bb-4b3e-beb9-725d3159f485.png)

### Describe the solution you'd like

Solution could be in two parts:

1. Allow an Enumeration to select the ValueType stereotype.
2. When an Enumeration is created with the SysML profile, the ValueType stereotype is automatically applied. Although I don't see this explicitly mentioned in the SysML spec, this is how other tools like MagicDraw work.

### Describe alternatives you've considered
I can't think of any alternatives.

**Comment by danyeaw** [comment]
Related to this, our profile parser should also be able to parse Enumerations, maybe as a Python `enum.Enum` type?

**Comment by amolenaar** [comment]
Currently Enumerations are converted to `enumeration` properties based on a class' extension (`-Kind`). It would be nice to use stereotypes instead.

**Comment by amolenaar** [comment]
@danyeaw said in [Matrix](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$4uDCzMxOi5IOUAkJ1UheTk9zQKBCpnjzglJkcS8hvEg?via=gitter.im&via=matrix.org):
> This is an explanation of why MagicDraw automatically applies ValueType to an enumeration: https://community.nomagic.com/correct-stereotype-for-enumerated-value-types-t2607.html

From what I understand, there is no «enumeration» type for SysML. Instead a «ValueType» should be used. Shouldn't we just remove Enumeration from the SysML _blocks_ menu?

**Comment by danyeaw** [comment]
I need a ValueType with Enumeration literals. I guess we could remove the toolbar button for an enumeration and then have a selection on the ValueType property page to turn on enumeration maybe. I'm not sure how that would work in the data model though.

**Comment by amolenaar** [comment]
Hmm.. Both `ValueType` and `Enumeration` inherit from `DataType`. `Enumeration` has a collection of `EnumerationLiteral`'s. Currently the model does not support applying stereotypes on model level. 

We could change the stereotype label in the diagram, but still it's an enumeration underneath. So model wise nothing changes.

Or we should have a special `EnumerationValueType` that inherits both `ValueType` and `Enumeration`, but then we're adding extra types to the model.

**Comment by amolenaar** [comment]
@danyeaw Isn't this similar enough?

![image](https://user-images.githubusercontent.com/96249/172655056-460f677f-4bd4-452c-90a4-b3710ba1a4c2.png)

**Comment by danyeaw** [comment]
Are you just assigning attributes to the valueType instead of enumeration literals?

**Comment by amolenaar** [comment]
Yup. Since `«valueType»`'s have no enumeration literals. They're just public attributes.

**Comment by danyeaw** [comment]
I need to able, for example, select the Controllability enumeration literals from a drop down list per hazardous event. I don't think an attribute will work for this.

**Comment by amolenaar** [comment]
Do we need an 'EnumerationValueType' then, as I described above? Or should we secretly use an Enumeration and only present it as a value type?

What I got from the forum entry above is that it should be a ValueType of sorts.

**Comment by danyeaw** [comment]
Instead of us creating a new type, what do you think about us adding the valueType stereotype as an additional one and make it inherit from both types?

**Comment by amolenaar** [comment]
I'm not sure I follow. Add valuetype as a base class for Enumeration? Or add a (pseudo) stereotype 'valueType' to the Enumeration item?
