### ISSUE TITLE
Diagram name not included in export

### ISSUE THREAD

**Issue by JacobCrabill** [gaphor/gaphor#1491]
### Describe the bug
The diagram name is not saved when exporting to PNG, PDF, or SVG.

### To Reproduce
1. Create diagram
2. Export as any format

### Expected behavior
The exported diagram should contain the name / title block shown within Gaphor's modeling view.

### Screenshots
Expected Output:
![image](https://user-images.githubusercontent.com/5885545/165351605-a7e347b9-3da3-49bb-8687-432a461e24d7.png)

Actual Output:
![example-gaphor](https://user-images.githubusercontent.com/5885545/165351959-fe52fa21-716d-468c-ba1d-60a223465d87.png)

### OS
- [X] Linux (Ubuntu 18.04)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.9.2 installed 26 April 2022 from Flatpack

**Comment by danyeaw** [comment]
@all-contributors please add @JacobCrabill for bug

Thanks for the report @JacobCrabill!

**Comment by danyeaw** [comment]
I can reproduce this issue as well.

**Comment by amolenaar** [comment]
![exp](https://user-images.githubusercontent.com/96249/166140794-a4a1ac5e-99f2-446c-9375-9172022c35b9.png)

Fixed :smile:
