### ISSUE TITLE
(UML) Unclear meaning of A and S checkboxes for class attributes

### ISSUE THREAD

**Issue by hamishmb** [gaphor/gaphor#1521]
### Describe the bug
The meaning of the A and S checkboxes in the attributes and operations section for class diagrams is unclear, and the help button doesn't say anything about what these mean.

My guess is that A=Abstract, but I'm not sure what S does. Turning it on and off (for attributes) doesn't seem to change anything in the diagram.

### To Reproduce
N/A

### Expected behavior
More text added to the help information, or maybe full names being used instead of just the letters A and S.

### Screenshots
N/A, I think.

### OS
- [*] Linux, Linux Mint 20.3 x86_64
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.10.0 (Flatpak)

### Additional information
N/A

**Comment by amolenaar** [comment]
Hi @hamishmb,

Thanks for your report. `S` stands for Static. Indeed it would be better if they are explained in the help box.

Do you feel about providing a PR for this?

**Comment by hamishmb** [comment]
Sure, I'll stick it in my backlog list for when I have some time. I assume A is indeed Abstract then?

Please note: if someone else happens across this before I've fixed it, feel free to do it instead.

**Comment by hamishmb** [comment]
Should I just add it to the help box then, or change the letters to the full words instead/as well?

**Comment by amolenaar** [comment]
Please add it to the help box. The full words will take up too much space, since it contains only the checkbox.

**Comment by hamishmb** [comment]
Okay, noted.

**Comment by danyeaw** [comment]
Hey @hamishmb! Any help needed to get started on this?

**Comment by hamishmb** [comment]
Nope, I just need to spend some time on it - I've got way too much on my to-do list :)
