### ISSUE TITLE
Can't create new diagrams

### ISSUE THREAD

**Issue by Toorero** [gaphor/gaphor#1569]
### Describe the bug
Every commit after [aa97ff2d8](https://github.com/gaphor/gaphor/commit/aa97ff2d843c172a5e7b7f9dca8da572eb5fa6f2) is faulty so I can't create any (UML) diagrams.

### To Reproduce
1. Click on "Create New Model..."
2. Click on "Generic"
3. Click the "Create New Diagram" button in the top left
4. Click on "Class Diagram"
---
1. Click on "Create New Model..."
2. Click on "Generic"
3. Right-Click the "New model" package
4. Click on "New Diagram -> Class Diagram"

### Expected behavior
A new class diagram shall emerge and be shown.

### Logs
```
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
Traceback (most recent call last):
  File "/gaphor/ui/actiongroup.py", line 168, in _action_activate
    method(from_variant(param))
  File "/gaphor/ui/treecomponent.py", line 166, in tree_view_create_diagram
    element = self.get_selected_element()
  File "/gaphor/ui/treecomponent.py", line 140, in get_selected_element
    if tree_item := self.selection.get_selected_item():
AttributeError: 'TreeComponent' object has no attribute 'selection'
```
### OS
- Arch Linux 5.18.6-zen1-1-zen Gnome 42.2 on Wayland
- Python 3.10.5
- [GTK4](https://archlinux.org/packages/extra/x86_64/gtk4/) 1:4.6.5-1
- [GTK3](https://archlinux.org/packages/extra/x86_64/gtk3/) 1:3.24.34-1

installed python packages:
```
alabaster
better-exceptions==0.3.3
certifi
darkdetect==0.5.1
docutils
exceptiongroup==1.0.0rc8
filelock
gaphas==3.6.0
gaphor
generic==1.1.0
imagesize
iniconfig
jedi==0.18.1
parso==0.8.3
platformdirs
pluggy
py
pycairo==1.21.0
PyGObject==3.42.1
PyGObject-stubs==0.0.9
pytz
snowballstemmer==2.2.0
sphinxcontrib-applehelpl
sphinxcontrib-devhelp
sphinxcontrib-jsmath
sphinxcontrib-qthelp 
tinycss2==1.1.1
webencodings==0.5.1
```

**Comment by amolenaar** [comment]
Thanks. I haven't found this issue yet. `TreeComponent` is introduced specifically for GTK 4.

**Comment by Toorero** [comment]
Fixed for me with #1571

**Comment by danyeaw** [comment]
@all-contributors please add @Toorero for bug

**Comment by Toorero** [comment]
The issue has appeared again on 2.11.0
