### ISSUE TITLE
State Machine - Transition on self not possible

### ISSUE THREAD

**Issue by nomisge** [gaphor/gaphor#1577]
### Describe the bug
Creating a UML-State Diagram it is not possible to create a transition, that starts and ends on the same state.

### To Reproduce
1. Create a new Diagram
2. place a state on the diagram
3. place a transition with rectliniear style starting on state and ending on state

### Expected behavior
The transitions head should anchor to the state, and the transitions attributes "name" and "guard" should be editable.
When the state is moved on the canvas, the transition should stay locked to it.

### OS
Linux

### Version
2.9.2

**Comment by amolenaar** [comment]
Hi @nomisge,

Indeed a self-transition shoudl be possible. Thank you for reporting.

Do you want to create a PR with a fix?

**Comment by nomisge** [comment]
Hi @amolenaar,
I wouldn't know where to start fixing the issue.
I believe it's more than just a view lines of code; It needs some conceptual decisions: E.g.: How should the lines of self-reflection be visualized (rectangular, ellipse, ..) and more important how should the workflow look like.

**Comment by amolenaar** [comment]
To remedy the problem all we have to look at is the code that establishes the relationship between a State and a Transition. That's here: https://github.com/gaphor/gaphor/blob/main/gaphor/UML/states/vertexconnect.py#L66.

Next we may want a special self-referencing line, like we have for sequence diagrams. I see these as 2 separate features.

**Comment by danyeaw** [comment]
@all-contributors please add @nomisge for bug

**Comment by danyeaw** [comment]
@nomisge Thanks again for the bug report! :+1:

**Comment by nomisge** [comment]
@amolenaar Thanks for fixing it :+1:
