### ISSUE TITLE
Drag and Drop Allowed for Selection Tool

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#158]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Click and drag the selection tool button in the General tool section on the diagram Toolbar.
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/diagrampage.py", line 324, in _on_drag_data_received
    tool.create_item((x, y))
AttributeError: 'TransactionalToolChain' object has no attribute 'create_item'
```

### Expected behavior
Drag and drop not allowed from the Selection Tool button. The selection tool should be used for selecting elements already on the diagram only.

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:
Ubuntu 19.04

**Comment by amolenaar** [comment]
Fixed by #163
