### ISSUE TITLE
Gaphor in Windows is Incorrectly Installed to x86

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1580]
### Describe the bug
GTK is compiled for 64-bit and Gaphor is running in x64 mode:
![image](https://user-images.githubusercontent.com/10014976/177000387-fb124953-41b4-4727-a5ac-68816363a02c.png)

However, it is installed in the C:\Program Files x86\ directory.

To fix this, we'll need to update the `win_installer.nsi` file and change the INSTALLDIR to `$PROGRAMFILES64`.

### Expected behavior
Gaphor is installed to the correct Program Files directory.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: Latest

**Comment by amolenaar** [comment]
Will it uninstall the old version of Gaphor still (from the x86 folder)?

**Comment by danyeaw** [comment]
I'm not sure what will happen, we'll have to test it

**Comment by amolenaar** [comment]
Where should it be installed then? In `C:\Program Files\`?

**Comment by danyeaw** [comment]
Yup!
