### ISSUE TITLE
Unicode encoding Problems

### ISSUE THREAD

**Issue by qsodev** [gaphor/gaphor#1585]
### Describe the bug
The model files are incorrectly encoded.  

Models created on a Windows machine cannot be opened on Linux.   
Models created on Linux contain wrong characters on Windows.

### To Reproduce

1. On Windows open Gaphor create a new `UML Model`
2. Save the file
3. Try to open this file on Linux
4. Error `This file does not contain a valid Gaphor model`
5.  Terminal output shows `UnicodeDecodeError`...

The problem here is that Gaphor creates some sample diagrams. In `Use Cases` diagram there is a note that contains non standard `-` character. This causes the error on Linux.  
The same problems occur when you write German Umlaute like `üöä ÜÖÄ`. You get the same UnicodeDecodeErrors !

#### The other way:
1. On Linux open Gaphor create a new `UML Model`
2. Write some nonstandard characters like `ü ö ä ÖÄÜ`
3. save
4. open this file on Windows -> the File opens but the characters are wrong.

### Expected behavior
All unicode characters should be encoded correctly and the file should open an all platforms

### OS
- [x] Linux (Archlinux, Flatpak)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.10 ( Portable on Windows, flatpak on Linux )

**Comment by amolenaar** [comment]
Hi, thank you for reporting this. All models should have been encoded with utf8.

**Comment by amolenaar** [comment]
I created a little model myself. I can confirm the issue. It looks like the model is written with the default encoding (Windows 1252 on my VM), which is not UTF-8, as it should be.

**Comment by danyeaw** [comment]
@all-contributors please add @qsodev for bug

**Comment by danyeaw** [comment]
Thanks @qsodev for the bug report!
