### ISSUE TITLE
Model loading does not deal with formatted XML

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1597]
### Describe the bug

When a user opens a Gaphor model in an editor and formats it, it can be that the text is split over multiple lines.
When we load that model, this results in an error

```xml
   <MessageItem id="e390b238-fdfa-11ec-a2d6-a87eeaeedf68">
        ...
        <points>
            <val>[(384.9156628491927, 56.22816292584298), (412.46842824578357, 56.22816292584298), (412.46842824578357,
                70.01784116951711), (390.9156628491927, 70.01784116951711)]
            </val>
        </points>
        ...
    </MessageItem>
```

### Expected behavior

Gaphor should be lenient enough to deal with such text

### OS
- [x] Linux (Please put in notes the specific distro)
- [x] macOS
- [x] Windows

### Version
Version of Gaphor: 2.10 / main

Thanks to @Toorero for producing a model that exposes this issue.

**Comment by Toorero** [comment]
You're welcome. Definitely 100% intended to 😅
