### ISSUE TITLE
Sequence Diagram: CreateMessage shows LostMessage circle

### ISSUE THREAD

**Issue by Toorero** [gaphor/gaphor#1599]
### Describe the bug
If you create an *unconnected* CreateMessage in a Sequence Diagram, a circle like on LostMessage appear. If you'd connect the tip to another Lifeline element, it will be converted into a Communication Diagram style message.

![grafik](https://user-images.githubusercontent.com/22551563/177862082-e44b5bf5-1ada-4967-8c2f-11a1b7328a3f.png)

### Expected behavior
![grafik](https://user-images.githubusercontent.com/22551563/177863468-7244aeb4-9876-49a6-a0ea-a3341f5c663c.png)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.10.0

### Work Around
I can currently work around this issue *temporarily* by creating an CreateMessage, connect the tip temporarily to sth, unconnect it and move the other Lifeline to the end of the tip, so they don't connect together. But as soon as I restart the program, the LostMessage circle is present again.

### Suggested Fix
I would favor if the CreateMessage just can't be converted into a Communication Diagram style message, so I can snap it as accustomed.

**Comment by amolenaar** [comment]
The _LostMessage_ on an unconnected create message seems okay to me.

It would be cool if a message is set to a _Create_ message as soon as one end connects to a _Lifeline timeline_ or _Execution Specification_ and the arrow end to a _Lifeline body_.
