### ISSUE TITLE
Close SourceForge Page

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#161]
The SourceForge download page for Gaphor is usually the first or second result for most search engines when searching for `gaphor`. The downloads are out of date, it would be good if we could just close down the site.

### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [X] Documentation issue or request

**Comment by amolenaar** [comment]
I’ll dig up my old sf.net account.

**Comment by amolenaar** [comment]
From the sf.net documentation:

> If your project has moved elsewhere, there also is an option there to mark the project as moved. That often can be better, so visitors & users of your project can find its new location, instead of just getting a Page Not Found.

I set the project to "moved" and updated all links to GitHub. Would that be okay?

**Comment by danyeaw** [comment]
Sounds great, thanks!
