### ISSUE TITLE
Cannot reflow text in UML use case ovals (newlines)

### ISSUE THREAD

**Issue by hamishmb** [gaphor/gaphor#1616]
### Describe the bug
The Use Case ovals in the UML Use Case diagrams do not allow the text to be reflowed by doing newlines - this can make it difficult to make complicated diagrams tidy.

### To Reproduce
1. Create a new UML model.
2. Add a use case diagram.
3. Observe that use case names cannot be reflowed with linedowns.

### Expected behavior
This is allowed in order to make the diagrams tidier more easily.

### Screenshots
N/A?

### OS
- [*] Linux (Linux Mint 20.3, based on Ubuntu 20.04 LTS)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.11.0

### Additional information
N/A?

**Comment by amolenaar** [comment]
Fair point.

**Comment by amolenaar** [comment]
Something like this? The text is now split over multiple lines if the text does not fit.

![image](https://user-images.githubusercontent.com/96249/179549238-7d04dff5-7aad-48a6-97b0-ce95272cdf03.png)

btw. the oval shape makes you have to play a bit before the text properly fits.

**Comment by hamishmb** [comment]
Yeah, just like that. Thanks!
