### ISSUE TITLE
GTK4: Gtk-CRITICAL Warning for GTK CSS Node Insert After

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1631]
### Describe the bug
When running gaphor in GTK4, I am getting a GTK Critical error for `gtk_css_node_insert_after`:

`Gtk-CRITICAL **: 16:05:13.330: gtk_css_node_insert_after: assertion 'previous_sibling == NULL || previous_sibling->parent == parent' failed`

### To Reproduce
1. Create or open a model
2. See Gtk-CRITICAL warning

### Expected behavior
No warning

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: latest main with GTK4

### Additional information
It looks like the GTK code for this is located here: https://github.com/GNOME/gtk/blob/main/gtk/gtkcssnode.c#L820

**Comment by amolenaar** [comment]
Should we use [Adw.Application](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.Application.html) to initialize the app?

**Comment by amolenaar** [comment]
I can trigger this warning by editing a value in a `Gtk.TreeView` (the GTK3 tree structure). Also the edit boxes are misplaced.

**Comment by mathiascode** [comment]
GTK issue:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3561
https://gitlab.gnome.org/GNOME/gtk/-/issues/3585

**Comment by danyeaw** [comment]
This seems to be fixed now in the latest main version :+1:
