### ISSUE TITLE
In SysML activity diagram: object flows output from output pins cannot live in packages

### ISSUE THREAD

**Issue by hulsed** [gaphor/gaphor#1657]
### Describe the bug
Output pins in activity diagrams force flow relationships to be in the top level. This is make it difficult to have an organized model/package structure.

### To Reproduce
1. Make new activity diagram with two actions.
2. Place an output pin on action 1 and input pin on action 2
3. Extend flow object from action 1 to action to through the pins
4. Observe that the flow is now in the top level of the model tree and cannot be moved

### Expected behavior
Ideally these relationships should be placed in the activity diagram (with the others). And they should be able to be moved into packages if desired.

### Screenshots
![image](https://user-images.githubusercontent.com/23367230/183164092-9c22637e-aec2-447a-9e53-d783a3882d8b.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.11.0 (portable)

**Comment by amolenaar** [comment]
Hi @hulsed,

Thank you for reporting. I would expect the object flow to be allocated to the same activity as the actions and pins.

**Comment by amolenaar** [comment]
Fixed. Now we check the Activity (owner) of the Action owning the Pin.

![image](https://user-images.githubusercontent.com/96249/183312054-e0bdb695-584b-4713-906c-1098a0625f47.png)
