### ISSUE TITLE
Activity diagram elements placed in the wrong activity

### ISSUE THREAD

**Issue by hulsed** [gaphor/gaphor#1659]
### Describe the bug
When adding elements to an activity, elements are associated with the previous (rather than current) activity.

### To Reproduce
1. Create a new blank model with SysML profile
2. Create a BDD and add two activities
3. Create an activity diagram for Activity 1 and add an action
4. Create an activity diagram for Activity 2 and add an action
5. This action shows up the tree for Activity 1 instead of Activity 2

### Expected behavior
Actions in the diagram in the current activity should be placed in the current activity, rather than the previously-created activity.

### Screenshots
![image](https://user-images.githubusercontent.com/23367230/183217609-0560692c-777e-41cf-8d3d-be836ecc205c.png)

### OS
- [ ] Linux 
- [ ] macOS
- [x] Windows 

### Version
Version of Gaphor: 2.11.0 portable

**Comment by amolenaar** [comment]
Hi @hulsed,

Thanks for your report. This is a use case I had not considered so far. It totally makes sense to check if the diagram is located in an Activity. Previously diagrams could only be added to packages.
