### ISSUE TITLE
Release Pipeline Unable to Upload whl and tar.gz

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1755]
### Describe the bug
When releasing version 2.12.0, the linux-gtk4 build was failing with a socket hangup error when running the upload-release-artifacts action. The other builds were uploading their assets successfully.

I disabled the action, but if we want to upload the whl and tar.gz from the built project, we need to resolve this.

**Comment by amolenaar** [comment]
@danyeaw Do you want to fix this? I'm fine with the way it is: it's in PyPI anyway.

**Comment by danyeaw** [comment]
Ya, I think the way it is is fine as well.
