### ISSUE TITLE
Windows Code Signing Certificate Expired

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1756]
### Describe the bug
The Windows code signing certificate expired last month. I didn't receive a notification that it was going to expire, and the build didn't error out, only provided a message that the suitable certificate couldn't be found.

I have submitted a request for a new 3 year certificate, but it will take a few days to go issued.

**Comment by amolenaar** [comment]
Does this mean Windows users get scary messages again?

**Comment by danyeaw** [comment]
Yup :(

**Comment by danyeaw** [comment]
Closed by #1782
