### ISSUE TITLE
Data Type Values Restriction, Property stereotype management, Import/reference for reuse

### ISSUE THREAD

**Issue by nexasone** [gaphor/gaphor#1758]
1. Thanks to all the team working on gaphor for their intelligent and hard work.
2. Data Type Restriction
   I'm trying to make a profile with a stereotype <<Requirement>> with some properties Requirements Profile Diagram from Requirement Profile Package
   then instantiating this profile in the Requirements Diagram from Requirements Model Package
   whatever the property type I chose it defaults to string, for example the booleanAttr:boolean it accepts string or any text
   another example is integerAttr: integer it accepts string or any text
   another example is status and priority property values, they are not restricted to their corresponding enumeration values
   How to restrict property values to their types? 
   
3. Property stereotype management
   When making a stereotype for a property meta-class
   to apply the stereotype and edit its properties, I have to add the property to the diagram this make diagram over-polluted!!
   Is there a way to manage it by selecting it from the class shape or from the left side model hierarchy panel.
   It would be much easier to be able to manage property's stereotype by selecting it from the shape or from the left side model hierarchy panel, without the need to add it to the diagram
4. How to import/reference other models for reuse.
attached example: requirements-profile.gaphor
   
[requirements-profile.zip](https://github.com/gaphor/gaphor/files/9654687/requirements-profile.zip)

**Comment by danyeaw** [comment]
Hi @nexasone Thanks for the suggestions. Maybe we could break these in to separate issues?

Based on the description, I don't think 2 or 4 are currently supported. I am not sure what you mean by 3, maybe some screenshots would help explain?

**Comment by amolenaar** [comment]
Regarding point 2. We have no way to explicitly deny values. Gaphor itself is not aware of value types such as integers and boolean. It's up to the user.

Regarding point 4. We have no way to link to external models for reference. Referencing external models comes with its own set of problems. For example: what to do when an element in the referenced model has been deleted?

Not sure what you mean with point 3.

**Comment by amolenaar** [comment]
This issue is not really actionable IMHO. I'll close it. Feel free to re-open if you think something has to be done.
