### ISSUE TITLE
Fork me on Github link doesn't "click"

### ISSUE THREAD

**Issue by Lazerbeak12345** [gaphor/gaphor#1769]
### Describe the bug
If I click on the "fork me on github" link in the about window, it doesn't work. Instead, the mouse highlights it. It doesn't even underline when you hover.

### To Reproduce
1. Open about window
2. try to click on the text to no avail, as your mouse highlights the letters composing the link

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

```
OS: Linux (5.19.11-200.fc36.x86_64)
Python version: 3.9.9
GTK version: 4.6.7
Display: GdkWaylandDisplay
Gaphor version: 2.12.0

No errors have been intercepted. We’re good.
```

### Expected behavior

I expected to be able to interact with the link.

### Screenshots

![image](https://user-images.githubusercontent.com/22641188/193368313-f6d8ec48-9b66-4eeb-9d88-d8bbf396d8a6.png)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

#### distro info

```
Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.5
Kernel Version: 5.19.11-200.fc36.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-2520M CPU @ 2.50GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 3000
Manufacturer: LENOVO
Product Name: 4180BV1
System Version: ThinkPad T420
```

### Version
Version of Gaphor: 2.12.0

### Additional information

You might have noticed two important things: I'm using Wayland instead of X11, and I'm using KDE (Qt), and not Gnome (GTK).

In addition, I've encountered at least 5 other bugs (with popup messages) that I suspect are related to that core detail. I won't bother reporting them, unless you specifically request me to.

**Comment by Lazerbeak12345** [comment]
Update about the 5 other bugs.... a .gaphor file became corrupted due to this. I'll now be reporting bugs that I can reproduce.

**Comment by danyeaw** [comment]
@Lazerbeak12345 Thanks for reporting the issue. Normally, web links are opened across KDE and GNOME using freedesktop XDG MIME. What happens when run `xdg-open https://github.com/gaphor/gaphor` in your terminal? Does it open this GitHub repo in your browser?

**Comment by Lazerbeak12345** [comment]
> What happens when run `xdg-open https://github.com/gaphor/gaphor` in your terminal? Does it open this GitHub repo in your browser?

yes, the webpage was opened as expected.

I should note, the "link" in the app was behaving more like blue selectable text than a clickable widget.

**Comment by Lazerbeak12345** [comment]
The latest update fixes this.

**Comment by danyeaw** [comment]
@all-contributors please add @Lazerbeak12345 for bug

**Comment by danyeaw** [comment]
Thanks @Lazerbeak12345 for the bug report, I'm glad it is now fixed!
