### ISSUE TITLE
Unexpected error when deleting an element

### ISSUE THREAD

**Issue by DKX47** [gaphor/gaphor#1788]
### Describe the bug
Trying to remove any element in any diagram with the "del" key doesn't remove the element but produces an error.

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

OS: Linux (5.19.0-76051900-generic)
Python version: 3.10.6
GTK version: 4.8.1
Display: X11Display
Gaphor version: 2.12.1

Errors:

Time since application startup: 0:00:06
|Traceback (most recent call last):
|  File "/app/lib/python3.10/site-packages/gaphor/diagram/tools/shortcut.py", line 25, in on_delete
|    state == 0 or state & Gdk.ModifierType.MOD2_MASK
|    │             │       └ <GdkProxyModule <IntrospectionModule 'Gdk' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Gdk-4.0.typelib'>>
|    │             └ <flags 16 of type Gdk.ModifierType>
|    └ <flags 16 of type Gdk.ModifierType>
|AttributeError: type object 'ModifierType' has no attribute 'MOD2_MASK'

### Expected behavior
Delete the selected element

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

flatpak version

### Version
Version of Gaphor: 2.12.1

**Comment by amolenaar** [comment]
Hi @DKX47, Thank you for reporting. It looks like field `MOD2_MASK` is not defined for GTK 4.0.

Did you use a modifier key when you hit `Delete`?

@all-contributors add @DKX47 for bug reports

**Comment by DKX47** [comment]
Hi @amolenaar, no I didn't use any modifier key

**Comment by amolenaar** [comment]
As a workaround you can start Gaphr with the environment variable `GAPHOR_USE_GTK=3`. This will start Gaphor with GTK3, instead of 4.

**Comment by amolenaar** [comment]
I found this issue can also be triggered if _caps lock_ is enabled (or _scroll lock_).

**Comment by DKX47** [comment]
Thanks @amolenaar for your support, that did the trick :)

To anyone else stumpling upon this bevor the patch is released: Execute in your terminal:
flatpak override --user --env=GAPHOR_USE_GTK=3

**Comment by lessinge** [comment]
Thanks a lot @DKX47  :+1:
