### ISSUE TITLE
Feature request: Zoom via Ctrl+Mouse Wheel

### ISSUE THREAD

**Issue by perovsek** [gaphor/gaphor#1798]
### Is your feature request related to a problem?
Sometimes I want to make fine adjustments to nodes in connector elements, blocks, etc. and I want to zoom in.

### Describe the solution you'd like
`Ctrl+Mouse Wheel` for zooming seems very intuitive for me to zoom because it works in the same way in Firefox and Inkscape.

### Describe alternatives you've considered
Buttons for zoom / un-zoom / default zoom already exist but clicking them is slower than using the proposed key+mouse combination.

**Comment by danyeaw** [comment]
Closed by #1815

**Comment by danyeaw** [comment]
@all-contributors please add @perovsek for bug
