### ISSUE TITLE
Actor's "Abstract" toggle does nothing 

### ISSUE THREAD

**Issue by anreji** [gaphor/gaphor#1827]
### Describe the bug
Enabling the "Abstract"-toggle for an UML use-case diagram actor does nothing. (I don't know if this is a bug or a missing feature, but I chose the bug-template, because the toggle is there, after all)

### To Reproduce
1. Choose "UML" in "Create a New Model" dialog
2. Click on "New Diagram" icon → "New Use Case Diagram"
2. Press 't' and create new actor
3. Toggle "Abstract"
4. Observe... nothing

### Expected behavior
I think it was intended, that the actor's name changes to be cursive, if "Abstract" is toggled, like the toggle for classes already does, or that an "<\<Abstract\>>" gets appended to it. 
 
### Screenshots
![image](https://user-images.githubusercontent.com/69592284/197646567-bcd4af26-73f7-4d43-bd9f-637768e04616.png)
![image](https://user-images.githubusercontent.com/69592284/197646591-e70fb017-3270-42da-a9bc-4ce8ee26fd3c.png)

### OS
Linux (Fedora Workstation 36)

### Version
Version of Gaphor: 2.12.1, Flatpak from Flathub

**Comment by danyeaw** [comment]
@all-contributors please add @anreji for bug
