### ISSUE TITLE
Export to EPS

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#1828]
### Is your feature request related to a problem?
I am trying to embed a diagram into a [LaTeX](https://en.wikipedia.org/wiki/LaTeX) document.

### Describe the solution you'd like
Functionality to export the diagram to [Encapsulated PostScript](https://en.wikipedia.org/wiki/Encapsulated_PostScript) (EPS) format.

**Comment by amolenaar** [comment]
Hi,

[Cairo](https://www.cairographics.org) supports a [PostScript exporter](https://pycairo.readthedocs.io/en/latest/reference/surfaces.html?class-pssurface-surface). What would be useful then? Plain Postscirpt or Encapsulated PostScript?

**Comment by vanillajonathan** [comment]
Yes, it seems LaTeX does support embedding plain PostScipt files too.

https://tex.stackexchange.com/questions/185744/how-do-i-include-postscript-graphics-in-a-latex-file
