### ISSUE TITLE
Recent Models menu opens New Model dialog

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#1829]
### To Reproduce
1. Go to '≡' (top-right menu)
2. Click on 'Recent Models...' (or press <kbd>Ctrl</kbd>+<kbd>O</kbd>)
4. See that the "Create a New Model" dialog opened.

### Expected behavior
Some other dialog to open, not the same dialog as the "New Model..." menu entry.

### OS
- [x] Linux (Ubuntu 22.10)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.12.1

**Comment by amolenaar** [comment]
Hi @vanillajonathan,

It works for me. It may be that, if there are no recent models, the new model dialog is shown.

**Comment by vanillajonathan** [comment]
I see, I find it a bit confusing. That wasn't obvious to me.

**Comment by amolenaar** [comment]
What would be better? Disable the Open Recent Model entry in the menu altogether? Or just show you an empty recent-models dialog?

**Comment by vanillajonathan** [comment]
I am not sure. Either of those two would better than the current situation.

**Comment by danyeaw** [comment]
I think graying out / disabling the menu item would make sense to me if there aren't any recent models :+1:

**Comment by vanillajonathan** [comment]
Sounds reasonable.
