### ISSUE TITLE
Delete with CANC

### ISSUE THREAD

**Issue by Lucaffo** [gaphor/gaphor#1834]
When i want to delete a file, i used to press CANC and confirm with enter "Do you want to delete this file?" or without this popup. 

I'd like to add the esc button to delete the current selected fle in the top-left hierarchy. 

Or in another way, add the support for shortcuts? 

![image](https://user-images.githubusercontent.com/55745404/198383473-5738d7dd-80e3-4baf-9fe5-2f2041539a1b.png)

Anyway you (all) made a great work with this project! GG

**Comment by amolenaar** [comment]
Hi,

Thank you for the suggestion.

However, `ESC` is normally not used for deleting elements. When it comes to shortcuts we try to stay close to what's common on Linux/macOS/Windows.

**Comment by Lucaffo** [comment]
I'm dumb, i mean CANC :(

**Comment by amolenaar** [comment]
Ehhmm.. I do not have such a button on my US keyboard layout :thinking:

**Comment by amolenaar** [comment]
I created a small PR that allows you to hit Delete (CANC?) to remove an element from the tree view. However, this only works for GTK4. From your screenshot I see you're using the GTK3 version. Which OS are you using?

**Comment by Lucaffo** [comment]
I use Windows 10 👍🏻

**Comment by amolenaar** [comment]
Cool. The next release will use GTK4 for Windows.
