### ISSUE TITLE
No context menu on navigation panel

### ISSUE THREAD

**Issue by rserranon** [gaphor/gaphor#1836]
### Describe the bug
I can't access the context menu in the navigation panel, therefore I can't delete, rename, etc.

### To Reproduce
1. Go to Navigation panel
2. Click on `<ctrl>` mouse click (right click on Mac)

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`. No errors

### Expected behavior
I expect the context menu to appear, as per the documentation: "n the navigation view, you can also right-click the model elements to get a context menu."

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ X] macOS, chip M1
- [ ] Windows

### Version
Version of Gaphor: 2.12.1, installed via Homebrew as per the documentation: brew install --cask gaphor

**Comment by amolenaar** [comment]
Hi @rserranon,

I checked on my mac (2016 MacBook Pro) and the right button on my (magic) mouse just works:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/96249/198870658-5806ef14-8154-429d-9404-8b51c3014f17.png">

Does it work with similar, GTK-based, apps like Inkscape and GIMP?

**Comment by rserranon** [comment]
Thanks!, It worked using two fingers click rather than <ctrl> click.
