### ISSUE TITLE
Migrate macOS version to GTK4

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1839]
### Is your feature request related to a problem?

From our main releases, the macOS build is the still running on GTK 3.

### Describe the solution you'd like

We should decide if and when  we switch to GTK 4.

There are some pro's and cons:

* **pro** The app becomes a _lot_ more responsive.
* **pro** We're one step closer to phasing out GTK 3.
* **con** Drag and drop support does not work (currently drag/drop event controllers are not activated for macOS). DnD can be disabled in our code, but text entry fields also support DnD. ~When you (accidentally) drag some text from a text field, the app freezes.~ DnD is required to allow for dragging and resizing the window, so we can't disable it completely (drag threshold > screen size)

The following GTK4 issues need to be resolved:

- [x] [macos: drag-n-drop is not fully working](https://gitlab.gnome.org/GNOME/gtk/-/issues/3423) - input freezes after drop.
  * MR: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5291  (_merged_)
- [x] [macos: support for keybinding translations](https://gitlab.gnome.org/GNOME/gtk/-/issues/3421) - currently `Ctrl` is the primary modifier key on macOS, instead of `Cmd`.
  * #1901 fixes it for our own keybindings. 
  * #1911 takes care of (some of) the default key bindings for text entry.
  * https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5296 (_merged_) shown the command symbol in the Keyboard Shortcuts window.
- [x] Add keybinding: `Cmd`+click for multi-select in model browser. Doesn't work: Ctrl-click is handled in an event controller in [`GtkListItemWidget`](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtklistitemwidget.c#L450).

### Describe alternatives you've considered

We could stay with GTK3 for now, but new features (like HARA table views) will probably not be supported.

### Additional context

~The AppImage build should either be migrated to GTK4 or discontinued.~ AppImage has been ported to GTK4, macOS is the only platform still on GTK3.

**Comment by amolenaar** [comment]
As a side note: the version of Cairo provided by Homebrew is 1.16.0, which is quite old.

**Comment by amolenaar** [comment]
GTK 4.9.3 has been released with DnD on macOS fixed.

**Comment by danyeaw** [comment]
Yay, that's so exciting!

**Comment by amolenaar** [comment]
We could... build GTK ourselves :smile:

**Comment by amolenaar** [comment]
GTK 4.10 has been released on the 4th of March. Looks like we can move our macOS package to GTK4 at last.
