### ISSUE TITLE
Include flatpak manifest for easy testing

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1840]
There's currently no flatpak manifest in the repo, so it's not possible to just clone the repo and one-click build it in Builder, which is very helpful for testing and drive by contributions. Since the app is on Flathub I assume that manifest could juts be adapted/added to the repo?

**Comment by amolenaar** [comment]
Hi @bertob,

This would be really nice indeed. You open the project in Builder and everything works from the get-go, and on the latest GNOME version.

But how should it be set up? Are there example (python-based) projects we can use as a starting point?

Currently our flathub manifest is in a separate repo, at https://github.com/flathub/org.gaphor.Gaphor.

**Comment by bertob** [comment]
> But how should it be set up? Are there example (python-based) projects we can use as a starting point?

There are plenty of Python apps that do this, probably the majority of GTK Python apps. Some examples I can think of off the top of my head are https://gitlab.gnome.org/GNOME/gnome-music and https://gitlab.gnome.org/World/lollypop.

**Comment by bertob** [comment]
AFAIK duplicate manifests is how everyone does it, but in practice they're not exactly the same anyway usually, since the development manifest often uses the master branch for dependencies, and the like.

**Comment by danyeaw** [comment]
@all-contributors please add @bertob for idea
