### ISSUE TITLE
TypeError when Closing the Editor

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#185]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Closing the editor window results in the following error:
```
TypeError: close() takes 1 positional argument but 2 were given
```
It is then not possible to reopen the Editor.

### Minimal reproduction of the problem with instructions

1. Open Gaphor
1. Hit Ctrl+E
1. Close the window

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by danyeaw** [comment]
I can't reproduce this in the latest master version.

**Comment by amolenaar** [comment]
It should be fixed, indeed 😊
