### ISSUE TITLE
Horizontal Option for Interfaces between Components Doesn't Work

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#186]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
The horizontal option doesn't have an effect

### Expected behavior
The interface is forced to be horizontal on the screen

### Minimal reproduction of the problem with instruct

1. Open Gaphor
1. Create two new Components
1. Insert an interface between the components
1. Open the editor on the interface
1. Select Horizontal

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Is this still an issue once #213 is merged?

**Comment by amolenaar** [comment]
The Horizontal option on the line only has effect when the Orthogonal option is also selected. Is that the cunfusing bit? The naming does not reveal the intent of this option for sure.

**Comment by danyeaw** [comment]
@amolenaar Yup, that was the confusion. I guess I never really understood what the Orthogonal option does until I tested it more right now. Would it be more clear to have a Toggle Switch that is labeled "Line Style" with two options:
1. Oblique
2. Rectilinear

We then could also gray out the horizontal option if Oblique is selected.

**Comment by amolenaar** [comment]
The term “horizontal” is vague. It used to refer to the orientation of the first line segment, but it’s not clear to a user. If there was just a term that could describe this behaviour better.

**Comment by amolenaar** [comment]
@danyeaw Would "Flip Orientation" be a good alternative to "Horizontal"?

**Comment by danyeaw** [comment]
Closed by #272.
