### ISSUE TITLE
Sequence diagram: option to force a message to be always horizontal

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#1863]
### Is your feature request related to a problem?

When moving message arrows around in a sequence diagram, it's easy to end up with arrows that are not strictly horizontal, like this:

![image](https://user-images.githubusercontent.com/5868014/202521952-eaf96f45-73d5-4d68-9ade-adfe4d23fd16.png)

To my knowledge, once this situation is reached, there is no easy way to make the arrow strictly horizontal again. Since such arrows are almost always horizontal, in UML sequence diagrams, this is makes things a little tedious .

### Describe the solution you'd like

Add an option similar to the existing one called _Rectilinear_, but that would force the arrow to be (1) single segment and (2) horizontal, at all times.

### Describe alternatives you've considered

The _Rectilinear_ option almost does the trick, but unfortunately does not like single segment arrows, and seems to always want multiple segments (at least when I use it).

### Additional context

Gaphor  2.12.1

**Comment by danyeaw** [comment]
Thanks @ebousse for the idea!

**Comment by ebousse** [comment]
My pleasure! But before anything thanks to the Gaphor team for implementing ideas this quickly :smile:
