### ISSUE TITLE
Toolbox is Missing from RAAML.gaphor Model

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#1872]
### Describe the bug
When opening the `models/RAAML.gaphor` model, the toolbox is missing.

Creating a new model works fine, including opening different profiles. Opening other models like `UML.gaphor` and `RAAML-full.gaphor` also work fine.

### To Reproduce
1. Open the RAAML.gaphor model from the Open a Recent Model dialog or from the hamburger menu

There are no errors displayed.

### Expected behavior
Toolbox is visible

### Screenshots
![image](https://user-images.githubusercontent.com/10014976/204138160-21213cb3-5a9f-482b-b985-d5fa1fa0dfe4.png)

### OS
- [X] Linux - MicroOS
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: latest main

**Comment by amolenaar** [comment]
User settings for models are in `~/.cache/gaphor/` as file name hashes. 

Some things to check:
* Can you find out which file contains the settings for your model? What's the contents of that file?
* If you rename `~/.cache/gaphor` to `~/.cache/gaphor/.old`, does the issue persist?
* Is there anything printed on the terminal?

**Comment by danyeaw** [comment]
> Can you find out which file contains the settings for your model? What's the contents of that file?

It looks like the file hash is 378b2137186c6bd4d6bd117507d4c10575c2d8aa7f043db1

```
{'current-diagram': '5921d168-235f-11ea-ab0b-c72c0738acd2',
 'modeling-language': 'C4Model',
 'opened-diagrams': [],
 'remove-unused-elements': True,
 'reset-tool-after-create': True,
 'show-editors': False,
 'show-tips': True,
 'toolbox-C4Model--expanded': {},
 'toolbox-C4Model-cls-expanded': {},
 'toolbox-RAAML--expanded': {},
 'toolbox-SysML--expanded': {0: True,
                             1: True,
                             2: False,
                             3: True,
                             4: True,
                             5: True,
                             6: True,
                             7: True},
 'toolbox-UML--expanded': {0: True,
                           1: True,
                           2: True,
                           3: True,
                           4: True,
                           5: True,
                           6: True,
                           7: True},
 'toolbox-UML-act-expanded': {0: True,
                              1: True,
                              2: False,
                              3: True,
                              4: False,
                              5: False,
                              6: False,
                              7: True},
 'toolbox-UML-cls-expanded': {0: True,
                              1: False,
                              2: False,
                              3: False,
                              4: False,
                              5: False,
                              6: False,
                              7: False},
 'toolbox-UML-pkg-expanded': {0: True,
                              1: False,
                              2: False,
                              3: False,
                              4: False,
                              5: False,
                              6: False,
                              7: False},
 'toolbox-UML-uc-expanded': {0: True,
                             1: True,
                             2: False,
                             3: False,
                             4: False,
                             5: False,
                             6: False,
                             7: False},
 'ui.namespace-height': 542,
 'ui.namespace-width': 223,
 'ui.window-size': (833, 590)}
```

> If you rename ~/.cache/gaphor to ~/.cache/gaphor.old, does the issue persist?

That fixes it

> Is there anything printed on the terminal?

Nope, just regular startup messages.

**Comment by amolenaar** [comment]
Hmm.. it says the modeling language is C4Model. Apart from that, I do not see anything weird.

**Comment by amolenaar** [comment]
Found it! The toolbox is there, only it has a height of 0. Therefore it's completely at the bottom. You should be able to find it if you carefully move your mouse around the left-bottom edge of the window. It when it shows the up-down-arrow, click and move it up. The toolbox reappears.

**Comment by amolenaar** [comment]
We can make the resize bar thinker, but it looks less slick.
