### ISSUE TITLE
Sidebar toolbar styling

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1880]
The items in the toolbar at the top of the right sidebar have .raised styling, which should generally only be used for free-floating elements. In this case there's no reason not to just make these elements .flat.

![image](https://user-images.githubusercontent.com/1908896/204266102-a58236ac-d98b-48bc-9bef-494713f6d7c6.png)

Quick Inspector hack to show what I mean, I just applied the .flat class to each button:

![image](https://user-images.githubusercontent.com/1908896/204266542-5f8b9432-5d0a-407d-8e96-500d4ebe8257.png)

**Comment by amolenaar** [comment]
Thanks. I made a few attempts to "minimize" the layout. It looks okay to get rid of the button backgrounds completely.

FYI, this is the GTK3 version:
![image](https://user-images.githubusercontent.com/96249/204336628-19837312-5ac3-4810-b5b0-8321901a0d79.png)

**Comment by amolenaar** [comment]
It looks nice and clean indeed.

![image](https://user-images.githubusercontent.com/96249/204576725-7db6f086-5736-4eed-85ff-69bc798ffaa0.png)
