### ISSUE TITLE
[Activity diagrams] A ControlFlow edge should be a solid line

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#1900]
### Describe the bug

For creating edges activity diagrams, currently Gaphor provides two different tools in the palette: one to create _ControlFlow_ edges, and one to create _ObjectFlow_ edges, which is correct according to the UML specification/metamodel.

However, Gaphor currently uses two different notations for these two kinds of elements: dashed lines for _ControlFlow_ and solid line for _ObjectFlow_:
![image](https://user-images.githubusercontent.com/5868014/205599245-c1e32137-f773-4235-b694-7aca295c40c3.png)

This is in contradiction with the UML specification (here page 380 of version 2.5.1), which tells that all edges in an activity diagram should be solid:

![image](https://user-images.githubusercontent.com/5868014/205598655-5b1997c3-2573-41dd-b309-11bbe0abf6db.png)

### OS
- [x] Linux
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.13.0

**Comment by danyeaw** [comment]
Hi @ebousse, thanks for the report. We are using the SysML Control Flow Style:
![image](https://user-images.githubusercontent.com/10014976/205773407-072e7f0a-cda6-4f88-bfba-a9bb8343f5bb.png)

I am not an expert at UML, so I didn't actually realize that it used a different notation. Do we want to make the notation configurable? It is wild to me that Control and Object Flows use the same notation, but as you point out, that's what the UML spec says.

**Comment by amolenaar** [comment]
If we make them look the same, there's no way to distinguish a control flow from an object flow.

Previously there was one activity edge and we used some heuristic to determine if it should be a control or object flow. We decided to split them, because they mean different things.

**Comment by ebousse** [comment]
It is indeed a rather annoying syntactic ambiguity :(

I don't have any good suggestion regarding how to differentiate the two sorts of edges, tool-wise. Maybe a drop-down choice when selecting a general "Activity Edge" tool in the palette? Or two tools, one with an icon a small letter "O" (for ObjectFlow) and another with "C" (for ControlFlow)?

**Comment by amolenaar** [comment]
... we can make the gaps in the line smaller, so it looks more solid-ish.

**Comment by amolenaar** [comment]
Nah. That would create a dependency between the presentation element (model) and the selected profile (ui).

I think it's a good thing to distinguish between a control and an object flow, despite what the UML spec says.

**Comment by ebousse** [comment]
> I think it's a good thing to distinguish between a control and an object flow, despite what the UML spec says.

Could such distinction still satisfy the UML notation, which at least requires an activity edge arrow to be solid and not dashed? Maybe instead consider a more subtle difference in thickness?

Also, in my case (and I suppose I am not alone in that case) it's very important to produce diagrams that faithfully satisfy the formal UML notation. Could we therefore imagine an option to disable such a visual distinction, at least when exporting in PNG or when printing?

**Comment by danyeaw** [comment]
I think we should create a configuration that changes how the Control Flows are displayed.

**Comment by amolenaar** [comment]
We have a configuration method already: style sheets. We'd have to test if the line style can be overridden.

**Comment by amolenaar** [comment]
@ebousse Is the solution I propose in PR #1913 satisfactory?

Should the solid-line-for-control-flow css be default to the UML template?

**Comment by ebousse** [comment]
> @ebousse Is the solution I propose in PR #1913 satisfactory?
> Should the solid-line-for-control-flow css be default to the UML template?

IMHO this looks fine, as long as we get solid lines by default when creating a new UML Activity Diagram − which I think is what you suggest regarding the default CSS for UML?

**Comment by amolenaar** [comment]
Yes. It would use solid lines by default, for the UML template.

I also added [an example to our docs](https://gaphor.readthedocs.io/en/latest/style_sheets.html#solid-control-flow-lines).
