### ISSUE TITLE
Appimage build is failing due to missing `pip`

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1918]
### Describe the bug

The Appimage build is failing due to missing `pip`:

![image](https://user-images.githubusercontent.com/96249/207338081-9f9d1ec5-4080-4136-a624-f9a604e767af.png)

Is this due to an (automated) rebuild of the docker container?

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

**Comment by danyeaw** [comment]
Closed by #1919
