### ISSUE TITLE
Attributes and operations can not be directly edited from the diagram (requires editor now)

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#192]
### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
It used to be possible to double click on an attribute and operation and edit it directly in the diagram. With the new diagram structure, this capability got lost

### Minimal reproduction of the problem with instructions

NOTES:

Do we really need this? Maybe integrate the editor more closely with the diagram window?

**Comment by danyeaw** [comment]
Related to this issue:
1. The option to create an attribute in the new Element Editor only appears if you first double click on the element.
2. If you copy and paste an element, and then add an attribute to one of the copies, it only updates on the other copy if you hide and then show the attributes.

**Comment by amolenaar** [comment]
Yes. I see that. Looks like the handlers are not subscribed.

1. Open the element editor
2. Create class
3. Copy/paste the class
4. Add an attribute to the class. It does not depend which class is selected.
5. The original class is only updated. The copy us not updated.

**Comment by amolenaar** [comment]
BTW. With the editor now integrated in the main window, I'm fine with editing attributes and operations from the editor window only.
