### ISSUE TITLE
Simplify window title edited indicator

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1924]
The current title is the file name with the added "[edited]" label next to it if the file has been edited. This is a bit clunky, I'd propose going with the convention of prepending a middle dot character to the file name instead, like other editors in the GNOME ecosystem do.

**Comment by amolenaar** [comment]
![image](https://user-images.githubusercontent.com/96249/208054594-31cec744-fcc7-4206-8e0a-1d49a0cbfba2.png)

It's about the details. For me they've become blind spots. Thanks a lot for your help!
