### ISSUE TITLE
All tabs have the same icon

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1926]
I noticed that all tabs have the same icon, regardless of the type of diagram. I'd either make them different, or drop the icon, since it doesn't add anything to distinguish the tabs.

![image](https://user-images.githubusercontent.com/1908896/208100581-3f6af3cf-bf48-4144-92fa-21f9f8358f2f.png)

**Comment by amolenaar** [comment]
The plan was to also have different types of content, e.g. tables for requirements. Until that's a thing, we can probably drop them as well, since we do not have such functionality yet.

**Comment by amolenaar** [comment]
Currently, if there's only one diagram opened, the tab is hidden. I think it should be shown: you do not want to be editing the wrong diagram :smiley: .

![image](https://user-images.githubusercontent.com/96249/208181049-cd48448d-cf47-4cc0-9f3d-85d45ed8c01d.png)

**Comment by danyeaw** [comment]
It would be nice if we made icons for each diagram type in the future. It would really help you find the diagram you are looking for in the tree view and the open tabs.

**Comment by bertob** [comment]
Dropping the icons for now works for me, but showing the tab bar for a single tab is weird, no other app does that. The tabs are also not full-width like in other apps, I assume that's some kind of setting in AdwTabBar?

**Comment by amolenaar** [comment]
Hmm.. The diagram name is important, you do not want to edit the wrong one (like files in Builder). I think I went a bit overboard by not expanding tabs.

**Comment by bertob** [comment]
> Hmm.. The diagram name is important, you do not want to edit the wrong one (like files in Builder).
It's hard to figure out which diagram you're editing if the tab (name) is hidden.

Maybe I don't quite get how this works, I thought models == files but I realized now that you can have multiple models in the sidebar, and close/open them within the same file?

![image](https://user-images.githubusercontent.com/1908896/208692540-321be2bd-8cf5-4e9e-8354-ba488c8b391b.png)

Anyway, I think the status quo with the empty tab bar that just says "main" is not great. Maybe the model name could be the window title?

**Comment by amolenaar** [comment]
Indeed, a file contains one model. A model can contain multiple diagrams.

The tree view is a hierarchical representation of the model. In your screenshot it shows one package named _New Model_. In that package is one diagram named _main_.

Generally, a model contains more than one diagram. Those diagrams typically focus on different aspects of the system you're modeling, e.g. structure (components), state machines, sequence diagrams.
If you create a new model with the UML template, you'll see what I mean.

With regards to naming, we can probably come up with something more appealing that _main_. Maybe _My first diagram_?

**Comment by bertob** [comment]
Gotcha. Even so, if we're displaying them as tabs, I really don't think we want the tab bar itself to be visible when there's only one. I'll open a new issue for that though since it's kind of a new topic :)

**Comment by bertob** [comment]
By the way, it'd also be good to make the distinctions between file, model, and diagram clearer. Personally I'm not sure I've totally grasped the difference yet with how they're presented in various places in the UI.

It might also help with this to have some example files of complex diagrams somewhere, so people who don't know the domain well can get a sense for what such a diagram looks like with real data.
