### ISSUE TITLE
Clarify flows for opening new tabs/windows

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1927]
Currently, the way to open a new tab is the diagram menu: 

![image](https://user-images.githubusercontent.com/1908896/208101119-daf2f5ae-11fd-4f45-99ce-241cd9aa9bc5.png)

The way to open a new window is "New Model..." in the primary menu.

![image](https://user-images.githubusercontent.com/1908896/208101237-6b253d7a-f53d-463e-b45c-09f05b02f3cf.png)

This is not ideal, because neither of them explicitly tell you where the new models open.

Potential solutions:
- Drop the diagram menu in favor of a simple "New Tab" button, and add an inline chooser with all the options from the menu to the new tab page
- Keep the diagram menu as-is but use the new tab icon, and change the tooltip to "New Tab"
- Change "New Model..." to "New Window" in the primary menu

**Comment by amolenaar** [comment]
Shouldn't the terminology be somewhat targeted to our audience? They're talking "models" and "diagrams".

Replacing the new-diagram icon with new-tab makes it look like this:

![image](https://user-images.githubusercontent.com/96249/208316593-c66049a9-9b5e-4bea-bf87-014bec9b864d.png)

This makes it more explicit we're adding something (bigger `+`). I like to keep the tooltip as _Open diagram menu_ though, since that is more specific (in user slang) to what the menu will provide.

With GNOME Builder, there's a `+` icon for creating and opeing files. But then there will be a lot of down arrows.

![image](https://user-images.githubusercontent.com/96249/208316957-2a9f5d95-462f-429b-8a1d-f02e1f229d9d.png)

**Comment by bertob** [comment]
I guess following the Builder `+ v` pattern would be more predictable, since the New Tab button usually directly adds a tab without an extra step.

**Comment by amolenaar** [comment]
@bertob Do you think changes are still preferable, after my explaination in https://github.com/gaphor/gaphor/issues/1926#issuecomment-1359602259?

> Indeed, a file contains one model. A model can contain multiple diagrams.
> 
> The tree view is a hierarchical representation of the model. In your screenshot it shows one package named _New Model_. In that package is one diagram named _main_.
> 
> Generally, a model contains more than one diagram. Those diagrams typically focus on different aspects of the system you're modeling, e.g. structure (components), state machines, sequence diagrams. If you create a new model with the UML template, you'll see what I mean.
> 
> With regards to naming, we can probably come up with something more appealing that _main_. Maybe _My first diagram_?

**Comment by amolenaar** [comment]
@bertob Something like this?

![image](https://user-images.githubusercontent.com/96249/215359739-bb7fcbfb-4c3c-40ed-894f-1df7312df99d.png)

The icon next to `Profile: UML` is set automatically by the menu button. The arrow next to the `+` I can toggle.

**Comment by bertob** [comment]
Looks good, i think.

> The icon next to Profile: UML is set automatically by the menu button. The arrow next to the + I can toggle.

I'm not sure I follow here, do you mean the arrow is a separate button from the plus?

**Comment by amolenaar** [comment]
> I'm not sure I follow here, do you mean the arrow is a separate button from the plus?

No, they're the same button. Only for text, the arrow is mandatory, for icons it's not.

**Comment by bertob** [comment]
> No, they're the same button. Only for text, the arrow is mandatory, for icons it's not.

Gotcha, LGTM then.

**Comment by danyeaw** [comment]
Thanks @bertob and @amolenaar!
