### ISSUE TITLE
Toolbox: Add horizontal padding

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1936]
The toolbox currently has no horizontal padding, I'd add 12px on both sides. Quick inspector hack (margin-start and margin-end on the viewport):

![image](https://user-images.githubusercontent.com/1908896/208547476-cd20512f-1703-4cac-9751-65c25ef5af06.png)

**Comment by amolenaar** [comment]
@bertob Shouldn't the editor pane (right side) also have a left/right padding of 12px then? Or stick to 6px instead.

And how about the tree view? It looks a bit misaligned to me.

![image](https://user-images.githubusercontent.com/96249/208619544-1729a871-d48e-473b-aec5-f42e37aeb5e7.png)

**Comment by bertob** [comment]
Hmmm you're right, 6 works as well, so let's go with that if it matches other parts of the UI better.

As for the tree view, the problem is that if we have a margin we'd need to also round the hover/active state backgrounds, and I'm not sure how feasible that is. Definitely worth trying though, yeah.

**Comment by amolenaar** [comment]
> Hmmm you're right, 6 works as well, so let's go with that if it matches other parts of the UI better.

:+1:

> As for the tree view, the problem is that if we have a margin we'd need to also round the hover/active state backgrounds, and I'm not sure how feasible that is. Definitely worth trying though, yeah.

It should not be that hard, since it's a ListView. I'll have a look.

**Comment by amolenaar** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/96249/208665205-cf740259-d6a4-49b6-97a6-f18303d7dda2.png)

**Comment by amolenaar** [comment]
Thanks again for helping out :)
