### ISSUE TITLE
Ugly blue background on Help buttons

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1938]
The Help buttons in the right sidebar have an old-style blue hover state, I'd style these like normal .flat buttons.

![image](https://user-images.githubusercontent.com/1908896/208658205-9c01f841-2dfd-4195-94d9-b5e736b558e8.png)

**Comment by amolenaar** [comment]
I updated the color. I figured it would also make sense to have it more pill-like.

![image](https://user-images.githubusercontent.com/96249/208725932-0b606206-27d8-4629-b5e6-4736a6104ce4.png)

**Comment by bertob** [comment]
Looks better, yeah. I'd also increase the horizontal padding by 6px or so, pills need some breathing room on the sides :)

**Comment by amolenaar** [comment]
@betrob More padding, more breath:

![image](https://user-images.githubusercontent.com/96249/208751416-f7a03d86-d298-477f-83f5-32af7488a64f.png)

This is better, indeed.
