### ISSUE TITLE
Toolbox: content doesn't scroll to top edge

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1939]
I assume padding is applied on the wrong level:

![image](https://user-images.githubusercontent.com/1908896/208694198-69225314-9ba2-4778-90d0-331f7505ff00.png)

**Comment by amolenaar** [comment]
I think I broke this by adding the side padding.

Fixed, as well as the bottom padding:

![image](https://user-images.githubusercontent.com/96249/208752406-dc3e4b67-3726-4e7b-9a76-3179230d5d67.png)
