### ISSUE TITLE
Unexpected error after creating a package

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#1952]
### Describe the bug

Unexpected error when creating a package

### To Reproduce
1. Start gaphor
2. Select sysml
3. Select each element and press delete to remove all package
4. Create new package diagram
5. Select the diagram on left side and press right mouse click
6. Select new package menu item

OS: Windows (10)
Python version: 3.11.1
GTK version: 4.8.1
Display: GdkWin32Display
Gaphor version: 2.14.0

Errors:

Time since application startup: 0:01:01
|Traceback (most recent call last):
|  File "F:\Development\Tools\Gaphor\gaphor-2.14.0-portable\data\gaphor\ui\actiongroup.pyc", line 191, in _action_activate
|  File "F:\Development\Tools\Gaphor\gaphor-2.14.0-portable\data\gaphor\ui\treecomponent.pyc", line 159, in tree_view_create_package
|AssertionError
└─────────────────────────────╌┄┈

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.14.0

**Comment by amolenaar** [comment]
Indeed, the Add Package option should not be enabled when using the popup on anything but packages.

**Comment by danyeaw** [comment]
Thanks @sz332 for the bug report!
