### ISSUE TITLE
Don't show tab bar if there's only one tab

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1955]
We generally don't show tab bars when there's a single one (except in Builder, but that's for reasons which don't really apply to other apps, i.e. that it has an in-app tiling system). The current status quo is not great, because there's a useless second bar at all times, which just says "main" when you create a new model:

![image](https://user-images.githubusercontent.com/1908896/209475062-8bf73ca8-14ea-4318-8cdc-d8c03f587872.png)

As far as I understood, the bar was enabled to make it clearer which diagram you're currently working on, so we'd need to find an alternative place to show the title. Would the window title in the headerbar be an option here, e.g. instead of "Gaphor" in the example above?

Independently from that we should find a better default name than "main". Would something like  "Diagram 1" or "Main Diagram" work?

Followup from #1926

**Comment by danyeaw** [comment]
Thanks @bertob for the suggestion!

I am assuming if there were two tabs open, and you close one, that the tab bar would collapse up, and the diagram would take up the space that the tab bar was using. Is that a correct understanding of how it would work?

**Comment by amolenaar** [comment]
Yes. That's actually how it worked for 2.12. However, then the diagram name is no longer visible, so you can't know which diagram you're editing.

The header bae shows the name of the model (file name without suffix). If it's a new model it'll show `Gaphor`.

![image](https://user-images.githubusercontent.com/96249/209583510-95380055-0f1f-4a4b-bff4-fcf9bddcd85c.png)

We could add the diagram name (in this case `sequence-diagram – main`).

I changed the diagram name to _New diagram_ in #1956.

**Comment by bertob** [comment]
> The header bae shows the name of the model (file name without suffix). If it's a new model it'll show Gaphor.

If the file name is visible below anyway, could we put the diagram name there instead? Alternatively I guess we could try "model name • diagram name" in the title?

**Comment by amolenaar** [comment]
I'll give it a try. Alternatively we can also show the qualified name (packages + diagram name) in the top bar. We do not have space for that in the tabs, normally.

**Comment by amolenaar** [comment]
Like this?

![image](https://user-images.githubusercontent.com/96249/211784118-47bd3062-2923-43f0-b545-f82ffaaca364.png)

Or show the full path?

![image](https://user-images.githubusercontent.com/96249/211784263-7d604035-4ba6-482a-9e43-7fb729912875.png)

If the path contains more than 3 elements, I suggest it's shown as **Model :: &hellip; :: Package :: Diagram name**.
For now I used `::` as separator. I suppose `﹘`, or `·`  would also make a nice candidates.

![image](https://user-images.githubusercontent.com/96249/211785348-2cb915ee-0a67-4783-94b1-e4b54f24d2f2.png)

**Comment by bertob** [comment]
I'd go with just the title, the full path gets too messy. If you think it's important an actual pathbar could be an option, but IMO just the name is fine, since the treeview on the left is always accessible. One thing to consider could be visually distinguishing the parent folder in the tree if it's collapsed, so it's easier to find the active item.

**Comment by amolenaar** [comment]
Just the diagram name looks more clean indeed.

I also created #2005, which provides a `Adw.StatusPage` when no diagram is opened.

**Comment by danyeaw** [comment]
Thanks @bertob for your suggestion for improvement and @amolenaar for your implementation :+1:
