### ISSUE TITLE
Update Sphinx to 6.x

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2006]
Sphinx can't be updated to 6.x, since Myst-NB is not supporting that yet. We use Myst-NB for some of our executable notebooks on gaphor.readthedocs.org: [Jupyter and Scripting](https://gaphor.readthedocs.io/en/latest/scripting.html), and [Example: Gaphor services](https://gaphor.readthedocs.io/en/latest/gaphor-services.html).

I created this issue to track the progress. It's awaiting a new release of myst-parser.

https://github.com/executablebooks/MyST-NB/issues/466
https://github.com/executablebooks/MyST-Parser/issues/660 (fixed -> v1.0.0)

**Comment by danyeaw** [comment]
It looks like there is a PR to update MyST-NB's usage of MyST-Parser: https://github.com/executablebooks/MyST-NB/pull/479
