### ISSUE TITLE
404 on the flathub (file was not found)

### ISSUE THREAD

**Issue by kacperpaczos** [gaphor/gaphor#2012]
Try clikc install on flathub:
https://flathub.org/apps/details/org.gaphor.Gaphor
and we have link:
https://dl.flathub.org/repo/appstream/org.gaphor.Gaphor.flatpakref
![image](https://user-images.githubusercontent.com/23406555/213010605-4fa07beb-9d42-4ce5-8452-60f786d89073.png)

**Comment by amolenaar** [comment]
Hi @kacperpaczos,

Thank you for your report. Indeed, hitting the `Install` button causes this issue. I think we have to upstream it to flathub, since we have no control over this.

As a workaround: the installation instructions can also be found on our website: https://gaphor.org/download/#linux

**Comment by amolenaar** [comment]
From what I read from the (Glib) code, setting XDG_DATA_DIRS is the right thing to do.

The `XDG_DATA_DIRS` environment variable is properly set in the [glib runtime hook of PyInstaller](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_glib.py#L21).
So my patch #2016 is not (completely) correct. As far as I know, setting `os.environ` also propagates to the C layer, but it looks like that's not happening (?)

@danyeaw Any ideas?

**Comment by danyeaw** [comment]
Hi @amolenaar, is this comment about the Flathub issue or the AppImage save one?

**Comment by amolenaar** [comment]
Wrong issue indeed :see_no_evil:

**Comment by danyeaw** [comment]
@kacperpaczos It looks like this issue is resolved now, could you please verify?

**Comment by kacperpaczos** [comment]
Thx
