### ISSUE TITLE
Get rid of deprecated GTK+ features

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#202]
Gaphor is still using some deprecated features from GTK+ 3. The application should be updated so that no deprecated features are used.

Deprecated features include:

* stock icons
* `Gtk.UIManager` and friends (Gtk.Action) 

This issue is a placeholder to collect information on how to perform this update.

* [Stock item deprecation](https://docs.google.com/document/d/1KCVPoYQBqMbDP11tHPpjW6uaEHrvLUmcDPqKAppCY8o/pub)
* [Freedesktop icon naming](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names)
* [Stock item migration sheet](https://docs.google.com/spreadsheets/d/1HavJQRPpMuq-N0GoN1wJR-9KEGXpKy3-NEPpZZkUGJY/pub?output=html)

There seems to be no real replacement for `UIManager`, esp. the ability to add and remove partial menus. We either have to come up with our own solution or stick with a more dynamic menu.

* [Using the GAction framework](http://gexperts.com/wp/using-the-gaction-framework/)

Menu generation can be done via `Gtk.Builder` (=xml), but we might just as well code something in Python directly.

(My) plan is that once we're no longer using deprecated features, we can use the `HeaderBar` and `ActionBar`, as described in the [GNOME HIG](https://developer.gnome.org/hig/stable/).

* [Introducing the CSD Initiative](https://blogs.gnome.org/tbernard/2018/01/26/csd-initiative/)

**Comment by amolenaar** [comment]
Allan Day made me this lovely mockup for a new menu layout:

![new-gaphor-mockup-aday](https://user-images.githubusercontent.com/96249/65424298-7de9ed80-de0b-11e9-9206-b8a039105c79.png)

**Comment by danyeaw** [comment]
That looks great!

**Comment by amolenaar** [comment]
Fixed by #207.
