### ISSUE TITLE
Allow selection of multiple elements in the tree view

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#2022]
### Is your feature request related to a problem?

Sometimes I want to reorganize my UML model, for instance by introducing a new package structure. This means creating a package and moving a set of elements inside this package.

Unfortunately, it is not possible to select multiple elements in the tree view, which means elements have to be moved one by one, which can be tedious.

### Describe the solution you'd like

I suggest to add the possibility to select multiple elements at a time in the tree view.

### Describe alternatives you've considered

None so far.

### Additional context

2.15.0

**Comment by amolenaar** [comment]
Indeed, this is a valid use case.

**Comment by danyeaw** [comment]
Closed by #2037. Thanks @ebousse for the idea!
