### ISSUE TITLE
Associations: text overlaps with association end decorations

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2025]
### Describe the bug

@ebousse says:

> Hi there, sorry to come back on this matter, but I have a question: should I open an issue when I observe a case where the automated placement produces something unreadable, with the idea that the automated placement should eventually be improved as much as needed to avoid such issues?
> 
> For instance I encounter this case:
> 
> ![image](https://user-images.githubusercontent.com/5868014/213745857-3264727c-e8ec-440f-9fdd-c9ec28e1e96d.png)
> 
> It's hard to see, but at the bottom part of the association there is a label with `*`. I believe this label should not be drawn atop the arrow end in such case?
> 

I checked and indeed, the alignment is of on one of the sides of the association:

![image](https://user-images.githubusercontent.com/96249/213864053-14fb0cc9-8f87-47d2-ae4f-ea86342d0088.png)

**Comment by amolenaar** [comment]
This is better:

![image](https://user-images.githubusercontent.com/96249/213865247-67c833b0-8d13-4bf3-b340-25a30a78b1eb.png)

**Comment by ebousse** [comment]
indeed, looks great! :+1:
