### ISSUE TITLE
Drag the canvas with the mouse 

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#2028]
Follow-up from  #1377 

Do you consider the possibility to drag the canvas with either the right or the middle mouse button?

I'm personally in favor of being able to drag the canvas with the middle mouse button, as it seems to be quite standard in drawing tools nowadays (eg. GIMP, Inkscape or Draw.io do it). In fact I got so much used to move around the canvas in this fashion in other tools that I feel quite slow in Gaphor currently 😄

**Comment by amolenaar** [comment]
Hi, I did not consider this. Using the middle mouse button is a nice addition indeed.

**Comment by amolenaar** [comment]
I had a look. Gaphas (the canvas library) already has a `pan_tool`. However, somehow it doesn't wor properly if I assign the secondary or middle mouse button. This will require a more investigation.

**Comment by amolenaar** [comment]
I raised an issue. It works fine on macOS, but I could produce a failing example on plain GTK.

https://gitlab.gnome.org/GNOME/gtk/-/issues/5561

**Comment by danyeaw** [comment]
Nice C skills @amolenaar! 😄

**Comment by ebousse** [comment]
Very nice! And it seems your change made it into GTK 4.9.3 released a couple of days ago :)

**Comment by amolenaar** [comment]
Yup. It could still take a few months for GTK 4.10 to be released, though. (4.9.3 is a development release)

**Comment by danyeaw** [comment]
Thanks @ebousse for the enhancement request!
