### ISSUE TITLE
ValueError: Namespace Gtk not available for version 4.0

### ISSUE THREAD

**Issue by murakrishn** [gaphor/gaphor#2034]
### Describe the bug
I am trying to launch gaphor and face the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/gaphor", line 5, in <module>
    from gaphor.ui import main
  File "/usr/local/lib/python3.10/site-packages/gaphor/ui/__init__.py", line 17, in <module>
    gi.require_version("Gtk", gtk_version)
  File "/usr/local/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
```

### Expected behavior
I am expecting to have a successful install of `gaphor`

The above image depicts the errors I receive from the command line.

### OS
- [ ] Linux
- [x ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.15.0

**Comment by amolenaar** [comment]
Hi @murakrishn,

First of all thank yu for giving Gaphor a try :smiley:.

I suppose you followed the instructions on https://gaphor.readthedocs.io/en/latest/macos.html? There's indeed an error: by default Gaphor is using GTK4, but for macOS it's still using GTK3 by default.

You can force gaphor to use GTK3 by setting the environment variable:

```bash
export GAPHOR_USE_GTK=3
```

I updated the docs.

Hopefully we can support GTK4 properly on macOS with the next release of GTK.

**Comment by murakrishn** [comment]
Hi @amolenaar,

Thank you for your quick response! Yes, I followed your instructions and now I am able to launch Gaphor!!

Looking forward to using Gaphor and hopefully contributing to the development of this awesome project!
