### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#204]
GNOME has the concept of symbolic icons. Those icons change color depending on the theme. We should concert our icons (pixmaps) to these symbolic icons, so Gaphor is at least usable in dark mode. 

Also changes to Gaphas are required to support a dark background.

**Comment by lightonflux** [comment]
I couldn't find an issue for a dark background/canvas. Is this already tracked in another issue?

**Comment by amolenaar** [comment]
@lightonflux You can add styling to the model. This styling will be saved as part of a model.

See https://gaphor.readthedocs.io/en/latest/style_sheets.html

![image](https://user-images.githubusercontent.com/96249/106012374-a21ea400-60bb-11eb-9335-17e158c32d30.png)
