### ISSUE TITLE
Model browser: Cramped vertical padding

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#2053]
The padding on these sidebar items is a bit too tight, I'd try adding 2 or 3px the top and bottom on the rows:

![image](https://user-images.githubusercontent.com/1908896/215510191-ae7d6963-8ac5-4bc1-8505-f1dc6767f2a7.png)

**Comment by amolenaar** [comment]
This is the result with adding 1px to top and bottom:

![image](https://user-images.githubusercontent.com/96249/215539925-ed7e8d55-5c0d-41cb-b028-365e5b939ef0.png)

And 2 px top and bottom:

![image](https://user-images.githubusercontent.com/96249/215540238-07b7d61a-4bcf-4941-add9-59979dfc1e49.png)

**Comment by bertob** [comment]
2 is definitely an improvement, yeah. I'd maybe try 3 and 4 just to compare against, but could also just land 2px and maybe iterate further later.

**Comment by amolenaar** [comment]
I tried 3px, but it seemed a bit to spacious.
