### ISSUE TITLE
GNOME CoC

### ISSUE THREAD

**Issue by sophie-h** [gaphor/gaphor#2064]
GNOME Circle projects automatically fall under GNOME's Code of Conduct. I would suggest replacing the current CoC with GNOME's for clarification.

https://gitlab.gnome.org/Teams/Circle#code-of-conduct

We recommend linking the CoC in the README file as well, but issue/MR templates is also perfectly fine.

**Comment by amolenaar** [comment]
Hi @sophie-h,

Thank you for bringing this to our attention. Does this mean that we can also rely on support from the GNOME project, if a voilation to the CoC occurs?

**Comment by danyeaw** [comment]
@all-contributors please add @sophie-h for ally

**Comment by danyeaw** [comment]
https://github.com/all-contributors please add @sophie-h for a11y

**Comment by danyeaw** [comment]
@all-contributors please add @sophie-h for a11y

**Comment by sophie-h** [comment]
> Does this mean that we can also rely on support from the GNOME project, if a voilation to the CoC occurs?

Yes, the GNOME CoC Committee sees itself as responsible for all Circle projects.
