### ISSUE TITLE
Button for right sidebar does not represent sidebar state

### ISSUE THREAD

**Issue by lightonflux** [gaphor/gaphor#2071]
### Describe the bug
The button that toggles the sidebar on the right does not represent the state (open/closed) of the sidepanel. 

### To Reproduce
1. Press the button
2. Watch if the button changes

### Expected behavior
The button should change. Either by being in a pressed state or an icon change. 

#### Open
![grafik](https://user-images.githubusercontent.com/1377943/216841983-0708af73-0afc-46ac-8fb1-2bf89ffe694c.png)

#### Closed
![grafik](https://user-images.githubusercontent.com/1377943/216841966-c709b85f-4a8d-4fb3-92f9-449a79e49e07.png)

### Comparison with gnome-builder

See button for the left sidebar

#### Closed
![grafik](https://user-images.githubusercontent.com/1377943/216842224-2c2ae4d6-c4fe-4cad-9bae-f43730c6ba48.png)

#### Open
![grafik](https://user-images.githubusercontent.com/1377943/216842231-a1788c1b-0d37-458d-98be-b09e97396886.png)

### OS
- [x] Linux flatpak
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.16.0

**Comment by amolenaar** [comment]
Hi @lightonflux, Thank you for pointing this out. Indeed, it would be nicer if the button state represents the sidebar state.

**Comment by amolenaar** [comment]
It was a simple fix. I'm happy you pointed it out.

Thanks again!

**Comment by danyeaw** [comment]
@all-contributors please add @lightonflux for bug
