### ISSUE TITLE
Support allocations

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2087]
### Is your feature request related to a problem?

["Allocation is a mechanism for associating elements of different types, or in different hierarchies, at an abstract level."](https://support.ptc.com/help/modeler/r9.2/en/index.html#page/Integrity_Modeler/sysml/SysML_Allocate.html). It is common practice that a functionality (activities) trace your requirements and functionality allocates functionality to a physical domain.

### Describe the solution you'd like

Ideally, full SysML 1.6 support for allocations would be desirable, but simply <<allocate>> connection would be sufficient.

### Describe alternatives you've considered

I can see that `Allocate` is mentioned in the codebase, but not exposed by a selectable tool.

### Additional context

As mentioned in the description, allocations involve many things and it may not be feasible to not have allocations at all until full support is implemented. A connection would be sufficient. This needs some investigation into SysML 1.6 specification.

**Comment by amolenaar** [comment]
`Allocate` is a kind of `Dependency`. I would probably extend the `Dependency` item to support `Allocate`. Are there any specific rules we can apply so `Allocate` is automatically selected? I suppose the target should be a behavior and the source a classifier?

**Comment by marek-piirikivi** [comment]
Here's what I found out from the [specification](https://sysml.org/.res/docs/specs/OMGSysML-v1.6-19-11-01.pdf) starting from the page 171 (or 199 in physical pages). There is an entire chapter dedicated to allocations.

Allocations is a crosscutting construct. This means that it does not belong to any of the diagrams.

> Allocate is a kind of Dependency

According to the specification, `allocate` relationship is specialization of  `DirectedRelationshipPropertyPath`.

> I suppose the target should be a behavior and the source a classifier?

"Allocate is directional in that one NamedElement is the "from" end (no arrow), and one NamedElement is the "to" end (the end with the arrow)." [p174, 2nd paragraph]. So it seems that it connects any two `NamedElement`s.

Allocation can indeed get much more complicated, because not only can you form allocations between two elements, but you can also apply allocation relationship on connectors as well.

> Are there any specific rules we can apply so Allocate is automatically selected?

I do not understand that question.

**Comment by amolenaar** [comment]
From what you quote from the specs it would indeed be a separate model element.

In our model, `Allocate` also inherits from `Abstraction`, which is a kind of dependency. Yet, it has a lot more going on, so it's not _just_ a dependency. Hence a separate (toolbox) entry would make sense.

> > Are there any specific rules we can apply so Allocate is automatically selected?
> I do not understand the question.

Never mind, I was too much thinking solutions.

**Comment by marek-piirikivi** [comment]
> In our model, Allocate also inherits from Abstraction, which is a kind of dependency.

I copied the diagram from the specification and indeed, it inherits from Abstraction (if I read the symbols correctly).
![image](https://user-images.githubusercontent.com/45357878/218684416-37c5b40f-7bde-46ad-8d0f-b01f6b1565d7.png)

> Never mind, I was too much thinking solutions.

My mind was in the problem domain trying to figure out:
1. whether we want to do this; and
2. the scope when we do this (only connection? Full support?) - the specifics

I think we should do this (1) purely because it is defined in SysML 1.6 specification and we do not have this. Some modellers (including myself) may find it useful in their modeling flow.

For (2), I personally would already be pleased with just an ability to select `allocate` connection from the toolbox and form a connection between any two `NamedElement`'s. However, we should also be forward-compatible in case we want to improve allocations support in the future. This means that we should take full allocation support into consideration when making decisions to implement just a connection part of it.

**Comment by marek-piirikivi** [comment]
Closing this because minimal needs has been met. Issue(s) to extend options on how to describe allocations should be opened separately.
