### ISSUE TITLE
AttributeError: 'MultiSelection' object has no attribute 'get_selected'

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#2107]
### Describe the bug
In the left side thing, I right-clicked on "New Diagram" in the tree under "New model".

### To Reproduce
1. Open up "New model" in the tree.
2. Right click to the empty blank space left of the icon on "New model"

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
No idea.

### OS
- [x] Linux (Ubuntu 22.10)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.17.0

### Additional information
    Gaphor version:    2.17.0
    Operating System:  Linux (5.19.0-31-generic)
    Python version:    3.10.6
    GTK version:       4.8.3
    Adwaita version:   1.2.2
    PyGObject version: 3.42.2
    Pycairo version:   1.23.0
    Cairo version:     1.16.0
    Pango version:     1.50.12
    Display:           GdkWaylandDisplay
    
    
    Errors:
    
    Time since application startup: 0:00:42
    |Traceback (most recent call last):
    |  File "/app/lib/python3.10/site-packages/gaphor/ui/treecomponent.py", line 354, in on_show_popup
    |    selection.unselect_item(selection.get_selected())
    |    │                       └ <Gtk.MultiSelection object at 0x7fd6a3a8fc00 (GtkMultiSelection at 0x559944161750)>
    |    └ <Gtk.MultiSelection object at 0x7fd6a3a8fc00 (GtkMultiSelection at 0x559944161750)>
    |AttributeError: 'MultiSelection' object has no attribute 'get_selected'. Did you mean: 'get_selection'?
    └─────────────────────────────╌┄┈

**Comment by danyeaw** [comment]
Hi @vanillajonathan, thanks, I can reproduce this. I think the expected behavior would be that right-clicking to the left of objects does nothing.

**Comment by vanillajonathan** [comment]
I think it should probably bring up a context menu, because it shouldn't matter where on the row you click. I see the whole row as one unit.

**Comment by danyeaw** [comment]
That makes sense to me as well.

**Comment by amolenaar** [comment]
Crap. I never tried _that_.

Nice find, @vanillajonathan !
