### ISSUE TITLE
Dragging magnet results in TypeError

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#2119]
### Describe the bug
Draggong the Magnet (F1) to the diagram crashes.

### To Reproduce
1. Go to Magnet (F1) under General
2. Drag it to the right to the model

### Expected behavior
No idea.

### OS
- [x] Linux (Ubuntu 23.04-daily)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.17.0

### Additional information
```
Gaphor version:    2.17.0
Operating System:  Linux (6.1.0-16-generic)
Python version:    3.10.6
GTK version:       4.8.3
Adwaita version:   1.2.2
PyGObject version: 3.42.2
Pycairo version:   1.23.0
Cairo version:     1.16.0
Pango version:     1.50.12
Display:           GdkWaylandDisplay


Errors:

Time since application startup: 0:00:07
|Traceback (most recent call last):
|  File "/app/lib/python3.10/site-packages/gaphor/diagram/tools/dnd.py", line 56, in on_drop
|    create_item(view, tool_def.item_factory, x, y)
|    │           │     │                      │  └ 296.90234375
|    │           │     │                      └ 266.7890625
|    │           │     └ ToolDef(id='toolbox-magnet', name='Magnet', icon_name='gaphor-magnet-symbolic', shortcut='F1', item_factory=None, handle_index=-...
|    │           └ <gtkview.GtkView object at 0x7f79b18c2f00 (GaphasView at 0x56230bc4ff90)>
|    └ <function create_item at 0x7f79b1d0caf0>
|  File "/app/lib/python3.10/site-packages/gaphor/diagram/tools/placement.py", line 68, in create_item
|    item = factory(view.model, parent)
|           │       │           └ None
|           │       └ <gtkview.GtkView object at 0x7f79b18c2f00 (GaphasView at 0x56230bc4ff90)>
|           └ None
|TypeError: 'NoneType' object is not callable
└─────────────────────────────╌┄┈
```

**Comment by amolenaar** [comment]
Ah, You Dnd'ed the magnet. That doesn't work indeed. The same if you drag the Pointer icon.

The idea of the magnet is that you move all elements right or below (depending on your movement) the mouse button. It's a feature originally in MagicDraw IIRC.

I think it would be best if both buttons can not be dragged at all. We should also add some documentation on the icons. Maybe a short description on the tooltip will already help.

**Comment by vanillajonathan** [comment]
If it cannot be dragged it shouldn't show the mouse cursor for dragging when holding down the mouse button and moving the mouse.
