### ISSUE TITLE
Support for Adding Diagrams to Diagrams

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2124]
### Is your feature request related to a problem?
I would like to be able to create a Model Navigation to more easily link to the important diagrams in a model.

### Describe the solution you'd like
I want to be able to drag and drop diagrams on to a diagram, preferably with different icons for the different diagram types.

For example, with our SysML template, I want to create a Model Navigation that looks like this with diagram icons added:
![image](https://user-images.githubusercontent.com/10014976/222923544-80f466f8-1fcd-418d-b0c1-9f19d32ff5b8.png)

or a similar example from the MagicGrid method:
![image](https://user-images.githubusercontent.com/10014976/222923646-24d1041d-e6bf-49c8-bdd6-5c1dc881972f.png)

### Describe alternatives you've considered
No Model Navigation

**Comment by amolenaar** [comment]
Sounds reasonable :). I suppose we can do that pretty quickly. Only we cannot have different icons for diagram types.

**Comment by amolenaar** [comment]
How would this work? Currently we double-click to open a diagram. Double-click on any other element adds it to the diagram. We can use DnD. I suppose we should also provide an entry in the popup menu.

**Comment by danyeaw** [comment]
Yup, I think drag and drop would be the way.

**Comment by amolenaar** [comment]
Should there be any additional behavior to the diagram, once added to a diagram?

I suppose we want to let it open the diagram. On double-click?
