### ISSUE TITLE
Add Support for SysML ItemFlow on Associations

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2125]
### Is your feature request related to a problem?
I want to be able to create a Feature Context Diagram with ItemFlows on the Associations:
![image](https://user-images.githubusercontent.com/10014976/222927569-09fc8c39-8f6e-4b16-8e2f-ac19b9f5c273.png)

### Describe the solution you'd like
In #1192 we implemented ItemFlows on Connectors, I would also like to have them on Associations.

### Describe alternatives you've considered
Use an Internal Block Diagram for the context diagram instead.

**Comment by amolenaar** [comment]
Fixed by #2312.
