### ISSUE TITLE
Autolayout is Inverting BDDs

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2126]
### Describe the bug
Autolayout is inverting BDDs:
![image](https://user-images.githubusercontent.com/10014976/222927765-84aa3c94-131b-4010-a0e1-868010bbe3e8.png)

### To Reproduce
1. Create a BDD
2. Tools -> Autolayout

### Expected behavior
I would expect that when doing autolayout on a BDD that is goes from top to bottom with the main part on the top and the parts contained within to be below. Something like this:
![image](https://user-images.githubusercontent.com/10014976/222927739-d176f83b-91a3-4785-89fa-329556fa79fe.png)

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main

**Comment by amolenaar** [comment]
This may be a tricky one. The direction in which the diagram is rendered depends on the direction (head, tail) of the association. If you would've added the association the other way around, you would probably end up with the desired result.

What we can do is check for aggregation type on associations.

https://github.com/gaphor/gaphor/blob/main/gaphor/plugins/autolayout/pydot.py#L272

**Comment by danyeaw** [comment]
Closed by #3479.
