### ISSUE TITLE
Add support for UML ball-and-socket notation

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#2133]
### Is your feature request related to a problem?
I would like to use the ball-and-socket notation in UML diagrams but while Gaphor does have support for interfaces it does not seem to have support for the ball-and-socket notation.

### Describe the solution you'd like
Add support for UML ball-and-socket notation.

### Additional context
https://www.uml-diagrams.org/component-diagrams-reference.html

![image](https://www.uml-diagrams.org/component-diagrams/assembly-connector-simple-port.png)

**Comment by amolenaar** [comment]
Hi, this is already possible.

![image](https://user-images.githubusercontent.com/96249/223673736-390ce983-3332-42a7-8369-e3cb58c961f9.png)

On the interface, you have to toggle the _Folded_ switch.
The link from `ICustomers` to `Customers` is an _Implementation_, and the link from `Authentication` to the `ICustomers` is a _Dependency_.

**Comment by vanillajonathan** [comment]
Thanks for clarification, I got it working now. It seems I can do all kinds of crazy things such as connecting containment and composite association to an interface. Maybe Gaphor should somehow guide me and/or prevent me from doing silly things.

**Comment by amolenaar** [comment]
> Thanks for clarification, I got it working now. It seems I can do all kinds of crazy things such as connecting containment and composite association to an interface. Maybe Gaphor should somehow guide me and/or prevent me from doing silly things.

Containment sounds fair: an interface is a namespace element. 

Associations I'm not sure. If you look purely at the [class structure](https://docs.gaphor.org/en/latest/models/uml/03._Classification.html#properties), it's allowed. It may be that there are some constraints wrt to using associations with interfaces.

**Comment by vanillajonathan** [comment]
Alright, but maybe there are some things that I can do that I shouldn't be able to do, it would be good if Gaphor would prevent me from doing silly things that I shouldn't do.

**Comment by danyeaw** [comment]
#2086 is already about constraining elements on diagrams. I am all for it because it makes the tool easier to use - as long as we don't make it ultra rigid.

Since ball and socket is supported, closing this one.
