### ISSUE TITLE
Multiple windows/models opened in one application

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#214]
### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

### Current behavior

Currenly, only one model can be opened at a time.

### Expected behavior

I'd like t be able to open multiple models. This is more in line with the model of the average application.

copy objects between them

### If this is a feature request please fill out the following:
<pre><code>
As a (user, developer, contributor, etc):
I want to open more than one model at a time
So that I can peek at it, copy from it, etc.
</code></pre>

NOTES:

* Are we going multi-window, or use stacks, such as Glade does?
* Some state changed, e.g. from the canvas, are emitted through a global event dispatcher. This should either be made non-global or we need a way to deal with it (see also next point)
* Many methods use a `@transactional` decorator. It's easy to make an action transactional, however, state is global again.
* Which services should be global (e.g. copy) and which should not be (e.g. undo-manager)

**Comment by danyeaw** [comment]
I ran in to this today as well while trying to start to create SysML and other profiles. We may be able to tackle this in multiple steps:

1. Allow two versions of Gaphor to be able to run in parallel with multiple-windows, even if you can't copy-paste between them
1. Allow copy-paste
1. Determine if we want other further integration. Do we need to be able to open a project in a new window? or just have users always open another copy of Gaphor for a 2nd model.

**Comment by amolenaar** [comment]
Do we want new windows or "tabs"/stacks in the main window (like Glade does it)?

I though of creating a set of "appservices", which live on application level. All normal services remain on window level. The one app service I can think of is the `file_manager`. There should be some mechanism that channels events from Gaphas and `@transactional` decorations to the right "window", with their set of services (`event_manager`, `element_factory`, etc.).

Copy/paste is possibly also one of those services that should eventually end up at app level as well.

Step 0 would then be to create a service that forwards those events. that would allow the parallel window mode at least.

**Comment by amolenaar** [comment]
Hmm.. We need some rules on how to handle multiple sessions active in Gaphor

I define a _session_ as a window containing a model (or new template).

* Start gaphor (`activate` callback):
  * with no instance running -> start Gaphor with a new model template
  * with a running instance with a model or new template -> focus Gaphor, change nothing
* Start `gaphor model.gaphor` (`open` callback):
  *  with no instance running -> start Gaphor and load the model file
  * with running instance and fresh (unchanged) new template -> load model in *active* session
  * with running instance and fresh (unchanged) model -> load model in *new* session
  * with running instance and changed model -> load model in *new* session

**Comment by danyeaw** [comment]
With a running instance with a model open, I would expect that running `gaphor` would start gaphor with a new model template instead of focusing Gaphor
