### ISSUE TITLE
Clean up GTK+ 3 code

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2142]
Now that GTK 4.10 has been released, and we can finally build our macOS packages with GTK4, we can clean up the code base.

- [x] Update documentation (macOS)
- [x] Remove uses of `Gtk.get_major_version()`
- [x] Remove `GAPHOR_USE_GTK` from the code and build scripts
- [x] Remove `GAPHOR_PKG_GTK` from the packaging code
- [x] Remove GTK+3 only tests
- [x] Remove markers for GTK4-only tests
- [x] Remove builder functions for `.glade` files
- [x] Remove all `.glade` files
- [x] Remove GTK+3 specific modules, such as `hoversupport`
- [x] Remove GTK+3 specific styling

Did I miss something?

**Comment by danyeaw** [comment]
Closed by #2146
