### ISSUE TITLE
Export Language overwrite

### ISSUE THREAD

**Issue by cloud-erik** [gaphor/gaphor#2162]
### Is your feature request related to a problem?
At the moment laguage for GUI and export is derived from system laguage. Even if the model itself is language independet, it is only possible to export drawings in system laguage.
So I could not use gaphor for projects or publications with language =! system laguage.

### Describe the solution you'd like
For publication or interaction in international projects, it would be great to set (at least export-) laguage independet from system language.

### Describe alternatives you've considered

- Change of system language to project language. But this is not convinient if you would like to work in system in local laguage or if system language is set by administrator.
Also switching back and forward could happen if working for projects with different languages.

- Changing source code of e.g. https://github.com/gaphor/gaphor/blob/a16d18c33609c4b1c7544da5daa1758bef53de7e/gaphor/i18n.py local and overwrite language.

### Additional context
When working in a international environment, it would be helpfull, if its possible to set laguage of exported drawings different from loacal laguage.
E.g., you work in a project with aggreed project laguage is English but team is globaly distributed, it would be nice if language (at least for export) could be set independend from system language.

Other used case would be, if translation in local laguage is not suficient.

See also #1176

**Comment by amolenaar** [comment]
Hi @cloud-erik, thank you for your report.

I do not think I understand. The system language is only used for the GUI. The models/diagrams do not have any internationalization support. You can use whatever language you agree upon, independent of the system language.

**Comment by cloud-erik** [comment]
Hi @amolenaar thanks for pointing me to that point. Maybe I am just misunderstading the model or structure.
Let me try to explaine a little more on following exmaple.
If I have a PC with local laguage German and I create e.g. a requirement it is created with type "Anforderung", which is the germand translation of requirement. I found no way to translate or rename that when I export to pdf, png or eps.
Same also for other elements.
So If would like to create a English drawing, only way is to change system language (if I have it installed and I am allowed to).
Please see attached example where marked parts which I could not translate so far.
![Requirement](https://user-images.githubusercontent.com/67910530/226382488-9427d952-b449-442f-8212-4ca46c48d903.jpg)

And I would be happy, if it would be possible to set language (for everything or just export) independent from system. In my example to English.

**Comment by amolenaar** [comment]
Ah! I totally forgot about those. Indeed, some default stereotypes and keywords are translated. My bad.

It sounds very reasonable to change the translation for those terms. Maybe introduce a "model language", so the terms match the language used in the model?

**Comment by amolenaar** [comment]
There's a few places where the "model language" (natural language) is important:

1. Whenever shapes are updated
    a. When performing the `update` of presentations -- also `ElementPresentation.update_shapes()`
    b. In the `postload()` method (shapes are updated there)
1. When presentations are drawn (`Presentation.draw()`, export, maybe the painter tools)
1. When presentations and diagrams are created 

I suppose the challenge is to add proper tests :wink:

**Comment by peter88213** [comment]
I made the same bad experience as @cloud-erik. For me, it makes no sense at all to translate common UML stereotypes, for example. 

Anyway, I would rather have the whole thing in English, including the user interface. 

By the way, I find Gaphor quite good as a lightweight replacement for Papyrus. After updating to the current version, I have the impression that Gaphor has become more stable.

**Comment by amolenaar** [comment]
> I made the same bad experience as @cloud-erik. For me, it makes no sense at all to translate common UML stereotypes, for example.

Unfortunately people have different preferences. We try to keep the configuration options to a minimum (also saves a lot of errors).

> By the way, I find Gaphor quite good as a lightweight replacement for Papyrus. After updating to the current version 2.17.0, I have the impression that Gaphor has become more stable.

Thank you. We're working on improving the stability and usability. Nothing is as frustrating as an app that just crashes or does other weird things.

> EDIT: In the meantime, I was able to solve the problem myself by simply deleting the German localization. Never mind.

That's one way of solving it.

**Comment by peter88213** [comment]
> > For me, it makes no sense at all to translate common UML stereotypes, for example.
> 
> Unfortunately people have different preferences. We try to keep the configuration options to a minimum (also saves a lot of errors).

However, this is not about matters of taste, but about the UML metamodel. As far as I know, this is not country-specific, is it?

**Comment by cloud-erik** [comment]
> EDIT:
> In the meantime, I was able to solve the problem myself by simply deleting the German localization. Never mind.
Good idea for a quick and dirty workaround - Thanks foir sharing.


> > > For me, it makes no sense at all to translate common UML stereotypes, for example.
> > 
> > 
> > Unfortunately people have different preferences. We try to keep the configuration options to a minimum (also saves a lot of errors).
> 
> However, this is not about matters of taste, but about the UML metamodel. As far as I know, this is not country-specific, is it?

Thats also my understanding, but as @amolenaar already said, people have different preferences ;-).
But I like Idea of model language. Maybe it would make sense to implement a model language with default EN?

> EDIT:
> In the meantime, I was able to solve the problem myself by simply deleting the German localization. Never mind.

Good idea for a quick and dirty workaround - Thanks for sharing.

**Comment by danyeaw** [comment]
@all-contributors please add @cloud-erik for idea
