### ISSUE TITLE
Cannot export diagram with a special character in its name

### ISSUE THREAD

**Issue by peter88213** [gaphor/gaphor#2179]
### Describe the bug
Exporting a diagram with a slash in its name to SVG raises an unhandled exception.

### To Reproduce
1. Create a diagram with a slash in its name, e.g. "Scenes / Story Arc relationships"
2. Start SVG export.

Error log:
```
Gaphor version:    2.17.0
Operating System:  Windows (10)
Python version:    3.11.2
GTK version:       4.8.3
Adwaita version:   1.2.1
PyGObject version: 3.42.2
Pycairo version:   1.23.0
Cairo version:     1.17.8
Pango version:     1.50.12
Display:           GdkWin32Display


Errors:

Time since application startup: 0:00:10
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\gaphor\ui\actiongroup.pyc", line 191, in _action_activate
|  File "C:\Program Files\Gaphor\gaphor\plugins\diagramexport\__init__.pyc", line 55, in save_svg_action
|  File "C:\Program Files\Gaphor\gaphor\plugins\diagramexport\__init__.pyc", line 29, in save_dialog
|  File "C:\Program Files\Gaphor\pathlib.pyc", line 674, in with_name
|ValueError: Invalid name 'Scenes / Story Arc relationships'

```
### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.17.0

### Additional information
Obviously, the slash in the diagram's name conflicts with the path name generation.
I recommend stripping special characters from the diagram's name (or replace them with underscores) when auto-generating a file name from it.

**Comment by amolenaar** [comment]
Hi @peter88213, thank you for the issue.

Indeed replacing or escaping special characters would be the way to go I think. I wonder if Python already has a function for that :thinking:.

**Comment by peter88213** [comment]
> I wonder if Python already has a function for that

You might wish to try this:
```
import re
diagramName = 'Scenes / Story Arc relationships'
recommendedPath = re.sub('\W', '_', diagramName)
recommendedPath
```

**Comment by amolenaar** [comment]
@peter88213 Thanks. This regex works pretty well, even with unicode characters.

**Comment by danyeaw** [comment]
@all-contributors please add @peter88213 for bug
