### ISSUE TITLE
Font setting in stylesheet does not affect diagram contents

### ISSUE THREAD

**Issue by peter88213** [gaphor/gaphor#2180]
### Describe the bug
Setting the font family in the stylesheet affects the diagram label, but not the diagram contents.

### To Reproduce
1. Edit "font-family" in the style sheet. Set e.g "Ink Free"
2. Only the diagram label is rendered in the selected font. The characters in the diagram look like the standard font.

### Expected behavior
All characters in the diagram should be rendered in the selected font.

### Screenshots
![screen](https://user-images.githubusercontent.com/42072564/227784221-9bf42a48-0288-4599-bc74-7a96dafa72b6.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.17.0

**Comment by amolenaar** [comment]
Hi,

This is correct. You apply the `font-family` to the diagram element, not to all elements. Elements in the diagram are not considered child elements of a diagram.

Hence, if you redefine the CSS as:

```css
* {
 font-family: serif;
}
```

All elements will pick up the font.

See also https://docs.gaphor.org/en/latest/style_sheets.html#diagram-styles.

**Comment by peter88213** [comment]
My fault, sorry. Thank you for the clarification.

**Comment by amolenaar** [comment]
The example in the docs is wrong:

https://docs.gaphor.org/en/latest/style_sheets.html#the-drafts-package
