### ISSUE TITLE
Adding model root element to diagram then deleting element from diagram deletes whole model

### ISSUE THREAD

**Issue by skalemkiewicz** [gaphor/gaphor#2181]
### Describe the bug
If the model root element is added to a diagram and then the element is deleted from the diagram, the application deletes the entire model.

### To Reproduce
1. Open Gaphor.
2. Create New Model -> Generic. Gaphor creates a new model.
3. Open settings, ensure that "Remove Unused Elements" is enabled.
4. In the left pane, expand the model's root node to expand the default diagram.
5. Open the diagram.
6. Drag the model's root node from the left pane onto the diagram. Gaphor creates a package element on the diagram.
7. Select the package element that is on the diagram and delete it. Gaphor will remove the element from the diagram but will also remove the root node from the model in the left pane leaving only the diagram.

### Expected behavior
Gaphor should only remove the element from the diagram, not delete the entire model.

### Screenshots
![Before](https://user-images.githubusercontent.com/938809/227799184-e1062851-eea5-488e-80f6-2c9d3cb0de04.png)

![After](https://user-images.githubusercontent.com/938809/227799201-27ea7c9d-a687-4779-b4c1-ea510d5acd04.png)

### OS
Linux Pop!_OS 22.04 LTS

### Version
Version of Gaphor: 2.17.0

### Additional information
Output from error report:

Gaphor version:    2.17.0
Operating System:  Linux (6.2.6-76060206-generic)
Python version:    3.10.6
GTK version:       4.10.1
Adwaita version:   1.3.1
PyGObject version: 3.44.0
Pycairo version:   1.23.0
Cairo version:     1.16.0
Pango version:     1.50.14
Display:           X11Display

No errors have been intercepted. We’re good.

**Comment by danyeaw** [comment]
Hi @skalemkiewicz, thanks for the bug report! It sounds like we need to check that an item doesn't have any nested or children items before removing it.

**Comment by skalemkiewicz** [comment]
Hi @danyeaw, you're welcome! That seems reasonable -- or even to walk all of the child elements to see if they are being used before deleting. I guess it depends on how this feature was envisioned to be used. 

In Sparx Systems's Enterprise Architect, deleting an element from a diagram using the delete key will only remove the element from the diagram but keep it in the model. If you really want to remove the element from the diagram and the model, it requires a user to SHIFT+DELETE.

**Comment by skalemkiewicz** [comment]
Sorry, clicked the wrong button and accidentally closed the ticket instead of just posting the comment.

**Comment by amolenaar** [comment]
If you want Sparx-like behavior, you can disable the "Remove Unused Elements" option in the preferences.

Normally, when an element is removed, all nested elements are removed as well (e.g. a class and it's attributes).

**Comment by skalemkiewicz** [comment]
> If you want Sparx-like behavior, you can disable the "Remove Unused Elements" option in the preferences.
> 
> Normally, when an element is removed, all nested elements are removed as well (e.g. a class and it's attributes).

Thanks. That makes sense. 

 I wasn't really recommending that a similar behavior be implemented. Just pointing out one alternative approach I saw in case others weren't aware of it. 

I should add that if I turn off this feature in the settings and follow the steps I outlined, the root node won't be deleted. Instead, the diagram is unnested from the root node.

**Comment by danyeaw** [comment]
I think this is still surprising behavior, removing something from a diagram makes sense to delete that thing, it doesn't make sense to delete everything under it recursively

**Comment by amolenaar** [comment]
> I think this is still surprising behavior, removing something from a diagram makes sense to delete that thing, it doesn't make sense to delete everything under it recursively

When you delete an element, all composite elements are removed as well (e.g. classes with attributes). Most owner relations (the one you see in the model browser) are composite.

I had another look at this. I think the behavior is okay. By removing the package, you're not removing the model, just a package. You can create new packages without a presentation in a diagram from the model browser popups (right click), or create them in a diagram if you prefer.

Gaphor tries to keep the [model and diagrams in sync](https://docs.gaphor.org/en/latest/design_principles.html#keep-the-model-in-sync).

**Comment by danyeaw** [comment]
With this behavior as it is, Gaphor is not just cleaning up, it is being destructive. It is removing elements that could be appearing on many diagrams. The option says to Remove unused elements, if a package has elements nested in it - it is definitely still being used.

**Comment by amolenaar** [comment]
> With this behavior as it is, Gaphor is not just cleaning up, it is being destructive. It is removing elements that could be appearing on many diagrams.

... but they are not, since there are no other presentations, hence the element can be removed. At least, that's how the current logic is reasoning.

> The option says to Remove unused elements, if a package has elements nested in it - it is definitely still being used.

So far I considered an element unused, if there are no presentations in any diagram. This is a different (equally valid) definition of what it means to remove unused elements. A less surprising one, probably :smiley:.

We can pretty easy adapt the behavior, by adding a `deletable` function for `Package`. Would there be any other elements that should be considered packages for other elements? Such as Activity, Interaction, a Class with a nested Class?

**Comment by danyeaw** [comment]
Thanks @skalemkiewicz for this bug report, this is now fixed.
