### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#220]
### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

### Current behavior

All text is in English.

### Expected behavior

Adapt the language to your language of choice. Gaphor used to support a couple of languages, but this feature has been lost in the upgrade process.

### Minimal reproduction of the problem with instructions

Something like `LANG=nl gaphor`?

**Comment by danyeaw** [comment]
Closed by #236.
