### ISSUE TITLE
Add General Support for Code Import to generate a single UML map of a codebase.

### ISSUE THREAD

**Issue by duaneking** [gaphor/gaphor#2214]
### Is your feature request related to a problem?
I'm trying to map a very large code base; I cannot find a single tool that is open source and free that allows me to simply scan the directory support the model as UML.  I'm finding a lot of proprietary software that claims to be open source that is completely neutered and ineffective and unable to do its job without a third party plugin or component that you have to buy for an excessive amount of money.

### Describe the solution you'd like
I would like to be able to point the tool at a directory containing source code in C#/Java and export a UML.

### Describe alternatives you've considered
I have literally tried everything I can think of. The prior open source solutions have all been taken off of the market by their authors and made closed source/expensive. In addition, many non-functional abandoned solutions seem to litter the landscape and make it that much harder to find a solution.

### Additional context
Adding code import to UML support for languages in general would be amazing and actively put this project on the map as a project worth investing time and energy in.  I cant easily add languages without the initial support that doesn't currently exist.

**Comment by danyeaw** [comment]
Hey @duaneking, sorry you are having trouble finding an open source tool to your liking, and thanks for the suggestion. This doesn't sound like our focus right now for this project. This is also a similar request for importing Python code at https://github.com/gaphor/gaphor/issues/1363, but it sounds like you are looking for something more general for a C# or Java project.

Are you interested in contributing support for this?

**Comment by duaneking** [comment]
I responded in the other thread.

**Comment by danyeaw** [comment]
Thanks again @duaneking for the feature request. We have updated the README to make it more clear that this isn't one of our goals for the project.
