### ISSUE TITLE
Implement OIDC client

### ISSUE THREAD

**Issue by kuwv** [gaphor/gaphor#2235]
### Is your feature request related to a problem?

Connecting to other MBSE services would require gaphor to have OIDC support. This would not only allow gaphor authentication and authorization to other services but the ability for plugins to use this.

### Describe the solution you'd like

Implement an OIDC client using Authorization Code Flow w/ PKCE.

### Describe alternatives you've considered

This could definitely be done in a plugin but some plumbing may need to be done so that calls to resources can auth.

### Additional context

https://www.oauth.com/oauth2-servers/pkce/

**Comment by danyeaw** [comment]
Hi @kuwv, what use case is this for? Sure, connecting to a service may need some authentication to login, but what service do you want to login to with Gaphor?

**Comment by kuwv** [comment]
@danyeaw this would be a requirement to implement OSLC. If you don't implement that then you can close this.

**Comment by amolenaar** [comment]
Let's close this issue, then. We'll run into it if we start implementing an OSLC client.
