### ISSUE TITLE
Action Diagram: cannot connect fork/join node with object flow

### ISSUE THREAD

**Issue by Reissner** [gaphor/gaphor#2278]
### Describe the bug
Well, it is what i write in the headline: 
If I create an action diagram all works fine, except the fork join node: 
This i can drag to the canvas, but i cannot connect it. 
Maybe I am doing it wrong, but gaphor does not treat it like the other nodes. 

### To Reproduce
1 create Action diagram in sysml, 
2 put some node, e.g. object node, 
3 put some fork/join node, 
4 try to connect (object flow does not work, whereas control flow does)

No error report

### Expected behavior
I would have expected, that both control flows and object flows work. 
The latter even more important. 

### OS
- [suse tumbleweed ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.18.1

**Comment by danyeaw** [comment]
Thanks @Reissner for submitting this, I can reproduce this and I agree that it should work to connect Object Flows to the Fork/Join Node. :+1:

Would you be interested in helping to fix this?

**Comment by mikekidner** [comment]
@danyeaw Would the right place to start solving this be the tests in 
`/UML/actions/tests/test_flowconnect.py:    """Base class for flow connecting to decision and fork nodes.`

I've also come across this bug, and would like to try and fix it.

**Comment by danyeaw** [comment]
Hi @mikekidner! Check out the flowconnect module:
https://github.com/gaphor/gaphor/blob/main/gaphor/UML/actions/flowconnect.py#L225

It has Control Flows registered, but not Object Flows.

**Comment by mikekidner** [comment]
@danyeaw see L56 and L89 of flowconnect.py. I've added "or" to check if line is ObjectFlowItem or ControlFlowItem. Tests pass again.

**Comment by danyeaw** [comment]
Hey @mikekidner, nice, do you want to go ahead and push that update?

**Comment by mikekidner** [comment]
Yep, sorry - I committed to main instead of the branch! Oops.

**Comment by amolenaar** [comment]
Closed by #2383
