### ISSUE TITLE
Consider extra steps to avoid malicious code injections

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2288]
### Is your feature request related to a problem?

Would it be worth to check our dependencies as described in this [blog from Phylum](https://blog.phylum.io/bad-beat-poetry/)? It could help in the case our lock file is tampered with and malicious dependencies have been injected.

**Comment by danyeaw** [comment]
Hi @amolenaar, thanks for sharing that, I learned something new today! I think this is a good idea.
