### ISSUE TITLE
Create a Wikipedia Page for Gaphor

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#233]
### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [X] Documentation issue or request

Gaphor isn't found on Wikipedia, and is absent in the list of UML tools. It would be great if it was represented. Creating a wiki page is some work, see this [overview](https://contentmarketinginstitute.com/2011/11/how-to-develop-a-wikipedia-page/).

**Comment by TheElementAce** [comment]
I'll knock this out by the end of the week!

**Comment by danyeaw** [comment]
@TheElementAce That would be great, thanks!

**Comment by danyeaw** [comment]
@amolenaar also pointed out on Gitter that there use to be a wiki page:
https://web.archive.org/web/20120726084205/http://en.wikipedia.org/wiki/Gaphor

It looks like it was removed since it didn't meet the Wikipedia standards.

**Comment by danyeaw** [comment]
@TheElementAce Are you still interested in helping out with this?

**Comment by TheElementAce** [comment]
Yes I am!

I'm not sure why didn't get a notification on this thread until now. Sorry about that. If it's cool with you, I'd like to get this rolling again.

**Comment by danyeaw** [comment]
@TheElementAce That would be great :+1:

**Comment by TheElementAce** [comment]
Excellent

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheElementAce** [comment]
I've made a slack channel, since we'll likely be conversing often. Would you rather speak in Slack:

https://join.slack.com/t/overheadindustries/shared_invite/enQtODc3NjkzMTYxMDc5LWIxMTgyMjgxMDI1MWZlYzQ0MTJiMDNiNjBmZWVmMTliNmFiMGY3NmZmZWZlNDk2ZWQ3NGZhYjBjYTNlYjQ5NTc

or would you rather keep everything here?

**Comment by danyeaw** [comment]
@TheElementAce we already have something similar to Slack called [Gitter](gitter.im/Gaphor/Lobby). We would love for you to join to chat about this.

**Comment by danyeaw** [comment]
@TheElementAce Any help needed on this?

**Comment by Shubhangi2901** [comment]
I am willing to claim his if its still open!
Also if any help needed in completing this issue. @danyeaw

**Comment by danyeaw** [comment]
@Shubhangi2901 We would love to have your help with this!

**Comment by Shubhangi2901** [comment]
Thank you :) ! This is my first time contributing to open source. I will reach out to you if I get stuck. @danyeaw

**Comment by Shubhangi2901** [comment]
Hey, As per my previous update I had submitted a wiki on Gaphor online, however they rejected my submission. I am attaching a screenshot of the comment on my wiki edit for Gaphor.

Please give me suggestions to fix this.
![Capture](https://user-images.githubusercontent.com/8040609/75295419-7924cd80-57df-11ea-8349-53134b2d91b5.PNG)

**Comment by danyeaw** [comment]
I think finding information in published, reliable, secondary sources may be difficult. There are articles on Gaphor:

Journal articles:
https://www.uni-hildesheim.de/media/fb4/informatik/AG_SSE/PDFs/UML-Tools-2.0.pdf

Somewhat independent review sites:
https://modeling-languages.com/mixing-use-cases-classesstates-single-diagram-gaphor/

Personal websites (not normally meeting the bar)
https://sites.google.com/site/idelerdennis/blog/uml-modeling-in-linux
http://blog.sudobits.com/2011/08/03/uml-tools-for-ubuntu/
http://judebert.com/progress/archives/332-UML-Editors-Gaphor.html
http://www.boduch.ca/2009/01/gaphor-plugin-example.html
https://plg.uwaterloo.ca/~migod/uml.html

Others:
https://www.thinkpenguin.com/gnu-linux/gaphor
https://community.linuxmint.com/software/view/gaphor
https://github.com/mahmoud/awesome-python-applications#graphics
https://pygobject.readthedocs.io/en/latest/#who-is-using-pygobject

**Comment by amolenaar** [comment]
Most of these references are pretty old, though :/ I hope they still count.

**Comment by devarshigoswami** [comment]
I understand this issue hasn't been resolved. Care to allow me to give it a try?

**Comment by danyeaw** [comment]
@devarshigoswami By all means, we would love the help!

**Comment by danyeaw** [comment]
I have updated the draft: https://en.wikipedia.org/wiki/Draft:Gaphor
I also created a new page for a [List of SysML tools](https://en.wikipedia.org/wiki/List_of_SysML_tools)
Hopefully we can get the draft approved soon!

**Comment by danyeaw** [comment]
https://en.wikipedia.org/wiki/Gaphor

**Comment by danyeaw** [comment]
The article is now back to draft 😅

**Comment by danyeaw** [comment]
The draft of our page was deleted. I have requested it to be restored: https://en.wikipedia.org/wiki/Wikipedia:Requests_for_undeletion#Gaphor

**Comment by danyeaw** [comment]
It looks like someone named Terilica added some additional references and resubmitted the page to AfC.
