### ISSUE TITLE
Editing Stylesheet crashes gaphor

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2330]
When editing the stylesheet, if the css becomes is invalid, the application crashes.

**Comment by mikekidner** [comment]
Also stylesheet window doesn't allow pasting of text.

**Comment by amolenaar** [comment]
@mikekidner I assume that's on macOS? It's possible that copy/paste has not been fully implemented for macOS in the GUI library we use (GTK).

**Comment by mikekidner** [comment]
Yes, you're correct it is a GTK3 issue. Ctrl-V works as expected.

**Comment by amolenaar** [comment]
> When editing the stylesheet, if the css becomes is invalid, the application crashes.

This happens with 2.18.0. It's fixed in 2.18.1.

**Comment by danyeaw** [comment]
Since you deleted the bug issue template and there are two different topics here, can you please open a new issue with the required information? Please make sure you are using the latest released version as well. Thanks!
