### ISSUE TITLE
Failing Flake8 C901 for Code Complexity

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#234]
### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Refactoring needed

### Current behavior
flake8 reports that these current parts of the code base are too complex:
- [x] gaphor/storage/storage.py:39:1: C901 'save_generator' is too complex (23)
- [X] gaphor/storage/storage.py:174:1: C901 'load_elements_generator' is too complex (26)
- [ ] utils/model/gen_uml.py:214:1: C901 'generate' is too complex (40)

### Expected behavior
flake8 C901 passes. I have added noqa to these sections of code. This issue tracks that we eventually restore the flake8 checks on these parts.

**Comment by amolenaar** [comment]
Fixed `gaphor/storage/storage.py:174:1: C901 'load_elements_generator' is too complex (26)` on master

**Comment by amolenaar** [comment]
Fixed `./gaphor/storage/storage.py:37:1: C901 'save_generator' is too complex (22)` by moving the element save code to a separate function.

**Comment by amolenaar** [comment]
Closed, since #452 will take care of cleaning up the UML coder.
