### ISSUE TITLE
mac debug in VSCode 

### ISSUE THREAD

**Issue by mengibin** [gaphor/gaphor#2357]
### Describe the bug
start the debug, get error information

### To Reproduce
start the debug, get error information

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### OS

- [ ] macOS

### Version
Version of Gaphor:

### Additional information
 File "/Users/mengbin/Documents/study/sysml/gaphor/gaphor/__main__.py", line 8, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/mengbin/Documents/study/sysml/gaphor/gaphor/main.py", line 21, in main
    if args.profiler:
       ^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'profiler'

**Comment by amolenaar** [comment]
Hi @mengibin, how did you start the debug session?

This is the configuration I use to start an interactive debug session with Gaphor:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Gaphor UI",
            "type": "python",
            "request": "launch",
            "module": "gaphor",
            "justMyCode": false,
            "env": {
                "GDK_BACKEND": "wayland",
            }
        }
    }
}
```

**Comment by mengibin** [comment]
thanks，your solution is perfect!!

**Comment by danyeaw** [comment]
Should we add this to the docs?
