### ISSUE TITLE
Change size of merge editor panel

### ISSUE THREAD

**Issue by madiharvey** [gaphor/gaphor#2359]
### Is your feature request related to a problem?
When I'm merging two models and using the merge editor, the size of the panel is at a fixed size and I can't expand it out. It's an issue when elements or diagrams have longer names and the full name can't be seen.

### Describe the solution you'd like
It would be useful if the resizing tool that can be used for the toolbox, model browser etc. can be used for the merge editor panel

**Comment by danyeaw** [comment]
Closed by #2364

**Comment by danyeaw** [comment]
@all-contributors please add @madiharvey for idea

**Comment by danyeaw** [comment]
Thanks @madiharvey!
