### ISSUE TITLE
Where is the AppImage of the new version 2.19.0!?

### ISSUE THREAD

**Issue by MInessota** [gaphor/gaphor#2369]
Hi,

I use gaphor on Linux Mint 20.3, this new version (2.19.0) doesn't have the AppImage version of the program!

**Comment by danyeaw** [comment]
Hi there @MInessota. We are no longer supporting AppImage, the background for why we made the decision is here: https://github.com/gaphor/gaphor/issues/2285

**Comment by MInessota** [comment]
I understand, I agree with the remarks about the AppImage.

Thank you for developing Gaphor, it's a very good program!
