### ISSUE TITLE
Fail to open i965 (mesa errors on Ubuntu 20.04)

### ISSUE THREAD

**Issue by phamduchongan93** [gaphor/gaphor#2385]
### Describe the bug
the error appears regarding libGL: MESA-LOADER.

### To Reproduce
1. Install gaphor via flatpak via ` flatpak install flathub org.gaphor.Gaphor` command.
2. Execute `flatpak run org.gaphor.Gaphor` to run the program 
3. the output appear
```
libEGL warning: MESA-LOADER: failed to open i965: /usr/lib/x86_64-linux-gault/lib/dri, suffix _dri)

libGL error: MESA-LOADER: failed to open i965: /usr/lib/x86_64-linux-gnu/
```

### Expected behavior
no error 

### OS
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

### Version
2.18.1

**Comment by amolenaar** [comment]
Hi, 

Is it only the error you see or is Gaphor not starting?

Ubuntu 2004 is quite old, so it may be they're not shipping this driver.

**Comment by phamduchongan93** [comment]
Yes, gaphor does load normally but the error keep showing during the program running session. My concern is if this error is caused by a CPU architect or a graphical error which might effect the performance of the program.

**Comment by amolenaar** [comment]
Yes, you'll miss some OpenGL optimizations, but the app is nearly as fast, since our diagram rendering (cairo) does not support opengl anyway.

You can safely ignore those messages.

**Comment by phamduchongan93** [comment]
Thanks for the clarification. I just gonna close issue since this is the issue from my OS side.
