### ISSUE TITLE
Problem loading a saved file

### ISSUE THREAD

**Issue by Gelth56** [gaphor/gaphor#2411]
### Describe the bug
When i load a saved file, there is nothing in model browser.

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/138449643/9aaf80c1-6e19-43e5-957f-c8c75b5c1ae9)

### OS
- [ ] Windows

### Version
Version of Gaphor:
Gaphor version:         2.19.1
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.4
GTK version:            4.10.3
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.23.0
pygit2/libgit2 version: 1.12.2 / 1.6.4

Aucune erreur n’a été interceptée. Tout va bien.

### Additional information
The file
[zapette.zip](https://github.com/gaphor/gaphor/files/11935145/zapette.zip)

**Comment by amolenaar** [comment]
Hi @Gelth56, Thank you for your error report. I can reproduce the issue with your example.
