### ISSUE TITLE
After using merge tool model becomes invalid

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2421]
### Describe the bug
Using merge tool (2.19.0) to resolve merge conflicts between edits made on 2.19.0 and 2.19.1. Merge was completed, but after closing file it no longer opened succesfully. On either version.

Running from the debugger showed:

```
miyomoto:gaphor mikekidner$ poetry run gaphor
No translations were found for language en_AU.UTF-8: [Errno 2] No translation file found for domain: 'gaphor'
gaphor.storage.storage INFO Read 4181 elements from file
> /Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/properties.py(639)postload()
-> len(u) <= 1
(Pdb) l
634  	    def postload(self, obj):
635  	        self.version += 1
636  	        if self.upper == 1:
637  	            u = self.filter(obj)
638  	            assert (
639  ->	                len(u) <= 1
640  	            ), f"Derived union {self.name} of item {obj.id} should have length 1 {tuple(u)}"
641  	
642  	    def save(self, obj, save_func):
643  	        pass
644  	
(Pdb) p u
[<gaphor.SysML.sysml.Block element bdb9c7e6-0bca-11ee-8816-ba28606445aa>, <gaphor.UML.uml.Package element a24bd3b4-0b02-11ee-8936-ba28606445aa>]
(Pdb) p obj
<gaphor.SysML.sysml.Block element 19fad756-0b0e-11ee-8936-ba28606445aa>
(Pdb) p self.name
'namespace'
(Pdb) w
  /Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/filemanager.py(213)_load_async()
-> for percentage in storage.load_generator(
  /Users/mikekidner/BitBucketRepos/gaphor/gaphor/storage/storage.py(292)load_generator()
-> for percentage in load_elements_generator(
  /Users/mikekidner/BitBucketRepos/gaphor/gaphor/storage/storage.py(166)load_elements_generator()
-> elem.element.postload()
  /Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/element.py(146)postload()
-> prop.postload(self)
> /Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/properties.py(639)postload()
-> len(u) <= 1
(Pdb) 
```

### Expected behavior
Not make the file invalid for both versions. 
Prevent the merge and advise users to upgrade the 2.19.0 model to 2.19.1 before attempting the merge.

### Screen Shots
<img width="582" alt="Screen Shot 2023-07-06 at 12 48 39 pm" src="https://github.com/gaphor/gaphor/assets/50702106/8746a402-96c9-4f05-ba48-6243ef7fe976">
<img width="472" alt="Screen Shot 2023-07-06 at 12 48 18 pm" src="https://github.com/gaphor/gaphor/assets/50702106/73a27c1a-8a07-43d0-aeb6-5f598813d977">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x ] macOS
- [ x] Windows

### Version
Version of Gaphor: 2.19.0 & 2.19.1

**Comment by amolenaar** [comment]
Hi @mikekidner, Thank you for the report.

This issue happens due to derived properties. We have a check that derived properties with a multiplicity `[0..1]` end up having only one item. Normally the application code ensures this remains true. With the merge functionality we can bypass those runtime checks: derived unions are lazy evaluated. 

In the case you show I expect the `owner` relation to have a reference to both a block and a package.

Maybe it;s better to take one element in a deterministic way, instead of bailing out. It would make the model more resilient against situations like this.
