### ISSUE TITLE
Package import from file/clipboard

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2422]
### Is your feature request related to a problem?
To help with re-use, collaboration and consistency it would be great to be able to import packages from other models. 

### Describe the solution you'd like
Import packages from other models. Either via: 
drag & drop into left hand menu. 
Copy-Paste into left hand menu, or
Reference imported package in a diagram as a URL

### Describe alternatives you've considered
I've looked at appending the XML itself, but it appears that element ID's are not unique between two models.

### Additional context
As per sysML diagrams, which would possibly keep a 'live' connection to the source package.
<img width="791" alt="Screen Shot 2023-07-06 at 1 12 34 pm" src="https://github.com/gaphor/gaphor/assets/50702106/0ccf73e1-c429-4b75-82f9-08b0a61b3796">

However the drag/drop copy/paste maybe be more intuitive for users

**Comment by amolenaar** [comment]
Hi @mikekidner,

You can copy element from one diagram to another, also in another model. You should select elements in a diagram and copy them, then paste in another diagram.

It's not possible to copy directly from the model browser (top left).

**Comment by danyeaw** [comment]
I think this use case is a bit different than copy and paste. It would be useful to allow projects to use other projects, for things like common elements and customizations used across a bunch of models.

This would be very powerful, but would also take some considerable work I think. The git equivalent to this would be a submodule.

**Comment by mikekidner** [comment]
@amolenaar thanks for the note about copy/paste - I hadn't realised, and that does solve the immediate issue. @danyeaw I agree that linking to other models/repos will be a large amount of work - but it may also be relevant for sysMLv2 implementation,  where there appears to be have emphasis on API's to remote models, (which makes it a longer term feature).

**Comment by mikekidner** [comment]
When using copy/paste from I noticed that the content of a package is not brought across, if the package is copied from one diagram to a diagram in another model. Same goes for blocks, the component blocks do not come into the new model file.

**Comment by amolenaar** [comment]
That's correct. It copies the model element with the minimal set of content. For a class operations and attributes are copied along.

For copying to other models (deep copy) it sounds reasonable to copy the contents of a package as well.

I may be misunderstanding you. Blocks are copied with their parts and references, right?

**Comment by mikekidner** [comment]
Hi @amolenaar, I couldn't get blocks to bring their parts over.
I'm copying the parent block from a diagram, into a new model. Only the parent block comes across.

<img width="1434" alt="Screen Shot 2023-07-14 at 5 15 44 am" src="https://github.com/gaphor/gaphor/assets/50702106/82e12be2-997a-4c3e-a416-b7f55d9ae27e">

I've used cmd-C to copy and both cmd-V and cmd-shift-V to paste.

**Comment by amolenaar** [comment]
The copy functionality is too limited. I initially wrote it with the idea that you copy elements on diagrams within the same model. However, I never considered that you want to copy (parts of) models to a new model.

This requires a bit of rethinking of how copy/paste should work.

**Comment by amolenaar** [comment]
Okay, I think I sorted it out. Copying should still happen from diagrams, but you can now paste complete hierarchies, including diagrams with content. See #2475.

@mikekidner @sz332 @danyeaw The PR works for me. Can you also test it?
