### ISSUE TITLE
Port type in label

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2424]
### Describe the bug
Diagram label and tree label are inconsistent for typed ports. 

### To Reproduce
1. create block definition diagram
2. create port definition block
3. create component block with port
4. set port type to definition
5. Observe port correct

### Expected behavior
The port label should be similar to the internal block diagram parts (`Name:Type`) when a definition is provided. This is correct in the tree but not in the diagrams. Figure 9-7 in the [SysML 1.6 spec](https://sysml.org/.res/docs/specs/OMGSysML-v1.6-19-11-01.pdf) shows this for proxy and full ports 

### Screenshots
Current
![image](https://github.com/gaphor/gaphor/assets/58485783/1840e165-74ea-4b1d-9f36-65123072ecb0)

Corrected Visualization
![image](https://github.com/gaphor/gaphor/assets/58485783/36f19779-98ff-46a2-8c0a-6f9faaef0d2f)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.1

**Comment by amolenaar** [comment]
In the SysML spec I see both versions. Not sure when to use what.

**Comment by danyeaw** [comment]
Other tools let you show the name, the name and the type, or just the type. I rather not add a configuration for this, but I also see why you would want to show the type on all your ports, and also a situation where you would just have the names, since showing the names and types can get pretty cluttered quickly.

**Comment by amolenaar** [comment]
We could create a toggle on item level, same as we do for attributes and operations in a class.

**Comment by sz332** [comment]
I second this request, as a user I would like to be able to configure whether only name, type, or both are displayed on a diagram for a specific port.
