### ISSUE TITLE
Appearance/placing of ports on activity diagram is unusual

### ISSUE THREAD

**Issue by madiharvey** [gaphor/gaphor#2428]
### Describe the bug
When placing an input/output pin or proxy port on an activity or block diagram, the pin does not automatically attach to a nearby action or block, and it doesn't appear as a pin. The pin can be dragged onto an activity and seems to function as expected, but the appearance looks strange. 

### To Reproduce
1. Add an action to an activity diagram and place an input/output pin
2. Attempt to attach the pin to the action
3. Same steps for adding a block and proxy pin to a block diagram

### Expected behavior
The pin to appear as expected (small square on the outside of the action). Notably, the pin behaviour seems to be correct on the coffee machine example model, but it is only on my own model that the pins behave this way.

### Screenshots
Straight after adding the pin to the activity diagram:
![image](https://github.com/gaphor/gaphor/assets/136543386/3535b232-fe53-4a6d-9d1c-86b6751f2ae7)
After adding the pin to the action and connecting an object flow arrow:
![image](https://github.com/gaphor/gaphor/assets/136543386/63b3951c-5762-4fcc-964f-3cc4d34b1836)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x ] Windows

### Version
Version of Gaphor: 2.19.1

**Comment by amolenaar** [comment]
Hi @madiharvey, Thank you for submitting this issue.

This looks kinda odd indeed. It looks like something is off in the rendering of the port.

If you save and load the file, does this behavior persist? Can you share the model file?

**Comment by amolenaar** [comment]
@all-contributors Add @madiharvey for bugs

**Comment by madiharvey** [comment]
Hi @amolenaar , saving and reloading the file doesn't seem to change the appearance of the port. However, if I try to add a port/pin to a new model file, it appears and behaves correctly. So it seems to just be an issue with the particular model file I am working on. I can't share the original model for privacy reasons however I've made a copy of this file and deleted all the data from it to try replicate the issue. The package diagram contains an action with an output pin.
[port-bug.zip](https://github.com/gaphor/gaphor/files/11996752/port-bug.zip)

**Comment by amolenaar** [comment]
Thanks, it reproducible, on Linux.

![image](https://github.com/gaphor/gaphor/assets/96249/2a3b357b-fdb8-4faf-b148-d78956712c6b)

**Comment by mikekidner** [comment]
We've noticed the behaviour occurs for "Execution Specification" objects on Life Lines the same model.

**Comment by mikekidner** [comment]
@madiharvey / @amolenaar This appears to be related to the style sheet. Deleting the style sheet cures the issue. 
the border-radius parameter is the problem any value other than 0 creates this problem
*  {
font-family: D-DIN;
font-size: medium;
line-width: 1;
border-radius: 3;  This is bad, when applied to pins, ports, execution nodes
}
