### ISSUE TITLE
Parameter nodes text overflowing

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2429]
### Describe the bug
Trying to put a long name into a parameter node of an activity on an activity diagram makes the text overflow the boundaries of the node.

### To Reproduce
1. Create a blank activity diagram.
2. Add an activity to the diagram.
3. Add a parameter node to the activity with the text "This is a long title".

### Expected behavior
Parameter node to resize with the text inside of it.

### Screenshots
<img width="512" alt="Screenshot 2023-07-07 at 08 06 02" src="https://github.com/gaphor/gaphor/assets/1304898/f76dcacb-8e65-4ca8-b662-f6704e5d055a">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.1

**Comment by amolenaar** [comment]
Hi @Bambofy, thank you for reporting this issue.

Indeed I would expect the parameter to scale, so it can contain all text.

Let's fix this.

**Comment by amolenaar** [comment]
@all-contributors Add @Bambofy for bugs
