### ISSUE TITLE
Parameter nodes render as solid white rectangles in dark mode

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2437]
### Describe the bug
In dark mode on OS X the parameter nodes on an activity node turn solid white and it hides its labels.

### To Reproduce
1. Open gaphor.
2. Switch to dark mode.
3. Add an activity node.
4. Add parameter nodes to the activity node.

### Expected behavior
Parameter nodes rendered as stroked white rectangles with white text within.

### Screenshots
<img width="302" alt="Screenshot 2023-07-08 at 11 27 53" src="https://github.com/gaphor/gaphor/assets/1304898/e3ecb2ae-00f0-46ff-b6dd-0ac242f18c25">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.1

**Comment by amolenaar** [comment]
Parameters have a solid background, since they're overlapping with the edge of an Activity. However, the color should be updated for dark mode.

Thank you for bringing this up.

**Comment by danyeaw** [comment]
Thanks @Bambofy for the report!
