### ISSUE TITLE
Grid snapping

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2438]
### Is your feature request related to a problem?
When making activity diagrams it is really time consuming having to place each node in a pixel perfect location if you want to layout on a uniform grid.

### Describe the solution you'd like
Some option which allows you to snap the nodes onto a grid instead of pixel

### Describe alternatives you've considered
Modelio has a snap and alignment functions.

**Comment by amolenaar** [comment]
Hi, Thanks.

There is already an issue for this: #798. Given you're not the first to request this, it may be worth looking into :smiley:

I'll close this issue as a duplicate. Feel free to add a comment to #798.
