### ISSUE TITLE
macOS Packaging Doesn't Support Python 3.8

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#244]
As part of #239, I was trying to package the macOS dmg using Python 3.8. When I try this I am getting the following error:

    cp: Gaphor.app/Contents/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python: No such file or directory

It looks like the script does get the PYVER correctly, and replaces the value in the `Gaphor` file using sed. Packaging from Python 3.7 works fine.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Brew had some trouble updating the default python to 3.8. It builds on 3.7 just fine. I can still check if it will work with Python3.8, but I expect little trouble now.

**Comment by amolenaar** [comment]
Fixed by #313.
