### ISSUE TITLE
Support diagram model element type in SysML

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2444]
### Is your feature request related to a problem?

Diagram header only supports diagram name. It is not possible to explicitly know what modelElementType and model element (modelElementName) the diagram corresponds to. This is important information in SysML to properly navigate the model.

### Describe the solution you'd like

1. I would like to be able to properly select diagram modelElementType and corresponding modelElementName (if diagram kind requires) according to the rules described by SysML v1.6 standard specification. Below is a screenshot of the specification describing which diagram kind options are available for each diagram.

![image](https://github.com/gaphor/gaphor/assets/45357878/1e2c639e-2f49-4b4e-83d2-905630fdd0cd)

2. I would like to see diagram header generation automated and contain the information in SysML standard proposed way: <diagramKind> [modelElementType] <modelElementName> [diagramName].

This solution would promote correct SysML usage and improve user experience: a) by guiding users to use diagrams more correctly reducing the learning curve; and b) by simplifying model navigation and understanding of the model.

### Describe alternatives you've considered

Currently, I have manually inserted necessary information into the diagram name. See the following example:
![image](https://github.com/gaphor/gaphor/assets/45357878/a441d72a-8cba-46d0-a4ab-33c26223d10c)
This serves the purpose of the simplification of the model understanding.

### Additional context

I would like to propose more details about the diagram modelElementType and modelElementName selection.
* For the new diagrams, default modelElementType should be package which would take the composing package element as diagram modelElementName, if the diagram type is bdd, pkg, req, uc.
* For other new diagrams - act, ibd, par (not supported by gaphor, but hopefully soon), seq, sm - new corresponding element should be created. 
* For the existing elements, corresponding diagram can be created by right-clicking the element and then selecting "New diagram" which would list only the diagrams where the element type can be valid element type.

I would consider this issue complete with a minimum of having an option to select diagram kind and corresponding diagram kind elements from the dropdown; and auto-updating rendering of the diagram header.

**Comment by danyeaw** [comment]
@marek-piirikivi Thanks for the idea. I think #2213 is related to this, since it includes the idea that the boundary of a diagram represents the diagram kind.

**Comment by amolenaar** [comment]
It may be more friendly to use the abbreviated diagram type name.

E.g. 

```
[cls] My Class Diagram
[act] My Activity
[sd] My Sequence Diagram
```

**Comment by marek-piirikivi** [comment]
> It may be more friendly to use the abbreviated diagram type name.

I would prefer not to diverge from the specification.

I just noticed that all this time I meant to use modelElementType instead of diagram kind. Indeed, type == kind in the standard. I'll fix that.

**Comment by marek-piirikivi** [comment]
Closing because a better alternative PR was opened https://github.com/gaphor/gaphor/pull/2540

**Comment by marek-piirikivi** [comment]
I'll close this because #2540 added SysML specific header with necessary information. The minimal requirements for this issue have been met. I'll open a separate issue about the constraining.
