### ISSUE TITLE
Error when adding an activity control flow arrow.

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2447]
### Describe the bug
Sometimes when manipulating arrows and parameter nodes an error appears. Seems to be related to issue #2433.

### To Reproduce
1. Make a blank activity diagram.
2. Add an activity node.
3. Add a parameter to the activity node.
4. Add two actions to the activity node.
5. Add a control flow arrow from one action to the other.
6. See error.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.2

### Additional information
[error_report.txt](https://github.com/gaphor/gaphor/files/11996035/error_report.txt)

**Comment by amolenaar** [comment]
Fixed in Gaphor 2.19.3.
