### ISSUE TITLE
Missing toolbar icons

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2448]
### Describe the bug
Only placeholders are displayed instead of the icons.

### To Reproduce

Download portable version 2.19.2 of Gaphor for windows.

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/8182138/5997b02f-3302-40f3-a08a-c07fe9ec7b92)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version

2.19.2

**Comment by danyeaw** [comment]
@sz332 Thanks, I noticed this as well this morning. It looks possibly our update to the newer version of gvsbuild broke our adwaita-icon-theme icons, I'll have to look in to this.

**Comment by amolenaar** [comment]
Fixed in Gaphor 2.19.3.
