### ISSUE TITLE
Double click on connections (relationships) causes error

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2449]
### Describe the bug

Double clicking on connections (relationships, "Kapcsolatok") causes error:

### To Reproduce

Double clicking on connections (relationships) causes error:

Gaphor version:         2.19.2
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.4
GTK version:            4.10.4
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4

Hibák:

Time since application startup: 0:18:54
|Traceback (most recent call last):
|  File "C:\Home\Tools\Gaphor\gaphor-2.19.2-portable\data\gaphor\ui\modelbrowser.pyc", line 84, in list_view_activate
|  File "C:\Home\Tools\Gaphor\gaphor-2.19.2-portable\data\gaphor\ui\modelbrowser.pyc", line 135, in open_element
|AssertionError
└─────────────────────────────╌┄┈

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/8182138/5cc12555-82e4-4871-8286-3b9b1754aa6f)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.19.2

**Comment by danyeaw** [comment]
@sz332 Which relationship type was experiencing this error? I tried with an association, and I wasn't able to reproduce this.

**Comment by sz332** [comment]
Started a default SysML project, selected Structure ("Szerkezet", my language is hungarian), I probably had the information window open on the right side, and double clicked the Assocations (the one that is selected in blue).

**Comment by sz332** [comment]
![image](https://github.com/gaphor/gaphor/assets/8182138/2bc1c665-d3dc-41cc-a89c-71efd1bfb0f3)

New install, new project, SysML, open logical-structure, open Logical Structure diagram, double click on "> Relationships".

**Comment by danyeaw** [comment]
Thanks, I can reproduce this. Double clicking on relationships shouldn't do anything, so it looks like we need to filter out those.
