### ISSUE TITLE
Doctests and Console Plugin Tests Cause Seg Fault with GitHub Actions

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#245]
PR #239 found an issue with pytest causing a seg fault in Linux only and only when running on the GitHub Actions runner. The seg fault occurred during collecting the tests. These are things that didn't work:
1. Downgrading to from Python 3.8 to Python 3.7
2. Downgrading Pytest to version 4.x
3. Disabling the pytest-cov plugin
4. Using or not using the pytest-xvfb plugin (using xvfb-run instead)

I isolated the cause by collecting and running each test one at a time:
`find gaphor/ -name 'test_*.py' -exec xvfb-run -a pytest {} \;`
 
I found two issues:

1. Doctests
2. Tests in `gaphor/plugins/console/tests`

As a workaround, I changed the settings in the `pytest.ini` to disable these checks.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
Run `xvfb-run pytest` on the GitHub Actions CI, below with gdb debugging:
```
(Gaphor) runner@fv-az76:~/work/gaphor/gaphor$ gdb -ex r --args python -m pytest                                 
GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Starting program: /home/runner/work/gaphor/gaphor/.venv/bin/python -m pytest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 7738]
[Detaching after fork from child process 7740]
[Detaching after fork from child process 7741]
[Detaching after fork from child process 7742]
============================================= test session starts ==============================================
platform linux -- Python 3.8.0, pytest-5.3.0, py-1.8.0, pluggy-0.13.1
rootdir: /home/runner/work/gaphor/gaphor, inifile: pytest.ini, testpaths: gaphor, tests, docs
plugins: xvfb-1.2.0, cov-2.8.1
collecting ... [New Thread 0x7fffe1493700 (LWP 7755)]
[New Thread 0x7fffe0c92700 (LWP 7756)]
[Detaching after fork from child process 7757]
collecting 224 items                                                                                           
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
PyModule_GetState (m=0x0) at Objects/moduleobject.c:565
565     Objects/moduleobject.c: No such file or directory.
```

### Expected behavior
All tests pass

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:
The GitHub Action [action-tmate](https://github.com/mxschmitt/action-tmate) was invaluable for debugging this. It pauses the runner and allows you to ssh in to debug :tada:.

**Comment by danyeaw** [comment]
I have also submitted a GitHub Actions community [posting](https://github.community/t5/GitHub-Actions/Seg-Faults-with-Python-in-Linux-while-Running-Pytest/) to help resolve this.

**Comment by danyeaw** [comment]
I submitted this as an [issue](https://github.com/actions/virtual-environments/issues/159) to the GitHub Actions virtual-environments team. It is currently on the backlog for resolution.

**Comment by amolenaar** [comment]
I added a workaround to the code base. Let's keep this issue open until it's fixed on GitHub/Microsoft side.

**Comment by danyeaw** [comment]
This is no longer an issue with Python 3.8.
