### ISSUE TITLE
Conjugated support for ports

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2451]
### Is your feature request related to a problem?

Yes.

### Describe the solution you'd like

As a user in a SysML diagram, I would like to configure whether a port is conjugated or not. If it is, then the label shall display a small ~ sign indicating it is conjugated.

**Comment by amolenaar** [comment]
According to the SysML 1.6 spec, conjugated ports are a deprecated feature:

![image](https://github.com/gaphor/gaphor/assets/96249/14a6c601-ef00-4d4d-baf9-aece7eed6caf)
(page 227)

**Comment by sz332** [comment]
Ah, okay, then we can close this ticket at this point, and think about the real need (ability to model the information about a port whether it is provided or required).
