### ISSUE TITLE
Errors when moving parameter nodes.

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2454]
### Describe the bug
When moving parameter nodes sometimes all of the elements disappear and an error is reported.

### To Reproduce
1. Make a blank model.
2. Add two activities.
3. Add a parameter to each one.
4. Drag a parameter node.
5. See error.

[error.txt](https://github.com/gaphor/gaphor/files/12006340/error.txt)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor:
2.19.2

**Comment by Bambofy** [comment]
I have forked the repository and set up the development environment, but i can't reproduce the error in the development environment?

**Comment by amolenaar** [comment]
This issue is resolved by #2460.
