### ISSUE TITLE
Don't translate modeling language specific words

### ISSUE THREAD

**Issue by tfirchau** [gaphor/gaphor#2461]
### Is your feature request related to a problem?
As a non-native English speaker I would prefer that modelling language elements (like "Block", "Port", ... ) are not translated. As languages like UML and SysML are originally specified in English, it is - in my experience - very uncommon to translate them even when talking about them in a different language. 

I also think that this will become a technical problem with the SysML v2 and its textual notation (#615). Translating the keywords of the textual notation would probably make it non-compliant to the specification. But only translating the elements of the graphical notation would create an inconsistency between both notations.

I'd be interested in other no-native English speakers to share their opinion.

### Describe the solution you'd like
Limit translation to the user interface and don't translate model language elements.
This would also have the side-effects of making a "complete" translation of gaphor easier and avoiding future problems with SysML v2.

### Describe alternatives you've considered
I tried switching my preferred language on Windows to English, but that caused all kinds of other problems. 
I also tried working with the German translation. But, although it was quite good, I was confused by the unfamiliar names for model elements. 
Ultimately this creates a lot of friction for me and keeps me from using gaphor.

### Additional context
_none_

**Comment by amolenaar** [comment]
Hi @tfirchau, thank you for your report.

We've had requests in the past that actually wanted to the UI to be localized as much as possible. It is possible to select a different language for the model itself, so the terms used in the diagrams are (for example) English, while you use German as your system language.

Assuming you're on Windows, you can set a the language via an environment variable, e.g. `LANG=C`. `LANG` is a default way to set the language on Unix, but the variable is ignored on Windows. You can set it in your system preferences.

**Comment by tfirchau** [comment]
Thank you for the reply :) Setting the environment variable to English (``LANG=en_US.UTF-8``) on windows sets everything in gaphor (UI+Model Element names) to English. (So far, so good) 

> It is possible to select a different language for the model itself ...

I must confess that I kind of ignored the drop-down menu in the model settings. Maybe because it seemed not to work at first glance, because it actually _only_ changes the translation in the diagram. The translation in the element palette on the left stays the same. (See the following image for "\<\<primitive\>\>" in the diagram and then "Grundelement" in the element palette.)

![grafik](https://github.com/gaphor/gaphor/assets/71006757/1b9d563d-bcfe-48ef-84bc-35185b36bf9e)

I would have expected it to also change the element names in the palette. 

There is nothing in the documentation about setting the ui / model language. Maybe I could contribute some explanation  there?

**Comment by sz332** [comment]
I think conceptually Gaphor handles two different languages. One is the language of the model, the other is the language of the interface. In my opinion both should be configurable in the tool (and not by some external variables). 

As a user it was not clear for me that by setting the language (Sprache in @tfirchau's screenshot) only sets the language of the model.

So, maybe it would make sense to have somewhere an application level configuration where you can set modeler's language and to have a model configuration where you can separately set the model's language, and it shall be clearly indicated in the label that the user is configuring a model's language, and maybe in a toolbar giving some detailed information about what does it even mean.

**Comment by amolenaar** [comment]
> See the following image for "<<primitive>>" in the diagram and then "Grundelement" in the element palette.

Indeed, it looks a bit funny that the terminology used in the toolbox is different from the terms used in the diagrams.

> There is nothing in the documentation about setting the ui / model language. Maybe I could contribute some explanation there?

That will be much appreciated :smiley: 

> I think conceptually Gaphor handles two different languages. One is the language of the model, the other is the language of the interface.

Correct.

I agree that "Language" does not cover the intent of the option. "Diagram Language", "Language used in Diagrams", or "Language used by the model" would probably be better. This language modifier is only applicable for the loaded model (and saved as part of the model), and it defaults to English.

There has been a similar request before: #2346.

**Comment by amolenaar** [comment]
> Would you consider changing it, @amolenaar ? I would also totally accept "no" as answer, since I have no idea how much work this would imply, but I figure it wouldn't be trivial.

I can see how easy it is to use the Diagram Language for the tooltips. Not sure if the section headers should be translated as well.

> > I agree that "Language" does not cover the intent of the option. "Diagram Language", "Language used in Diagrams", or "Language used by the model" would probably be better.
> 
> I would interpret "Language used by the model" as UML, SysML, .. so that does not sound right. "Diagram Language" sounds most fitting.

i agree.

> If you agree that it should be changed to that, I would volunteer to (figure out how to) change it and also update the documentation I added recently.

I would appreciate that.

**Comment by tfirchau** [comment]
> I can see how easy it is to use the Diagram Language for the tooltips. Not sure if the section headers should be translated as well.

On one hand the section headings usually also reference model language elements, but on the other they are not actual model elements, more UI elements. Neither is a real killer-argument. So maybe leave it as is for now and only change the tooltips?

What do you think about the tooltips of the tools in the General category?

**Comment by amolenaar** [comment]
I think this issue fixed. You can set the language used in the model separately and store it in the model.
