### ISSUE TITLE
Support for call behaviour actions

### ISSUE THREAD

**Issue by Bambofy** [gaphor/gaphor#2464]
### Is your feature request related to a problem?
Without the call activities each nested activity forces the higher level activity diagrams to expand making them impossible to view.

### Describe the solution you'd like
Call actions which let us link between activity diagrams.

### Describe alternatives you've considered
1. Putting all of the hierarchical activities in one diagram makes it really difficult to see the high-level activity flows.
2. Putting the name of the activity in an action node doesn't convey the idea that it is linked to another activity.
3. Adding an inverted '⑃' symbol to the end of the action's name is ok but it isn't exactly the same thing as having the symbol standardized in the bottom right corner.

### Additional context
1. Reference in the UML specification (https://www.omg.org/spec/UML/2.5.1/PDF) heading "16.3.4.1 Call Behaviour Actions".

<img width="161" alt="Screenshot 2023-07-12 at 07 47 48" src="https://github.com/gaphor/gaphor/assets/1304898/88644f09-03a8-4fac-bf4c-19e0b4c29121">

2. Example of decomposed action (slide 24 "Rate and buffer reduction") https://www.i3s.unice.fr/~map/Cours/MASTER_TSM/Cours5_Activity.pdf

**Comment by Bambofy** [comment]
Shortened the problem description.

**Comment by marek-piirikivi** [comment]
I would like to work on this.

This is what I have currently.
![image](https://github.com/gaphor/gaphor/assets/45357878/298d765a-de91-4ef0-97c4-a61c4dc2f457)

What kind of connection should be established between call behavior action and an activity?

**Comment by amolenaar** [comment]
Fixed by #2495.
