### ISSUE TITLE
Can not load model: Proxyport.informationFlow

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2466]
### Describe the bug

@2old4this reported an issue on Matrix. His saved models (Gaphor 2.13) could not be loaded.

This is caused by a `ProxyPort.informationFlow` attribute. This attribute was present in Gaphor 2.13, however
ProxyPort has no informationFlow attribute in Gaphor 1.19.

How did it get there? Was it a change in the model without proper migration step in the loader?

### Version
Version of Gaphor: 2.19.1

### Additional information

[Matrix discussion](https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$d-ojU0iqtd7vBMNexYRFPsCefNvEOElMWfiq6NAT1sQ?via=gitter.im&via=matrix.org&via=kompot.si)

I have been able to reproduce this issue:

1. Open Gaphor 2.13
2. Create 2 Blocks, connect a ProxyPort on both
3. Create a Connector between both ports
4. Enable Information Flow on the connector and define a name and a type
5. Save the model
6. Load the model with Gaphor 2.19

https://github.com/gaphor/gaphor/blob/main/gaphor/storage/storage.py#L428-L431 contains an upgrade function that deletes `informationFlow` from `Property`, however, it does not take into account `ProxyPort` (which is a subtype of `Property`).

**Comment by danyeaw** [comment]
@all-contributors please add @2old4this for bug
