### ISSUE TITLE
Input and output pins shall not be detachable from an action

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2484]
### Describe the bug
Input and output pins are belonging to an action. Free floating pins do not make any sense. It should be not allowed.

### To Reproduce

- Create an activity diagram
- Add input or output pin
- Drag and drop pin
- Pin is free floating

### Expected behavior
When pin is added to an activity it cannot be moved out from the action but only deleted

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/8182138/1e1cfbb5-565b-4456-94e6-028180678d48)

### OS
- [X] Linux (latest)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: main branch

**Comment by marek-piirikivi** [comment]
Would this be an acceptable solution? If "yes", I'll prepare a pull request (if someone is not already working on it. And I suppose I'll also apply similar behavior on the ports as well.



https://github.com/gaphor/gaphor/assets/45357878/85e9e54e-79d7-46c5-8e1e-de49246f3c62

**Comment by sz332** [comment]
Yes, absolutely, it works totally as expected. Please prepare a PR.

**Comment by sz332** [comment]
Solved in #2542, closing the issue.
