### ISSUE TITLE
Pin should have type and multiplicity as well

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2485]
### Is your feature request related to a problem?
Every pin shall have a name, type and multiplicity. This is not possible currently.

### Describe the solution you'd like
In the properties panel for a pin, add:
- Type: classical type selector
- Multiplicity: multiplicity selector, setter component (do we have it)
- Display: Name, Type, ?None?

### Additional context
Display is again some common feature, we shall think about some common solution for it.

**Comment by sz332** [comment]
@amolenaar what is a preferred way for setting multiplicity for a model element? Do we have an already existing template/widget I can use?

**Comment by amolenaar** [comment]
For multiplicity we have no template yet.

For now I would stick with a text input field ([Gtk.Entry](https://amolenaar.pages.gitlab.gnome.org/pygobject-docs/Gtk-4.0/class-Entry.html#gi.repository.Gtk.Entry)) and parse the text with our [parse/format](https://github.com/gaphor/gaphor/blob/main/gaphor/core/format.py#L19) functions.

**Comment by sz332** [comment]
Merged into main, closing the issue.
