### ISSUE TITLE
Do not close the tree when (last) element is removed

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2488]
### Describe the bug
When removing an element from a diagram that is not referenced it will be also removed from the model. This is 
an expected behavior. However, it also closes the tree, which is pretty annoying. In my opinion it might refresh the
tree, that's fine, but should not close it.

### To Reproduce
1. Create a diagram
2. Open the tree
3. Add an element
4. Select the element
5. Press delete button
6. Element will be removed, but also tree is closing

It seems that when also deleting an element in the tree it will close the tree as well. The two cases might or might not related.

### Expected behavior
Do not close the tree.

### OS
- [ ] Linux
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: main branch

**Comment by danyeaw** [comment]
Thanks @sz332 for submitting this!
