### ISSUE TITLE
Wrong position of text editor for tagged value in stereotypes

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2490]
### Describe the bug
It is not clear whether it is a bug or feature, but when editing tagged values for assigned stereotypes, the text editor for stereotypes are displayed inconsistently.

### To Reproduce
1. Create a stereotype with two tagged values
2. Assign a stereotype to a class
3. Try to edit both values
4. The textfield is displayed inconsistently

### Expected behavior
It shall be displayed consistently.

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/8182138/bbb584af-3b8a-4ae4-bea4-373413db6394)

![image](https://github.com/gaphor/gaphor/assets/8182138/951e2363-bd39-4297-a2ce-a6e13e17f0ac)

For disclaimer, it is displayed like 3 pixels upwards. For age, it is displayed a whole row upward.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.19.2

**Comment by amolenaar** [comment]
This is a regression in GTK 4 TreeView widget (compared to GTK 3). We want to migrate all tree and lists to the new GTK 4 structure, which is a lot simpler. However, our first attempt (Activity Parameters) caused some unexpected crashes.

See #2231 and #2436.

I'll close this as a duplicate.
