### ISSUE TITLE
Block values compartment takes default state when opening 

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2511]
### Describe the bug
When the block has clearly "Show Values" active and opening property page for it, "Show Values" shows inactive state, even if it should be on.

### To Reproduce
1. Go to bdd
2. Create a block
3. Click on the block
4. Activate "Show Values"
5. Click anywhere on the diagram to close the property page
6. Click on the block again to open the property page
7. "Show Values" is in inactive state

### Expected behavior
It is expected that "Show Values" behaves as other compartment enabling options.

### Screenshots

https://github.com/gaphor/gaphor/assets/45357878/b505244e-e550-4f34-b62c-69485abf0015

### OS
- [x] Linux (Mint)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.3

### Additional information

All the other compartment enabling options work correctly.

**Comment by sz332** [comment]
@danyeaw might I take a swing at this as well?

**Comment by danyeaw** [comment]
@sz332 Ya, that would be awesome!

**Comment by amolenaar** [comment]
Fixed by #2515
