### ISSUE TITLE
Lifeline and message traceability to Block/Actor/Property

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2514]
### Is your feature request related to a problem?
Lifelines are currently untyped or referenced to other blocks which inhibits traceability between behaviors (operations) and components. I would like to be able to assign types to lifelines (from other preexisting blocks). Alternatively, (better) would be to display existing parts (blocks or Actors) on interaction diagrams as lifelines so they are inherently tied together with the associated messages/operations. 

### Describe the solution you'd like
See SysML Table 12.1. "The Sequence diagram describes the flow of control between actors and systems (blocks) or between parts of a system."

![image](https://github.com/gaphor/gaphor/assets/58485783/0d2efb1a-14c2-4288-b491-920cbbdb5920)

The individual lifelines shown in the spec are pre-existing components in the model. Either an unnamed block (just typed), a named block (e.g., a typed property from an internal block diagram), or an actor. Creating lifelines from blocks/actors/properties may be the more optimal route as opposed to adding a type selector for a lifeline.

Related: the SysML site specifically calls out avoiding using strings as the messages and instead using operations/signals. It would be useful if new messages introduced in the interaction diagrams could be tied back to their source block/actor as operations. Auto-assigning the operation to the source block might work initially. However, it may be desirable to assign operations to ports on the source block instead of the block itself. The corollary is that operations already defined on the originating block (or its ports) could be selected when inserting a message instead of generating a new operation on the source components.

![image](https://github.com/gaphor/gaphor/assets/58485783/0da2171d-8b38-48e4-938d-63b5bc6a001d)

#### Example
Shown below is the intended end goal with an interface behavior diagram and accompanying port definition for the control unit taken from Holt, "Systems engineering demystified", Pakt, 2023

![image](https://github.com/gaphor/gaphor/assets/58485783/86e90e09-fc0e-4823-af73-53488b38c97f)

![image](https://github.com/gaphor/gaphor/assets/58485783/fd48b6da-7ee7-4e3a-b0ae-b45d426a420b)

### Describe alternatives you've considered
Noted above

**Comment by amolenaar** [comment]
I'm not sure how that should be modeled: a Lifeline has a relation with `ConnectableElement`. However, concrete types of `ConnectableElement` are Interface, `Property` and `Parameter`. No classifiers

From the UML spec:

![image](https://github.com/gaphor/gaphor/assets/96249/d29806db-ab38-4566-ae74-cf967866067b)

**Comment by tompkins-ct** [comment]
Limiting to the connectable elements should be fine as shown in the spec definition. 

For cases where a class/block doesn't yet have a defined instance(property), maybe an anonymous one is created by default otherwise a specific instanced property (already defined) should be selectable after selecting a type. Thoughts?

In the future, it would be useful to enable the ability to add multiple lifelines to a single block to represent ports connected to the property/block (if they exist) to better link the operations to the connected ports instead of the base property/type. Thoughts?

**Comment by sz332** [comment]
According to the UML specification what we can do is set something of a type: ConnectableElement. A solution could be the following (this is how others do)

Create an interaction
Add a Property to the interaction (it is a subtype of ConnectableElement)
Set the name of the Property to whatever (modifiable)
Set the type of the Property to the Block, Class, etc.
Set represents (type of ConnectableElement) to this property

**Comment by Sycophantic-Witty** [comment]
> However, I would expect it to look like the following (with `test` being an unshown identifier...if present at all). The selected connectable element is the lifeline, so the type of the connectable element should show up in the box.
> Thoughts?

That would match what the UML says about lifelines (UML 2.5 §17.3.4.1):
```
<lifelineident> ::= ([<connectable-element-name>[‘[‘ <selector> ‘]’]] [: <connectable-element-type>]
[<decomposition>]) | ‘self’
```

I am manually writing element type names in the `Name` field of lifelines, otherwise it proves very difficult to find out what a lifeline represents based on the current labeling behavior. The obvious problem with this "solution" is that the lifelines are semantically disconnected from the types they represent.

**Comment by danyeaw** [comment]
Thanks @tompkins-ct for the feature request, this will be in the next release.
