### ISSUE TITLE
Create tool for direct association

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2516]
### Is your feature request related to a problem?

When using Gaphor for conceptual modeling creating direct association can be done but takes too many steps. 
Need to create an association, select it, go to the properties page, set tail's navigation to navigable.

### Describe the solution you'd like

I would like to have a new icon in the toolbar where I can select direct association which creates associations alike.

**Comment by sz332** [comment]
@amolenaar I started playing with it but ran into a problem. When a diagram element is created I am able to do some configuration for the item. However the problem is that navigability shall be only set AFTER a connection is made with two elements. So, what could be a solution to have a kind of "callback" function that is executed when such a connection is being made as a result of a create direct association action? What is the mental process behind that, that we as developers should follow?

**Comment by amolenaar** [comment]
I believe there's a property in AssociationItem that holds the preferred option, so it can be applied as soon as the association is fully connected.

**Comment by sz332** [comment]
What I see is that classestoolbox.py contains the toolbox items. It is supporting custom configuration with config_func. This is called when the items is being created. For composite and shared association the preferred_aggregation is being set. As a result, 
the AssociationItem's on_association_end_value method is called (it is like a callback). But it only changes the draw_head. 

There is probably some code that also modifies the underlying model as well, but I just cannot find it. Any idea?

**Comment by sz332** [comment]
I think I found it. It might be in classconnect.py's relationship_or_new method.

**Comment by sz332** [comment]
Fixed in PR #2526, closing issue.
