### ISSUE TITLE
AttributeErrors During Unlink Phase While Closing Model

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#252]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
1. Open `gaphor/UML/uml2.gaphor`
1. Once it is loaded, close Gaphor
```
gaphor.UML.properties ERROR Failed to unlink _stub_7fa5d9d82eb0 from <gaphor.UML.uml2.Class object at 0x7fa5d9dfda30>
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/UML/properties.py", line 549, in unlink
    values = getattr(obj, self._name)
AttributeError: 'Class' object has no attribute '_stub_7fa5d9d82eb0'
```
It looks like these errors are being thrown for most or all of the objects as they unlink.

### Expected behavior
No Errors.

### System Information
OS:
- [X] Linux - Ubuntu 19.10
- [ ] MacOS
- [x] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
Fixed by #258
