### ISSUE TITLE
Presentation elements in model browser

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2524]
### Describe the bug

From a side-tracked discussion in #2522:

> > > @sz332 said: It also seems that when we drag an existing model element into a new diagram then no new uuid is generated for the new ClassItem. That in my opinion is a bug, but might be unrelated.
> >
> > @amolenaar said: That would be a serious issue, since elements (also ClassItem) are managed by their id. I'm not able to reproduce it. Can you create an issue for this with steps to reproduce?
>
> @sz332 said: Also when dragging from the model tree what I see is the type of the element being dragged is ClassItem instead of item, which I just don't understand. Is it by design?

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior

* `~Item` classes should not be part of the model browser

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19

### Additional information

@sz332 Feel free to edit this description directly.

**Comment by sz332** [comment]
I checked the code and it seems it is working as expected: during drop the type is a model element type, and based on the diagram the presentation element is determined, and an instance of it is being created. 

The ticket can be closed.

**Comment by amolenaar** [comment]
Phew 🙂. Thanks for checking.
