### ISSUE TITLE
Dragging and Dropping a Package Makes Nested Elements Disappear

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#253]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
In the Navigation, if you drag-and-drop a package1 so that it is nested under package2, anything that was nested under package1 is no longer visible.

### Expected behavior
Moving a package shouldn't change visibility of nested objects in that package.

### Minimal reproduction of the problem with instructions

1. Create a new Package called package1
1. Create a diagram in the package
1. Create a new Package called package2 at the same level as package1
1. Drag package1 into package2
1. The diagram in package1 will no longer be visible

### System Information
OS:
- [X] Linux - Ubuntu 19.10
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
It’s not visible in the tree view?

**Comment by danyeaw** [comment]
@amolenaar right, the expand triangular icon disappears

**Comment by danyeaw** [comment]
🎉
