### ISSUE TITLE
Common code for dropdown list value management

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2533]
### Is your feature request related to a problem?
In the codebase when developing a new feature we often need to create a dropdown where specific types can be selected. This is currently done by copy/pasting existing code for creating the labels/values across the project.

### Describe the solution you'd like
There should be a common place where we can create a model for a dropdown with a filter, so that we can remove much of the copy-paste, cleaning up the codebase.

In general I am talking about stuff like:

![image](https://github.com/gaphor/gaphor/assets/8182138/59c7b9ec-456e-487c-ae68-9a827a35582f)

and:

![image](https://github.com/gaphor/gaphor/assets/8182138/51f27ea4-7d1a-48b2-9bde-18242da6e417)

**Comment by amolenaar** [comment]
In #2530 I moved the type selection (for TypedElement) to a central place. We should be able to reuse this component throughout the system.
