### ISSUE TITLE
Funky backgrounds with lines

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2537]
### Describe the bug

By crafting a simple style sheet, lines start to fill themselves with a background color.

### To Reproduce
1. Open a model
2. Apply the following css
3. Observe effect

```css
diagram * {
 background-color: #99c1f180;
}
```

### Expected behavior

Lines should not try to fill the background.

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/96249/7d94525b-da8e-4e09-ad34-f839127ece2c)

### OS
- [x] All

### Version
Version of Gaphor: 2.19.0

**Comment by sz332** [comment]
Let's just call it Picaso mode and sell it as a feature :D
