### ISSUE TITLE
Constrain SysML diagram creation in the model explorer to conform with SysML 1.6 specification

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2544]
### Is your feature request related to a problem?
Currently, one can create any SysML diagram in the model explorer. However, not every diagram can be owned by everything. For example, an activity diagram should only be owned by an activity - creating it with any different owning element type does not make sense.

### Describe the solution you'd like

Allow creating diagrams according to the following specification:
![image](https://github.com/gaphor/gaphor/assets/45357878/263fde70-77fb-43e0-903e-2ccd14e1971e)

In the model explorer, context menu should only propose legal diagram options. A diagram should also be created without selecting an appropriate model element, in which case, new element would be created automatically and the diagram placed inside it. For diagrams that may have multiple different kinds of diagrams, package would be the default.

### Describe alternatives you've considered

Currently, the responsibility to ensure the correct usage of the language falls on the modeler.

### Additional context
This should only apply in SysML modeling language profile.

**Comment by mikekidner** [comment]
I like this. Much easier than remembering where to put the square brackets each time! Thanks @marek-piirikivi
