### ISSUE TITLE
Extend/fix the existing plugin development documentation

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2546]
### Is your feature request related to a problem?

It took me a couple of hours to figure out how to make a hello world plugin work. Thanks Marek!

### Describe the solution you'd like

We need to extend the plugin development documentation to include every information. That also includes extending pyproject.toml
file.

**Comment by amolenaar** [comment]
The plugin docs are a bit fragmented, indeed:

* Installing plugins: https://docs.gaphor.org/en/latest/plugins.html
* Example code: https://github.com/gaphor/gaphor_plugin_helloworld
* Another document, not so much about plugins, despite the name: https://gaphor.org/tutorials/plugins/
* A little gem of information about plugins: https://docs.gaphor.org/en/latest/service_oriented.html#example-plugin

**Comment by mikekidner** [comment]
@sz332 what information was missing? Or was it just hard to find?
Some folks in my team are starting to write a plugin, and are also keen to improve the documentation. We will submit an update when we get it working. 
The plugin will focus on extracting documentation from the model

**Comment by amolenaar** [comment]
@sz332 @mikekidner Is there still something to be done for this issue, or can it be closed?

**Comment by mikekidner** [comment]
@amolenaar I think this can be closed.

**Comment by amolenaar** [comment]
I'll close it then. Feel free to reopen.
