### ISSUE TITLE
Sequence diagram - Lifeline - start with a dashed line

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2556]
### Is your feature request related to a problem?

When creating a sequence diagram and adding a linefile, a dashed line shall be also created in order the user can immediately start working with the sequence diagram. 

### Describe the solution you'd like

When adding a lifeline, the dashed line has to be there with a predefined height.
If there are no lifelines, then use a predefined height (for example 200 pixel)
If there are existing lifelines, then use the max of their dashed line height

![image](https://github.com/gaphor/gaphor/assets/8182138/6aafbc50-38f4-480f-b518-ebb1af58fbd5)

**Comment by amolenaar** [comment]
These elements can be used for both Sequence and Communication diagrams. 

<img width="457" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/ea2de24f-5326-4057-ac76-51f8e315619a">
