### ISSUE TITLE
Sequence diagram - lifeline - ability to use a block as connected element

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2557]
### Is your feature request related to a problem?

When creating a lifeline I would like to be able to connect either a class or a block.

### Describe the solution you'd like

Allow the connection of class or block to a lifeline.

### Additional context

According to the UML specification it has to be ConnectableElement. 

A way to solve this problem is to add a Property element to the Interaction (as model element), referencing to the Class, Block, etc. and having a custom name.

In case of having an Interaction and a single lifeline with pointing to the Block named A we will have the following in the model:

Interaction 
  - Property: name: whatever, type: pointing to Block "A"
  - Lifeline: Conneactable element: pointing to the Property

**Comment by amolenaar** [comment]
The odd thing is that it [expects a `ConnectableElement`](https://docs.gaphor.org/en/latest/models/uml/11._Interactions.html#lifelines). Interfaces and Properties are Connectable Elements, but classifiers (classes, blocks) are not. 

See also #2514, #2530.

Let's continue discussion in #2514.

I'll close this as a duplicate.
