### ISSUE TITLE
Sequence diagram - message - drawing issues

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2560]
### Describe the bug

When creating a message between two lifelines and dragging the message to the left or to the right, it is jumping out and back
to it's place.

### To Reproduce
1. Create a sequence diagram
2. Add two lifelines
3. Draw a message inbetween them
4. Drag the message to the left
5. You will see the message actually moving and jumping back (movement cancelled?)

### Expected behavior
Horizontal movement shall be not happening at all

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.19.3.dev3420+5529a503

**Comment by amolenaar** [comment]
This boils down to the diagram constraints being resolved asynchronously.

You see the same if you take a class' lower-right handle and move it all the way to the top-left.
