### ISSUE TITLE
Sequence diagram - drag and drop support

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2563]
### Is your feature request related to a problem?

I would like to be able to set things using drag and drop instead of manually selecting for sequence diagrams.

### Describe the solution you'd like

- Drag and drop a class, block, etc. to lifeline block shall set it's "type" (technically through a property, but as a modeler I don't really care)
- Drag and drop of an operation shall assign an operation to a message
- Drag and drop of a Signal should set the type of the message

**Comment by amolenaar** [comment]
Fancy :wink:

**Comment by sz332** [comment]
> Fancy 😉

Haha, and I just started thinking about how much we can help the work of a modeler by using drag and drop as many places as possible.

**Comment by amolenaar** [comment]
Implemented in #3126.
