### ISSUE TITLE
Use keyboard to move diagram elements 

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2565]
### Is your feature request related to a problem?

When working on a laptop it is sometimes move convenient to move around diagram elements using the keyboard
than with a mouse, especially when we want to align diagram elements precisely. 

Let allow the modeler to use the keyboard to move  the selected diagram elements around.

### Describe the solution you'd like

Use the arrow keys to move the selected elements up, down, left, right with very small steps (a pixel or a couple of pixels). 
Use of shift and arrow shall move the the diagram elements with bigger steps (10px, 20px, needs to be tried out).

**Comment by sz332** [comment]
Will take a swing at this.

**Comment by danyeaw** [comment]
Closed by #2617.
