### ISSUE TITLE
Keyboard Shortcuts Don't Work in ToolPalette

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#257]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior
I have seen them work, but the Tool Palette keyboard shortcuts currently aren't working. Nothing happens when I type Shift+E or L or any of others. Other keyboard shortcuts like Ctrl+E for the Editor Window work fine.

### Expected behavior
Tool Palette keyboard shortcuts working.

### System Information
OS:
- [X] Linux - Ubuntu 19.10
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by amolenaar** [comment]
I tried, and it seems to work, although it's the diagram that needs focus. If the tree view has focus, entering text will show a search popup.

**Comment by amolenaar** [comment]
@danyeaw Does this change fix the issue?

**Comment by danyeaw** [comment]
In Linux with Ubuntu 19.10: I click on the diagram, and even select a diagram object and the keyboard shortcuts still don't work for me.

In Windows: the keyboard shortcuts work fine.

**Comment by danyeaw** [comment]
Although I was able to reproduce this yesterday, I tried to reproduce this again to see if it was a Wayland vs. X11 issue, and it seems to be working now. I am closing this until I can reproduce in Linux.

**Comment by h8672** [comment]
### Got problems with tool palette shortcuts:
- Cannot select tool with shortcuts in tool palette.
- If selected a tool with mouse, cannot change it to pointer tool with escape.

Also some trouble if using Tabs to move in tool palette:
- First need to resize tool palette to allow moving with tab key in it...
- To move to tool palette, you can use Ctrl_Tab to move past each UI category (Ctrl_Shift_Tab to reverse).
- Moving with Tab in tool panel highlight is updated on **2nd press** and I cannot select if light blue highlight is on top of current focused tool with enter.
- Moving backward with Shift_Tab allows you to select new tool with Enter, but on **2nd press** it is highlighted and you cannot select it.
- Behaviour doesn't change with different themes (Tried all themes Pop OS delivered, pop, pop-dark. adwaita, adwaita-dark, high contrast).
- There's also different highlights for each tool categories in tool palette, which might be confusing.
- Highlight and focus are currently different, focus doesn't show up on screenshot, but it doesn't move past to the next tool if highlight isn't on same tool first.

### Might be connected issue

If the main state for tool palette doesn't update with first key, it just expects a second press, but focus is on diagram so it just updates current tool palette without waiting a confirmation.

Selecting a highlighted tool ***with a mouse*** after drawing is successful with every ***2nd press***.

----

I don't know if it is a problem with current version of GTK or just how it is currently in use in the tool palette.

### OS
- [x] Linux (Pop OS 21.10)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.7.1 (flatpak)
