### ISSUE TITLE
Ability to add elements in the model tree (under desirable package) and later add it into diagrams

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2580]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
Ability to add elements in the model tree (under desirable package) and later add it into diagrams

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by sz332** [comment]
@shobeira is the following, already existing ticket the same as the one you asked for? There is a video in one of the comments.

https://github.com/gaphor/gaphor/issues/2552

**Comment by shobeira** [comment]
Yes, it is. I am completely agree is the issue #2552 you mentioned and it also would be great to be able to search for specific element in the element tree/browser. The video is very nice, well implemented.

**Comment by sz332** [comment]
@shobeira it is not yet implemented, but marek is working on it, it was more like a preview. If you have any other request (like the search) please add it to #2552  as a comment.
