### ISSUE TITLE
Using images in diagrams

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2583]
### Is your feature request related to a problem?

I would like to be able to see images (like png, jpeg) on a diagram, move it around, and resize. It would be nice to be able to see the same image on multiple diagrams as well.  

### Describe the solution you'd like

The way an image could be created are the following:

-  Drag and drop from file browser
-  Copy paste
-  Create a new image element in the model and selecting an image as a property 

All these operations would create an image element in the model that would contain the image, not just a reference to the image.

Then this image could be dragged to the model into the diagram, then the image will be displayed as a box. It can be moved around and/or resized as any box like model element.

**Comment by danyeaw** [comment]
Closed by #2651.
