### ISSUE TITLE
Ability to differentiate between diagrams in the model browser

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2587]
### Is your feature request related to a problem?

I would like to be able to differentiate between the diagram types displayed in the model browser/tree.

### Describe the solution you'd like

One solution could be custom icons for each diagram type.

**Comment by marek-piirikivi** [comment]
Another solution could be to display abbreviation in addition to its name in the model browser; or use it in combination with the initially proposed solution.

**Comment by sz332** [comment]
> Another solution could be to display abbreviation in addition to its name in the model browser; or use it in combination with > the initially proposed solution.

Totally agree, we need to make an experiment to see how it actually would look like, and go with the one easier to understand.
