### ISSUE TITLE
Abstract, attributes, operations does not seem to make sense for Requirements in SysML

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2588]
### Describe the bug

When selecting an element of requirement type, abstract, attributes, and operations are displayed. I understand that it is coming from the UML metamodel but in my opinion those are meaningless and should be removed.

### To Reproduce
1. Create a new model
2. Select SysML profile
3. Create a requirement diagram
4. Add a new requirement
5. Select the new requirement
6. Bug: Abstract, Attributes and Operations are displayed

### Expected behavior

The properties that are not really relevant should be not displayed.

### Screenshots

![image](https://github.com/gaphor/gaphor/assets/8182138/2eabe19a-3ce6-486b-b456-7e925c267c56)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.19.3.dev3420+5529a503

**Comment by danyeaw** [comment]
@sz332 Did you want to also remove the Is Abstract as well before we close this issue?
