### ISSUE TITLE
Moving and deleting an element from the Element browser cuase collapsing the browser

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2593]
### Describe the bug
Moving and deleting an element from a package in the element browser cuase collapsing the element browser/tree to a random element in the tree.

### To Reproduce
1. Create an element in the element browser (preferebly under a package. The model I am working on has a large number of packages)
2. Try to remove the element and you will see the tree behave differently

It is bothering specially if you are going to change a few elements and each time you have to find the right package you were in before deleting the element.

### Expected behavior
It is expected to delete/move an element without affecting the tree location you were working on.

### OS
- [Ubuntu 22.04] Linux

### Version
Version of Gaphor: 2.19.3

**Comment by sz332** [comment]
Can you please try with a daily build? I think it has been fixed.

**Comment by shobeira** [comment]
where can I find the daily build @sz332 ? The realease versions are available but I can not find the daily build. would be easy to try the daily build in AppImage format though.

**Comment by shobeira** [comment]
Was able to try with the latest package ([gaphor-x86_64](https://github.com/gaphor/gaphor/suites/14850372923/artifacts/845673008) and there is no collapse after deleting an element from the model browser.

Thank you for your time and effort.
