### ISSUE TITLE
Reorder model elements in the model browser/tree

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2594]
### Is your feature request related to a problem?
Showing a long name underneath of element on diagrams.

### Describe the solution you'd like
Reorder elements as I wish without restriction of alphabetical order.

### Describe alternatives you've considered
Currently model elements are sorted alphabetically and I use nested numbering format to order them the way I need.

**Comment by marek-piirikivi** [comment]
> Currently model elements are sorted alphabetically and I use nested numbering format to order them the way I need.

I would like to add that this system collapses as soon as you have more than 10 items in the list.

**Comment by amolenaar** [comment]
Closing as duplicate of #2334.

I think we can support different types of ordering/sorting. Changing the order manually is a lot of hassle, since we also have to store that order.
