### ISSUE TITLE
Double clicking on diagram title highlight the diagram on the model tree

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2597]
### Is your feature request related to a problem?
Unclear where the diagram is on the model tree.

### Describe the solution you'd like
Double clicking on diagram title highlight the diagram on the model tree

### Describe alternatives you've considered
In order to differentiate diagrams from other elements in the model browser, it would be nice to have diagrams on top of the package it exists on.

**Comment by marek-piirikivi** [comment]
> In order to differentiate diagrams from other elements in the model browser, it would be nice to have diagrams on top of the package it exists on.

This could be problematic to achieve within SysML profile, because the diagrams can also be owned by non-package elements. What could be achievable to is to show diagrams as the first items under its containing element. So, basically what you said, but more generic.

Currently, what can also be done is to just search the diagram name within the model tree. There exists a search bar which can be opened with ctrl+f.

**Comment by shobeira** [comment]
That is what I meant indeed.

I am not sure, but in SysML everything goes under a Model package. If so, it could be possible to sort all diagrams on top of other elements in the package eventhough the diagram is placed in the parent package named "Model".

**Comment by sz332** [comment]
Let's make one step back, and let's try to figure out what the user's problem/need actually is. The reason for this is we tend to jump directly into a solution space instead of talking through the issue we have in the problem space, and it often results suboptimal solutions.

@shobeira can you please help us making the transition back into the problem space so that we can talk it through? What is hinders your workflow and why?

**Comment by shobeira** [comment]
While I was working on a diagram, it was needed to add an element to the package which the diagram was placed in it. I was unable to find the package which the diagram was placed on it. I went through the whole model tree to find the diagram and add an element to the model.

**Comment by sz332** [comment]
So the way I understand you would like to have a capability to find the current diagram in the model an easy way. 

The current behavior is: if we click a diagram element, the corresponding model element is automatically selected. 

This means we have a synchronization of selection between the diagram and the model browser. (in other tools it is something you can switch on and off).

How could we add this new capability consistently from UX perspective?

**Comment by marek-piirikivi** [comment]
@sz332 I think that you currently can not select the diagram in any way from the diagram itself... but when clicking on a element; I think it selects correct thing from the model browser already :thinking: 

@shobeira Suggests that clicking on a title should take to role of selecting the diagram. It is not terrible UX.

**Comment by sz332** [comment]
So to summarize: if we have a diagram open, by clicking on the title, we would select the diagram, and as a result of that event, the  model browser will select the corresponding item, representing the diagram?

**Comment by mikekidner** [comment]
So is this complementary to the "show element on diagram" functionality which exists already when you right click an element in the model browser.
Would right _click on title_ -> "show diagram in model browser" be consistent?

As you mention there is also the _click on element_ -> "highlight element in browser" behaviour. 

We need to be careful this doesn't clash with other feature requests re ordering, expanding, collapsing of the model browser automatically as events happen on the diagrams.

**Comment by sz332** [comment]
Good point about not having a title bar.

So, what do you think about right-click, displaying a popup window with now a single option? That would also enable us to allow adding more actions.

An alternative to this could be to left click on the diagram that would select the diagram and in the properties we could have an an action button doing the same.

Let's do a tradeoff-analysis. What do you think about the two solutions? What are the advantages, disadvantages, and which one you'd like to have more?

**Comment by shobeira** [comment]
For generic diagram, it is systematic to make them all unified and have a title bar for all of them including generic diagrams. That way, there is no difference between generic diagram and the rest of diagrams (I know SysML and UML diagrams).

Currently, by right-clinking on an element in the element browser, there is an option to show the element on a diagram. And by selecting an element on a diagram, the element in the element browser will be selected.

My suggested feature comes from the scenario below:
Working on a diagram (e.g: BDD) and the diagram is located in the project tree under "Structure" package which is beneath of "Physical Level" package itself. The model tree is collapsed and you are going to add an element to the diagram but have no idea where the diagram is located on the model tree.

Model-tree
└ Physical level
	└ Structure
		└ **Block Definition Diagram (BDD)**

The user need to:
Open the collapsed model tree to see all model hierarchy and all elements to find the diagram he is intending to add an element to it, select the package containing the diagram and add the element to the package.

Alternatively, the main issue may be arosed from the complexity in the process of adding an element to a diagram:
If I want to add an element to a diagram from the element browser area by drag and drop method, the element will place on the diagram while it is placed on 1 level up from the diagram location in the model browser. That makes it difficult to add elements to a diagram and everytime I need to move element into the related package in the model browser. That's why suggesting the double click feature on the diagram title in order to find the right place to add elements to the diagram.

As a user, I prefer to click on the diagram title to go directly to the right package where the diagram is located, rather than having to right click on the title bar and clicking on the "Show Diagram in Model Browser". The simplicity of Gaphor is what attracts me. I was using StarUML before Gaphor, and Eclipse Papyrus before that.

**Comment by sz332** [comment]
I like the proposal of right click, also opens up lots of opportunities for further development.

**Comment by danyeaw** [comment]
@all-contributors please add @shobeira for idea
