### ISSUE TITLE
Opening multiple models cause changing of background color of the diagrams

### ISSUE THREAD

**Issue by shobeira** [gaphor/gaphor#2598]
### Describe the bug
The background of the recent model opened is applied to all model opened before the recent one.

### To Reproduce
Open multiple models with Gaphor.

### Expected behavior
Each model has its own style sheet and is expected to be based on that. Regardless of what other model style sheets are.

### OS
- [ Ubuntu 22.04] Linux

### Version
Version of Gaphor: 2.19.3

**Comment by amolenaar** [comment]
@shobeira Thank you very much for report.

**Comment by danyeaw** [comment]
@all-contributors please add @shobeira for bug

**Comment by shobeira** [comment]
> @all-contributors please add @shobeira for bug

That's nice of you mate! didn't expect it. Cheers.

**Comment by shobeira** [comment]
@danyeaw that's nice of you mate! didn't expect it. Cheers.
