### ISSUE TITLE
Diagram specific settings

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2599]
### Is your feature request related to a problem?

This is more like a feature request that opens up additional possibilities but it would be great when we could have
settings for each and every diagram. 

There could be some settings that are common for every diagram type (like enable/disable grid), and also diagram type specific (display order numbers for sequence diagrams).

**Comment by amolenaar** [comment]
I think we need more concrete, actionable issues.

I'll close this one, since it has had no update for over a year.
