### ISSUE TITLE
Display the type of the selected model element

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2607]
### Is your feature request related to a problem?

Sometimes it is not easy to identify the type of the selected diagram element, because in order to identify I need to go through all the icons and try to match. It would be nice to see the model type of the selected element in a textual format.

**Comment by danyeaw** [comment]
Hi @sz332, where would this type be displayed?

**Comment by mikekidner** [comment]
@sz332 would this feature be for users that are not familiar with UML/sysML notation or are you referring to the element-type, which is normally shown in the right hand panel if it is applicable?

**Comment by marek-piirikivi** [comment]
@sz332 Are you thinking that when you select an element from the diagram and property page pops up, you would like to see its type on the property page?

Or are you talking about selecting from the model browser? I see you are talking about diagram elements, but stereotypes/types are usually shown on the diagram, so there shouldn't be any confusion. :thinking:

**Comment by sz332** [comment]
I am talking about the property panel. Simply a label showing that the selected element is a type of Class.

**Comment by sz332** [comment]
![image](https://github.com/gaphor/gaphor/assets/8182138/edc93bcf-719e-4a4c-8f24-6934cc3c3ba1)

**Comment by danyeaw** [comment]
Closed by #2630
