### ISSUE TITLE
Enumeration is shown as valueType on the diagram

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2609]
### Describe the bug
When creating enumeration on the diagram, it is typed as valueType instead of enumeration.

### To Reproduce
1. Create block definition diagram
2. Select enumeration from the toolbox
3. Click on the diagram

### Expected behavior
`«enumeration»` should be shown instead of `«valueType»`.

### OS
- [x] Linux (Mint)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.19.3

### Additional information
The problem seems to be only with visualization on the diagram. In the model explorer, the element is correctly typed (according to the icon).

**Comment by danyeaw** [comment]
Hi @marek-piirikivi, a SysML Enumeration is a UML Enumeration with ValueType applied. I think you will find this same behavior in MagicDraw, were you expecting no ValueType stereotype?

**Comment by marek-piirikivi** [comment]
According to the SysML standard, in bdd, ValueType representation is described as 
![image](https://github.com/gaphor/gaphor/assets/45357878/03a581f5-f277-4ef6-8d57-ad48498179c0)
and enumeration representation is described as
![image](https://github.com/gaphor/gaphor/assets/45357878/1c6573ca-00b3-4d81-a6a1-c0e81fb71833)

I searched the web as well, and everywhere there seems to be `«enumeration»` used, as I would expect. I think MagicDraw is incorrect if it shows ValueType stereotype in the representation. :thinking:

**Comment by danyeaw** [comment]
I think this is on purpose so that properties typed by it will list as value properties in the values compartment of a block.

![Using Enumeration in SysML.png](https://github.com/gaphor/gaphor/assets/10014976/a9e3a5f2-5967-4baf-beac-23e6a616b411)

**Comment by marek-piirikivi** [comment]
@danyeaw The essence of my problem is purely cosmetic. I can see that specification defines that enumeration should be displayed with «enumeration» as it is in UML. I would not take MagicDraw as the source of truth - it seems to be conflicting with the specification in this case. I checked out Papyrus and Astah and both of them show «enumeration».

I think we should conform with the specification in this case.

**Comment by sz332** [comment]
I agree that the correct thing to show is enumeration, as specified by the standard. 

If the reason for MagicDraw guys was only for rendering, then maybe we could discuss how to do that. Also, it is always possible to add the valueType stereotype on an enumeration, or we could even have two tools: one conformant with standard, the second one with added valuetype stereotype.

**Comment by danyeaw** [comment]
I agree that following the SysML spec is important. Maybe we should discuss the use case of why someone would add an Enumeration in a SysML model? Surprise isn't great but also making a user take a bunch of steps to use an Enumeration isn't great either.

**Comment by marek-piirikivi** [comment]
> but also making a user take a bunch of steps to use an Enumeration isn't great either.

I think you are missing the point of this issue. Everything stays the same except `valueType` keyword on the diagram is changed to `enumeration` when the item is representing enumeration.

The problem originates when I had value types and enumerations on the same diagram and I could not visually tell the difference which is which and had to select them and look into the model browser. So, it is a bit about improving user experience; and mostly just conforming with the specification.

**Comment by danyeaw** [comment]
This was done on purpose in order to support things needed for RAAML: https://github.com/gaphor/gaphor/issues/1485

In that issue, there is also discussion in the MagicDraw forum why MagicDraw does it this way. We can decide to do it differently, but we need the ability to create enumeration literals with ValueType. Renaming ValueType to Enumeration will not achieve that.

The SysML Spec does show a diagram with enumeration literals, and it has ValueType here:
![image](https://github.com/gaphor/gaphor/assets/10014976/f289afd0-9f7d-470b-94a6-244bae3c3563)

I think it may actually be an error in section 8.2.1.

**Comment by marek-piirikivi** [comment]
ah, fair enough. Indeed, it is not certain which one is the correct way to display it. I'll close this issue. Thank you for your time! @danyeaw @sz332
