### ISSUE TITLE
Defined ports not adding to parts

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2612]
### Describe the bug
If a port has already been manually added to a block or part, when the block is on a diagram double-clicking the port in the model browser displays the port on the block. However, a predefined port cannot be added to the part by the same method. A new port has to be created.

### To Reproduce
1. Create a block
2. Use the corresponding part on an ibd
3. Add a port to the part
4.Go to the bdd, and double click the port in the model browser -> the port adds to the block.
5. Now try the above, but creating the port on the block first and then double clicking to automatically add to the part in the ibd.
6. It does not.

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
If a port has been defined on a block or part, double clicking the port property in the model browser should add the port to the block or part on the diagram not just the block.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor:2.20

**Comment by danyeaw** [comment]
Thanks @mikekidner. This sounds like a good idea, I would expect this is a new feature since probably no one tested this use case.

**Comment by marek-piirikivi** [comment]
If possible, would @mikekidner, be so kind and rephrase the expected behavior? I have trouble understanding what should happen. :slightly_smiling_face: 

Currently, I can create the block. Add port to it. Then I can reuse the same block in another diagram. When I double-click on the port, it is correctly added to the block as I would expect.

**Comment by mikekidner** [comment]
Yes, no worries.

Create a parent (B0) and child (B1) block, 
Add a port to B1. 
Now use the B1-Part on the ibd of B0, try to add a port to the B1-Part by double-clicking in the model browser.

**Comment by marek-piirikivi** [comment]
![image](https://github.com/gaphor/gaphor/assets/45357878/35d2ed75-a0ad-4cf3-a327-e67ded173496)
![image](https://github.com/gaphor/gaphor/assets/45357878/f63992cf-dd80-46bf-9c7e-e19e08ad35b3)

@mikekidner I followed your instructions. See the screenshots whether it looks as if I did. It behaved as I expected. I have trouble understanding your expectations. Especially "double clicking the port property in the model browser should add the port to the block or **part on the diagram** not just the block." It did add it to the port. What is meant by the "part on the diagram"?

**Comment by mikekidner** [comment]
Hi @marek-piirikivi, by "part" I mean the property B1 owned by B0.
Here is a bdd for block B0, 
<img width="534" alt="Screen Shot 2023-08-10 at 5 27 18 am" src="https://github.com/gaphor/gaphor/assets/50702106/c0a7b113-2c7d-4a42-907a-04114937ea42">

here is the ibd, showing the parts of B0,  
<img width="589" alt="Screen Shot 2023-08-10 at 5 27 30 am" src="https://github.com/gaphor/gaphor/assets/50702106/f4a541b5-a788-46f3-8fca-b5ce73435cf1">

Now, I'm working in the IBD defining connections, so I create a port on B1, and it shows a property beneath B1 in the model browser.
<img width="613" alt="Screen Shot 2023-08-10 at 5 30 05 am" src="https://github.com/gaphor/gaphor/assets/50702106/335a93d4-ee7d-4d06-b27c-33e53a0979ec">

Returning to the bdd, I can then double click on the port "+ p_b1" in the model browser, and the pre-defined port is added to the block B1. Which is great.
<img width="512" alt="Screen Shot 2023-08-10 at 5 33 38 am" src="https://github.com/gaphor/gaphor/assets/50702106/a380e8cc-629f-45a5-ae14-f5e0ebf3ef71">

 But wait, I need to define a port on part B2... so I do that here in the bdd, by adding port p_b2 to the B2 block
<img width="580" alt="Screen Shot 2023-08-10 at 5 34 59 am" src="https://github.com/gaphor/gaphor/assets/50702106/09a99ef7-2216-4f24-9e27-62f5b0a69ff9">

Now, returning to the ibd in order to complete the connections between the parts. In the ibd I expect I can show the pre defined port "p_b2" on the part "B2Part:B2" by once again double clicking the port "+p_b2" in the model browser, but I can't. Double clocking does nothing and dragging it on generates an error message
<img width="724" alt="Screen Shot 2023-08-10 at 5 38 36 am" src="https://github.com/gaphor/gaphor/assets/50702106/e04ad07c-bae6-40f9-97db-3b0e46a80e96">


Does that make more sense?

**Comment by marek-piirikivi** [comment]
@mikekidner Yes, thank you! All clear now.

**Comment by mikekidner** [comment]
> When only a single kind of a part is on the diagram; double clicking adds it the the part.

Yes. that would be what I'd expect to happen.

> When two or more parts share the type (imagine a scenario where a vehicle has multiple wheels); double clicking would not do anything; you have to drag to select appropriate part.

I think doing nothing would confuse the user. The port should add to all the parts, this is in line with the behaviour above, and it's likely the user will need those ports e.g. to connect each wheel to the axle. It would be easy to delete the ports if not needed. But this opens up the issue of _not-showing_ vs _deleting_ . A separate issue for further discussion I think....

**Comment by marek-piirikivi** [comment]
> I think doing nothing would confuse the user.
Ah, yes. You are absolutely right. I'll just add it to all the things that can own this port as a default. I can not imagine a scenario where we would not want that. An you can always create multiple ibd-s to highlight different aspects of the usage which would show only relevant parts anyways.

**Comment by mikekidner** [comment]
@marek-piirikivi did you start to work on this? Is there any parts you need help with?

**Comment by marek-piirikivi** [comment]
@mikekidner I did not start with this yet. This issue is still up for grabbing.

**Comment by mikekidner** [comment]
@marek-piirikivi I'd love to have a go at this but unsure where to start. Do you have any advice on where the code needs changes?

**Comment by marek-piirikivi** [comment]
@mikekidner I would start by having a look at the `modelbrowser.py` and search for the path that would lead me to the attempt to add something on a diagram and then investigate the reasons on why it does not let you add the port on the diagram. I know there is `dnd.py` which deals with drag&drop. Once I would understand what prevents the port being added, I would see what needs to be changed to allow it.

**Comment by marek-piirikivi** [comment]
@mikekidner Did you ever start working on this? I have a merge candidate that I would like you to confirm whether it is as you expected.

https://github.com/gaphor/gaphor/assets/45357878/00387305-3fcb-492b-9291-a4b3d91e5de7

**Comment by marek-piirikivi** [comment]
I fixed the icon as well. Noticed that it was broken.

**Comment by marek-piirikivi** [comment]
@mikekidner This is now resolved and is on the train to go out in the next version. In addition, few other problems with proxy port were solved such as a) its removal whenever any item representing the port was deleted → now only when last representation is deleted, the element gets deleted (only when "Remove unused elements" is active); b) we can add multiple representations of the same port on the same diagram by dragging it to the closest part or block which can own the port.
