### ISSUE TITLE
Update appstream screenshots

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#2620]
The appstream screenshots are quite old (pre-GTK4 port), and don't reflect the look of the current UI anymore:

![image](https://github.com/gaphor/gaphor/assets/1908896/00befb04-09e0-47e2-9882-e17f8d611a98)

**Comment by danyeaw** [comment]
Thanks @bertob, good idea to update these - those definitely are a few years old :+1:

**Comment by amolenaar** [comment]
This also applies to our website.

**Comment by danyeaw** [comment]
Fixed, thanks for the issue report. :+1:

**Comment by amolenaar** [comment]
we should also update the screenshots on the website.
