### ISSUE TITLE
Trace (and derived relationships) show up at the top model level

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2621]
### Describe the bug
Trace relationships (trace, derive, refine, satisfy, and verify) show up at the top level of the model instead of under their supplier block (or supplier block containing folder). 

### To Reproduce
1. Create 2 requirement blocks
2. add a derive relationship

### Expected behavior
I'd expect the relationships to appear under the supplier block similar to associations. 

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20.0

**Comment by danyeaw** [comment]
Thanks @tompkins-ct, I can reproduce this.

@amolenaar to influence this, do we make the relationship an ownedElement of the suppler requirement?

**Comment by amolenaar** [comment]
Yes, the owner-ownedElement relation should be defined as "subsets", both ways.

**Comment by danyeaw** [comment]
@all-contributors please add @tompkins-ct for bug
