### ISSUE TITLE
Derive relationship icon missing in model browser

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2622]
### Describe the bug
as above 

### To Reproduce
1. Make 2 requirments
2. Add derive relationship

### Expected behavior
Correct icons.

### Screenshots
<img width="786" alt="image" src="https://github.com/gaphor/gaphor/assets/58485783/c8e36554-77f6-46e0-ac42-fa852e63b02b">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20.0

**Comment by marek-piirikivi** [comment]
I can reproduce. I'll fix this.

**Comment by marek-piirikivi** [comment]
Should be fixed with merging #2626. I'll close the issue. @tompkins-ct You can consider it fixed next release.
