### ISSUE TITLE
New Model pop-up hidden by currently open model window. Closing model window closes Gaphor

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2623]
### Describe the bug
When creating a new model with an existing model already open. The pop-up window is behind the already open model window. Closing the model window closes the application.

### To Reproduce
1. Open an existing model
2. Click on the right hand "Open Application Menu "-> choose "New Model" 
3. See that dialog pop-up is behind currently open window
4.Close the open model, in order to get to the pop-up
5. Oh-no! I just closed the application by mistake.
6. Next time remember to drag windows around to get to the pop-up

### Expected behavior
That the pop-up is always on top.
And possibly that as the pop-up was open, I'd expect closing the existing model window would not close the application.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20

**Comment by amolenaar** [comment]
Nice catch. If you use the shortcut (Cmd-N) it works as expected.

I assume it has something to do with closing the popover menu.

**Comment by danyeaw** [comment]
Closed by #2655. Thanks @mikekidner for submitting this!
