### ISSUE TITLE
Should a comment be a model element?

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#2632]
### Is your feature request related to a problem?

When creating a new comment it will be not a model element, but only an element as part of the diagram.

### Describe the solution you'd like

Sometimes I would like to use the same comment on multiple diagrams, making it a model element (instead of just a diagram element) could enable us to do that.

**Comment by amolenaar** [comment]
Currently you can do that by copy/pasting the comment.

In order to show a comment in the Model Browser, we need to have an owner-ownedElement relation on the Comment. The UML spec have a relation for that defined, but we haven't implemented it.

**Comment by amolenaar** [comment]
Should we do anything here? Comments (annotations) are part of the modeling language.
