### ISSUE TITLE
macOS keybinding overrides are no longer loaded

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#2636]
### To Reproduce
1. Go to a text field, type some text
2. Hit Cmd+a
3. Nothing happens, Ctrl+a selects all.

### Expected behavior

Common keybindings on macOS should work

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20.0

### Additional information

This issue exists since GTK 3 code has been removed from the UI module (March 2023).

**Comment by danyeaw** [comment]
Fixed by #2637
