### ISSUE TITLE
Copy and paste in comments on Mac uses Ctrl-V rather than Cmd-V

### ISSUE THREAD

**Issue by AlDante** [gaphor/gaphor#2669]
### Describe the bug
When entering text in a comment or copying an error report, on a Mac (details of my setup below), then you have to use Windows keys - i.e. Ctrl-C and Ctrl-V, rather than Mac standard Cmd-C and Cmd-V. 

### To Reproduce
1. Go to Tools/Error Reports or create a comment
2. Select text to copy and enter Cmd-C
3. Enter Cmd-V in the bug report
4. No text is copied.

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.
Gaphor version:         2.20.0
Operating System:       Darwin (22.5.0)
Display:                GdkMacosDisplay
Python version:         3.11.4
GTK version:            4.10.4
Adwaita version:        1.3.3
GtkSourceView version:  5.8.0
Cairo version:          1.16.0
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4

Errors:

Time since application startup: 0:22:13
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'
└─────────────────────────────╌┄┈
Time since application startup: 0:22:14
|Traceback (most recent call last):
|  File "/Applications/Gaphor.app/Contents/MacOS/gaphor/ui/toolbox.pyc", line 233, in _flowbox_drag_prepare
|AttributeError: 'NoneType' object has no attribute 'draggable'

### Expected behavior
Expect copy and paste on Mac to work with Mac standard keys (Cmd-V and Cmd-C)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor:2.20

### Additional information
Apple Silicon Mac, M1 Max, Ventura

**Comment by amolenaar** [comment]
With the latest version, copying and pasting works in the Property Editor again.

However, I cannot paste with Cmd+v in the popup text field (e.g. when creating a new Class). Ctrl+v works, though.

**Comment by amolenaar** [comment]
I'm closing this as copy/paste seems closely related to the IME issue described in #2647.
