### ISSUE TITLE
Deleting block deletes ports from instances of block on other diagrams

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#2672]
### Describe the bug
A block with ports is shown on multiple diagrams. Deleting one of these blocks removes ports in the other diagram.

### To Reproduce
1. Create new diagram with block  (B1) and add port (p1) to block

<img width="574" alt="Screen Shot 2023-08-25 at 10 09 17 am" src="https://github.com/gaphor/gaphor/assets/50702106/43280907-9fe6-41d0-ac25-847307af129c">

2. Create another diagram and add the block
3. Add another port on this _another_ diagram

<img width="545" alt="Screen Shot 2023-08-25 at 10 12 30 am" src="https://github.com/gaphor/gaphor/assets/50702106/65f73f2c-82f2-4f7d-b180-2714f3ce5149">

4. Now, return to  _new_ diagram and delete the block.
5. Check the _another_ diagram
6.  See how port p1 has gone, but p2 remains

<img width="230" alt="Screen Shot 2023-08-25 at 10 15 01 am" src="https://github.com/gaphor/gaphor/assets/50702106/b8db6d76-0da2-42ce-8d96-8c3b5ce8a276">

### Expected behavior
Both ports should remain, as the block has not been deleted from the model, only from a diagram (not the only diagram where it occurs).

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20

### Additional information
It appears that the ports defined in a diagram get deleted with that diagram. But the ones defined elsewhere remain. I'd expect a block defintion to be persistent and not dependent on the diagram where it occured.

**Comment by sz332** [comment]
Might it be caused by the cleanup service?

**Comment by mikekidner** [comment]
This appears to be fixed, but now deleting the block on one diagram leaves orphaned ports.

**Comment by mikekidner** [comment]
This appears fixed in 2.24, but deletion of the blocks from one diagram leaves orphaned port symbols. I'll make another issue for this.
