### ISSUE TITLE
Add/Increase tolerance when selecting a line with a mouse

### ISSUE THREAD

**Issue by alensiljak** [gaphor/gaphor#2739]
### Is your feature request related to a problem?
When trying to select a line on a diagram, i.e. an Association, it often takes several clicks before I hit the line exactly.

### Describe the solution you'd like
If possible, there would be a tolerance, where the nearest line would be selected if it is within n pixels or whatever sensible units of distance. If multiple lines are found within the radius, then no action would be taken.

### Describe alternatives you've considered
Regularly practicing targeting elements with a mouse cursor.

**Comment by amolenaar** [comment]
Hi @alensiljak,

Lines have a tolerance of 2 points at the moment. Maybe that's a little less?

**Comment by alensiljak** [comment]
Possibly. I have a scaling on (I think 125% or more, must check) and it is very impractical to select a line. I'm not sure if there's other sensible measure other than pixels. Perhaps increasing it a bit would work on systems with scaling.

**Comment by danyeaw** [comment]
@all-contributors please add @alensiljak for bug

**Comment by danyeaw** [comment]
Thanks @alensiljak, this is now improved and will be out in our next release :+1:

**Comment by alensiljak** [comment]
Thank you!
