### ISSUE TITLE
Copy/Paste functionality should use Gtk.Clipboard

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#274]
### I'm submitting a...
- [X] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

To fix this completely, we have to use [GTK 4](https://github.com/gaphor/gaphor/issues/618).

### Current behavior

* Copy/paste does not work as expected. When a diagram item is copied, it's not possible to paste a text copied from somewhere else.
* It's not possible to copy (part of) a diagram and paste it in another application.

### Expected behavior

* Copying diagram items is only done when the diagram has focus - now it's a "win" action.
* Copy diagram items should allow them to be pasted as PNG/SVG in other applications.

### Minimal reproduction of the problem with instructions

1. Add an item to a diagram.Edit name field in element editor and paste. It won't paste anything in the text field but raise an exception instead.
2. Add an item to a diagram. Copy the item, edit name field in element editor and paste. It'll paste the diagram item instead

### Notes

This issue only concerns copy/pasting within Gaphor.
1. in the same model: copy model elements, relations between elements if they're copies together.
2. Model to model: What should be the rules when copying from one model to another? Model elements should also be copied along. They should get new id's.

We can unite 1. and 2. to some extend. Two options:
1. If both reference the same model, only the Presentation element (diagram item) is copied
2. If elements already exist with the same id, they are reused (this breaks when a model has been copied on disk and edited)

We can also copy/paste to other applications, in this case the selected elements should be rendered to PNG or SVG, in order to be easily copy/pastable in other documents.

### References
* https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/Clipboard.html
* https://python-gtk-3-tutorial.readthedocs.io/en/latest/clipboard.html

**Comment by amolenaar** [comment]
Copy and Paste should be treated as two separate actions. Copy should make a snapshot of
* the selected items
* their connections
* their model elements
* and maybe more (e.g. reference to a stereotype)

Pasting can be done in different ways:
1. paste in the same model
 * add diagram items to the active diagram
 * reuse references to existing model elements
 * recreate connections on diagram side (recreate on model side if removed in between copy and paste)
2. paste in a different model
 * add diagram items to the active diagram
 * Add model elements to the ElementFactory
   * Which elements/references should be created/reused?
   * reuse id or create new id's? Reuse would mean you can copy parts from one model and add them to the new model incrementally (e.g. when multiple diagrams are involved).
 * ...
3. paste outside Gaphor
 * Provide the copied bits as an image SVG/PNG to the 3rd party application 

### Notes:

* diagram items are not part of the model as held by ElementFactory 
  * now that diagram items inherit from Presentation, shouldn't they?

**Comment by amolenaar** [comment]
Not all `Gtk.Clipboard` API's are exposed in Python. We want to expose multiple target types (Gaphor data, but also images) and that's not possible with the GTK+ 3 API: [it's lacking the `set_with_data()` method](https://gitlab.gnome.org/GNOME/gtk/issues/364). This issue will not be resolved, since GTK 4 will have a new Clipboard API.

This implies we can only use the Clipboard to either store text (data, maybe a magic text that will allow Gaphor to look up it's internal copy buffer) or images (used if we want to allow users to copy/paste (parts of) diagrams. Not both.

I think we can work around this limitation, though:

* On the Clipboard we can put an image of the copied (diagram) content.
* We need to keep track internally of all model related state. Make copies where necessary and maintain those in a copy service. Let's assume here that on Linux, Windows and macOS, only one Gaphor instance is running at any particular time, hosting multiple windows.
* By listening to Gtk.Clipboard's `owner-change` events, we can know when our own copy is no longer the one to use. When Gaphor is no longer the source, the internal model snapshot can be disposed.
* We may want a simple Text and Image item, so users can paste something in a Gaphor model as well.

I think a user won't notice the difference :wink: .

References:

* For GTK 4, a new Clipboard API has been introduced: `Gdk.Clipboard`. This version has a binding friendly API (https://developer.gnome.org/gdk4/stable/gdk4-Clipboards.html). This API has not been backported to GTK3.
* [Data transfer in GTK4](https://blog.gtk.org/2020/01/29/data-transfer-in-gtk4/

**Comment by ghillebrand** [comment]
Hi,
It seems in 3.21 on Win10 that copy (ctrl-c) and paste (ctrl-v) works _inside_ a model, but external apps (eg WinWord) doesn't see any clipboard content, either text or image.
Am I missing something?

Thanks for all the effort - enjoying a powerful tool.

Grant
