### ISSUE TITLE
Display element UID

### ISSUE THREAD

**Issue by Sycophantic-Witty** [gaphor/gaphor#2750]
### Is your feature request related to a problem?
I would like to be able to refer to model elements by UID in documentation generators.

### Describe the solution you'd like
Display the UID of the selected object or diagram, in e.g. the property view, to copy & paste UIDs to model query scripts.

### Describe alternatives you've considered

- Add a contextual menu to elements with a "Copy UID to clipboard" entry.
- Add a "detailed properties" dialog showing the UID as well as all UML/SysML/... properties of the selected element.

### Additional context
N/A

**Comment by amolenaar** [comment]
Hi @Sycophantic-Witty,

Why do you not use the qualified name (name including namespaces) instead? 
That's what we do in the [Sphinx Extension](https://github.com/gaphor/gaphor/blob/main/gaphor/extensions/sphinx.py#L74-L84). UID's are internal (mostly used for saving/loading).

**Comment by Sycophantic-Witty** [comment]
Hi @amolenaar,

For instance, I would use a UID instead of the FQN of an element when referencing a somewhat deeply nested package to document the elements it contains. When a name in such a path changes (typo fix, renamed for a better name, package moved to another package, etc.), using an FQN instead of a UID implies that documentation fragments need a review as well as potential updates to change this name, even though the content documented in those fragments did not change.

I understand that you intend to keep how Gaphor generates UIDs an internal thing. However, using them to reference parts of a model in documentation only assumes that elements have a UID, and that a UID remains valid for ever.
Or do I misunderstand the intent? Do you actually mean that UIDs could one day completely disappear from Gaphor models?

**Comment by Sycophantic-Witty** [comment]
Ah but a trivial piece of Python code can retrieve UIDs based on FQN. Therefore, another way would be to copy the fully qualified name of an element to the clipboard (either using a dedicated UI feature or from a field in some property display), preferably in standard UML format (names separated with '::').

Perhaps with a Gaphor plugin?

**Comment by amolenaar** [comment]
Would it be an idea to add a section at the bottom of the Property Editor: "Type Information" (collapsed by default), that contains the ID of the selected diagram item, and underlying model element and the types of the diagram item and model element?

**Comment by Sycophantic-Witty** [comment]
> Would it be an idea to add a section at the bottom of the Property Editor: "Type Information" (collapsed by default), that contains the ID of the selected diagram item, and underlying model element and the types of the diagram item and model element?

That would be awesome! And perhaps a similar section for the active diagram as well?

**Comment by amolenaar** [comment]
Note to self: Add a CSS selector.
