### ISSUE TITLE
Upgrade InAppNotifier to Use libadwaita Toast

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2760]
### Is your feature request related to a problem?
The current notifications uses a Gtk.Revealer. Libadwaita now provides a Toast which is a really nice in-app notification.

## Describe the solution you'd like
Upgrade the notification module and ui file to use Adw Toasts

### Describe alternatives you've considered
Keep it the same

**Comment by amolenaar** [comment]
The only concern I have with the toast thingy is that it pops up in the diagram view. The current notifications are more out of the way.

It's probably worth the try, though, to see how it looks.
