### ISSUE TITLE
Connector end moved after reloading a model

### ISSUE THREAD

**Issue by Sycophantic-Witty** [gaphor/gaphor#2768]
### Describe the bug
Saving & loading a model loses the original position of some connector ends.

### To Reproduce
1. Create a diagram with four classes (say A, B1, B2, B3)
2. Create three composite associations between A and each Bn.
3. Save the model.
4. Restart Gaphor and open the model.
5. One end of a composite association has moved.

Nothing reported in the error report.

### Expected behavior
After reloading the model, the diagram looks the same as it looked when saved.

### Screenshots
Diagram view when saving the model:
![moving-connector-end-before](https://github.com/gaphor/gaphor/assets/94297113/ed79aa62-8afa-44c9-afc6-4eeab5a546eb)

Diagram view after reloading the model:
![moving-connector-end-after](https://github.com/gaphor/gaphor/assets/94297113/29004474-04e8-4a60-8fe4-8bbeb36a92d0)

### OS
- [X] Linux (Debian GNU/Linux 12.2 "bookworms")
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.21.0

### Additional information
Model: ![moving-connector-end.zip](https://github.com/gaphor/gaphor/files/12879104/moving-connector-end.zip)

**Comment by 2old4it** [comment]
I have the same issue with activities.
Diagram saved:
![Use_Case_Function_1](https://github.com/gaphor/gaphor/assets/76972837/049e7fd2-6b7c-4f06-864b-2ac6ec77b0bc)

Diagram after reopen:
![Use_Case_Function_2](https://github.com/gaphor/gaphor/assets/76972837/f86725ea-fbf0-4391-aa57-d7e21a736dce)

gaphas 3.11.3
gaphor 2.21.0

python --version
Python 3.11.5

Linux (Linux 5.15.128-1-MANJARO

**Comment by Sycophantic-Witty** [comment]
> ... Can you share the models?

I attached the model when I created the issue. If you open it, you should see the second image. Edit the A->B1 connector to look as in the first image and proceed from step 3 to reproduce.

**Comment by amolenaar** [comment]
@Sycophantic-Witty Thanks. I overlooked that.
