### ISSUE TITLE
Add mulltiline text, choice for user

### ISSUE THREAD

**Issue by SebCanet** [gaphor/gaphor#2777]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
For example, in use case diagram, when we fill a use case, we cannot choose if we agree or not with the automatic line return. And for an actor text does not return to a new line, and we cannot type a "shif + enter" line break to force it.

Solution:
1. add an selectable option "automatic line break"
2. add a manual line break capability

### Describe alternatives you've considered
Nothing

### Additional context
Educational context

Thanks a lot!

**Comment by amolenaar** [comment]
Something like this?

<img width="1173" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/ae3e5ea2-a8b0-4458-aa27-1e56acf260f4">

If text is wrapped now depends on the `white-space` CSS property.

BTW. This is a work-in-progress.

**Comment by SebCanet** [comment]
Thanks, that's it.
