### ISSUE TITLE
Pyinstaller build failures on Windows and macOS

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2782]
### Describe the bug
PyInstaller 6.1.0 is now working great, but it made a breaking change to move all the files except for the executable and icon to an _internal folder. I really like this improvement, but it is causing errors with our Windows installer and macOS packaging.

### To Reproduce
1. poe package
2. poe win-installer

### Expected behavior
Windows installer builds successfully

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [X] Windows

### Version
Version of Gaphor: main

### Additional information
I thought about reverting the update, but we may be able to just correct the packaging scripts instead

**Comment by amolenaar** [comment]
I think we have time to correct this.

Currently Dependabot jobs do not package the apps. Maybe they should, so we find this issues before we merge.

**Comment by danyeaw** [comment]
Yup, that would be ideal. The update passed CI and building the PyInstaller frozen app was also working. This broke downstream of that.

**Comment by danyeaw** [comment]
Fixed by #2788 and #2790.
