### ISSUE TITLE
macOS: About Dialog Links Not Working

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#2798]
### Describe the bug
On macOS, if I click on a link in the About Dialog, nothing happens.

### To Reproduce
1. Go to hamburger menu
2. Click on About Dialog
3. Website

```
Gtk-WARNING **: 13:55:42.707: Cannot connect to session bus when initializing OpenURI portal: Cannot spawn a message bus without a machine-id: Unable to load /opt/homebrew/var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/opt/homebrew/var/lib/dbus/machine-id”: No such file or directory
```

If I `brew install dbus` I get a slightly different error:

```
(gaphor:45189): Gtk-WARNING **: 14:53:51.173: Cannot connect to session bus when initializing OpenURI portal: Cannot autolaunch D-Bus without X11 $DISPLAY
```

### Expected behavior
Website links open

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: latest main

**Comment by amolenaar** [comment]
D-Bus is a Linux-only thing, right? So it would expect it not to work properly on macOS.
And if it would run, would it be able to open a link?

It would be nice to just open links, though.
