### ISSUE TITLE
Add sysml diagram on model navigator

### ISSUE THREAD

**Issue by 3fla1416** [gaphor/gaphor#2803]
### Is your feature request related to a problem?
It's not possible to add sysml diagram on model navigator.

### Describe the solution you'd like
Add sysml diagram on model navigator like generic diagram.

**Comment by danyeaw** [comment]
Hi @3fla1416, thanks for the issue / request. Can you please explain more about what you mean, you have the Model Navigation diagram open and you are trying to add another diagram to it by dragging it on to the diagram, but it's not possible?

**Comment by 3fla1416** [comment]
Yes, but it's just doesn't work with SysML diagram type. 
I have the Model Navigation diagram open and i try to add another SysML diagram to it by dragging it on to the diagram, but it's not possible.

With the generic diagram it's works, i can drag it on the model navigator, but for having the title of the SysML diagram i need to edit .graphor file and add "req":
```
<diagramType>
<val>req</val>
</diagramType>
```
It's not friendly.

So, i think it's easier to add the possibility to drag n drop the SysML diagram type on other diagram for resolve this issue.

**Comment by amolenaar** [comment]
Yup, it works nicely for a "normal" diagram, but not for a SysML diagram.

Thanks for reporting @3fla1416
