### ISSUE TITLE
State name text won't wrap

### ISSUE THREAD

**Issue by ghillebrand** [gaphor/gaphor#2813]
### Describe the bug
When trying to resize a State so that the text wraps, it always goes back to its original width.
The text wraps whilst the object is being resized, but as soon as the mouse stops moving, it jumps back to all-on-one-line 

### To Reproduce
Steps to reproduce the behaviour:
1.     Create a State and name it with a few words like Biologically Primary Information
2.     Try to resize it by dragging the bottom right handle so the width is smaller
3.     The width always reverts to the original width as soon as the mouse stops moving, even before the left button is released.

No errors reported - see Version section

### Expected behaviour
The text should wrap on spaces

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/9532378/fd37af00-6f98-43ff-b52c-d1c82fe37aaa)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor:
```Gaphor version:         2.21.0
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.5
GTK version:            4.12.0
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.24.0
pygit2/libgit2 version: 1.12.2  / 1.6.4


No errors have been intercepted. We’re good.
```

### Additional information
This seems closely related to this bug reported on Actions [here ]( https://github.com/gaphor/gaphor/issues/1278)
Adding a word-wrap option to the CSS did not help:
```diagram {
  /* line-style: sloppy 0.3; */
 word-wrap: break-word;
 /*background-color: coral; */
}
```

**Comment by amolenaar** [comment]
Thanks @ghillebrand,

This issue has popped up a couple of times.

word-wrap is not supported in our CSS. It would be a nice addition and would make the option to break in multiple lines
configurable.

See also #2777.

**Comment by danyeaw** [comment]
@all-contributors please add @ghillebrand for idea

**Comment by danyeaw** [comment]
@ghillebrand Thanks for the bug report and suggestion!
