### ISSUE TITLE
How come the concept section of the documentation doesn't have a single diagram?

### ISSUE THREAD

**Issue by alkis05** [gaphor/gaphor#2816]
### Is your feature request related to a problem?
The problem is that an open source modeling tool doesn't present a model to communicate its own architecture for people looking into modifying it in the concept section of the documentation.

### Describe the solution you'd like
For the documentation to include diagrams in the concept section at least.

### Describe alternatives you've considered
A disclaimer stating it is all a joke about the irony.

### Additional context
"Add any other context or screenshots about the feature request here."
Right, wouldn't it be wonderful if I provided visual explanation of the thing? I think you get the picture.

PS: Excuse me if it all sound too sassy.

**Comment by danyeaw** [comment]
Hi @alkis05, great idea! Would you like to help add some diagrams?

**Comment by alkis05** [comment]
I knew you would say that (I've watched some of your talks). I just thought the devs not only have better insight on how the app is structured, I would've thought you already modeled it.  
It is a bad idea to ask me for help on this, because it is going to be awful. But just so people don't say I didn't even try, here it is two of them to put on the Design Principles (a sysml Req diagram) and one for the frame work (a sysml bdd diagram). 
![Design_Principles](https://github.com/gaphor/gaphor/assets/5754055/27c660eb-f6f8-4b91-99e9-352da3659a7d)
![Gaphor_components](https://github.com/gaphor/gaphor/assets/5754055/07155b51-5446-4efe-a35d-ba8411b623f4)

Actually, maybe a gaphor model of gaphor would be an interesting thing.
[gaphor.zip](https://github.com/gaphor/gaphor/files/13329665/gaphor.zip)

I know comments are not the place to put this stuff. If I were to make a pull request, what would be the recommended place to put it?

**Comment by amolenaar** [comment]
@alkis05 I like the requirements diagram 👍. It's pretty neat.

I think the static structure we should be able to derive from the code, like we did on https://docs.gaphor.org/en/latest/gaphor-services.html. 

I would expect the biggest caveat for new users would be the event system. It makes a lot of components loosely coupled, but also makes it hard to determine what happens because of what.
