### ISSUE TITLE
Unable to save to mounted Google Drive

### ISSUE THREAD

**Issue by jrbso** [gaphor/gaphor#2830]
### Describe the bug
When attempting to save or export a file to a mounted Google Drive on Ubuntu 22.04, the operation fails with the error "An unexpected error has occurred"

### To Reproduce
1. On Ubuntu 22.04, go to Settings > Online Accounts > Google
2. Authenticate to Google
3.  Allow recommended permissions.
4.  On the Ubuntu Google Account dialog, make sure that "Files" is enabled under "Use for"
5. Confirm that the Drive filesystem has been mounted and is visible in the left-hand navigation bar in Files.
6. In Gaphor, go to the hamburger menu and select "Save as"
7. Navigate to the mounted drive in the Save dialog.
8. Select a folder that you have R/W rights to.
9. Click Save
10. See error

### Error Report:
Gaphor version:         2.21.0
Operating System:       Linux (6.2.0-32-generic)
Display:                GdkWaylandDisplay
Python version:         3.11.5
GTK version:            4.12.3
Adwaita version:        1.4.0
GtkSourceView version:  5.10.0
Cairo version:          1.17.8
Pango version:          1.51.0
PyGObject version:      3.46.0
Pycairo version:        1.25.1
pygit2/libgit2 version: 1.13.0  / 1.7.1

Errors:

Time since application startup: 0:21:37
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 111, in response
|    if filename := overwrite_check():
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 102, in overwrite_check
|    filename = get_filename()
|               └ <function save_file_dialog.<locals>.get_filename at 0x7f29a41f1b20>
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 96, in get_filename
|    return Path(dialog.get_file().get_path())
|           │    └ <Gtk.FileChooserNative object at 0x7f29a413fb80 (GtkFileChooserNative at 0x55d89b833690)>
|           └ <class 'pathlib.Path'>
|AttributeError: 'NoneType' object has no attribute 'get_path'
└─────────────────────────────╌┄┈
Time since application startup: 1 day, 4:19:33
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 111, in response
|    if filename := overwrite_check():
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 102, in overwrite_check
|    filename = get_filename()
|               └ <function save_file_dialog.<locals>.get_filename at 0x7f27bf417100>
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 96, in get_filename
|    return Path(dialog.get_file().get_path())
|           │    └ <Gtk.FileChooserNative object at 0x7f27bf411e40 (GtkFileChooserNative at 0x55d8a60c3340)>
|           └ <class 'pathlib.Path'>
|AttributeError: 'NoneType' object has no attribute 'get_path'
└─────────────────────────────╌┄┈
Time since application startup: 1 day, 4:28:40
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 111, in response
|    if filename := overwrite_check():
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 102, in overwrite_check
|    filename = get_filename()
|               └ <function save_file_dialog.<locals>.get_filename at 0x7f280b0f3ec0>
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 96, in get_filename
|    return Path(dialog.get_file().get_path())
|           │    └ <Gtk.FileChooserNative object at 0x7f27bf3d6900 (GtkFileChooserNative at 0x55d89b9d93f0)>
|           └ <class 'pathlib.Path'>
|AttributeError: 'NoneType' object has no attribute 'get_path'
└─────────────────────────────╌┄┈
Time since application startup: 1 day, 4:29:04
|Traceback (most recent call last):
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 111, in response
|    if filename := overwrite_check():
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 102, in overwrite_check
|    filename = get_filename()
|               └ <function save_file_dialog.<locals>.get_filename at 0x7f27bf415c60>
|  File "/app/lib/python3.11/site-packages/gaphor/ui/filedialog.py", line 96, in get_filename
|    return Path(dialog.get_file().get_path())
|           │    └ <Gtk.FileChooserNative object at 0x7f27bf3d3680 (GtkFileChooserNative at 0x55d8a7013270)>
|           └ <class 'pathlib.Path'>
|AttributeError: 'NoneType' object has no attribute 'get_path'
└─────────────────────────────╌┄┈

### Expected behavior
I expected the file to be saved to the specified Google Drive folder.

### OS
- [x] Linux (Ubuntu 22.04.3 LTS)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.21.1

**Comment by amolenaar** [comment]
This issue looks similar to #2717. Something is off with Freedesktop portals, which are used to make the host filesystem available in a Flatpak container.

**Comment by amolenaar** [comment]
@jrbso Is this problem still present? Does it also happen with other Flatpak applications?

**Comment by jrbso** [comment]
Sorry for the slow response! 
My problem has been resolved. 

I just got done using Gaphor to create a domain model for a new distributed system. Worked great! Thanks for the awesome work!
