### ISSUE TITLE
Ability to set BG/FG colors for a node/as a colorscheme

### ISSUE THREAD

**Issue by actionless** [gaphor/gaphor#284]
### I'm submitting a...
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

### Current behavior
Currently only text, size and position of the node could be changed.

### Expected behavior
Also add possibility to set colors of the nodes.

**Comment by danyeaw** [comment]
@actionless Thanks for the Feature suggestions :gift:. Colors are always nice to make things a little less boring :rainbow:, and although color doesn't have semantic meaning, I like the idea to allow for themes as well. We would love help implementing Features like these, is this something you would be interested in contributing?

**Comment by actionless** [comment]
i think #285 could be implemented first, as it don't require modifying the diagram file format

mb under that ticket you could create sorta check list with code items (ie module/class of gaphor/gaphas) which need to be changed in order to add such kind of feature

**Comment by amolenaar** [comment]
File-wise not a lot is changing. There will be an extra property saved (or two) for a model element that does not have the default color (black).

In that regard I think just allowing someone to set fg/bg colors is simpler than a predefined scheme. Personally I have no clue what such a scheme should look like. Also it can be dependent on nesting depth, and a lot of personal preference (or company colors).

I think the default Gtk color chooser allows for different color scheme's and also custom colors. However, it't pretty big. I'd like something that can fit in the element editor.

**Comment by actionless** [comment]
> Personally I have no clue what such a scheme should look like

mb smth like [skinparam](https://plantuml.com/skinparam) in plantuml or smth css-like (to avoid having hardcoded depth level)

**Comment by amolenaar** [comment]
> > I think just providing colors for nodes (background/lines/text) is a better starting point. With GTK palettes you can set a default palette. With color themes there're so many variantions (e.g. colors of nested nodes).
> 
> my point what after having just bg/line/text people would ask for more, and that simple syntax will be growing and growing until will turn into some incomplete brand new programming language :)
>
> even for easy start still css could be used ie,
> 
> ```
> * {
>    border-color: red;
>    text-color: blue;
>    background-color: green;
> }
> ```

> and parsed in some naive way, but next grow gradually into real CSS support

Moved discussion on theming from #286 over to here.

**Comment by amolenaar** [comment]
The more I think about it, the more I like the CSS approach:

* Users are not distracted with tinkering styling.
* It allows us to support "dark mode" diagrams.
* I consider CSS well understood. GTK itself relies heavily on style sheets.

Diagram items already have a style properties within, used to define the shapes. Style properties already resemble standard CSS properties as much as possible.

If I can define a style at application level, and provide it to an item during rendering, it should be pretty easy to pull many styling properties to a higher level. Let's start with just the `*` operation, as @actionless proposes. We can start by loading a user custom style from `~/.config/gaphor/style.css`. That will allow a user to at least configure some styling properties.

In subsequent iterations styles can be differentiated on item, grouping, model properties.

Examples:
* Change background color of all package items
* Change color of a Component item held by a Node item
* Change color of a class when an Association is connected

We can create a service (tool) in Gaphor that allows for editing and updating the style sheet.

Notes:
* Styles should also be applied to exported diagrams (png, svg), or not (e.g. when using dark mode)?
* Should styling be part of the model file at some point?
* Should add styling for diagram background, e.g. to support dark mode.

**Comment by actionless** [comment]
yeah, i think it's very important to support it on export

regarding embedding style into diagram file itself -- i think it may be done optionally, but started with just global stylesheet in the app, ie to develop it in a "progressive jpeg" way

and yeah background color is important to configure, however it could be started just as transparent and color support added later

**Comment by actionless** [comment]
btw there is also https://pypi.org/project/css-parser/ but idk which of two is better, other libs which i saw were quite old

**Comment by amolenaar** [comment]
By looking at the libraries.io stats, it looks like tinycss2 is used much more (css-parser has only one reference). One of the users of tinycss is reddit, so we're in good company :D

**Comment by actionless** [comment]
so, let me know if i could help with some "subtasks" for this idea, as i could code some pygobject stuff a bit

**Comment by amolenaar** [comment]
So far, this would be my approach to building it:

1. Take `ItemPainer` (and `BoundingBoxPainter`) from Gaphas (just copy, inheritance will make things only more complicated), and extend the drawing context object with a `style` property. Since the context object is passed down to the shapes (box, text) we can provide styling this way. Maybe some default styling can already be pulled out to the new `ItemPainter` (color, fill, font).

2. Figure out how to create proper CSS rules and build an engine that will "cascade" the styles. tinycss2 will only parse the CSS for us.

I think it will be challenging to come up with good style definitions. Styles can depend on:
* their place in the diagram (e.g. Node with nested component should change text location)

But also on model properties:

* The item-> model relationship (e.g. draw an unconnected Generalization or Association in a different color than a connected one)
* properties on a model (e.g. draw class without associations different from one with associations). 

(the last one may be stretching it a little, though).

So I thing point 1. will be relatively simple. Point 2. however needs some smart design choices. I'd love to get some help with that. So far I have not found a Python CSS engine that can do the cascading (and it has to be fast, since its part of the drawing loop). cssselect2 maybe?

**Comment by actionless** [comment]
mb we could maintain a copy of diagrams tree as a python ElementTree, with only element id, so the process when items changed will go like that:

1) when building a new tree, also mirror the new structure into elementree
2) do match of the rules against mirror elementtree, and store the result, as a hashtable where keys are element IDs and values are matched CSS rules
3) when doing rendering of the real element tree, look up the matched style from pt2 by element id

**Comment by actionless** [comment]
or instead of pt.1 mb would be nicer to add for the current diagram tree some method like `as_element_tree()` which will convert the current tree into that id-only element tree

PRO: it will not require "sync"-ing element tree every time when changing the real tree
CON: the full build of tree will take more time than just updating existing one, the question only how much longer, ie if that will be noticeable as UI slowdown

**Comment by actionless** [comment]
but also when you mentioned the connection arrows between items, i don't have any solution yet how to handle them nicely, i'll write up later if/when i'll have some idea

**Comment by amolenaar** [comment]
This sounds like a plan :+1: 

At a later stage we can write our own matcher, which avoids having to sync with an ElementTree. 

So a simple bit of CSS for a Node item may look like this:

    NodeItem {
      color: green;
    }

A component item nested in a node item:

    NodeItem ComponentItem {
       color: red;
    }

We can assign model properties as classes:

    ClassItem.ownedAttribute {
      // do something special for classes with attributes defined
    }

or use a nested selector with the [`:has()` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:has):

    ClassItem:has(Class > Property) {
      // do something special for classes with attributes defined
    }

Not sure about these ones, tough :/

NB. Items drawn in the diagram all have an `Item` suffix`. Elements in the model do not.

**Comment by actionless** [comment]
>
```css
SomeNode:has(OtherNode > NestedNode) {
  // do something special for classes with attributes defined
}
```

yup, this one looks legit/the way how i saw it, the only possible issue, as :has() was added relatively recently (https://drafts.csswg.org/selectors-4/#relational) i'm not sure if cssselect lib will support it

however for properties i think it might be better to use the attribute selectors(https://www.w3.org/TR/CSS2/selector.html#attribute-selectors):

```css
ClassItem:has(Class[Property]) {
//
}
```

**Comment by actionless** [comment]
and speaking of attribute selectors, actually mb the thing with arrows could be solved like that:

```xml
<Diagram id="1">
 <Node id="2"></Node>
 <Node id="3" connected_to="OtherTypeNode"></Node>
 <OtherTypeNode id="4"></Node>
</Diagram>
```

```css
Node {
   color: red;
}

Node[connected_to="OtherTypeNode"] {
  color: blue;
}
```

**Comment by amolenaar** [comment]
I did not think of attribute selectors. It's all in the name :) Excellent!

We can put the actual attributes there. I think it should be

    ClassItem:has(Class[ownedAttribute]) {}

then. Since `ownedAttribute` is the attribute name.

**Comment by actionless** [comment]
yup, i think is better to start from less and grow additional functional little by little

but generally i see no problem with querying them as `ClassItem OtherClassItem > Text { background-color: red; }` and such

**Comment by amolenaar** [comment]
cssselect2 does not have a `:has()` pseudo-class yet. Looks like attribute selectors are supported.

**Comment by amolenaar** [comment]
> but generally i see no problem with querying them as ClassItem OtherClassItem > Text { background-color: red; } and such

Agreed, although I think the current design/structure of items and item rendering gets in the way. Now all shapes are internal to the diagram item.

**Comment by actionless** [comment]
then it might be better implementing such separation in the next iteration of this feature :)

**Comment by amolenaar** [comment]
When thinking ahead, one case is giving me trouble, though: font-sizes. For Class-like elements a small _(from package-name)_ text can be placed below the class name, in case the class is defined in a different package than the diagram. The font size for this text is smaller than the regular text. The text size should not be hard coded, since it will look weird when the font-size is changed in CSS.

I'm not sure how to address this.

**Comment by actionless** [comment]
mb let's just skip font-sizes at all for the initial implementation -- it feels like that's smth what could be added any moment later

**Comment by amolenaar** [comment]
@actionless @danyeaw I've been thinking 'bout where to put the style sheet.

In a service is not optimal, since the (gaphas) canvas then needs access to this service for updates on diagram items and for drawing. Also the styling is then attached to a single installation of Gaphor, which can lead to inconsistent (ugly) diagrams.

I think it will be better to create a _Stylesheet_ element in the model. That way the style will always be attached to the model and can be changed per model. Styling will automatically be applied when rendering a diagram, e.g. via the `gaphorconvert` tool.
Diagrams will also look consistent, since the styling is stored with the model.

The _Stylesheet_ element will get the necessary methods to query for an item style, of course :smile:. Only one instance is needed per model.

The stylesheet can be managed/changed though a dialog window accessible through _Hamburger_ -> Tools -> Stylesheet or may be an option in the element editor (right pane).

What do you think?

**Comment by actionless** [comment]
> or may be an option in the element editor (right pane).

this definitely would require additional effort on converting element style into the stylesheet. and some logic to handle, if that a style for this particular element id, or for all elements of this type

the rest sounds good to me :+1:

**Comment by amolenaar** [comment]
> this definitely would require additional effort on converting element style into the stylesheet. and some logic to handle, if that a style for this particular element id, or for all elements of this type

I was thinking of the stylesheet editor as a big text area where the CSS stylesheet contents can be edited. It's next iteration stuff, though. Let's first get in some styling.

**Comment by danyeaw** [comment]
@amolenaar I like this proposal. I agree that saving the style information with the model is a good approach. For sharing of models between people, making the model look the same no matter who is opening it is important, even if colors don't by themselves have any semantic meaning.

I could also see in the future that we may want to add styling as a global setting as well, so that for all new models created by a user or group of users get the styling that they prefer.

**Comment by amolenaar** [comment]
True. That we can apply via a service. The initial challenge was to get the style information available in the right places. I think it would be good to have an editor in Gaphor, so you can edit a stylesheet and immediately see the result. Then, these can be saved, loaded and shared.

The next big challenge is to convert CSS in to Style objects for each diagram item type.

**Comment by amolenaar** [comment]
At this point, one can add a `*` style to a style editor embedded in Gaphor. Next step would be to address somewhat more complex styles.

Next step is to apply CSS rules based on a diagram item.

After looking at the cssselect2 package I think it's best we create our own rule compiler for now:

1. It will provide faster round-trip time and will allow for faster learning.
1. cssselect2 relies heavily on the ElementTree/HTML structure (which is not 100% abstracted by the `ElementWrapper` class)
1. Many of the selector refer to ordering, such as `:nth-child`. This is not useful for us (parent-child relationships are, though).
1. Pseudo-class selectors are specific to HTML elements in this implementation
1. It will allow fine control and include pseudo-selectors like `:has()` without any trouble.
1. We need dynamic fields like `:hovered` and `:active`, which are not implemented for cssselect2.

Of course, if there are still many similarities I think it's best to propagate the changes upstream.

**Comment by amolenaar** [comment]
The CSS Selector works pretty well, I think.

There's still a few things to do:

- [ ] names should be defined without -Item prefix
- [ ] Properties (attributes) still need to be added
- [ ] I'd like to get rid of the "Enable Style Sheet" toggle. Style sheets are the way to go. Period.
- [ ] Add a link to documentation close to the CSS text area
- [ ] Extra: Move item (inline) styles to a style sheet and use classes instead


One question: Say I nest a component in a node. If I define styling for the node, will it also cascade down to the component? I do not think so.

**Comment by amolenaar** [comment]
@actionless @danyeaw I think the CSS integration is pretty much complete. I enjoyed coding it. I managed to use TDD for the most part. I'm really happy with how it came out.

Eventully I created my "own" version of cssselect2, to accomodate for Gaphor's needs wrt style sheets.

There's one small deviation from the official CSS specs: attributes can be defined with dots in between. So you can say:

```css
class[ownedAttribute.name*=foobar] {}
```

@actionless Thanks again for the brain storming sessions and guidance! They helped a lot in focusing on the right features.

**Comment by danyeaw** [comment]
@amolenaar Congrats on completing this, really nice work!

**Comment by actionless** [comment]
btw in the recent Inkscape release they also added an interface for helping editing CSS, mb that would be smth you'll be interested to look on for inspiration: https://wiki.inkscape.org/wiki/index.php?title=Release_notes/1.0#Selectors_and_CSS_.5BExperimental.2C_hidden.5D
