### ISSUE TITLE
Support global color schemes for diagrams

### ISSUE THREAD

**Issue by actionless** [gaphor/gaphor#285]
### I'm submitting a...
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

### Current behavior
Currently all the diagrams are black and white.

### Expected behavior
Being able to define global colorschemes, where will be defined default*[1] BG and FG colors for different kind of nodes and connection lines.

![2020-03-31--1585667536_1550x717_scrot](https://user-images.githubusercontent.com/1655669/78043007-193bbc80-7373-11ea-87e4-844f0ada4833.png)

________________________

[1] I've created a separate ticket about setting color for specific nodes: https://github.com/gaphor/gaphor/issues/284 This issue is not related to that one.

**Comment by amolenaar** [comment]
I'll close this issue, since we continued the discussion in #284 and this is more or less a duplicate now.
