### ISSUE TITLE
Horizontal and vertical text alignment inside a node

### ISSUE THREAD

**Issue by actionless** [gaphor/gaphor#287]
### I'm submitting a...
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

### Current behavior
Text is always placed inside the absolute center of the node.

### Expected behavior
For nested nodes it would be useful to be able to put the text aligned to the top border of the node intead of the center:

![2020-03-31--1585677648_520x334_scrot](https://user-images.githubusercontent.com/1655669/78059590-65dec200-738a-11ea-8fe5-84236179092b.png)

**Comment by danyeaw** [comment]
@all-contributors please add @actionless for ideas bug

**Comment by amolenaar** [comment]
Yes. We need to do this!

**Comment by actionless** [comment]
thanks! works fine
