### ISSUE TITLE
Missing merge node icon in model browser

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2874]
### Describe the bug
In the model browser, merge node icon is missing.

### To Reproduce
1. Add activity diagram
2. Add merge node item
3. See the model browser - the icon is missing

### Expected behavior
The icon should be the same as in the toolbox.

### OS
- [x] Linux (Mint)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.22.0

### Additional information

There have been similar bugs with gaphor because in the toolbox, the icon is explicitly defined, but in the model browser, it is derived from the element type. It may be possible that it broke because icon generation removed "unused icons".

**Comment by marek-piirikivi** [comment]
Edited title and description for "merge" exclusively because decision node is fine.

**Comment by danyeaw** [comment]
Thanks @marek-piirikivi for submitting the issue!
