### ISSUE TITLE
Start with empty model or example already filled

### ISSUE THREAD

**Issue by SebCanet** [gaphor/gaphor#2905]
### Is your feature request related to a problem?
When launching SysML profile, it's not empty so I have to modify everything: delete diagrams I don't need, erase blocks or change names, etc.

### Describe the solution you'd like
Start with an empty profile or an example (like it is actually).

### Describe alternatives you've considered
None possible.

### Additional context
Educational context.

**Comment by SebCanet** [comment]
Thanks, I understand the way you think we should use. But for my stdent they will see in big the "SysML" and click on it,
I think you should seperate "new model" and "template", this panel seems confusing for newbies on your software.

**Comment by marek-piirikivi** [comment]
"template" is actually in the description where you see SysML button.
![image](https://github.com/gaphor/gaphor/assets/45357878/fe5535ce-2594-4d14-a95b-dc70e6d03df8)

I partially agree with @SebCanet that people who want to create new SysML model will most likely click "SysML" option (me included).

I do not have a good proposal on the course of action. I admit that I am also guilty of making the mistake with this UI, but then again, the UI itself is explicit on what it promises and that's precisely what you get.

**Comment by SebCanet** [comment]
As you choose a profile after generic choice, maybe we could have 2 columns:
UML Template ->                          UML empty model ->
SysML Template ->                        SysML empty model ->
RAAML Template ->                       RAAML empty model ->
CA Template ->                             C4 empty model ->
Empty model ->

Or start choose between Template or Empty model, then choose UML or SysML or ... or empty.
I'm trying to imagine how my students will react :-D

**Comment by marek-piirikivi** [comment]
There have also been thoughts about not having the profile distinction from the drop-down at all and you can choose explicitly whether you want to create UML elements/diagrams or SysML diagrams. For example, right clicking on package > SysML > Create activity diagram; or right click > UML > Create activity diagram. First UI would kinda still remain the same, though whether you want to start with SysML template or UML template.

**Comment by danyeaw** [comment]
My experience with production SysML models is that the starting templates are extremely complete. Users do exactly what you mentioned of renaming elements and modifying diagrams set up in a modeling method already. In the case of our starting template, the modeling method is a form of MagicGrid.

This has huge advantages, users don't have to start modeling from scratch which is a tremendous amount of work, it improves modeling consistency, and provides guidance to a modeling method.

We should continue to improve the starting model templates, not remove them.

If some users don't want a modeling method defined and do want to start from scratch, I totally understand that. I also get that selecting SysML right now may have an expectation of a blank model. If we add more options to allow creation of a blank SysML model, that would be fine, but I think it would just create a blank model and select the SysML profile.

**Comment by amolenaar** [comment]
@SebCanet Can you share the template you want to use?

**Comment by SebCanet** [comment]
I've no specific template, often we start with nothing. The actual starting model is really interesting, just the problem is that it's full of "false" diagram we need to delete.

**Comment by danyeaw** [comment]
Hi @SebCanet, thanks for the idea. @amolenaar implemented a nice solution which keeps some of the package structure and diagrams, but removes all the example elements and moves them to a separate example section.

**Comment by SebCanet** [comment]
Hi,
that's great, is it useable with v2.4.40?

**Comment by danyeaw** [comment]
We'll release a new version soon with this update.
