### ISSUE TITLE
Add option to show abstract classifier by textual annotation {abstract}

### ISSUE THREAD

**Issue by nomisge** [gaphor/gaphor#2919]
### Describe the bug
UML 2.5.1 states in section 9.2.4.1
"The name of an abstract Classifier is shown in italics, where permitted by the font in use. Alternatively or in addition, an abstract Classifier may be shown using the textual annotation {abstract} after or below its name"

In Gaphor this is currently only manually possible for classes, and not at all for methods.

If fonts are used, that don't support italics or small print doesn't show nicely, than readers won't notice, that a class/method is supposed to be abstract.

### To Reproduce
1. Add a class with at least one method
2. Change the classes name and append {abstact} -> this works, but then the class name is changed.
3. Change the methods name and append {abstract} -> not working, since after confirming the change it is reverted.
4. Toggling the abstract options only has the 'italic effect'

### Expected / Suggested behavior
Add an option to settings, that when a class or method is declared abstract, the {abstract} annotation is automatically added according to the standard.
Maybe the option could offer three choices: only italic, only {abstract}, both

### Version
Any Version below 2.22

**Comment by amolenaar** [comment]
Hi @nomisge, Thank you for your report.

I do not understand why you want this. Why is the italics notation not enough?

For classes it only works because you add it to the Class name. For methods and attributes, the text is parsed and the tags (`{abstract}`) is dismissed.

Isn't the solution to use a font that has a proper italics version available?

**Comment by nomisge** [comment]
Thanks @amolenaar for looking at the report.

There are several reasons, the biggest beeing, that if the diagrams are printed on paper - no matter the font -  italics can always be overlooked. In my case this are exams I give to my students. And to add on that the state (in Germany) of the school I'm teaching at, does this with their final exams.
Another reason is, that other programs (used in education) already do this e.g. in JavaEditor https://javaeditor.org/.  This is for java only though.

Yes I know that it kind-a works by adding it to the name, but that is more like a bad workaround with caveats.

Since UML 2.5.1  describes an alternative to italics, I think this should be possible in gaphor. Thats a good reason too, isn't it?
There should be an option, that adds {abstract} to both class names and method names.

Should not be too hard to implement. If you give me a hint, which files need to be looked at, I would even try to have I go at it, although I am not familiar with gaphors code.

Thanks,

**Comment by amolenaar** [comment]
@nomisge Thanks for the clarification.

I think the best way to add this is to make it a CSS feature. Something like:

```css
*[isAbstract]::after { /* the UML model attribute is called isAbstract*/
  content: "abstract";
}
```

Alternatively it could be a switch, but we have to break through a couple of abstractions in order to have the switch setting reach the actual class item on the diagram. Also, such a (random) setting looks a bit out of place.

**Comment by amolenaar** [comment]
@nomisge, @danyeaw 

This is what I had in mind:

<img width="1018" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/b3cb93b0-7c5a-4c2d-b12c-1e34b1083454">

Take a note at the CSS. I added the ability to define CSS rules for the internal parts of a Class. In this case `name` and `operation` fields will have a suffix `{abstract}`.

Apart from this use case this will help us move a *lot* of "inline" styling to a style sheet.

**Comment by danyeaw** [comment]
@amolenaar Beautiful!

**Comment by nomisge** [comment]
@amolenaar Definitely the right way to go. Looking forward for the merge.

**Comment by danyeaw** [comment]
@all-contributors please add @nomisge for idea

**Comment by amolenaar** [comment]
@nomisge Thanks again for submitting this issue. This issue was the incentive I needed.

I think the CSS support is in a lot better shape now. With the fine grained CSS support we should be able to get rid of (almost) all hardcoded styling.

**Comment by nomisge** [comment]
@amolenaar no problem.
I just build version 2.23.0 and it works perfectly!
Maybe a css example could be added to the docs?

One where following css is used:

```
name[isabstract]::after,
operation[isabstract]::after{
  content: " {abstract}"
}
```

**Comment by amolenaar** [comment]
Thanks.

I added that already: https://docs.gaphor.org/en/latest/style_sheets.html#emphesize-abstract-classes-and-operations.
