### ISSUE TITLE
Support controlling visibility of requirement's text

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#2967]
### Is your feature request related to a problem?
Currently text is always visible. This takes up too much space on diagrams where the focus is just on the requirement relationship.

### Describe the solution you'd like
I would like to have a switch "Show text" on requirement property page.

### Describe alternatives you've considered
I couldn't come up with any other alternative other than to just ignore the problem.

**Comment by amolenaar** [comment]
Fixed by #3249.
