### ISSUE TITLE
Removal or toggle of <<Block>> on stereotyped blocks

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#2975]
### Is your feature request related to a problem?
When using stereotyped blocks in SysML the stereotype label starts to get crowded due to appended stereotypes `<<block, stereo1>>`. If multiple stereotypes are explicitly specified, I'd expect them all to show up. However, `<<block>>` is defined as implicit for all unlabeled blocks:

The SysML 1.7 spec says:
![image](https://github.com/gaphor/gaphor/assets/58485783/8c3efb2e-0306-4c66-9d37-f371a583a0db)

So, there is an implicit association that everything's a block if unlabeled on a sysml bdd. 

### Describe the solution you'd like
When a block is stereotyped remove the text `<<block>>`

### Describe alternatives you've considered
- add a toggle switch for displaying <<block>> stereotype
- Use classes instead of blocks, where possible, for a cleaner diagram (this is not an option if you need the block-specific attributes defined by SysML, but is okay for things like metamodels)

**Comment by danyeaw** [comment]
Hi @tompkins-ct, thanks for the suggestion. What if we allowed hiding of Block or other stereotypes with CSS?

**Comment by tompkins-ct** [comment]
That could probably work if there's enough logic available to isolate only blocks with assigned stereotypes, such that only `<<block>>` is removed.

**Comment by amolenaar** [comment]
It'll be tricky to apply CSS rules on such a small scale. I suppose @tompkins-ct 's suggestion is more feasible. Simple and clean.

**Comment by danyeaw** [comment]
@all-contributors please add @tompkins-ct for idea

**Comment by danyeaw** [comment]
Thanks @tompkins-ct!
