### ISSUE TITLE
Windows App doesnt start

### ISSUE THREAD

**Issue by stealthyboy** [gaphor/gaphor#2976]
### Describe the bug
App doesn´t start at all. No Failure post.
When I start the App, the hourglass symbol is ccoming twice and then nothing happpens.
starting with Admin is active.
in Task manager the Gaphor-App is shortly open and then disappears  completely.
More than once restarted and re installed. 

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
Normal Start

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor:

**Comment by danyeaw** [comment]
Hi @stealthyboy, thanks for submitting the issue. Which version of Gaphor is this with and are using the portable or installer type?

**Comment by stealthyboy** [comment]
i used portable and the installer type and Version 2.22 and 2.21.

Does Onedrive interfere with it?

**Comment by danyeaw** [comment]
It shouldn't. Would you be able to open your command prompt, change directory to where it is installed, and launch Gaphor with `.\gaphor.exe --self-test`?

**Comment by stealthyboy** [comment]
nope doesn´t work. It worked a bit, when i restarted my PC und opened it really fast after loging in.

**Comment by danyeaw** [comment]
When you run the command, does it give any output to the command prompt?

Do you have a virus scanner or anti-malware active?

**Comment by stealthyboy** [comment]
There is no output, when I use the Command.

The Programm starts randomly sometimes.

**Comment by stealthyboy** [comment]
And i have no virus scanner or anti malware active

**Comment by stealthyboy** [comment]
I use Win 11.

**Comment by danyeaw** [comment]
@stealthyboy I tried to reproduce this, but unfortunately I wasn't able to. I have Windows 11 10.0.23606 Preview. Everything installs and runs fine. So we need to figure out why your setup is different.

**Comment by amolenaar** [comment]
Is it still an issue with our new 2.24 release?

**Comment by amolenaar** [comment]
I close this issue. If the issue persists, feel free to reopen it.
