### ISSUE TITLE
Swimlanes aren't displayed

### ISSUE THREAD

**Issue by bjornstromberg** [gaphor/gaphor#2988]
### Describe the bug
the picture in the online docs example does not reflect the text (swimlanes missing) nor the actual view of the example model in the repo.

### To Reproduce
1. Go to 'https://docs.gaphor.org/en/latest/coffee_machine_logical.html#functional-boundary-behavior'
2. watch pictures below and read text, text says there is swimlanes, picture does not..
3. open model in example dir (coffee-machine.gaphor) and watch the swimlanes the text talk about..
4. doublechecked the svg that was uploaded and it does not contain any swimlanes.

### Expected behavior
picture in the tutorial actually correctly represented, cause the example otherwise is a clever/fun way to make an example worthy of actually reading... 

this is also the reason i took myself the time to atleast give a bug report that the picture does not match between the model and the generated example pictures, unless the pictures are not auto generated from the model it might be more that differ, but this one stuck out..

### Screenshots
1. from online docs
![picture in docs](https://docs.gaphor.org/en/latest/_images/9fdf0b3c-7170-11ec-999a-f47b099bf663.svg)
2. uploaded copy for history reasons when the docs change..
![uploaded copy so old state of picture is stored for history](https://github.com/gaphor/gaphor/assets/5454791/3164a0e9-1584-4e1c-8bad-8ec7afe4766b)
3. exported as svg from my system from the model
![Functional_Boundary_Behavior](https://github.com/gaphor/gaphor/assets/5454791/965bb62a-4d68-4a15-86df-5fd1554b06bc)
4. exported as png on my system from the model
![Functional_Boundary_Behavior](https://github.com/gaphor/gaphor/assets/5454791/f3094f5b-c943-4612-acf0-d354fd39d634)

### OS
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.22.1 (Flatpak)

### Additional information
Alpine Linux 3.19 with KDE and 2.22.1 (Flatpak)

**Comment by amolenaar** [comment]
Hi @bjornstromberg,

This is a weird one, indeed. The swimlanes element is there, but it never rendered anything:

<img width="1952" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/6908d56d-b9b5-4278-9770-82ade4f6b56f">

**Comment by bjornstromberg** [comment]
@amolenaar yea it felt like one of those wierd ones when the model actually contained the swimlane, 
and gaphor actually exported it correct on my machine..  

it will actually be interesting to see if the root cause actually gets found..

**Comment by bardouille** [comment]
Hello, I am having the same problem, swimlanes doesn't appear anymore, in any of my projects.
![image](https://github.com/gaphor/gaphor/assets/39093395/9758509e-c3e8-4cb0-b8d4-b8a01d1af543)

**Comment by bjornstromberg** [comment]
@bardouille what version of gaphor are you running and on what platform?

**Comment by bardouille** [comment]
@bjornstromberg I installed 2.23.0 this morning, on windows.

**Comment by bjornstromberg** [comment]
so 2.22.1 works and 2.23.0 does not, great then i will hold the upgrade to 2.23.0 until this is resolved

**Comment by marek-piirikivi** [comment]
I confirm. Swimlane rendering is also missing after moving from 2.22.1 → 2.23.0. :slightly_smiling_face:

**Comment by amolenaar** [comment]
I see the same. It looks like commit 36e0eddd1f7ffb6d157596a4fd25c18c3730c498 broke it.

**Comment by danyeaw** [comment]
@all-contributors please add @bjornstromberg for bug

**Comment by danyeaw** [comment]
Thanks for the bug report @bjornstromberg! We'll be releasing 2.23.1 soon.
