### ISSUE TITLE
Box and Circle elements not visible

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3008]
### Describe the bug
In v2.23 add a Box or circle element to a diagram. The element handles show up but the lines are not visible.

### To Reproduce
1. Add a Box element to a diagram
2. Do not see box. 

### Expected behavior
The Box element should be visible
### Screenshots

<img width="473" alt="Screen Shot 2024-01-11 at 9 25 13 am" src="https://github.com/gaphor/gaphor/assets/50702106/e62ff072-43bb-4cd0-9e8c-4349894ec791">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ x] macOS
- [ ] Windows

### Version
Version of Gaphor:2.23

### Additional information
maybe related to #2988 .

**Comment by danyeaw** [comment]
Hi @mikekidner, thanks for the bug report. Yup, I think this is related to #2988, and I can reproduce it on Linux. It seems to be corrected by https://github.com/gaphor/gaphor/pull/2996 as well. We'll release a new version with this fixed soon :+1:
