### ISSUE TITLE
Slots/Attributes in stereotypes do not wrap. [feature/bug?]

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3030]
### Describe the bug
Defining attributes via stereotyped blocks does not wrap which results in the property window obscuring the diagram area when blocks with larger text blocks are selected. Behavior is the same for adding attributes to classes.

Related: If these long attributes are shown in the diagram the blocks become unusable. 

### To Reproduce
1. Create a stereotype
2. Add an attribute to the stereotype
3. Create a block/class with the new stereotype
4. Fill in the slot for the stereotype

### Expected behavior
I would expect the text box to wrap or hide information when it exceeds the available space.

### Screenshots
Property window hidden:
![image](https://github.com/gaphor/gaphor/assets/58485783/b22c52ce-654b-481a-87a0-65816e626eb5)

Property window exposed:
![image](https://github.com/gaphor/gaphor/assets/58485783/aadf360c-0ae9-463e-bd67-a9f5efe51b64)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.23.2

### Additional information
Previous versions of Gaphor hid the slots when not actively showing them so the large box, while annoying, didn't obstruct the diagram area.

**Comment by amolenaar** [comment]
This will improve ones #3021 is merged. That PR allows those text fields to wrap.

<img width="1148" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/20b573d4-d072-44dd-850a-c84794db5167">

**Comment by amolenaar** [comment]
This issue has been fixed by #3021.

@tompkins-ct Thanks again for raising this issue.
