### ISSUE TITLE
Shared Objects between diagrams are deleted even when one still exists on the other diagram

### ISSUE THREAD

**Issue by mvinca-bandwidth** [gaphor/gaphor#3047]
### Describe the bug
When an element with connectors is copied from one diagram to another, deleting that element on the second diagram will delete the connectors on the first.

### To Reproduce
1. Create a new SysML project to get the SysML example
2. Change Preference to not Remove Unused Elements
3. Open the diagram Functional Boundary Behavior
![image](https://github.com/gaphor/gaphor/assets/93543843/0f5907ea-f13b-41a3-af4b-23eb1071a1aa)
4. In the model, right-click on Activity and choose New Diagram -> New Activity Diagram
![image](https://github.com/gaphor/gaphor/assets/93543843/b28fa230-edab-4299-891c-d02bad26f51d)
5. Click within Functional Boundary Behavior and select all with keyboard
![image](https://github.com/gaphor/gaphor/assets/93543843/2be50b88-faff-4320-8113-534474d6c20f)
6. Copy with keyboard
7. Click within New Activity Diagram and paste with Keyboard
![image](https://github.com/gaphor/gaphor/assets/93543843/211be21c-8d25-4256-9706-0d815efc3800)
8. In New Activity Diagram, delete the action "Determine Actuator Command"
![image](https://github.com/gaphor/gaphor/assets/93543843/50dd4356-d171-4c52-b68c-a1c891b3d0de)
9. View "Functional Boundary Behavior". Notice connections are now missing.
![image](https://github.com/gaphor/gaphor/assets/93543843/6f113a40-b983-4ca9-887b-4be9f81ea408)

### Expected behavior
Connections are not deleted from the original diagram

### Screenshots
Interspersed within the steps

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.21.1

**Comment by danyeaw** [comment]
@all-contributors please add @mvinca-bandwidth for bug
