### ISSUE TITLE
First activity partition gets all the nodes

### ISSUE THREAD

**Issue by marek-piirikivi** [gaphor/gaphor#3050]
### Describe the bug
When querying activity partitions and seeing what nodes under which partition is, it was discovered that the first partition in the set gets all the nodes and all the rest are empty.

### To Reproduce
1. Create the following activity diagram
![image](https://github.com/gaphor/gaphor/assets/45357878/ff6d1f3e-5e73-424a-b90f-b1567e410b83)
2. Open console and write
```
from gaphor.UML import uml
[f'{p.name}: {[n.name for n in p.node]}' for p in select(uml.ActivityPartition)]
```
3. See that the output is: `["Swimlane One: ['A1', 'A2']", 'New Swimlane: []']`

### Expected behavior

Expected output of the steps should be `["Swimlane One: ['A1']", "New Swimlane: ['A2']"]`

### OS
- [x] Linux (Mint)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.23.2

**Comment by marek-piirikivi** [comment]
A workaround is to create separate swimlanes with "Partitions" number as 1. Looks the same, you get the benefit of individually scaling a partition, and querying works as expected . So, the issue is not critical as long as you take the inconvencience to manage swimlanes individually.

**Comment by danyeaw** [comment]
Hi @marek-piirikivi, thanks, I can reproduce this as well using our coffee machine example.
