### ISSUE TITLE
Error when doing "undo"

### ISSUE THREAD

**Issue by ebousse** [gaphor/gaphor#3069]
### Describe the bug

I am not sure how and when this happened, but while doing some undo/redo I encountered an error, which led my Gaphor instance in a bad state (ie/ whatever I would do from there would trigger another error, even when trying to save my project).

Maybe the error was I was modifying a state machine (playing with the `Entry` attribute of a state), or when I tried creating a new class diagram, it's unclear.

### To Reproduce

Unclear, but undo/redo related.

The error report is too long for the Github issue system, so here is it as a file: 
[Gaphor-logs-error.txt](https://github.com/gaphor/gaphor/files/14138200/Gaphor-logs-error.txt)

### Expected behavior
No error.

### OS
- [x] Linux − Fedora 39, GNOME
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.23.2

**Comment by amolenaar** [comment]
I fixed one issue in undo handling a few days ago, #2895. But it doesn't look like that was the same issue.

**Comment by ebousse** [comment]
I have been using Gaphor quite a bit this past week, and I encountered crashes due to undo/redo on a daily basis, so maybe there are multiple issues here?

If I find a reproducible scenario, I'll share it here.

**Comment by amolenaar** [comment]
I created #3205. It's at least a partial fix to this issue (`NotInTransactionException('Updating state outside of a transaction: ...')`).
