### ISSUE TITLE
Font issue in Flatpak

### ISSUE THREAD

**Issue by mmahmoudian** [gaphor/gaphor#3080]
This is the first time I'm using this tool, so please excuse my lack of familiarity with the terminology and the software in general, and thanks for investing your time into this project :)

### Describe the bug
The fonts in the Flatpak looks weird and pixelated, also the text in the Preferences is poorly displayed. I guess the issue stems from lack of the required font on my system.

### To Reproduce
1. Install Flatpak from flathub: `flatpak install flathub org.gaphor.Gaphor`
2. Run the Flatpak. For example from terminal: `flatpak run org.gaphor.Gaphor`
3. See pixelated and jagged font

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

```
Gaphor version:         2.23.2
Operating System:       Linux (6.6.10-1-MANJARO)
Display:                GdkWaylandDisplay
Python version:         3.11.7
GTK version:            4.12.4
Adwaita version:        1.4.2
GtkSourceView version:  5.10.0
Cairo version:          1.18.0
Pango version:          1.51.0
PyGObject version:      3.46.0
Pycairo version:        1.25.1
pygit2/libgit2 version: 1.13.3  / 1.7.1


No errors have been intercepted. We’re good.
```

### Expected behavior
Have a smooth font that is friendly to the eye.

### Screenshots

Jagged characters:

![image](https://github.com/gaphor/gaphor/assets/390889/493c7ebf-6e31-4283-8389-bdc229a1e856)

![image](https://github.com/gaphor/gaphor/assets/390889/c1c266ee-9f20-4bb9-9e5a-feedc233c754)

Poorly arranged text:
![image](https://github.com/gaphor/gaphor/assets/390889/35683464-f037-487b-a1fd-132314a17ae7)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] <s>Windows</s>

<details>
<summary>System information</summary>

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.10-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7440HQ CPU @ 2.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: LENOVO
Product Name: XXXX
System Version: ThinkPad XXXX

</details>

![image](https://github.com/gaphor/gaphor/assets/390889/5e079d2b-9b01-4893-88ca-c06e85cdaa4f)

### Version
Version of Gaphor: XXXX

### Additional information
-- not applicable --

**Comment by amolenaar** [comment]
Is this a problem only with Gaphor? Are there other GTK based flakpaks with the same issue?

Do you use a scaling factor?

On my machine (Fedora 39, 200% scaling) fonts look fine.

**Comment by danyeaw** [comment]
Hi @mmahmoudian, thanks for the bug report, but you didn't respond to @amolenaar's request for more info, and I think this is probably a KDE issue and potentially installing xdg-desktop-portal would resolve it as discussed here: https://github.com/flatpak/flatpak/issues/4571

I don't think there is anything Gaphor can do to help resolve this, so I'm going to close this issue. If you think it is an issue with Gaphor, we can reopen it with your feedback. Thanks!

**Comment by mmahmoudian** [comment]
> Is this a problem only with Gaphor? Are there other GTK based flakpaks with the same issue?

I rarely allow GTK stuff touch my computer i realized similar issue with another flowchart program as well, and their dev was active in responding. We figure together that this only happens on Wayland and if I switch to X11 the find would resolve.

> Do you use a scaling factor?

No, so the porrly aligned text should have another reason

> On my machine (Fedora 39, 200% scaling) fonts look fine.

I don't trust to test GTK stuff on a Gnome-bias OS. Ubuntu Debian and Fedora are primarily shipped with Gnome and are loaded with GTK stuff. Therefore they provide biased view. Flatpak should not have such issues in theory, but ... Ideally, spinning multiple VMs and testing in those can help escaping these biases.

> potentially installing xdg-desktop-portal would resolve it

In today's Wayland world, one cannot survive without installing portals. I of course am no exception. I have portals installed. :)

> I don't think there is anything Gaphor can do to help resolve this

Thanks. My responsibility as a caring user was to raise your attention to the issue with proper information. Whether you want to investigate it or not is of course entirely your choice :) thanks again for your time

**Comment by amolenaar** [comment]
Hi @mmahmoudian,

Thank you for for your feedback. Indeed, running GTK applications on GNOME can yield different results from running a GTK app in a different environment.

> Flatpak should not have such issues in theory, but ...

There are so many real world scenarios. It's hard to cover every one of those. Maybe you want to raise it with the Flatpak people. They have a better understanding of what's needed inside and outside Flatpak (e.g. font files).

> Thanks. My responsibility as a caring user was to raise your attention to the issue with proper information. Whether you want to investigate it or not is of course entirely your choice :) thanks again for your time

Thank you. Given we are mostly working on Gaphor in our spare time, our time is limited.

You're running a standard Manjaro install?

**Comment by mmahmoudian** [comment]
> You're running a standard Manjaro install?

Yes, Manjaro KDE Plasma.

> Given we are mostly working on Gaphor in our spare time, our time is limited.

I completely understand that. This is the situation with the majority of [FLOSS](https://www.gnu.org/philosophy/floss-and-foss.en.html) tools including those that I work on, so I can fully sympathize. Thanks again for your contribution to FLOSS :)
