### ISSUE TITLE
Downloading a Windows exe in Firefox stops with false malware warning

### ISSUE THREAD

**Issue by Turidus** [gaphor/gaphor#3086]
### Describe the bug
When trying to download a Windows installer or portable executable with the current Firefox built (122.0.1), it stops the download and provides a malware warning (s. screenshot). This behavior was testet for different versions and it happens for all versions starting from 2.6.0. All versions before that download normally.
This happens when downloading either from the website or directly from github.

Checking a downloaded version with Sophos Endpoint Protection revealed no threat. The download works normally with Microsoft Edge.
Other downloads work normally with Firefox.

While this bug is most likely caused by firefox, I hope this report helps you by making you aware of a potential issue.

### To Reproduce
Go to the github or the download center for the offical website.
Select a windows executable of a version starting with 2.6.0 or later.
Try downloading this this executable with a current firefox build.

### Expected behavior
There is no malware warning when downloading a windows excecutable.

### Screenshots
![grafik](https://github.com/gaphor/gaphor/assets/31318547/999a363d-0c8d-41c1-a132-f9cf9070c8f9)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows (11, 23H2, Build: 22631.3007)

### Version
Version of Gaphor: >= 2.6.0

### Additional information
Firefox Version: 122.0.1

**Comment by leftbrainstuff** [comment]
Same issue in Windows but not using Brew in Mac to install

**Comment by danyeaw** [comment]
Although we have made some changes to make this better for the next release, this isn't actually an issue with Gaphor. It is a false positive created by Google. It would be best for everyone to report this as an issue to them directly: https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

Yes, Firefox does also make use of Google's Safe Browsing API 😉

**Comment by danyeaw** [comment]
@Turidus, thanks for submitting this issue. A few people reported this to Google, and I don't think there is anything else we can do. If anyone runs in to this in the future, we would greatly appreciate your help reporting it as a false positive. :+1:
