### ISSUE TITLE
Deleting block with ports leaves orphaned ports

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3115]
### Describe the bug
When deleting a block that has proxy-ports the port symbols remain on the diagram

### To Reproduce
1. Add a block
2. Add a port
3. Delete the block
4. See port symbols remain. No corresponding item in the left hand menu.

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
Deleting a block from a diagram should also remove the ports that it owns.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor:

**Comment by amolenaar** [comment]
Hi @mikekidner,

In #3075, @danyeaw and me decided to leave it like that. For simplicity's sake.

If you think the old behavior should be restored, that can be done pretty easily.
It's relatively simple to fix.

**Comment by mikekidner** [comment]
Leaving the orphaned ports is ok and as you say is a simpler solution to the broader issue of handling related elements. It's good that they can be dragged onto a different block and can then be redefined. 
I'll try to find a good place to update the docs to explain this behaviour - a new section on ports maybe a good thing
