### ISSUE TITLE
Interface Realization does not link

### ISSUE THREAD

**Issue by thejtshow** [gaphor/gaphor#3135]
### Describe the bug
Interface Realization relationships do not snap/bind to the base class.

### To Reproduce
1. create two classes
2. select interface realization (shift+I) 
3. click on one class and drag to the other class
4. see that the arrow is only connected to one class
5. repeat with generalization (shift+G)
6. repeat connection attempt
7. see that the generalization does snap to both classes

### Expected behavior
generalization should bind to both classes

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/9122119/09347710-d2ba-4946-aa55-5b6387b6ad09)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: `2.24.0`

### Additional information
Installed from windows installation package

**Comment by amolenaar** [comment]
Hi,

Thank you for your issue. An interface realization is implemented as a relation between an interface (on the arrow side) and a class. You cannot create this relation between two classes. For that you can use the generalization (inheritance) relationship.

**Comment by danyeaw** [comment]
Hi @thejtshow, with that explanation from @amolenaar, can we close this, or do you think that the UML spec allows for this relationship?

**Comment by thejtshow** [comment]
@amolenaar thank you for your input! I was attempting to model a real class I have in my implementation which is in c++ where I have a virtual base class, where it is both a class and an interface. I am a software engineer and not systems so I am a little out of depth here :) I will look into what you suggested. 

@danyeaw  I will review the spec and examples in the next day or so to see if I have any objections and get back to you. Apologies to you both for the delay!

**Comment by amolenaar** [comment]
I'll close this issue, since there's no action required at the moment.
