### ISSUE TITLE
Edge of Window underflow

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3167]
### Describe the bug
The edge of the gaphor window is not equal to the edge of the drawing window (it's larger).

### To Reproduce
1. open Gaphor
2. try to click just outside the drawn window
3. nothing happens

### Expected behavior
Clicking outside the application window should change the window focus.

### Screenshots
Hidden extended application window edge isn't visible. However, it does show up with Zoom screen share due to the highlighted app border.

![image](https://github.com/gaphor/gaphor/assets/58485783/007dd252-569d-4166-8089-edb981ae6253)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X ] macOS (Sonoma 14.1.1)
- [ ] Windows

### Version
Version of Gaphor: 2.24

### Additional information
It's just a bit annoying (I'm unsure if that's affecting other clicks / interactions due to underflow?)

**Comment by amolenaar** [comment]
Hi @tompkins-ct,

This is an issue with how GTK renders it's window shadows. It has been solved in GTK already: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6785.

The fix will be available in a release as soon as GTK 4.14 is released, somewhere in the next few weeks. Then we have to release a new version of Gaphor.

**Comment by amolenaar** [comment]
4.14 has been released and will he used for the next Gaphor release for macOS (it's in Homebrew).
