### ISSUE TITLE
Bold text in cases where it shouldn't be bold

### ISSUE THREAD

**Issue by bragefuglseth** [gaphor/gaphor#3178]
### Describe the bug
The titles of list rows throughout the app are bold, which is inconsistent with other GNOME apps. They should

### To Reproduce

1. Open app
2. Open about window
3. Observe bold text in row titles during both step 1 and 2
5. Open about window of other GNOME app
6. Observe how the row titles aren't bold

### Expected behavior
The row titles should have the regular font weight.

### Screenshots

Current state:
![Skjermbilde fra 2024-03-11 07-37-34](https://github.com/gaphor/gaphor/assets/91388039/013de7be-0227-4cd9-a09a-1ae80f880a8b)

Expected styling (from Settings)
![Skjermbilde fra 2024-03-11 07-37-57](https://github.com/gaphor/gaphor/assets/91388039/8e48a9c1-fdc4-4ca2-a9be-db4fcd265c65)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.24.0

**Comment by amolenaar** [comment]
The rows in the greeter are [Adw.ActionRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.4/class.ActionRow.html)s. Hence they have a bold title and smaller (greyish) subtitle.

![action row](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.4/action-row.png)

**Comment by bragefuglseth** [comment]
The rows in the app look different from the row in your screenshot (which has the correct styiling) :slightly_smiling_face:

**Comment by danyeaw** [comment]
Hi @bragefuglseth, I do agree that they look different. However, I'm not sure why. It looks like we are just setting the title and sub title.

**Comment by bragefuglseth** [comment]
Could it be because of custom CSS somewhere?

**Comment by bragefuglseth** [comment]
Indeed, there's a class in Gaphor's custom stylesheet _named [`.title`](https://github.com/gaphor/gaphor/blob/79a12fd15c5324d85d59e3f2d97df8336b074fdd/gaphor/ui/styling.css#L40) that has bold styling. Libadwaita uses this internally for its row titles as well, so Gaphor needs to use a different name for it 🙂

**Comment by amolenaar** [comment]
This is better, then:

<img width="912" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/1e465376-2cc2-4738-83b9-5d8a572658db">

**Comment by bragefuglseth** [comment]
LGTM!

**Comment by danyeaw** [comment]
Reopening until we check the about dialog as well.

**Comment by danyeaw** [comment]
It looks like the About Window is using a normal font for me, are you seeing something different?

<img width="828" alt="image" src="https://github.com/gaphor/gaphor/assets/10014976/6e843683-a4bb-4eb4-bfad-12bc1cdb252d">

**Comment by amolenaar** [comment]
Looks good.
