### ISSUE TITLE
Set repository browser in Weblate

### ISSUE THREAD

**Issue by rffontenelle** [gaphor/gaphor#3187]
Please set [repository browser](https://docs.weblate.org/en/latest/admin/projects.html#repository-browser) URL as in the translation components set in [Gaphor](https://hosted.weblate.org/projects/gaphor/) project in Weblate to make it easier to find a string's context in the source code.

* In the docs component ([docs-gaphor-org](https://hosted.weblate.org/settings/gaphor/docs-gaphor-org/#vcs)) VCS settings, set:
```https://github.com/gaphor/gaphor/blob/{{branch}}/docs/locale/{{filename}}?plain=1#L{{line}}```

* In the UI component ([gaphor](https://hosted.weblate.org/settings/gaphor/gaphor/#vcs)) VCS settings, set:
```https://github.com/gaphor/gaphor/blob/{{branch}}/{{filename}}#L{{line}}```

* In the website component ([gaphor-github-io](https://hosted.weblate.org/settings/gaphor/gaphor-github-io/#vcs)) VCS settings, set:
```https://github.com/gaphor/gaphor.github.io/blob/{{branch}}/{{filename}}?plain=1#L{{line}}```

**Comment by danyeaw** [comment]
Hi @rffontenelle, nice suggestion! I made the changes, could you please verify that they are working? Thanks!

**Comment by danyeaw** [comment]
Nice one, thanks @rffontenelle!

@all-contributors please add @rffontenelle for translation, ideas
