### ISSUE TITLE
2.24.0-portable blocked by BitDefender

### ISSUE THREAD

**Issue by RyanPi1** [gaphor/gaphor#3199]
### Describe the bug
when trying to use gaphor-2.24.0-portable on Windows 11, Bitdefender flags it as a security risk and immediately quarantines immediately after extraction. It specifically calls out "Gen:Variant.Cerbu.203942" as the part infecting ".../gaphor-2.24.0-portable/data/gaphor.exe". I personally couldn't find more info on this.

### To Reproduce
1. Run on Windows 11 Home, Version 23H2
2. Install Bitdefender Total Security build 27.0.30.140. turn on Bitdefender Shield.
3. Download gaphor-2.24.0-portable anywhere on the machine and run the exe to extract
4. This should cause a pop-up from Bitdefender 

### Expected behavior
software to extract and be useable

### Screenshots
1. ![image](https://github.com/gaphor/gaphor/assets/22305039/5619fc8b-e961-44fb-8ddb-0ac01571e86d)
2. ![image](https://github.com/gaphor/gaphor/assets/22305039/5ec13b2c-9a84-44f1-9839-9ddf201f97ba)
3. ![image](https://github.com/gaphor/gaphor/assets/22305039/eb2edc6b-9544-4a8d-9137-a407130ad791)
4. ![image](https://github.com/gaphor/gaphor/assets/22305039/c95287d8-2cfa-4847-ba67-dfa56dcff31b)
5. ![image](https://github.com/gaphor/gaphor/assets/22305039/fd399ee3-e32e-40ee-bca2-808292365853)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.24.0-portable

**Comment by danyeaw** [comment]
Hi @RyanPi1, thanks for submitting this issue and sorry you are running in to trouble with your virus scanner. This is called a false positive, and I submitted it to BitDefender. I would appreciate it if you would do the same:
https://www.bitdefender.com/consumer/support/answer/29358/

Unfortunately, there isn't much we can do besides this except hope the virus companies improve their products.

**Comment by danyeaw** [comment]
@RyanPi1 is this now resolved? VirusTotal is no longer showing this flagged by BitDefender.

**Comment by RyanPi1** [comment]
BitDefender is still flagging and disinfecting it, still citing Gen:Variant.Cerbu.203942. I did notice that an attempt to download the installer was also detected as an infected webpage with the same threat name. Can you please explain what this component is being used for?

**Comment by danyeaw** [comment]
@RyanPi1 Thanks for continuing to help test this, however we are sort of at the mercy of BitDefender here. Did you update your virus definitions and report this to BitDefender?

Does it also flag the installer version?

When you say component, what do you mean?

You could also set the Gaphor folder as an exception.

**Comment by dwdbmeagle** [comment]
Possibly related but the chrome browser on windows also blocks the installer download:
![image](https://github.com/gaphor/gaphor/assets/118610260/cc77265e-0f34-4c3f-9783-7f8e94eaaec5)

**Comment by danyeaw** [comment]
Hi @dwdbmeagle, I reported this to Google, please do the same: https://safebrowsing.google.com/safebrowsing/report_error/

Are you on Windows 10 or 11?

**Comment by RyanPi1** [comment]
As an update, I did send the portable installer file to BitDefender to analyze, and they said "The file is clean and detection should be removed in the next couple of updates."

**Comment by RyanPi1** [comment]
2.24.0-portable is not flagged by Bitdefender anymore. I downloaded, ran the extraction exe, and explicitly scanned all the files and Bitdefender said they were good.

**Comment by danyeaw** [comment]
Great, glad this resolved!
