### ISSUE TITLE
Colors of elements

### ISSUE THREAD

**Issue by Bart-Westenenk** [gaphor/gaphor#3200]
### Is your feature request related to a problem?
When coupling a few tables with multiple external services we wanted to colour them according to their source of truth.

### Describe the solution you'd like
In draw.io you could colour the entity / class. It would be nice to have a similar option for Gaphor elements.

### Describe alternatives you've considered
None

### Additional context
I am more than willing to help develop this feature.

**Comment by amolenaar** [comment]
Hi @Bart-Westenenk, thank you for your request.

In Gaphor, we color elements by creating a bit of CSS.

If the external services are loaded in a separate package, you could assign the color based on the package.

![image](https://github.com/gaphor/gaphor/assets/96249/adf4955e-1d0a-4ca9-8e06-ec0ab5eed543)

Does this work for you?

**Comment by Bart-Westenenk** [comment]
That's awesome actually! That could definitely work. Thank you.

**Comment by amolenaar** [comment]
Cool. You're welcome.

btw. If you do not want to use package name, you can also add a special line in the "note" section and check for that.
