### ISSUE TITLE
sub package will disappear when dragging parent package insert under to sub package

### ISSUE THREAD

**Issue by JACKADUX** [gaphor/gaphor#3229]
### Describe the bug
sub package will disaper when draging parent package insert under to sub package

### To Reproduce
1. create package
2. create sub package under package
3. create some diagrame
4. drag package under sub package
5. sub package will disapper

if save file and reopen file subpackage will appear again

### Expected behavior
Do not allow parent dragging to child or refresh button to redraw the tree

### Screenshots
![recording](https://github.com/gaphor/gaphor/assets/87265559/1b6919f5-a5cc-47a2-90ba-da21df702068)

### OS
- Windows

### Version
Version of Gaphor: 2.24.0

**Comment by amolenaar** [comment]
Hi @JACKADUX Thanks for reporting. This behavior should not be allowed.

@all-contributors add @JACKADUX for bugs.

**Comment by danyeaw** [comment]
Hi @JACKADUX, thanks again for the bug report!
