### ISSUE TITLE
Gaphor crashes on macOS when trying to save a model

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#323]
Mentioned by @Xander982.

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

When using the distributed version of Gaphor on a Mac, without any home-brew software installed, it breaks as soon as you hit Save.

https://gist.github.com/Xander982/4ab841f290e0236f1fd5154cec2cf194

### Expected behavior

Open save dialog, of course!

### Minimal reproduction of the problem with instructions

On a developer laptop, with Homebrew installed:
* Rename `/usr/local/Cellar` and `/usr/local/share/glib-2.0/schemas`.
* Start Gaphor
* Hit Save (Cmd-S)

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

Issue looks similar to https://stackoverflow.com/questions/57098941/gtk-file-chooser-dialog-crash-app-after-bundling

**Comment by danyeaw** [comment]
@all-contributors please add @Xander982 for content and bug

**Comment by amolenaar** [comment]
Fixed by #325.
