### ISSUE TITLE
Property page slot fields do not scroll or wrap.

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3235]
### Describe the bug
Slot fields in the property page do not scroll which causes the property page to overtake the working space.

### To Reproduce
1. Create a stereotype with attributes
2. Add a block using the stereotype
3. Fill in the slot with text
4. Observe lack of diagram space.

### Expected behavior
Slot text fields showed wrap and scroll or wrap and expand vertically instead of just horizontally (likely both depending on some width limits for the property panel. 

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/58485783/53d13c14-2621-4d28-8291-9fbb885653e5)

![image](https://github.com/gaphor/gaphor/assets/58485783/029c96ba-220b-420f-bd1f-4d0230f4710e)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.24

**Comment by danyeaw** [comment]
Hi @tompkins-ct, thanks for the issue report, that is definitely something we should fix! Would you be interested in working on a PR to address it as well?

**Comment by tompkins-ct** [comment]
@danyeaw I could take a swing at it, but I'm not very familiar with the code base to identify where to start. If you have some advice on where to start, I'll take it.

**Comment by amolenaar** [comment]
I think adding ellipsis at the end is also a suitable soliution:

<img width="319" alt="image" src="https://github.com/gaphor/gaphor/assets/96249/4bc0bef8-408c-457a-95e7-30da8033996b">

**Comment by tompkins-ct** [comment]
@amolenaar I think that sounds good. It was looking pretty clunky and less responsive with a scroll. However, when editing, does this expand the window too far? It may be a good idea to set a max width and wrap when editing the text field to improve readability.
