### ISSUE TITLE
zoom in/out buttons missing

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3255]
### Describe the bug
Zoom in and out buttons are no longer present in 2.25.0 or I'm just not finding it anymore...

### Expected behavior
Zoom in/out was located in top right corner. I noticed the hamburger menu moved to the left, but the zoom on the diagrams is missing. 

### Screenshots
![image](https://github.com/gaphor/gaphor/assets/58485783/8bc804b6-9650-4580-8d5b-bab93d3bfa97)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.25.0

**Comment by danyeaw** [comment]
Hi @tompkins-ct, good catch, I think we lost the zoom buttons during the UI refresh.

**Comment by amolenaar** [comment]
Are they really needed? Ctrl/Cmd-+, -, and 0 are the shortcuts. Same as in a web browser.

**Comment by tompkins-ct** [comment]
Maybe buttons on the main panel are not necessary, but it's pretty typical to include a button somewhere that references the hot key (whether the front panel or a menu)

Maybe this is an opportunity to improve that function and add
- zoom extents (maybe hotkey `A` (for all) or `H` (for home))
- zoom to box (Elsewhere, in CAD / 3D modeling, I'm partial to holding the right mouse button and dragging a box over a hot key for this one)

**Comment by danyeaw** [comment]
I noticed that some of the other GNOME apps put the zoom settings in the hamburger menu. However, if we were going to do this, it might make more sense to make the zoom settings a global setting across all diagrams instead of just for one. I am not sure that users would expect that zooming in on one diagram would zoom in on all diagrams.
