### ISSUE TITLE
Double clicking causes cloning

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#3262]
### Describe the bug
Double clicking on an item in the model browser results in the item to be cloned and inserted into the diagram. I find this very unexpected and confusing.

### To Reproduce
1. Double click on an item in the model browser.
2. Notice how it gets inserted into the diagram.

### Expected behavior
I don't know, maybe it should offer to rename the item, maybe it should do nothing, but it **definitely should not** clone the item and insert it into the diagram.

### OS
- [x] Linux (Ubuntu)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.25.0

**Comment by tompkins-ct** [comment]
I like that I can double-click on a relationship and it shows up in the current diagram (if the endpoints are present). I can't say I've used the double-click on other items to insert them.

However, the item doesn't get cloned (at least for block definition diagrams); it just gets added to the current diagram.

**Comment by danyeaw** [comment]
Hi @vanillajonathan, thanks for the issue report! As @tompkins-ct said, I don't think it clones the item (creates another copy), it simply puts a new instance of the object on the diagram.

What if double clicking selected the object on the diagram, or gave a message that the current element isn't on the current diagram if it doesn't exist?

**Comment by vanillajonathan** [comment]
Alright but I don't like that it puts a new instance of the object on the diagram, I found it unexpected and confusing.

Yeah, I think one of those options would be better.

**Comment by ghillebrand** [comment]
+1 on selecting the object/ giving a "not in this model" message.
Particularly since repeatedly double clicking creates a perfectly aligned stack of the clicked object in the model - so you can end up with a whole lot of extra objects in the model without realising it. As a certified newbie, this is confusing!
Dragging the object into the diagram makes sense.
