### ISSUE TITLE
Please add the automatic backup function as soon as possible！

### ISSUE THREAD

**Issue by fangsz2022** [gaphor/gaphor#3271]
### Is your feature request related to a problem?
The graph I spent half a day drawing was saved every few minutes using Ctrl+S, and finally an error message appeared, causing the Gaphor application to crash and almost all the data in the file to be cleared.

### Describe the solution you'd like
Please add the automatic backup function as soon as possible！
You can set an automatic backup interval, such as 5 minutes. If the main file is modified or encounters errors, users can manually restore it from the backup folder.

**Comment by amolenaar** [comment]
@fangsz2022 thanks for your report. This is not nice. If it's a hard crash, it's probably related to the libraries Gaphor depends on. Can you tell us which platform you're using? Windows, macOS, Linux distro.

**Comment by amolenaar** [comment]
Related to #2831.

**Comment by fangsz2022** [comment]
> @fangsz2022 thanks for your report. This is not nice. If it's a hard crash, it's probably related to the libraries Gaphor depends on. Can you tell us which platform you're using? Windows, macOS, Linux distro.

@amolenaar Thank you for your reply！
The operating system is Windows 11 Home Chinese version，Vertion：22631.3447
Gaphor version：2.25.0.dev5223+b41c4a26

**Comment by amolenaar** [comment]
Thanks @fangsz2022. I'll close this issue. Let's continue discussion in #2831.
