### ISSUE TITLE
Update screenshots for website and FlatHub

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#3274]
With the new UI, the current screenshots look a bit old ;). It's time for a refresh

**Comment by danyeaw** [comment]
Screenshots in our main docs are now up to date thanks to @mikekidner!

We could still use updates to:

1. https://github.com/flathub/org.gaphor.Gaphor/tree/master/screenshots
2. https://github.com/gaphor/gaphor.github.io/tree/main/images

**Comment by danyeaw** [comment]
Thanks @mikekidner, this is a great contribution! Really appreciated!

**Comment by danyeaw** [comment]
@all-contributors please add @mikekidner for docs
