### ISSUE TITLE
Gaphor shows diagram changed bar after saving

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#3275]
### Describe the bug

When I save a project on macOS, it shows the _diagram has changed on disk_ banner

### To Reproduce
1. Open a model
2. Save the model
3. See the banner appear.

### Expected behavior

The banner should only show if the diagram is changed outside of Gaphor.

It looks like Linux is okay. Probably because its using inotify, whereas macOS uses polling.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.25+

### Additional information

Is this issue also on Windows?

**Comment by teunhoevenaars** [comment]
hi @amolenaar I encountered the same on my Mac. I did a quick experiment (see https://github.com/gaphor/gaphor/pull/3278) where I added a sleep timer between saving and restarting the monitor; this prevents the pop-up on my machine if the timer is set to 2 sec (1 sec apparently is not enough). This doesn't feel like a good solution but perhaps it gives someone an idea how to resolve this more robustly.

PS I tried to install Gaphor on my Windows machine to test this behavior but did not manage; Gaphor wouldn't start at all. I'll try again later and if indeed consistent will make a separate bug.

**Comment by amolenaar** [comment]
I think the best fix is to fix it in glib directly. I haven't checked how the file monitor is implemented for macOS at the moment. Until then, I suppose adding a timeout is completely fine. This is kind of a convenience feature anyway.

**Comment by danyeaw** [comment]
Closed by #3278.

**Comment by matgaj** [comment]
The same thing still happens in Windows on 2.25.1

**Comment by danyeaw** [comment]
Hi @matgaj, thanks for letting us know about the issue you are having, but can you please open a new issue instead of posting on this one which was specific to macOS? Thanks!
