### ISSUE TITLE
Make alignment actions available from a toolbar

### ISSUE THREAD

**Issue by fangsz2022** [gaphor/gaphor#3285]
### Describe the solution you'd like
First of all, thank you for developing Gaphor, which is very simple and practical. During my development process, Gaphor has become the main modeling tool. The alignment function in the Tools menu is the most frequently used when drawing. Can you place the alignment toolbar in the interface, such as in the lower right corner or allow users to customize placement?

### Describe alternatives you've considered
After selecting multiple objects with the mouse, right-click to display the alignment menu.

**Comment by amolenaar** [comment]
Hi @fangsz2022, thanks for the feedback.

Indeed the placement of the alignment actions is not ideal. We recognized it while developing already.

There's multiple options here:

* Add them to the right-click context menu. Either directly or in a submenu.
* Create a special tool bar for things like alignment.
* Add Alignment at the top of the property editor (right pane) as soon as multiple items are selected.
* Use an [OSD](https://developer.gnome.org/hig/patterns/controls/overlaid.html) panel to the diagram.

Its placement should not overwhelm (new) users.

**Comment by amolenaar** [comment]
We have a toolbar now. I changed the title to emphasize we need to add alignment functions.
