### ISSUE TITLE
Update README Animation

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#329]
Our README animation is few versions old, and since then the look of the tool has been updated including new icons, an inline editor for editable text, and an side bar editor.

This animation is also used on gaphor.org.

Since Gaphor looks the best in Linux, we could use someone running default GNOME to create a new animation. Peek can be used to create the animation.

Since helping to update the docs is a great way to get involved, I am would love to have someone new contribute this update. :+1: 

### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [X] Documentation issue or request

### System Information
OS:
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

**Comment by seryafarma** [comment]
Hello, can I take this issue? I have several linux distros: Mint, ZorinOS, Elementary.

**Comment by amolenaar** [comment]
Hi @seryafarma,

Please do. It will be much appreciated :)

**Comment by danyeaw** [comment]
@allcontributors-bot please add @seryafarma for docs

**Comment by danyeaw** [comment]
@all-contributors please add @seryafarma for doc
