### ISSUE TITLE
Elements do not show content until clicked on

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3299]
### Describe the bug
When opening a model, the content of elements does not appear.
![Screen Shot 2024-05-07 at 11 01 18 am](https://github.com/gaphor/gaphor/assets/50702106/49779ba4-30cb-47a8-8e53-bbb5eb10f986)

Once you click on the element, they all show
![Screen Shot 2024-05-07 at 11 01 26 am](https://github.com/gaphor/gaphor/assets/50702106/f90680c3-2d95-4419-8b77-2b2efbda4b54)

### To Reproduce
1. Open a current model
2. See no content in blocks
3. Click on element
4. All content shows up

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Screenshots
See above
### OS
- [ ] Linux (Please put in notes the specific distro)
- [ x] macOS
- [ ] Windows

### Version
Version of Gaphor:2.25.1

### Additional information
Might be related to the requirements text hiding feature??

**Comment by amolenaar** [comment]
Hi @mikekidner,

I ran into this issue too. I patched it in #3296.

This is fallout from the recent changes and simplification to the digram update scheme, in order to make undo/redo work more reliably.
