### ISSUE TITLE
Support multiple item flows on a connector in the UI and on diagrams

### ISSUE THREAD

**Issue by mvinca-bandwidth** [gaphor/gaphor#3307]
### Is your feature request related to a problem?
Currently, the data model supports multiple items flows, but even when the data model is updated with multiple, these flows do not show up on a diagram.
![image](https://github.com/gaphor/gaphor/assets/93543843/cb2c6c0e-8739-4eda-8620-59a78138ac58)

The UI only allows for the addition of one item flow per connector.

### Describe the solution you'd like
The UI is updated to allow the definition of multiple item flows per connector
Diagrams show all item flows when multiples are defined

Can support something like 
![image](https://github.com/gaphor/gaphor/assets/93543843/4c650297-b819-4e0d-b05d-ae253de669e1)
(from UAF samples)

### Describe alternatives you've considered
Drawing multiple connectors, which gets very busy quickly.
Just adding text to mock item flow definition, which means they aren't really in the model, and looks weird as a comment.

### Additional context
Element discussion: https://matrix.to/#/!maFZnGxzqXqppVZrTd:gitter.im/$WB7SNH1E3SlgM2OBNLeQNmn2z6R2u8Mtm8gOtp1HBME?via=matrix.org&via=gitter.im&via=ruhr-uni-bochum.de

**Comment by amolenaar** [comment]
Duplicate of #2130?

**Comment by mvinca-bandwidth** [comment]
Yes, agreed.
