### ISSUE TITLE
Native ARM build for macOS

### ISSUE THREAD

**Issue by maxfaa** [gaphor/gaphor#3309]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Can you release native ARM builds for macOS ? Since all the macs since 2020 use M chips, and there will be more and more, until the total disappearance of the intel based ones. I don't know if ARM macs are in the majority today but it's only a matter of time, so... it would be great

**Comment by danyeaw** [comment]
Hi @maxfaa, thanks for the suggestion! I think if we upgrade our CI/CD runner from macos-12 to macos-14, we'll do our builds with macOS Sonoma with M1. Are you interested in making a pull request with this contribution?

**Comment by amolenaar** [comment]
Excellent suggestion!

I think we should make both an Intel and an ARM build.

**Comment by danyeaw** [comment]
If we were to do both, should we have the full build pipeline run for both?

**Comment by amolenaar** [comment]
I think we should.

Then we can distribute both an `-intel` and a `-arm` dmg. 

BTW. What would be the right term? `-arm`, `-apple-silicon`, `-m1`, or something else?

We may also want to have a look at the [Homebrew cask for Gaphor](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/g/gaphor.rb) and make pick the right architecture.
