### ISSUE TITLE
Minor import issues in spripting.md

### ISSUE THREAD

**Issue by hulsed** [gaphor/gaphor#3312]
### Describe the bug
Two issues with the jupyter notebook:
- SysML is never imported (first seen: https://docs.gaphor.org/en/latest/scripting.html#requirements-from-text-fields)
- factory is also never imported (first seen: https://docs.gaphor.org/en/latest/scripting.html#basic-validation)
This means that the notebook can't be run as-is. 

### To Reproduce
 (see above)

### Expected behavior
The imports should be somewhere in the notebook so it can be reproduced (and ideally, with some explanation of where they are coming from).

### OS
N/A
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: N/A

**Comment by danyeaw** [comment]
Hi @hulsed, thanks! Would you be interested in submitting a PR?

**Comment by hulsed** [comment]
I would, but I'm assuming the markdown was generated from a jupyter source file (.ipynb) that isn't in the repo--is that not correct?

**Comment by amolenaar** [comment]
The markdown file ([scripting.md](https://github.com/gaphor/gaphor/blob/main/docs/scripting.md)) is the only source. It contains special blocks that are executed by jupyter when the site is built.

.ipynb files are not source control friendly.

**Comment by danyeaw** [comment]
I tried to update them all during the last PR to update the scripting docs and I got build failures that I had to back out. I would recommend changing them incrementally to code cells and test one by one by rebuilding the docs.

**Comment by amolenaar** [comment]
Fixed by #3341.
