### ISSUE TITLE
shift-Z shortcut on Mac OS can rename diagram

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3326]
### Describe the bug
When using Shift-Z to make composite associations between blocks, the diagram name becomes editable when tail (diamond end) is connected to a block. This often results in diagrams getting called Z as the shortcut is retried. 

### To Reproduce
1. On bdd create two blocks
2. Keep eye on digram name in menu tree
3. press Shift-Z and clock on a block
4. See diagram name highlighted in menu

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.
No error reported.

### Expected behavior
Shift-Z should put the diagram name into an editable state.
### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor:2.25.1

**Comment by mikekidner** [comment]
I've noticed this also happens if you select a part in the menu and drag it on to the diagram. The diagram name becomes editable.
![Screen Shot 2024-05-28 at 11 15 21 am](https://github.com/gaphor/gaphor/assets/50702106/b2fdb217-f298-4c1f-97c2-ec88a8b76611)

**Comment by amolenaar** [comment]
I'm not able to reproduce this 😞 . Am I missing something?


https://github.com/gaphor/gaphor/assets/96249/95b90d80-0dc4-4b52-97c8-3ecb0181c71e

**Comment by mikekidner** [comment]
After a restart, I'm unable to reproduce either...
Odd, as I have encountered diagrams getting named "Z" by mistake a few times in the past. 
I'll try to narrow down the conditions under which it happens.

**Comment by mikekidner** [comment]
@amolenaar here is a video of the behaviour:

https://github.com/gaphor/gaphor/assets/50702106/e8b7a873-426b-462d-a8d3-25ce3c806a5f

**Comment by amolenaar** [comment]
@mikekidner Thanks a lot! I can reproduce it. This behavior shows when I try this in a use-case diagram, like you do. When I try the same in a Generic diagram, it's fine 😕 .
