### ISSUE TITLE
Not able to add {readOnly} to property

### ISSUE THREAD

**Issue by matgaj** [gaphor/gaphor#3327]
### Describe the bug
Gaphor won't allow appending a read {readOnly} to a property.

### To Reproduce

1. Create class
2. Add property, eg. "+Property: type"
3. Try adding readOnly attribute: "+Property: type {readOnly}"
5. Gaphor deletes the curly brackets and their contents

### Expected behavior
Correct handling of attributes, as described on page 17 of the UML specification.

### Screenshots
![obraz](https://github.com/gaphor/gaphor/assets/10777373/0c725f88-a6e1-4bab-9cdc-91d0e6006860)

### OS
Windows 11 Pro 23H2

### Version
Version of Gaphor: 2.25.1

**Comment by amolenaar** [comment]
Hi @matgaj,

I think the parser skips over `{...}` blocks. Those blocks normally refer to attributes assigned from stereotypes. This currently does not happen for attributes.

You can cheat a bit by defining it as `- parent: Player = {readonly}`, then `{readonly}` is assigned as default value.

**Comment by danyeaw** [comment]
@all-contributors please add @matgaj for idea
