### ISSUE TITLE
"Diagram has changed on disk" when saving a file to OneDrive on Windows

### ISSUE THREAD

**Issue by matgaj** [gaphor/gaphor#3330]
### Describe the bug
When I save a project that is saved in a onedrive folder, it shows the "diagram has changed on disk" banner

### To Reproduce

1. Create a new file
2. Save it to a OneDrive folder
3. Banner appears

### Expected behavior
No banner appears

### Screenshots
![obraz](https://github.com/gaphor/gaphor/assets/10777373/df10ee3e-8829-4865-b512-71310051ac00)

### OS
Windows 11 Pro 23H2

### Version
Version of Gaphor: 2.25.1

### Additional information
Files saved to local folders behave as expected

**Comment by amolenaar** [comment]
Hi @matgaj, Thanks for your report.

If Gaphor shows the banner when saving on OneDrive only? If you save to a location on your local drive, it's okay?

**Comment by matgaj** [comment]
Yes, it says so under additional information

**Comment by Sycophantic-Witty** [comment]
I can reproduce this when saving on a local drive as well.

1. Create new model.
2. "Save As..." locally (e.g.: "C:\tmp\model.gaphor")
3. The "Model Changed on Disk" banner appears.

**Comment by amolenaar** [comment]
Hmmm. Maybe we should double check by calculating a checksum (hash) for the model file.

**Comment by danyeaw** [comment]
@all-contributors please add @matgaj for bug
