### ISSUE TITLE
Windows: Corrupted Icons

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#3352]
### Describe the bug
I did a fresh install of Windows 11 Home on a new laptop, and I am getting corrupted icons in Gaphor.

### To Reproduce
1. Open Gaphor
2. See corruption

### Expected behavior
Icons look normal

### Screenshots

https://github.com/gaphor/gaphor/assets/10014976/38d2462c-9f07-4384-803c-ce893709fc1f

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

Windows 11 Home 23H2. AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

### Version
Version of Gaphor: 2.25.1 and the latest build from https://github.com/gaphor/gaphor/pull/3350

**Comment by amolenaar** [comment]
@danyeaw Is this also the case for 2.26?

**Comment by danyeaw** [comment]
Hi @amolenaar, unfortunately, yes it is still there with 2.26.0.

**Comment by theCapypara** [comment]
This is probably a general issue with gvsbuild / GTK4 on Windows: https://github.com/wingtk/gvsbuild/issues/1405

**Comment by danyeaw** [comment]
Fixed by https://github.com/gaphor/gaphor/pull/3486.
