### ISSUE TITLE
Developer installation crashes deep inside poetry -> meson with pygobject

### ISSUE THREAD

**Issue by ghillebrand** [gaphor/gaphor#3358]
### Describe the bug
Trying to setup the Windows developer environment, as per the instructions [here](https://docs.gaphor.org/en/latest/windows.html)

1st got an error around no gcc, resolved by following [this](https://dev.to/gamegods3/how-to-install-gcc-in-windows-10-the-easier-way-422j)

Now I get this 
``` poetry install
Installing dependencies from lock file

Package operations: 19 installs, 0 updates, 0 removals

  - Installing pygobject (3.48.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  + meson setup C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2 C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2\.mesonpy-_7kfwn1f -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2\.mesonpy-_7kfwn1f\meson-python-native-file.ini
  The Meson build system
  Version: 1.4.1
  Source dir: C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2
  Build dir: C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2\.mesonpy-_7kfwn1f
  Build type: native build
  Project name: pygobject
  Project version: 3.48.2
  C compiler for the host machine: gcc (gcc 6.3.0 "gcc (MinGW.org GCC-6.3.0-1) 6.3.0")
  C linker for the host machine: gcc ld.bfd 2.28
  Host machine cpu family: x86
  Host machine cpu: x86
  Program python3 found: YES (C:\Users\g.hillebrand\AppData\Local\Temp\tmp297ryfbf\.venv\Scripts\python.exe)
  Need python for x86, but found x86_64
  Run-time dependency python found: NO (tried sysconfig)

  ..\meson.build:22:20: ERROR: Python dependency not found

  A full log can be found at C:\Users\g.hillebrand\AppData\Local\Temp\tmp0s6ivx6b\pygobject-3.48.2\.mesonpy-_7kfwn1f\meson-logs\meson-log.txt
```

This _looks_ like meson is trying to find a 32 bit Python installer somewhere?
The folder with the full log is deleted as poetry exits, so I can't dig into those details.

Can I possibly ignore the lock file?

### To Reproduce
Unfortunately, I suspect it is something on my machine

Not a run time error

### Expected behavior

Gaphor source is installed, and runs (as it does on other machines!)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ x ] Windows 10

### Version
Version of Gaphor: Current from github

**Comment by ghillebrand** [comment]
"Can I possibly ignore the lock file?"
I renamed `poetry.lock` to `poetry.lock.original`
3 packages ran additional updates, then it crashes at the same spot in `pygobject`.

**Comment by danyeaw** [comment]
Hi @ghillebrand, sorry you are having issues. If you are getting a GCC error, that's not good and we should figure out why and not try to patch around it. Gvsbuild uses MSVC, and there should be no GCC.

Were you able to successfully install GTK using the Gvsbuild zip?

**Comment by ghillebrand** [comment]
Hi,
So, I don't know _why_ it wanted a C/ C++ compiler, but it did. I installed the 32bit gcc without thinking/ realising. That was what was causing the error. I'm fairly sure the 64 bit gcc would have solved things, but to be sure, I hooked down the 5GBs of VS and C++ environment.

The wingtk [instructions](https://github.com/wingtk/gvsbuild)  make it clear that you will need MS VS's dev env if you are building gvsbuild. I would have thought that using the latest gtk build as per instructions would "just work", but poetry was doing something with it. Their link didn't include a C++ compiler, but I added it for good measure.

Now, everything runs. I might be a bit unusual as a dev not having a C++ compiler on my path. I have one now!

So all good. Now, to figure out gaphor.
What is a good place to explore the ideas/ direction I need to implement a new model type (higraphs)? I have a bunch of newbie questions.

Thanks for the prompt response and help

**Comment by amolenaar** [comment]
Hi @ghillebrand,

The matrix channel at https://matrix.to/#/#gaphor_Lobby:gitter.im is one place. The discussions here, on GitHub is another place, we the discussion can be a bit more structured.

I tried to document it as good as possible on https://docs.gaphor.org/en/latest/modeling_language.html, so it would be good to start there.

**Comment by ghillebrand** [comment]
I shall spend some time looking at the documentation and the code, and getting a feel for "the lie of the land". I suspect then that creating a thread around "Creating a Higraph model type" or something might be the way to go.

ITO the C dependency, I think a note in the (otherwise very comprehensive!) instructions might be good. I strongly suspect that the the 64bit gcc would do the trick, and a version like [this](https://winlibs.com/) doesn't seem to need any admin rights? I pulled down the 5GB MSVS, but it seems like overkill!

Thank you for running supportive, positive little community here.

**Comment by ghillebrand** [comment]
OP  is happy that everything is resolved.
