### ISSUE TITLE
Move canvas by mouse with the right mouse button

### ISSUE THREAD

**Issue by dubst3pp4** [gaphor/gaphor#3369]
### Is your feature request related to a problem?
Many tools (e.g. Miro) allow you to move (scroll) the canvas by dragging it with the mouse while holding down the right mouse button. In contrast, Gaphor shows the "Show in Model Browser" menu.

### Describe the solution you'd like
I want to move the canvas by dragging it, which is much more intuitive than using the scrollbars or scroll wheel (using Shift to move the canvas horizontally).

### Describe alternatives you've considered
Holding down a modifier key while dragging would also be a great alternative. And it would work with touchpads too.

### Additional context
none

**Comment by amolenaar** [comment]
Hi @dubst3pp4,

Gaphor scrolls when you hold the middle mouse button.

The right mouse button is normally reserved for context menus.
