### ISSUE TITLE
Select element in toolbox/diagram

### ISSUE THREAD

**Issue by SebCanet** [gaphor/gaphor#3379]
### Is your feature request related to a problem?
When clicking on an element in left toolbox does not select it in diagram, whereas it opens its parameters in right panel. And when selecting an element ina  diagram it selects it in left toolbox.

### Describe the solution you'd like
When slecting an element, diagram / toolbox / properties are synchronous.

Many thanks!

**Comment by amolenaar** [comment]
Hi @SebCanet,

The idea is to change double-click in the model browser to select the element in the current diagram (see #3262). Will that solve your issue?

**Comment by SebCanet** [comment]
Hi,
thanks for answering, but it's not the same behavior. Actually when you single click on an element in the diagram, it selects it in the model browser (left panel) and it also opens its properties (right panel). But when I select this element in the model browser, it opens its properties but does not select it in the diagram.
I think this would more confurtable if all the panels are synchronized.

**Comment by amolenaar** [comment]
I think selecting the element in the diagram when you select it can have some negative side effects. Imagine the case where you're looking for a particular element to add to a diagram. The moment you select an element (that happens to be in the current diagram), your selection, and possibly visible area changes.

I think sticking to double click is a saver option. At least for now. But let's keep the single click option in mind.

**Comment by SebCanet** [comment]
Thanks for answering, but when double clicking on an element it creates another instance of the element on the diagram, it does not select it.
Maybe another selecting way, like shift+ click?

**Comment by amolenaar** [comment]
The idea is to change the behavior of double-click to select the element in the current diagram, or show an _element not found_ message. This would be somewhat more in line with what happens when you double-click a diagram.

You can drag and drop a model element into the diagram. I suppose Shift+double click could be used to add a model element to the diagram.

Shift-click is already used in the model browser for selecting a set of elements.

**Comment by amolenaar** [comment]
I close this issue. We'll implement it as described in #3262, and go from there.
