### ISSUE TITLE
Control panel for CSS

### ISSUE THREAD

**Issue by SebCanet** [gaphor/gaphor#3380]
### Is your feature request related to a problem?
It's difficult to modify css properties of an element, and know what we can change.

### Describe the solution you'd like
Selectors, buttons, sliders, anything that can help graphically select css propeties and modify it.

Many thanks.

**Comment by amolenaar** [comment]
Hi @SebCanet,

Currently #3329 is a work in progress to allow changing styles without actually knowing any CSS. Is this what you're suggesting?

**Comment by SebCanet** [comment]
Hi,
I did not see this issue, and yes that's the idea, This way we could enhance the styleeditor with new css rule.
Thanks.
