### ISSUE TITLE
Gaphor auto loads the previous (large) model during startup, leading to tempory indication that it may have crashed.

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3392]
### Describe the bug
I've been working on a model (~7MB size) and Gaphor is auto-opening the model on startup. However, this makes it look like the program crashed, because there is no loading splash screen and the app indicates "Application not responding"

### To Reproduce
1. Work on a large model in Gaphor
2. Close Gaphor
3. Restart gaphor
4. Gaphor icon plays startup animation on the dock (for 30s +)
5. Gaphor hangs on start (right click on the icon indicates the application is not responding)
7. After several minutes the model opens

Related to this, Gaphor is pretty slow at opening large models. It may be beneficial to look at improvements in loading models. 

### Expected behavior
Some indication that a model is loading or Gaphor doesn't autoload the last model opened.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS (M2 Pro, 14.2)
- [ ] Windows

### Version
Version of Gaphor: 2.26

**Comment by amolenaar** [comment]
@tompkins-ct thanks for the report. I notice this too when I open the UMl model in Gaphor. The lag was just not big enough to make me create an issue for it.

A side effect of not having a main window and status indicator, is that dialogs (e.g. in case of a merge conflict) get misplaced.
