### ISSUE TITLE
Diagram jumps around when selecting an item after (2 finger) scroll

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#3417]
### To Reproduce
1. Open a Gaphor model with some components
2. Scroll around
3. Select an element
4. If the scrolling did not completely stop, you'll see the diagram jump to a completely different position

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior

Smooth scrolling and selection.

I could trigger this on macOS, but not in Linux (Wayland).

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: main

### Additional information

It's probably due to macOS' smooth scrolling feature.

**Comment by teunhoevenaars** [comment]
I tried to reproduce this in Gaphor latest `main` (commit 62b2fa0d0719362e6d644a332cc55ec3b66daa46) while running the app as described in https://docs.gaphor.org/en/latest/macos.html#development-environment, but I could not trigger this behavior. My Mac is a [Macbook Pro, 13 inch, 2019](https://support.apple.com/en-us/111945)

**Comment by amolenaar** [comment]
The issue exposes itself with smooth scrolling. It'll be fixed in the next [Gaphas version](https://github.com/gaphor/gaphas/releases/tag/4.1.1).

**Comment by amolenaar** [comment]
Fixed by Gaphas 4.1.1.
