### ISSUE TITLE
Classifier.isFinalSpecialization missing from gaphor model

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3458]
### Describe the bug
The UML property Classifier.isFinalSpecification is missing from the gaphor model.

### To Reproduce

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor:

**Comment by amolenaar** [comment]
Hi @pbrown12303,

I cannot find a reference to `isFinalSpecification` in the [UML specs](https://www.omg.org/spec/UML/2.5.1/PDF).

**Comment by pbrown12303** [comment]
Section 9.2.2, Figure 9.1.

**Comment by pbrown12303** [comment]
And sorry, I made a typo. Its isFinalSpecialization, not Specification.
