### ISSUE TITLE
Long filenames in header force width of main window preventing access to right hand toolbar

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3460]
### Describe the bug
When opening a file with a very long path, the displayed filename above the main window forces the window width, which makes the RHS menu inaccessible if you have a small screen (like a laptop)
### To Reproduce
Save a file with a really long filename see how right menu is forced out of the application view. 

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
Maybe truncate the filename or allow the right hand main window edge to be moved, forcing the filename to be truncated. 
### Screenshots
<img width="1108" alt="Screen Shot 2024-08-22 at 8 22 44 am" src="https://github.com/user-attachments/assets/837f2785-9e70-403f-aaba-841f7f621fe8">

<img width="1020" alt="Screen Shot 2024-08-22 at 8 21 18 am" src="https://github.com/user-attachments/assets/fc2062b5-c7c9-438f-a2d8-d74b1b18f3d7">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.26

**Comment by danyeaw** [comment]
Hi @mikekidner, thanks for the bug report! Wow, that is a big filename 😆
