### ISSUE TITLE
How to assign types to Lifelines and Object Nodes

### ISSUE THREAD

**Issue by jmmd2002** [gaphor/gaphor#3466]
Hi. I read on the update notes that we are able to assign types to Lifelines. However, I didn't manage to find how, and so I am writing this to ask for help. 

Besides, I would also like to know if we can assign types to Object Nodes as well.

Thanks

**Comment by amolenaar** [comment]
Hi @jmmd2002, sorry for the late reply.

For Lifelines, you can select a type (Connectable Element) in the property editor
