### ISSUE TITLE
Dependency Ownership Inconsistent with UML Specification

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3467]
### Describe the bug
The Gaphor implementation of Dependency (and its sub-classes) makes the client the owner of the dependency. In the UML specification a Dependency is a subclass of PackageableElement, whose owner must be a Package.

### To Reproduce
Here's the Gaphor definition:
![image](https://github.com/user-attachments/assets/33f674c3-cd37-4b16-827a-c9c199003948)

Here's the UML Specification:
![image](https://github.com/user-attachments/assets/d970eee2-845f-4e53-9c33-468023458a86)

Note that in the Gaphor implementation, the owner property is derived from the client property.

### Expected behavior
According to the UML specification, the Dependency must be owned by a Package. This makes some sense, as the Dependency (or its subclasses may be declared in other contexts and not necessarily be a part of the NamedElement.

In MagicDraw, the default behavior when creating a Dependency (or any of its subclasses) in a diagram is to make the package owning the diagram the owner of the Dependency.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.26.0

**Comment by amolenaar** [comment]
Hi @pbrown12303,

Thanks for the report.

This deviation has been part of Gaphor, even before we showed relationships in the model editor. Indeed we could have  assign the dependency to the owner package (of the diagram?).

However, we're slowly moving towards SysMLv2. Due to this change, `Dependency` has been moved from the UML model to the Core model. The SysMLv2 core model (KerML) does not have a `PackagableElement`.

**Comment by pbrown12303** [comment]
The current Gaphor implementation imposes a constraint that it neither part of UML nor part of SysML 2. The artificial constraint is that the client is also the owner. 

As in UML, In the SysML 2 model, the client is not automatically the owner; Here's the SysML 2 model:

![image](https://github.com/user-attachments/assets/cd73f0fa-3041-43a1-a665-73b52efd2077)

In my modeling work I treat the ownership of a Dependency (and its derived classes, e.g. Refinement) as an explicit modeling choice. Yes, MagicDraw automatically makes the diagram's owning package the owner, but that's just a matter of convenience: MagicDraw needs a home for the Dependency and that's a reasonable default.

At present I am crafting a plugin to import MagicDraw UML models into Gaphor. **_It is important to note that not a single model I have examined (neither my own nor the examples that come with MagicDraw) have the client as the owner of the Dependency. This is a problem._**
