### ISSUE TITLE
For a Dependency, display the client and supplier in the Property Editor

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3468]
### Is your feature request related to a problem?
After creating a Dependency using the API there is no way to determine the supplier of the dependency

### Describe the solution you'd like
When a Dependency is selected, display the client and supplier values in the Property Editor

**Comment by amolenaar** [comment]
Hi @pbrown12303,

This sounds like a good feature. For associations we have this to, since you can edit the association ends.

**Comment by amolenaar** [comment]
Fixed by #3538.
