### ISSUE TITLE
Selecting an Association in the tree generates an error

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3469]
### Describe the bug
When a programmatically created association is selected in the tree, neither the client or supplier values are displayed in the Property Editor

### To Reproduce
1. Create an association using the API. Set owning package, both memberEnds and ownedEnd 
2. Select the association in the user interface tree. An error is generated

### Expected behavior
The Property Editor should show the details of the association without showing an error.

### Screenshots
```
Gaphor version:         2.26.0
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.12.4
GTK version:            4.14.4
Adwaita version:        1.5.2
GtkSourceView version:  5.12.1
Cairo version:          1.18.0
Pango version:          1.54.0
PyGObject version:      3.48.2
Pycairo version:        1.26.1


Errors:

Time since application startup: 0:23:27
|Traceback (most recent call last):
|  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\gaphor\UML\classes\associationpropertypages.py", line 148, in _on_end_navigability_change
|    with Transaction(self.event_manager):
|  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\gaphor\transaction.py", line 58, in __init__
|    self._handle(TransactionBegin(self.context))
|    |            |                -> <gaphor.transaction.Transaction object at 0x000002A8D3750B00>
|    |            -> <class 'gaphor.event.TransactionBegin'>
|    -> <gaphor.transaction.Transaction object at 0x000002A8D3750B00>
|  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\gaphor\transaction.py", line 113, in _handle
|    self.event_manager.handle(event)
|    |                         -> <gaphor.event.TransactionBegin object at 0x000002A8D3750B30>
|    -> <gaphor.transaction.Transaction object at 0x000002A8D3750B00>
|  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\gaphor\core\eventmanager.py", line 77, in handle
|    self._priority.handle(event)
|    |                     -> <gaphor.event.TransactionBegin object at 0x000002A8D3750B30>
|    -> <gaphor.core.eventmanager.EventManager object at 0x000002A8C9680380>
|  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\generic\event.py", line 63, in handle
|    raise ExceptionGroup("Error while handling events", exceptions)
|                                                        -> [AssertionError()]
|ExceptionGroup: Error while handling events (1 sub-exception)
└─┬──────────────────────────────╌┄┈
  |Traceback (most recent call last):
  |  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\generic\event.py", line 59, in handle
  |    handler(event)
  |    |       -> <gaphor.event.TransactionBegin object at 0x000002A8D3750B30>
  |    -> <bound method UndoManager.begin_transaction of <gaphor.services.undomanager.UndoManager object at 0x000002A8C9610F80>>
  |  File "c:\Users\pbrow\Workspaces\GaphorMDImportPlugin\.venv\Lib\site-packages\gaphor\services\undomanager.py", line 179, in begin_transaction
  |    assert not self._current_transaction
  |               -> <gaphor.services.undomanager.UndoManager object at 0x000002A8C9610F80>
  |AssertionError: assert not self._current_transaction
  └─────────────────────────────╌┄┈
```

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.26.0

**Comment by pbrown12303** [comment]
This one is complex and has nothing to do with creating the Association via the API.

I have observed that selecting the Association from the diagram does not create the error while selecting it from the tree does create the error. Why? Here are the gory details.

In assembling the ```AssociationPropertyPage```, two calls are made to set the end navigability for each end. Each results in a call to ```_on_end_navigability_change```. Here's the code:
```
    def _on_end_navigability_change(self, dropdown, _pspec, subject):
        if subject and subject.opposite and subject.opposite.type:
            with Transaction(self.event_manager):
                UML.recipes.set_navigability(
                    subject.association,
                    subject,
                    self.NAVIGABILITY[dropdown.get_selected()],
                )
```
When the Association is selected in the tree, the problem occurs in the second call to ```_on_end_navigability_change``` with the  ```Transaction(self.event_manager)``` invocation. Here's the code for ```Transaction.__init__```:
```
    def __init__(self, event_manager, context=None):
        """Initialize the transaction.

        If this is the first transaction in the stack, a
        :obj:`~gaphor.event.TransactionBegin` event is emitted.
        """
        self.event_manager = event_manager
        self.context = context

        self._need_rollback = False
        if not self._stack:
            self._handle(TransactionBegin(self.context))
        self._stack.append(self)
```

When ```_on_end_navigability_change``` is invoked the first time, the ```Transaction._stack``` is ```None```, which causes a ```TransactionBegin``` event to be created. The ```UndoManager.begin_transaction``` function - the handler for the ```TransactionBegin``` event - first asserts that ```self._current_transaction``` is ```None``` and then sets its value to be a new ```ActionStack()```. So far, so good.

The problem occurs in the second  ```_on_end_navigability_change``` invocation. The ```Transaction._stack``` is again empty and another ```TransactionBegin``` event is created. However this time, when the ```UndoManager``` checks ```self._current_transaction```, it is not ```None``` and an exception is raised.

So, why doesn't this happen when the Association is selected from the diagram? The answer is that the mouse event in the diagram starts a transaction in ```TxData.begin```. As a result, on both invocations of ```_on_end_navigability_change``` the ```Transaction._stack``` is not empty - so a ```TransactionBegin``` event is not generated. I am speculating a bit here, but I suspect the ```TxData.commit``` also cleans up the ```UndoManager._current_transaction```.

**HOW TO FIX THIS?**

This raises the question as to how to fix this problem. Should there be the equivalent of the ```TxData.begin``` on the mouse event in the tree? Or is there a different way to address this issue?

**Comment by amolenaar** [comment]
Did the transaction in the API not finish before the transaction in the giu was started?

There is indeed a gory detail regarding transaction and the undo-manager functionality: the undo-manager uses special handling (priority event handling) in the event handler. This makes sure all events are recorded as soon as they happen. 
But transactions are committed using the regular flow, so we catch as much events as possible, such as events that happen due to diagram updates (which happen asynchronously).

So what I think happened, is that a transaction is started before the previous transaction was completely closed.

I have some ideas on how to improve this, e.g. send commands instead of events.

**Comment by pbrown12303** [comment]
As you suspected, the top-level transaction was never committed. But I have questions as to the correct way to do a commit. The documentation is unclear on this. 

My first "fix" was to explicitly create a TxData just prior to the top-level transaction begin:
```
        txData = TxData(self.event_manager)
        with Transaction(self.event_manager) as ctx:
            # First we import any referenced profiles
```
This worked admirably (Association selection in the tree did not produce an error), but the documentation doesn't even mention TxData, so I figured I'd go back and try other approaches.

For the second try I looked at the documentation example:
```
    >>> with Transaction(event_manager) as ctx:
    ...     ... # do actions
    ...     # in case the transaction should be rolled back:
    ...     ctx.rollback()
```
From this I figured there must be a``` ctx.commit()``` function as well, but there is not, so that won't work.

For my third try I observed that the ```TransactionContext``` (i.e. the ```ctx``` in the example above) has an attribute ```_tx``` that points to the transaction created entering the ```with``` clause, so I tried ```ctx._tx.commit()```. This works, but it is less than obvious.

Since a commit() is always required to complete a top-level transaction, there should be a straightforward way to do the commit. I'm thinking that adding ```TransactionContext.commit()``` with an implementation of ```self._tx.commit()``` might be appropriate.

**Comment by amolenaar** [comment]
> As you suspected, the top-level transaction was never committed. But I have questions as to the correct way to do a commit. The documentation is unclear on this.
> 
> My first "fix" was to explicitly create a TxData just prior to the top-level transaction begin:
> 
> ```
>         txData = TxData(self.event_manager)
>         with Transaction(self.event_manager) as ctx:
>             # First we import any referenced profiles
> ```
> 
> This worked admirably (Association selection in the tree did not produce an error), but the documentation doesn't even mention TxData, so I figured I'd go back and try other approaches.
> 
> For the second try I looked at the documentation example:
> 
> ```
>     >>> with Transaction(event_manager) as ctx:
>     ...     ... # do actions
>     ...     # in case the transaction should be rolled back:
>     ...     ctx.rollback()
> ```
> 
> From this I figured there must be a` ctx.commit()` function as well, but there is not, so that won't work.

The transaction is committed (or rolled back) when the ``with`` block ends. `ctx.rollback()` only flags the transaction for rollback.

> For my third try I observed that the `TransactionContext` (i.e. the `ctx` in the example above) has an attribute `_tx` that points to the transaction created entering the `with` clause, so I tried `ctx._tx.commit()`.

That's not the way to go. Attributes starting with an underscore are considered "protected" or "private".

> Since a commit() is always required to complete a top-level transaction, there should be a straightforward way to do the commit. What is the correct way?

The correct way is to do what needs to be done in a transaction in a ``with`` block. The transaction is automatically completed when the ``with`` block ends.

The EventManager works in such a way that one event is completely handled before a next event is dispatched. This means that events are queued. *But* the UndoManager needs to know about model change events as soon as they happen: it needs to know all changes that happened, so they can to be rolled back in case of an error. In order to do that, there's a special [priority](https://github.com/gaphor/gaphor/blob/main/gaphor/core/eventmanager.py#L42) handler on the EventManager.

To make it more complicated: we cache changes to diagrams until the end of the transaction (we need to or the interaction will become really sluggish). Because of this, the [UndoManager](https://github.com/gaphor/gaphor/blob/main/gaphor/services/undomanager.py#L131-L144) listens to the normal event handler (not the priority one) for part of the events it needs to act on.

It's actually the UndoManager that makes the transaction logic complicated. During normal use this is not a problem, but if a second transaction happens while the queue of the EventManager is not empty yet, trouble starts.

PS. This is actually the reason that, when unsaved model changes are replayed, only one transaction is created. We record every individual transaction, but are not able to replay them as individual transactions.

Hmmm... Maybe it's enough for the event manager to empty its queue when a new transaction is initiated.

**Comment by amolenaar** [comment]
True. It looks like the property page is trying to do an update on the model (`_on_end_navigability_change`), which is something it should not do if you only select it.

**Comment by pbrown12303** [comment]
It's reading the model and updating the gui widget that displays the navigation setting. That's triggering the _on_end_navigability_change  event. In this scenario there should be a way to set the value without triggering the callback. In fact, the callback should only  be triggered if the value is changed via the gui.
