### ISSUE TITLE
Correlation between Pins and Actions is not maintained during Activity Diagram editing operations

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3481]
### Describe the bug
Editing operations in Activity diagrams do not maintain the proper correlation between pins and actions.

### To Reproduce
There are a number of scenarios that can demonstrate this bug:
1. If a pin X (either input or output) is associated with action A in one activity diagram and you have another activity diagram with action A already in it, you can drag pin X into the diagram and place it anywhere. It doesn't have to be connected to action A.
2. If a pin X is associated with action A in an activity diagram and you then create an action B and drag pin X from the tree onto action B, it can be attached to action B, but it will also still be shown as attached to action A. Note that attaching pin X to action B does place pin X under action B in the tree.
3. If pin X is associated with action A in an activity diagram, you can drag pin X from the tree and place another copy of the pin anywhere in the diagram. You can even attach it to action A again, and end up with two pin X's attached to action A.

### Expected behavior

- It should not be possible to create a pin without associating it with an action
- It should not  be possible to display a pin in an activity diagram (by dragging it from the tree) without having it graphically attached to the action with which it is associated

### Screenshots
![image](https://github.com/user-attachments/assets/98083d33-1131-4f8b-8cfe-39bf498bf990)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.26.0

**Comment by danyeaw** [comment]
Closed by #3479.
