### ISSUE TITLE
File attachment feature

### ISSUE THREAD

**Issue by pleaseaddhyphens** [gaphor/gaphor#3494]
### Is your feature request related to a problem?
I am developing custom UML and I think it would be good to have the ability to link certain file to the model. So I can establish traceability with the artifact documents that appear during system development.

### Describe the solution you'd like
It would be good to create an element that will contain path to the specific file in the working directory. Using GUI (File Explorer) I can attach the file (write the path) and show that file (again in the Explorer) 

### Additional context
I was skimming through the source code. And discover that to define new element I shall modify Core.gaphor at first declaring new subject class for the File and then proceed with diagramming logic. I stacked here because coder.py can't generate me coremodel.py

Am I at the right direction?

**Comment by pleaseaddhyphens** [comment]
I managed to generate code. The override file shoud be specified. I ran python gaphor\codegen\coder.py models\Core.gaphor -r models\Core.override

**Comment by amolenaar** [comment]
Hi @pleaseaddhyphens,

Cool you figured out what missed. We use a small tool (`poe`) to do the same. The commands are specified in the `pyproject.toml` file.
