### ISSUE TITLE
Deleting Pin from Tree does not remove Pin from Tree

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3496]
### Describe the bug
If a Pin is selected in the Tree and the right-mouse Delete function is invoked, the display of the Pin remains in the tree.

### To Reproduce
1. Create an Action and associate a Pin with it. The Action and the Pin will display in the Tree
2. Select the Pin in the Tree and use the right-mouse Delete function. The Pin remains in the tree. No error is generated

The problem appears to occur as a side effect of the ```Pin.opaqueAction``` being a subset of ```owner```. The exact scenario is as follows.

```tree_view_delete``` calls ```Element.unlink()```, which in turn calls ```Element.inner_unlink()``` function. Here's the code for that:

```
    def inner_unlink(self, unlink_event: UnlinkEvent):
        for prop in self.umlproperties():
            prop.unlink(self)

        log.debug("unlinking %s", self)
        self.handle(unlink_event)
```
When this function is initially entered, the Pin (the element in the event) has its ```owner``` derived attribute referencing the Action, as it should.

The loop at the beginning of the function iterates through the properties, calling unlink on them. One of these properties is the ```opaqueAction``` property. A side effect of unlinking the property is that the Pin's owner attribute becomes None.

In the latter part of the function, ```self.handle(unlink_event)``` is invoked. This ends up creating an ```ElementDeleted``` event for the Pin. One of the handlers for this event is ```TreeModel.remove_element()```. Note that by the time this function is invoked, ```<pin>.owner == None```. Here's the code:

```
    def remove_element(self, element: Element, former_owner=_no_value) -> None:
        for child in element.ownedElement:
            self.remove_element(child)

        if isinstance(element, UML.Namespace):
            for child in element.member:
                self.remove_element(child)

        # Deal with member relation, but exclude namespace, since it also relates to the owner
        former_namespace = (
            element.memberNamespace
            if (
                former_owner is None
                and element.memberNamespace
                and element.memberNamespace is not element.namespace
            )
            else None
        )

        if (
            owner_branch := (
                self.owner_branch_for_element(element, former_owner=former_owner)
                or (
                    former_namespace
                    and self.owner_branch_for_element(
                        element, former_owner=former_namespace
                    )
                    or None
                )
            )
        ) is not None:
            owner_branch.remove(element)

            if not len(owner_branch):
                self.remove_branch(owner_branch)
```
In the middle of this routine there is code that looks for the ```owner_branch```, which first invokes ```TreeModel.owner_branch_for_element```. Here's that code:

```
    def owner_branch_for_element(
        self, element: Element, former_owner=_no_value
    ) -> Branch | None:
        if (
            owner := (element.owner or element.memberNamespace)
            if former_owner is _no_value
            else former_owner
        ) is None:
            return self.branches[None]

        return next(
            (m for ti, m in self.branches.items() if ti and ti.element is owner),
            None,
        )
```
Here ```owner``` ends up being none (as a side effect of the previous property change) so TreeModel.branches[None] is returned. I have no idea where this value comes from, but it does not contain the Pin. 

That branch is passed back to ```remove_element```, which then calls ```branch.remove_element(pin)```. This ends up being a noop since the pin is not in the branch. 

As a result of this, the Pin remains in the tree as a child of the Action.

While is is clear what the problem is, the appropriate fix is less than obvious. 

### Expected behavior
The Pin should be removed from the tree. 

### Screenshots
Prior to selecting Delete:
![image](https://github.com/user-attachments/assets/75b90a79-94cf-4367-91d6-e5097b0908f4)

After Delete. Note that the Pin is gone from the diagram but remains in the tree.
![image](https://github.com/user-attachments/assets/c6f5d2c5-9085-4eed-a74b-53b159481dc4)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.26.0

**Comment by amolenaar** [comment]
I need a bit of (spare) time to investigate this further. My first hunch is that the [`deletable` dispatch function](https://docs.gaphor.org/en/latest/modeling_language.html#automated-model-cleanup) has a branch that prohibits deletion.

**Comment by amolenaar** [comment]
I tested it with the latest version (`main`), and it works again.
