### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bnounours** [gaphor/gaphor#3505]
### Describe the bug
After few minutes of use of Gaphor the virtual memory use increase a lot. Having the window selected is enough to see memory increase

### To Reproduce
1. Start application `flatpak run --ostree-verbose  org.gaphor.Gaphor`
2. Put some bloc
3. look at virtual memory used
![Capture d’écran de 2024-09-26 12-23-29](https://github.com/user-attachments/assets/5a6c11a0-08eb-4094-a09a-a9ac0858b51e)

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
Not memory leak

### OS
- [x ] Linux (Ubuntu 20.04.6 LTS)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.26.0
Used as a flatpak application

### Error Report
Gaphor version:         2.26.0
Operating System:       Linux (5.15.0-122-generic)
Display:                X11Display
Python version:         3.12.6
GTK version:            4.16.1
Adwaita version:        1.6.0
GtkSourceView version:  5.14.0
Cairo version:          1.18.2
Pango version:          1.54.0
PyGObject version:      3.50.0
Pycairo version:        1.27.0

**Comment by danyeaw** [comment]
Hi @bnounours, I expect that this is the GTK bug here, which is now fixed in 4.16.2:

https://gitlab.gnome.org/GNOME/gtk/-/issues/7013

**Comment by bnounours** [comment]
> Hi @bnounours, I expect that this is the GTK bug here, which is now fixed in 4.16.2:
> 
> https://gitlab.gnome.org/GNOME/gtk/-/issues/7013

Ok :) I will wait for GTK 4.16.2 and tell you if it is fixed

**Comment by bnounours** [comment]
Hello, I upgraded to Ubuntu 24.04 and the problem is gone. I used Gaphor for 30 minutes and "only" ~2GB are used in virtual memory and not increasing anymore. The strange part is GTK version did not changed. The only change is Display from X11 to Wayland

After Upage of Ubuntu:
Gaphor version:         2.26.0
Operating System:       Linux (5.15.0-122-generic)
Display:                GdkWaylandDisplay
Python version:         3.12.6
GTK version:            4.16.1
Adwaita version:        1.6.0
GtkSourceView version:  5.14.0
Cairo version:          1.18.2
Pango version:          1.54.0
PyGObject version:      3.50.0
Pycairo version:        1.27.0

**Comment by bnounours** [comment]
I let open if you want to investigate, but for my case the problem is resolved

**Comment by amolenaar** [comment]
Hi, the issue only occurs if GTK is using the new (`ngl`) renderer. It may be that the Ubuntu folks backported the fix, since it affects all GNOME apps.

Anyway. Good to see it works again.

BTW. GTK 4.16.2 has been released 2 days ago.

**Comment by amolenaar** [comment]
I close this issue, since it's resolved in the latest GTK version.
