### ISSUE TITLE
Auto layout top to bottom, or bottom to top

### ISSUE THREAD

**Issue by SebCanet** [gaphor/gaphor#3522]
### Is your feature request related to a problem?
On all my bdd, when usin auto layout, orhtogonal or not, the parent block is always on bottom of diagram, and child block are upon it, without choice.

### Describe the solution you'd like
Decide if parent is at top of diagram or not.

Thanks a lot.

**Comment by danyeaw** [comment]
Hi @SebCanet, thanks for the issue report. I think this is already fixed by https://github.com/gaphor/gaphor/pull/3479, and should be out in Gaphor 2.27.0 soon.

**Comment by danyeaw** [comment]
The new version is now out. If you are still having issues with autolayout, please open a new issue. Thanks!

**Comment by SebCanet** [comment]
That's great for me, thanks a lot! But I think to users who want to autolayout from bottom to top, can't we have a preference for the autolayout hwich permits to select 'top to bottom' or 'bottom to top'?

**Comment by danyeaw** [comment]
Hi @SebCanet, if users have this use case they can open another issue. In general, we are configuring Gaphor to work for the majority of users and avoiding lots of configuration. Every configuration has a negative impact on app complexity for the users and the developers.

**Comment by SebCanet** [comment]
Ok, I understand well, thanks.
