### ISSUE TITLE
UI Test is failing because test lacks i18n

### ISSUE THREAD

**Issue by nomisge** [gaphor/gaphor#3527]
Following UI test will fail if another language (e.g. German) is used.

https://github.com/gaphor/gaphor/blob/97a7b58a034e63b8714f701f172095559477fe4c/gaphor/ui/tests/test_modelbrowser.py#L268

Since the assertions argument is checked on the english output "general: General" only, it will fail in other languages. The German text would be "'allgemein: General'" obviously not the same.

If I haven't got it wrong, I suggest to either check for the string containing "General" only or the parts, that are not localized.

**Comment by amolenaar** [comment]
Hi @nomisge, Thank you for raising this issue. Indeed, the tests should be consistent whatever language used.

One fix would be to make sure the expected text is also translated:

```python
    assert branch.relationships[0].readonly_text == gettext("general: General")
```

Another would be to ensure tests are using the en_US locale, e.g. by some configuration in `conftest.py`.

What would be the better approach of the two?

**Comment by danyeaw** [comment]
I like the gettext style! @nomisge would you be interested in creating a PR?

**Comment by nomisge** [comment]
Sure. Will do.
