### ISSUE TITLE
Make the Gaphor UML model self-consistent

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3528]
### Is your feature request related to a problem?
The UML model in Gaphor is not presently self consistent. These inconsistencies arise in the modeling of associations and fall into two categories:

1. Subsets having a multiplicity greater than their supersets
2. Associations having one end as a derived set and the other end a settable value.

_As described below, resolving one of the subset inconsistencies would require changing the multiplicity of the core `Relationship.target` property, which is likely to have far-reaching impacts on the behavior of Gaphor when editing and displaying models._ 

The discussion below explores some of these inconsistencies in detail. It is likely that there are many others yet to  be discovered.

**BehavioralFeature.ownedParameterSet**

The `BehavioralFeature.ownedParameterSet` property is modeled with a multiplicity of `0..*`, but is declared to be a subset of `Element.namespace` which has a multiplicity of `0..1`. Pull request #3525 changed the `BehavioralFeature.ownedParameterSet` multiplicity to `0..1`. This change was straightforward and is consistent with the UML standard.

**Property.classifier**

The `Property.classifier` property is declared to be editable (i.e. not derived). Its opposite `Classifier.attribute` is declared to be a derived property and therefore is unsettable. This breaks the current logic of the `Association.set()` operation when `Property.classifier` is assigned a value.

In the UML standard, `Property.classifier` is declared to  be a read-only derived union of `Property.interface` and `Property.class`. Since these subset declarations are already present in the Gaphor model, pull request #3525 changed `Property.classifier` to a derived union. This change was also straightforward and is consistent with the UML standard.

**Deployment.deployedArtifact**

This one is problematic with the present Gaphor Core structure. The `Deployment.deployedArtifact` property is modeled in Gaphor with an multiplicity of `0..*`, but is declared to be a subset of `Dependency.supplier` which has a multiplicity of `0..1`. The `Dependency.supplier` property is, in turn, declared to be a subset of `Relationship.target`, which also has a multiplicity of `0..1`.

In the UML standard, `Dependency.supplier` has a multiplicity of `1..*` and `DirectedRelationship.target` has a multiplicity of `1..*`. 

So the solution is to change the Gaphor `Dependency.supplier` and `Relationship.target` model dependencies to `1..*`. However `Relationship` in Gaphor is presently a 1:1 mapping and this class is widely used. It is quite likely that the dynamic editing and display behavior of Gaphor makes assumptions about the multiplicity of `Dependency.supplier` and `Relationship.target`. Consequently, the scope of this change will be large and will, I suspect, require significant manual testing in addition to the automated testing already in place. This inconsistency has not yet been addressed.

### Describe the solution you'd like
The Gaphor model should, at a minimum, be self-consistent and, ideally, conform to the UML model standard.

**Comment by pbrown12303** [comment]
As it turns out, changing the multiplicity of Dependency.supplier and Dependency.client to `1..* and removing Element.owner as a subset of Dependency.client was not all that difficult! Now part of pull request #3525

**Comment by pbrown12303** [comment]
Removinng Element.owner as a subset of Dependency.client created a problem when creating dependencies in terms of how to place them in the correct package. In the UML specification, Dependency is a PackageableElement, which has a settable owningPackage property. But in the Gaphor model, Dependency is not a subclass of PackageableElement, so this property is not available.

**Comment by amolenaar** [comment]
> In the UML specification, Dependency is a PackageableElement, which has a settable owningPackage property. But in the Gaphor model, Dependency is not a subclass of PackageableElement, so this property is not available.

I corrected this in #3541. Basically all "KerML" changes have been undone. Except:

* `Element` has a `name` and `qualifiedName` property
* `Relationship` is in the core model and also contains `sourceRelationship` and `targetRelationship` (part of `DirectedRelationship` in the UML model).

https://gaphor--3541.org.readthedocs.build/en/3541/models/core.html shows what's left in the core model.

**Comment by pbrown12303** [comment]
If core is a required base for all language models then I think that Element and Relationship need to be in the language-specific model as well. Let me explain why using my minimalist ACRL model. 

![image](https://github.com/user-attachments/assets/3b96a8fc-7eaf-4a8f-bec1-ab4b69b98f01)

The first thing to note is that this is the complete language; there are no other concepts or relationships. My conjecture (the reason for implementing ACRL) is that all concepts and relationships can be representing with this minimal model. 

I think there are two aspects of this model relevant to our discussion. First of all, all relationships are derived, but none are derived via the subset mechanism. Instead, all references to elements are established by setting an element property with the relevant identifier. For example, the owning_concept of an Element is established by setting the value of Element.owning_concept_id. The owning_concept pointer is established by looking up the Element object with the appropriate concept_id. The relationships point to the objects identified by the identifiers. 

A second relevant aspect is that ACRL does not have relationship as a core construct. In ACRL a relationship is an Element that owns two References, each representing an end of the relationship. Here's an example of a relationship between an Order and a Shipment (terminology slightly different: ElementReference as opposed to just Reference).

![image](https://github.com/user-attachments/assets/843644a0-a7ac-43d8-907e-e365c3a93ced)
 
I do think it might be appropriate to have a Core with a BaseElement class with a `name` property, though I prefer the term `label`. This because, in general, a concept may have more than one name (term) associated with it. The thesaurus exists because of this phenomenon. In ACRL I would explicitly model the relationship between names and concepts.

Even `qualifiedName` makes the assumption that the language has a strict tree structure and that the names of children are unique at each node in the hierarchy. True in most instances, but not always.

**Comment by amolenaar** [comment]
> If core is a required base for all language models then I think that Element and Relationship need to be in the language-specific model as well.

I think `Base` should be the basis, as `Base` is the base type for `StyleSheet`, and `Presentation` (#3543).

However, a lot of the logic in Gaphor currently expects the `Element` type. Especially the GUI.
A few core concepts (`Diagram` and `Picture`) also require element-ish traits, mainly ownership.

I would like to implement a second model without a shared `Element`, but that was a bit too much for one weekend ;).

> A second relevant aspect is that ACRL does not have relationship as a core construct.

I was actually questioning myself if Relationship should be moved back into the UML model: the Core model is not using it by itself.

> Even qualifiedName makes the assumption that the language has a strict tree structure.

Well, it coexists with the `owner`/`ownedMember` relationship.

> For example, the owning_concept of an Element is established by setting the value of Element.owning_concept_id. The owning_concept pointer is established by looking up the Element object with the appropriate concept_id.

Why should `owning_concept` not have an association to another concept (`Element`?). Isn't having id's and lookup tables an implementation decision? It's an implicit reference, right?

(BTW. Each model element has access to the repository, so it can do those kinds of queries.)

**Comment by pbrown12303** [comment]
If you define the base classes with just the operations needed for Gaphor behavior then it would be simple to require each language model to implement those operations. That way each language class simply inherits the appropriate Gaphor base class and implements the required operations. I would think that the number of required operations would be relatively small, so a one-time investment in implementing them for each language would not be a big deal. 

A bit of explanation about my model's distinction between the identifier and the object. The reason for the distinction is that the entire model may not be loaded: there may be part of it residing in an external repository. The relationships navigate the portion that is currently loaded. My vision for ACRL anticipates many millions of concepts (most automatically created from other sources like a dictionary, thesaurus, or other reference).  The mechanics of handling references to as-yet unloaded concepts would, of course, need to be added - perhaps using the event infrastructure.

As for the hierarchy, I am willing to concede that it is reasonable to make it a requirement for a practical model. Worst case (really ugly) there is just a root node (the language) with a flat space of children immediately below. This is what you would get with a pure network model. For ACRL I am OK with the hierarchy requirement (it has one).

**Comment by amolenaar** [comment]
I think we achieved this goal by merging #3571, right?

**Comment by pbrown12303** [comment]
@amolenaar I believe you are correct.
