### ISSUE TITLE
Model changed on disk notification when saving in the program

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3536]
### Describe the bug
This bug was here previously (#3330) and now it's back. On MacOS, saving your file causes the "file changed on disk" note to pop up.

### To Reproduce
1. save a model (cmd+s)
2. see the notification pop up

### Expected behavior
Notification shouldn't show up in Gaphor when I used Gaphor to save.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS Sonoma 14.7
- [ ] Windows

### Version
Version of Gaphor: 2.27

**Comment by ghillebrand** [comment]
Most likely redundant by now, but I was getting this on Win10 as of V2.27.0.

**Comment by danyeaw** [comment]
Thanks @tompkins-ct and @ghillebrand for the bug report.
