### ISSUE TITLE
pip install gaphor fails probably due to dependencies not cited on install page

### ISSUE THREAD

**Issue by Bazmundi** [gaphor/gaphor#3539]
### Describe the bug
pip install gaphor fails probably due to dependencies not cited on install page

### To Reproduce
create conda area for gaphor under Ubuntu
conda install pip
pip install gaphor

### Expected behavior
gaphor installs 

### OS
- [x ] Linux (Ubuntu 24.04.4 LTS)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: according to gist below gaphor-2.11.0-py3-none-any.whl

### Additional information
[Add any other context about the problem here.](https://gist.github.com/Bazmundi/ee6d66329c430cab07bbae99bb426805)

**Comment by Bazmundi** [comment]
Yep, nope.  I may not bother as the app seemed to stop working when I was
using the app version on Ubuntu, and I am more wanting to be a user rather
than developer.

**Comment by danyeaw** [comment]
Are you having issues with the Flatpack version?
