### ISSUE TITLE
Dispense with Core in its present form: Its use prohibits compliance with the UML specification.

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3540]
### Is your feature request related to a problem?
Splitting the UML model concepts between Core.gaphor and UML.gaphor makes it impossible to comply with the UML language specification. 

A specific case in point is the modeling of Dependency (issue #3528, pull request #3525). Shown below is the UML specification for dependency. In Gaphor, Dependency is defined in Core.gaphor, while PackageableElement is defined in UML.gaphor. This makes it impossible to make Dependency a subclass of PackageableElement. This, in turn, makes it impossible to set the owningPackage property of a Dependency (it doesn't have one because it is not a subclass of PackageableElement). This is but one consequence of trying to split the model.

![image](https://github.com/user-attachments/assets/bb6697e7-3c12-4c7e-a578-586c7a6cc6d5)

### Describe the solution you'd like
Migrate all language-specific modeling concepts from the Core model into language-specific models. If common cross-language concepts are desired for tool purposes, make them base classes (e.g. BaseElement) that can be made sub-classes of the language-specific modeling concepts.  With this approach the language models are not constrained in any way and the base classes can support tool-specific behavior.

### Describe alternatives you've considered
There are no alternatives is compliance with language specifications is sought.

**Comment by danyeaw** [comment]
With #3541 merged, are we ready to close this one?

**Comment by pbrown12303** [comment]
Not quite. The UML classes in Core.gaphor need to be moved to UML.gaphor first. I believe @amolenaar is in the process of doing that as part of the preparation for multiple language support.

**Comment by amolenaar** [comment]
Those PR's have been merged now.

All we can do is move  the `Relationship` class back to the UML model (and maybe `Comment`).

We need `Element` in the core model, since `Diagram` also depends on it.

Not sure what to do with `Comment`: it's been moved to the core model and is displayed as part of the "general" tools, alongside lines and boxes.

The next big improvement will be integrating #3525.

**Comment by pbrown12303** [comment]
If you put Element in Core the target language will not be able to create any new associations with Element. This, I think, would be a fatal flaw.

I would not place any UML (i.e. target language) concepts in the Core model. Leave Core as a collection of implementation-specific classes that are used as ancestors for the language-specific classes. Core.BaseElement as an ancestor to UML.Element, Core.BaseDiagram as an ancestor to UML.Diagram, Core.Comment as an ancestor to UML.Comment. Name the attributes of Core in such a way as to ensure no conflict with the language-specific attributes, e.g. base_attribute_name. This way you don't place any constraints on the language model. I've been modeling languages for nearly 40 years and I can pretty much guarantee you that any assumptions you make about the target language model will come back to haunt you eventually.

**Comment by amolenaar** [comment]
I think I see where you're going. Let's move `Relationship` and `Comment` back to the UML model.

When I look at the `Element` class, it contains 3 separate concerns: naming, ownership, and the internal note.
The thing is that those concepts are used all over the place in Gaphor, so if we move those out of the core, we end up with Gaphor depending on the UML model again.

Instead I can break up the element class, and make deal with those separately.

![image](https://github.com/user-attachments/assets/0edb04a2-8c1f-46e8-ab68-e0ca2ba03eef)

Now the `Element` class in the UML language can inherit from those concepts.

I can't really think of a more readable/understandable alternative for `owner`/`ownedElement`.

**Comment by pbrown12303** [comment]
What I had in mind was more like this:
![image](https://github.com/user-attachments/assets/7a86572a-765e-47a2-96c8-3dbd571c7124)
Everything in CoreElement is abstract. The language-specific sub-class must implement all of the abstract methods. This allows these methods to be mapped to/from their language-specific attributes/relationships. Gaphor itself can use the core methods.

**Comment by amolenaar** [comment]
With #3571 merged, the work on separating UML from the Core model is almost complete. I'm really happy with how the changes turned out, and think those PR's brought some nice improvements to the code base.

There's still some work to do:

* Move `name` and `qualifiedName` from `Element` to `NamedElement`
* Reduce dependency on UML model (#3577)

There's still some challenges ahead. For example how to deal with completely different models in the GUI. But let's tackle those when we get there. 

Thanks, @pbrown12303 for helping on this.

**Comment by amolenaar** [comment]
I think this ticket is finished, how that #3649 is merged.

With those efforts it is (theorethically) possible to define a completely new modeling language from the ground up. Gaphor's core, diagramming, and UI no longer depend on the UML package.
