### ISSUE TITLE
XML namespace points to an inaccessible file

### ISSUE THREAD

**Issue by QazCetelic** [gaphor/gaphor#3551]
### Describe the bug
The link to the XML namespace file returns a 404

### To Reproduce
1. Create a diagram
2. Diagram's XML namespace (`xmlns`) is http://gaphor.sourceforge.net/model
```xml
<?xml version="1.0" encoding="utf-8"?>
<gaphor xmlns="http://gaphor.sourceforge.net/model" version="3.0" gaphor-version="2.26.0">
...
```

This is defined in `gaphor/templates/blank.gaphor`.

### Expected behavior
URL should point to a file that can be accessed.

### Screenshots
![image](https://github.com/user-attachments/assets/2e775ee1-fc78-4586-a24e-c4c71d9935fd)

### OS
- [x] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.27.0

**Comment by amolenaar** [comment]
Hi @QazCetelic,

It's correct that the XML Namespace does not resolve to a file. That's not the intention of a namespace.

[From Wikipedia](https://en.wikipedia.org/wiki/XML_namespace):

> A namespace name is a [uniform resource identifier](https://en.wikipedia.org/wiki/Uniform_resource_identifier) (URI). Typically, the URI chosen for the namespace of a given XML vocabulary describes a resource under the control of the author or organization defining the vocabulary, such as a [URL](https://en.wikipedia.org/wiki/Uniform_resource_locator) for the author's Web server. However, the namespace specification does not require nor suggest that the namespace URI be used to retrieve information; it is simply treated by an XML parser as a string.
