### ISSUE TITLE
Error when trying to move attribute from one class to another

### ISSUE THREAD

**Issue by peter88213** [gaphor/gaphor#3572]
### Describe the bug
I have a class diagram with two classes "Class 1" and "Class 2". 
"Class 2" has an attribute "attribute 1". 
It is not possible to move this attribute from "Class 2" to "Class 1" by dragging and dropping it inthe model tree.

### To Reproduce
1. Go to the model tree
2. Click on "attribnute 1"
3. Drag/drop it on "Class 1"

Gaphor version:         2.27.0
Operating System:       Windows (11, AMD64)
Display:                GdkWin32Display
Python version:         3.12.6
GTK version:            4.16.2
Adwaita version:        1.6.0
GtkSourceView version:  5.14.0
Cairo version:          1.18.2
Pango version:          1.54.0
PyGObject version:      3.50.0
Pycairo version:        1.27.0

Fehler:

Time since application startup: 0:00:56
|Traceback (most recent call last):
|  File "C:\Program Files\Gaphor\_internal\gaphor\ui\modelbrowser.pyc", line 594, in list_item_drop_drop
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 38, in change_owner
|  File "C:\Program Files\Gaphor\_internal\gaphor\diagram\group.pyc", line 56, in __call__
|  File "C:\Program Files\Gaphor\_internal\generic\multidispatch.pyc", line 134, in __call__
|  File "C:\Program Files\Gaphor\_internal\gaphor\UML\group.pyc", line 11, in container_group
|  File "C:\Program Files\Gaphor\_internal\gaphor\core\modeling\element.pyc", line 241, in __setattr__
|AttributeError: Property Property.package does not exist
└─────────────────────────────╌┄┈

### Expected behavior
"attribute 1" should now belong to "Class 1".

### Screenshots

![grafik](https://github.com/user-attachments/assets/c343e2bd-d90a-47be-98a3-22ba8cd3d45e)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.27.0

### Additional information
Currently I'm trying to refactor a rather large UML model where a lot of classes are split, so attributes and methods have to be moved. 
Because of the error described above, this is about to fail, so I am faced with the choice of rebuilding most of the model or switching to a different modeling tool.

**Comment by amolenaar** [comment]
I haven't tried this before.

**Comment by peter88213** [comment]
That sounds tempting. In fact, I had a look at the requirements for development at the weekend; however, I work under Windows, and setting up GTK (which I am unfortunately not at all familiar with) with Python doesn't seem to be that easy. Besides, I'm still too deep into my own project, which uses tkinter. 

Just as a general feedback: Gaphor is a great endeavor. At work, I had Rational XDE for a long time, and later, when SysML came along, MagicDraw, which is and remains my favorite. Then privately Eclipse Papyrus, which gets the job done, but is quite clunky. Gaphor seemed to me to be a welcome lightweight alternative. For an UML diagram in between, this is definitely the case. For a fully-fledged modeler, the approach is quite recognizable. Keep up the good work!

**Comment by amolenaar** [comment]
No problem.

Thanks for the complement. We try to strike the balance between features and usability. A novice modeler should feel welcome, and an experienced modeler should have enough tools at hand.

**Comment by peter88213** [comment]
It now works fine with version 3.0.0. Thanks for fixing it.
