### ISSUE TITLE
sysml object node cannot be typed

### ISSUE THREAD

**Issue by mikekidner** [gaphor/gaphor#3597]
### Describe the bug
The implementation of the SYSML object node does not allow an element type to be assigned.

### To Reproduce
1. In the SYSML profile, add an object node to a diagram
2. Inspect the properties - try to assign a type 

### Expected behavior
A type drop down in the element properties panel.

### Screenshots
<img width="1136" alt="sysml_distilled_fig6_10" src="https://github.com/user-attachments/assets/5ef6d625-72d1-4d9d-8e63-9c26498a878b">

### OS
- [ ] Linux (Please put in notes the specific distro)
- [x] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.27

**Comment by FranciscoTGouveia** [comment]
Hi @mikekidner! Just to make sure that I'm understanding, are you referring to the fact that an *Object Node* can be typed as `ValueType`, `DataType` or `Block` as stated [here](https://sparxsystems.com/enterprise_architect_user_guide/17.0/modeling_languages/sysml_activity.html) ?

**Comment by mikekidner** [comment]
Yep, you should be able to assign a type to the object node to define what kind of object it is.

**Comment by FranciscoTGouveia** [comment]
Hi @mikekidner! 
What do you think of this solution?

[Screencast from 2024-12-03 13-22-30.webm](https://github.com/user-attachments/assets/bd1e17c0-d7f8-46d7-9e0e-82fb37efdb8a)

**Comment by FranciscoTGouveia** [comment]
Hello @mikekidner! 
Hope you are doing well. Just leaving this comment as a kindly reminder.

On another note, does this seems like a good approach @amolenaar ?

**Comment by amolenaar** [comment]
@FranciscoTGouveia Shouldn't object nodes be typed by any Block/Value types you have defined in your model? (I have to check the docs on this one)

BTW. I notice some tweaks to the UI. I'd like to learn more about those :)

**Comment by amolenaar** [comment]
Related to #3466

**Comment by mikekidner** [comment]
Hi @FranciscoTGouveia , I think @amolenaar is correct that the object node should be typed by one of the blocks defined in the model, for instance "My_Class" or "My_Special_Value_Thing"
