### ISSUE TITLE
Creating a Generalization produces Gtk-CRITICAL messages for gtk_entry_buffer_set_text

### ISSUE THREAD

**Issue by pbrown12303** [gaphor/gaphor#3651]
### Describe the bug
Running Gaphor in the debugger results in the following messages in the DEBUG_CONSOLE when a Generalization is created:
![image](https://github.com/user-attachments/assets/49029dd6-99a7-41b3-bf0b-09dc9ff3cc58)

This seems to have an adverse impact on performance as well

### To Reproduce
1. Start Gaphor in the debugger and choose the default empty model. 
2. Create two classes
3. Create a Generalization relationship between the classes
4. Observe the above indicated messages in the debug console. Note that these messages do NOT appear in the Gaphor console.

### Expected behavior
There should be no Gtk messages when a Generalization is created

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.27.0

**Comment by amolenaar** [comment]
I can trigger the Gtk-critical message when I add a generalization, but it has no negative performance impact on my macbook.

I'll need a bit more time to do some proper debugging.

**Comment by pbrown12303** [comment]
My import produces hundreds of generalizations, each of which produces six messages. Slows down the execution noticeably and really clutters up the console output when I'm looking for other messages!

**Comment by amolenaar** [comment]
I found the source of the `Gtk-CRITICAL` warnings, but I think it's unlikely that that will fix the slow downs you encounter, unless the console is the limiting factor.
