### ISSUE TITLE
Hotkey not consumed on element creation

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3653]
### Describe the bug
The hotkey used to create an element shows up in the element name when editing on creation.

### To Reproduce
1. Create a diagram
2. Add an element using a hotkey (used 'R' for requirements)
3. Start typing a desired name
4. See that 'r' shows up in the element name as the first character. Note, only occurs if you start typing the name on element creation

No error reports.

### Expected behavior
The hotkey used to create the element should have been consumed instead it shows up in the next action.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS (15.1.1)
- [ ] Windows

### Version
Version of Gaphor: 2.27

**Comment by mikekidner** [comment]
Yes, I've noticed this too. All my notes start with K...

**Comment by amolenaar** [comment]
I've seen this on macOS. On Linux it seems to work fine. Therefore I think it's an issue with event handling in GTK.
