### ISSUE TITLE
Properties missing from the model browser

### ISSUE THREAD

**Issue by tompkins-ct** [gaphor/gaphor#3660]
### Describe the bug
Properties from the aggregate relationships are not showing up in the model browser. Only the first item shows up. Parts view on the block shows that the relationships are known in the model.

### To Reproduce
1. Create a block diagram
2. aggregate several blocks
3. make an internal block diagram
4. see that only the first property shows up in the model browser

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.

### Expected behavior
All aggregate items created should show up in the model browser.

### Screenshots
![image](https://github.com/user-attachments/assets/ad7eaa15-994a-4644-a0b2-b9254ef6e9a7)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS 15.1.1
- [ ] Windows

### Version
Version of Gaphor: 2.27

**Comment by amolenaar** [comment]
Do you mean #3557?

I think it works fine in the latest (main) version.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/ecffccb8-15e9-44b4-849a-2020c7f639e8" />

**Comment by tompkins-ct** [comment]
Yep, that's the one. It looks like the fix for that issue, corrected this one as well.
