### ISSUE TITLE
Certain Characters in Object Name Causes Odd UI Behavior

### ISSUE THREAD

**Issue by abjurstrom-torch** [gaphor/gaphor#376]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

If the name of an object (interface or class confirmed, maybe others) contains a "<" character, the tree list of objects shows incorrect/random names.  These names change as the mouse moves around causing refreshes of the names.

### Expected behavior

Name of object would display in object tree list as written.  Name of object would display without changing while being interacted with.

### Minimal reproduction of the problem with instructions

1. Open new file.
1. Create new object of type Interface.
1. Update name of object to `IMyClass<TType>`
1. Move mouse across item in object tree list.

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [X] Windows 10
- [ ] Windows 7

NOTES:

I am using 1.2.0rc2 portable.

It would be really nice to have this syntax supported for some languages that have generic types that are defined in angle brackets.

![graphorUIOddity](https://user-images.githubusercontent.com/62608984/88670936-5018a980-d0ab-11ea-8010-bf581b3c42d6.gif)

**Comment by amolenaar** [comment]
Thanks for the report. I'll try to fix it before 2.0 is released.

**Comment by amolenaar** [comment]
The text is interpreted as markup text (so it can display diagram names in bold, abstract classes in italic, etc.).

This breaks when users type test between `<` and `>`.

The console displays the following error message:

```
(gaphor:693902): Gtk-WARNING **: 20:41:50.554: Failed to set text from markup due to error parsing markup: Unknown tag 'Type' on line 1 char 23
```

**Comment by danyeaw** [comment]
@allcontributors please add @abjurstrom-torch for bug

**Comment by amolenaar** [comment]
@abjurstrom-torch Gaphor 2.0 has been released. It contains a fix for this issue.
