### ISSUE TITLE
Show relationships in tree view

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#386]
### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

### Current behavior

Relations are missing from the tree view. This is also the cause of issue #275.

### Expected behavior

Show relationships in the diagram.

A simple version can *just show* all NamedElements. Note that there are also NamedElements that are not assigned a namespace.

Next, items can be categorized. E.g. relationships can be grouped under a "Relationships" node.

Actions:
 
- [X] update the UML model to UML 2.5.1 layout to ease editing. 
- [ ] Ensure all elements are created with an owner
- [ ] Allow all elements to be dragged on a diagram and provide sensible behavior for relationships.
- [ ] Provide all elements with a default owner and add migrations to the storage module to retrofit existing diagrams.
- [X] Group relationships in a "pseudo-package" in the tree view. for readability.
- [ ] Provide useful names for relationships (e.g. many associations do not have a name) -> can be done by adding clauses to the `format()` generic function.

**Comment by amolenaar** [comment]
I found the tree view is to limited, since it only takes into account Namespace relationships.

To obtain all ownership relationships, we should check for `Element.owner` (opposite is `Element.ownedElement`). This shows all elements and their relationships.

However, these relationships are not always filled in correctly in the UML model (which is now a mix of UML 2.2 and UML 2.5) We should move to UML 2.5, but for that to work all associations should be visible, so they can be migrated.

So I should:

1. Make associations visible, so I can update the relevant parts to UML 2.5.1.
2. Ensure all items have the appropriate ownership relation (e.g. when loading a model, when adding elements)
3. Structure the model in such a way that relationships appear under their own special subnode.

**Comment by amolenaar** [comment]
I'm trying to show all elements in the namespace/tree view. To view the elements the tree view tracks the `Element.owner` - `Element.ownedElement` relationship. 

However, there are a whole bunch of elements (e.g. Action, LifeLine) that an not have a Package as their owner. Now these elements are "dropped" in the root of the tree view. E.g. a `State` Element is supposed to be placed in a `StateMachine`.

I'm looking into what to do with those elements:
1. Hide them? 
    * Would that mean we keep a blacklist/whitelist of items to track?
    * That's a hassle when new modeling languages are added to Gaphor. I like to be able to integrate those without a need to change the tree view.
2. For all elements that can not be owned by a Package, add an association between the element and a Package?
    * Pro: all elements can be showed in a package.
    * Pro: elements can be reordered within the tree view.
    * Pro: no changes required to the current tree view implementation. 
    * Con: Placement/Connector logic need to be addressed, though.
    * Con: everything is tied to Package, to large extend for presentation purposes. Package is more of a core modeling entity then.
    * Derived unions should be open for extension, so other modeling languages can also define ownership relations
3. Collect all elements without an owner under the Diagram they're presented in?
    * Pro: UML model remains in tact. Stay true to UML syntax.
    * Pro: I think most of this logic can be pushed in the model.
    * Con: Tree view needs to deal with unowned elements.
    * Con: will users understand this approach?
    * Con: how to handle copy/pasted elements?

I think 2. and 3. are valid options. Not sure which is the best option for now.

@danyeaw Any thoughts?

**Comment by danyeaw** [comment]
@amolenaar Is there an option 4, which is for us to make a list of all the elements that don't have a package as their owner and then one by one implement an owning element for them? For example, for Actions, I am use to the Activity owning it: 
![image](https://user-images.githubusercontent.com/10014976/94219420-cd4a7a00-feb4-11ea-9738-679a51477710.png)
I'm not sure we have the concept of activity being the defining element and an action is the usage in Gaphor currently.

For lifelines, I am use to the interaction owning them:
![image](https://user-images.githubusercontent.com/10014976/94219551-17cbf680-feb5-11ea-8c70-30a0fdf66e60.png)

A state could be nested under a Region, which is nested under a State Machine:
![image](https://user-images.githubusercontent.com/10014976/94219788-9de83d00-feb5-11ea-848c-e03e42efaaee.png)

**Comment by amolenaar** [comment]
I think you just mentioned all three cases where ownership is not in place. :) This was just the input I was looking for.

I think we should work towards option 4 indeed. 

However, to keep the bar low, someone can also draw a diagram without wrapping it's Actions in an Activity, I guess. If you need to know you have to create a State Machine only to create a little state diagram, then working with Gaphor becomes more difficult IMHO. I think we should not put such restructions on our users.

What would be easier is that Gaphor creates a State Machine implicitly when someone adds a state to a diagram. Same for Interaction and Activity. Then ownership is handled nicely. That may be "good enough" for most uses. Sure, we end up with State Machines and Activities that do not have a visual representation in a diagram, but Gaphor allows the same for packages, which are then purely used for grouping. 

* Pro: no changes to the (UML) model. We remain formal, for the people that value that.
* Pro: tree view remains as simple (complicated :wink:) as it is
* Pro: we do not need to implement a diagram item for StateMachine/Activity right away.
* Pro: copy/paste in diagrams, and dnd in tree view will *just work*
* Con: can't think of any downsides right now
* Placement tools need to be changed for those elements to handle namespacing correctly.
* Question: do we want to create a migration path for existing models? Or are we fine with dropping all items in the root of the tree view?

NB. Why are the "Activity", "Interaction" and "State Machine" mentioned twice in the screen shots?

**Comment by amolenaar** [comment]
I assume we'll add Lifeline `C` to the `NewInteraction` interaction, since that's the one currently in this package. 

![image](https://user-images.githubusercontent.com/96249/94287726-f02d6a80-ff56-11ea-81c8-b8f8f12dc80d.png)

If there was no Interaction in this package, Gaphor would create a new one.

**Comment by danyeaw** [comment]
@amolenaar I really like this updated proposal, creating implicit objects will keep things simple while allowing us to expose all of the elements in the tree view.

> NB. Why are the "Activity", "Interaction" and "State Machine" mentioned twice in the screen shots?

In this tool, the diagrams have a type. So if you create a State Machine Diagram, it automatically creates the State Machine element, and nests the diagram under it with the same name. The tan box icons are the SysML diagram icons.

> I assume we'll add Lifeline C to the NewInteraction interaction, since that's the one currently in this package.

I think that makes sense. That or we just have to constrain lifelines so that they can't leave the interaction on the diagram once created.

**Comment by amolenaar** [comment]
One last thing I missed:

- [ ] Show newly created items in tree view. E.g. for a State, open the StateMachine and Region to visualize it.
