### ISSUE TITLE
Support a way to resolve (git) merge conflicts with Gaphor

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#388]
### I'm submitting a...
- [ ] Bug report  
- [X] Feature request
- [ ] Documentation issue or request

### Current behavior

If a merge conflicts arises because two people edited a model file at the same time, it's hard to resolve. There are two options:

1. Interpret the XML and merge the right parts :crossed_fingers: 
2. Pick one version and re-apply the changes the other person made (or remembers)

### Expected behavior

We want to be able to resolve merge conflicts in a user friendly way.

We need to find out what a user friendly way is. via CLI or via the GUI? How to present "conflicts"? How to resolve those?

Should Gaphor be able to read a file containing a merge conflict?

NB. In the repo (tag 1.0.0) is a primitive compare tool (`utils/compare.py`). It may be useful for inspiration.

More refinement required, I suppose.

**Comment by amolenaar** [comment]
One way to go about this is to load the before and after model and generate a list of changes in terms of `ElementEvent`'s -- create element, update association, etc. The events can be grouped logically, to give some insight in the changes that have to be applied. E.g. a presentation element should be attached to a diagram and probably needs a subject.

**Comment by amolenaar** [comment]
I have an idea on how to pull this off.

1. A model with merge conflicts can be loaded in both it's _current_ and _incoming_ form. The _current_ model will be loaded in the session, and the _incoming_ model will be side-loaded for comparison.
2. The models are compared, this results in a list of removed, added, and changed objects.
3. Those changes are recorded in the _current_ model in a `ChangeSet` object.
4. Gaphor can show the changes in an ordered fashion in the right side pane. something like:
    a. Created diagrams (with elements as children)
    b. Modifications to diagrams
    c. Modifications to model elements
5. The user can apply changes by checking them. The changes will be marked in the change set (which is part of the model, so you can undo the changes).
6. The user can mark the change set as resolved, which will remove the change set from the model.

This way we can add meaning to the individual changes and group them. The _smarts_ are in grouping related changes. When you create a diagram, the items on the diagram are created too, including their model elements.

Technically, multiple change sets can exist, although I think we need only one.

@danyeaw What do you think?

**Comment by danyeaw** [comment]
That sounds like a great plan! How would the change sets be represented? Visually? XML? Some translation into text?

**Comment by amolenaar** [comment]
I think it'll be a tree view of sorts. You should at least be able to select and unselect changes. Maybe it should replace the left side bar (tree + toolbox).

Many changes will be dependant, I expect. You create an element and create it's attributes and operations in one go. So the representation should be "natural", in that it follows the normal way you interact with Gaphor (create attributes, but not associations).

One tricky thing will be presentations with different subjects.

**Comment by danyeaw** [comment]
Closed by #2112
