### ISSUE TITLE
Undo breaks model consistency

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#408]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

When you "undo" an action, there is a possibility diagram items (ending in `-Item`) end up in the main model. They should only be part of a diagram, though.

### Expected behavior

Undo should resolve to a previous state.

### Minimal reproduction of the problem with instructions

Create a class.
Undo, redo, save the model, load the model.

**Comment by danyeaw** [comment]
@all-contributors please add @@kellenmoura for bug

**Comment by danyeaw** [comment]
@all-contributors please add @kellenmoura for bug
