### ISSUE TITLE
Improve Activity Partition / Swimlane Support

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#426]
The current swimlane implementation needs an update:
- You create a partition
- You then have to create another partition inside the partition to name the partition
- There is no support for allocating a Block or Class to the swimlane

**Describe the solution you'd like**
Opinions that I think will simplify the design:
- A single partition isn't usable for anything. If there isn't a partition on the canvas, creating a partition should create two.
- Nesting partitions inside other partitions isn't needed for any practical reasons.
- There is no reason to have two different sets of swimlanes on the same diagram

Goals:
- No right click menu needed. We don't have a lot of right click options as it is, and I think adding right click to partitions wouldn't be very discoverable.

Proposed design:
- Creating a partition will create two swimlanes, both without a label, but with an inside line for where the allocation goes
- Using the partition tool from then on will allow you to snap another partition to the left or right of the current ones
- Dragging from the top of the partition will allow you to reorder partitions
- To make a name appear at the top of the swimlane, drag a block or class to the swimlane. I think the whole swimlane can be a drop zone
- There will be handles at the 4 outside corners of the overall group of swimlanes
- Resizing of the width happens by dragging the line between the swimlanes

**Comment by danyeaw** [comment]
One thing I thought of, how will a user delete / remove a swimlane that is already created? Should we allow them to drag it out of the group and then it will be selected with handles to allow it to be deleted?

**Comment by amolenaar** [comment]
> To make a name appear at the top of the swimlane, drag a block or class to the swimlane. I think the whole swimlane can be a drop zone

What do you mean by this? Can I not create arbitrary names instead? Maybe just double click on a swimlane?

> Resizing of the width happens by dragging the line between the swimlanes

Maybe in a first version, just divide the space equally?

**Comment by danyeaw** [comment]
Although giving the swimlanes a name is fine, the value of a swimlane is to connect the behavior in the activities to the structure in the model. The primary use case in my mind is to drag a block or class on to the swimlane to make this allocation.

Yup, dividing the space would be a good start.

**Comment by amolenaar** [comment]
@danyeaw I was just thinking: we can also allow the user to set the number of swimlanes via a field in the property editor.

Just a thought...

**Comment by danyeaw** [comment]
With the draft version, we can now create the number of swimlanes with the property editor. It automatically creates a UML.ActivityPartition element for each partition that is displayed. One issue I have run in to is that the names of objects are normally tied to the Item. Since we only have a single PartitionItem, how should we display the name?

Should we create a new SubPartitionItem? Should we write text to the cairo Context and just not use the normal Box shape?

**Comment by amolenaar** [comment]
looks nice. I really like how simple it is compared to the previous solution. :+1: 

I think the right side handles should move to the right, so they're located at the end of the partition.

We can generate a couple of "name" fields in the editor pane, so every swimlane will have its own input field. It should be not that hard to add an inline-editor as well.

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/99210131-00add480-2793-11eb-890a-05f151d03574.png)
I have updated the PartitionItem to be the size of all of the partitions, which locates the handles to the right.

Next up I'll look at updating the name fields in the property editor and add an inline-editor.

**Comment by danyeaw** [comment]
In order to make the names of a variable number of partitions editable, I am planning on using a CellRenderer like this: 
![image](https://user-images.githubusercontent.com/10014976/99341442-e0941900-2857-11eb-950b-201ef70fb211.png)

**Comment by danyeaw** [comment]
Next up:

- [ ] Allow Activities and ActivityPartitions to be deleted from the namespace treeview.
- [ ] Allow blocks / classes to be dragged on a swimlane to allocate behavior (and name the partition)

**Comment by amolenaar** [comment]
> Allow Activities and ActivityPartitions to be deleted from the namespace treeview.

@danyeaw Do we need this? you can remove the activities and partitions from the diagram. Wouldn't that make more sense?

**Comment by danyeaw** [comment]
@amolenaar I think that part is done. If you delete a diagram containing the Activity, it removes everything nested under it including the swimlanes. The Activity can then be removed by right click on it.

**Comment by amolenaar** [comment]
@danyeaw Then , the only item left is:

> Allow blocks / classes to be dragged on a swimlane to allocate behavior (and name the partition)

How should this work, model-wise? The idea is to set the type for the partition, right?

![image](https://user-images.githubusercontent.com/96249/145714674-277bcae1-cf4b-4416-8d4a-2bcc6e349bc1.png)


A quick solution would be to drag a block on a partition, and the name of the partition is set to the name of the block.

If we do it according to spec the `ActivityPartition.represents` should point to the element it represents (`Element` in the spec, but we probably limit it to `NamedElement`). I'm only wondering how to unset it again.

**Comment by danyeaw** [comment]
@amolenaar Yes, it allocates the activities in the swimlane to the block that the swimlane represents. This is really important because it creates linkage between the behavior expressed in the activity diagram and the structure that is providing that behavior.

In the diagram you posted above, the partitions have a name like pcu, and an allocated type. Some tools require you to select what allocation mode to use before creating the swimlanes - Definition or Usage. The definition elements are Activity and Block, and usage elements are Action and Part Property. I think we should probably keep things simple for now and assume only a definition mode.

What if dragging a block on to the swimlane adds text to the header to the right of the ":", then you can delete the allocation by deleting that text?

**Comment by amolenaar** [comment]
> What if dragging a block on to the swimlane adds text to the header to the right of the ":", then you can delete the allocation by deleting that text?

Dragging is a good idea anyhow. Changing it by deleting the text would require some specials (magic). Also, for a user it's not clear you can link a swimlane to a block. We would have to inform them somehow.

Or we create sections in the property editor, one for each swimlane where your can set the name, and its type from a dropdown. 
I think that will make it more explicit that such a relation can be created.

**Comment by danyeaw** [comment]
Ya I like that idea!
