### ISSUE TITLE
Package Gaphor for Debian

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#432]
As part of a wider epic to get Gaphor on the Elementary OS App Store, Gaphor needs to be packaged for Debian.

**Describe the solution you'd like**
Include packaging for Debian as part of Gaphor using the [Elementary OS Packaging Guide](https://docs.elementary.io/develop/writing-apps/our-first-app/packaging).

**Comment by Pratyush-Saxena** [comment]
@danyeaw I would like to ...take up this issue ....

**Comment by danyeaw** [comment]
@Pratyush-Saxena Thanks we would be glad to have your help! If you have any questions please feel free to post here or at https://gitter.im/Gaphor/Lobby.

**Comment by Pratyush-Saxena** [comment]
@danyeaw...it would be great if u give some more descripted way of doing this...

**Comment by danyeaw** [comment]
@Pratyush-Saxena It looks like you have some experience with GitHub/Git and creating Pull Requests, which is great. I haven't packaged an app for Debian myself, but I would start with the packaging guide above, and read the other information it links to as well. If you have more questions about a specific step, we can chat about it on Gitter.

**Comment by Pratyush-Saxena** [comment]
@danyeaw i have found a best way to make debian package for gaphor ...pls head hover [this](https://stackoverflow.com/a/7112197) link......but coz it needed setup.py file ..and your project doesn't contain it.

**Comment by danyeaw** [comment]
@Pratyush-Saxena yes, setup.py is the old way, we are using the modern pyproject.toml. That library isn't going to work.

**Comment by Pratyush-Saxena** [comment]
> @Pratyush-Saxena yes, setup.py is the old way, we are using the modern pyproject.toml. That library isn't going to work.

so why dont we first create setup.py file.....i guess then we can easly create debian package ...

**Comment by danyeaw** [comment]
@Pratyush-Saxena Thanks for looking in to this!

Since AppCenter will soon be supporting Flatpak versions in the AppCenter Dashboard, I think we should hold off on this. I am going to go ahead and close the issue.
