### ISSUE TITLE
Automatically Save State and Files

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#433]
This is part of an overall epic to get Gaphor on the Elementary OS App Store. Elementary OS does not use minimize buttons. The close button is supposed to quickly shutdown the app, and then when you reopen it, the app should go exactly back to where you before you closed it.

**Describe the solution you'd like**
1. Need to autosave files as they are being edited. If a file is not yet saved, we may need to autosave it to a temp location.
2. Need to save all program state, referencing the [State Saving](https://docs.elementary.io/develop/apis/state-saving) Elementary OS guide. They recommend using GLib.Settings, and this would include settings like having the side panel open or closed.

**Comment by amolenaar** [comment]
#### Auto-save files

How does that work for an editor?
We can not save the file on every change. We can track changes, though. Like we do for the undo manager. If we can append those to some sort of log, we should be able to replay those on start up for the already loaded models. When the model is saved (like with an editor) the log is purged. What to do when the model was edited outside of Gaphor (e.g. when shared via Git)?

#### Program state

We have the _Properties_ service for this. It does not save to _GSettings_, but to `~/.config/gaphor/resources`. 
This behavior is incomplete, though: it only stores the setting of one window (the last one edited). How to deal with this? Should we store settings based on file name? The Elementary guide does not mention this.

**Comment by amolenaar** [comment]
Would it be sufficient to just save unsaved files to a special (cache) place on shutdown, where they can be retrieved when the application loads.

I think we should store the program state per model (file name). The Properties service can listen on a FileLoaded event and then load the right set of properties from `~/.config/gaphor/resources.xyz`, where xyz is a (absolute) file name or a hash. I think a hash will work better. The properties file itself can contain file read file name for reference. The properties file should also contain a reference to the auto-saved model file.

Alternatively we can also store the properties as part of the model file. Kinda like we do with the StyleSheet. It would require a new class, but it can reuse the Properties service. This may be inconvenient, though, when model files are shared.

Maybe we need one more overall setting (file) that tells us all properties files to load on startup.

BTW. The advantage of using our own files is that we do not need to install a GSettings schema somewhere.

**Comment by amolenaar** [comment]
@danyeaw What should the behavior be when you quit Gaphor?

Currently it asks if the model needs saving. Should we just save the current model in a (temporary) place and quit, without asking questions? To retrieve it when Gaphor starts up again?

Should we save (override) the model anyhow?

Should we also persist the undo/redo stacks?

---

> I think we should store the program state per model (file name)...

Alternatively we can generate an id for a model and use that as key to load preferences for that model. That way one can move a model and the settings remain the same. The id can be used to reference user specific settings. Question is: when should we create a new id? When a model is saved to a new file?

**Comment by amolenaar** [comment]
@danyeaw should we do anything with this issue, or can it be closed?

**Comment by danyeaw** [comment]
While I think it would be great to get gaphor in the elementary OS AppCenter, I think there are other higher priority things to work on.
