### ISSUE TITLE
When I open a file an already opened model file, show the window with already opened model

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#482]
**Is your feature request related to a problem? Please describe.**

When i open a model, and open the same model again, I have two windows, showing the same model.

**Describe the solution you'd like**

When I open an already opened model, present the window with the already opened model.

**Comment by danyeaw** [comment]
@amolenaar What if a user wants to have two diagrams open side by side? I don't think our current tabs scheme allows that, which I think is fine. However, there might be some use cases where users want to have the model open twice.

**Comment by amolenaar** [comment]
You want to keep it as is, for now?

**Comment by danyeaw** [comment]
I would be open to changing the behavior, I think we just need to keep in mind this use case as well.

**Comment by danyeaw** [comment]
Closed by #711.
