### ISSUE TITLE
Installation with pip fails

### ISSUE THREAD

**Issue by MikHulk** [gaphor/gaphor#494]
Hi,

I am trying to install graphor in a virtualenv with pip 20.2.3 and python 3.7, on debian 10.

But I get an error about this package:

```
ERROR: Could not find a version that satisfies the requirement graphor (from versions: none)
ERROR: No matching distribution found for graphor
```
I followed instruction given on the website
https://gaphor.org/download.html#linux

**Comment by amolenaar** [comment]
Hi,

Your error says it's unable to install g*r*aphor. That should be 'gaphor', without the 'r' 🙂.

**Comment by MikHulk** [comment]
oh no...

sorry...

**Comment by MikHulk** [comment]
I though graphoe like a graph... my bad...

**Comment by amolenaar** [comment]
It would've made a nice name indeed :).

I suppose it works for you now?

**Comment by MikHulk** [comment]
Hi,

Yes It works perfectly, Thank you.

I am looking for a tool like this for a while and came across it by chance when reading documentation about PyGobject.

I have looked into the code I am really impressed by its quality. If I have time I think I am going to try to write some extensions. I like the way Gaphor is implemented.
