### ISSUE TITLE
New app icon?

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#506]
The current app icon doesn't really follow the HIG, would you be interested in help with a new one?

Here's a first experiment:

![image](https://user-images.githubusercontent.com/1908896/97812369-21e5cf80-1c81-11eb-9889-03e91927f3e2.png)

**Comment by amolenaar** [comment]
Hi @bertob,

It would be great if you can help us with an even more awesome logo :). The current logo draws it's inspiration from the UML logo (https://uml.org) and the old GTK+ logo (the cube). I basically used the UML colors and the GTK logo shape ;).

UML is well known for its class diagrams.

Gaphor has an extensive data model, so it does more than tools like Visio (or Dia ;) ), which only provide visuals. 

Is the website (https://gaphor.org) of any help?

**Comment by danyeaw** [comment]
@bertob Great idea and we would of course be glad to have your expertise and help!
As @amolenaar said, often users pickup Gaphor and think it is a simple drawing tool and we want to make sure the logo doesn't give that impression. How could we visualize that you use the tool to create diagrams, but also that there is a data model underneath? I think that is a tricky thing to put in a logo. Do you have any ideas?

**Comment by bertob** [comment]
Hmm gotcha, I'll try some alternatives that look less like a generic diagram app.

**Comment by bertob** [comment]
New, less generic attempt:

![image](https://user-images.githubusercontent.com/1908896/100282834-a0761a00-2f6c-11eb-9b03-bd12e1e5bc8b.png)

Do you think it looks like UML?

**Comment by danyeaw** [comment]
@bertob I really like this! I think it looks like a great compromise of showing the modeling capabilies, but still looking good visually.

**Comment by bertob** [comment]
@danyeaw  cool, I made a few small tweaks and opened an MR :)

**Comment by ZanderBrown** [comment]
Some nice art here (as always with @bertob), one day I may even give in and adopt one the proposals for Dia - but not yet :-)

(sorry for noise/spam)

**Comment by danyeaw** [comment]
Closed by #524
