### ISSUE TITLE
gaphor and gaphas links are broken at cairo webpage

### ISSUE THREAD

**Issue by wrobell** [gaphor/gaphor#525]
Please see https://cairographics.org/examples/.

**Comment by amolenaar** [comment]
Hi @wrobell,

Thanks for pointing this out. Those links are really, _really_ old.

**Comment by amolenaar** [comment]
PR has been submitted. Let's wait and see.

https://gitlab.freedesktop.org/cairo/cairo-www/-/merge_requests/1

**Comment by danyeaw** [comment]
@wrobell Thanks for submitting this. With @amolenaar submitting the PR, I think we can close this issue here since that is all we can do on our side.
