### ISSUE TITLE
Create a Release Checklist

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#531]
Although we have automated most things, there is still a few steps to create a release including updating the flatpak and the website.

I propose we create a release checklist in the docs or a `RELEASE_CHECKLIST.md` in the root of the project.

**Comment by amolenaar** [comment]
Sounds like a plan. 

Note that we can also trigger the flatpak build automatically when Gaphor has been released. But even then, it would be good to document it ;)

**Comment by danyeaw** [comment]
Closed by #538
