### ISSUE TITLE
Appimages for Gaphor

### ISSUE THREAD

**Issue by freddii** [gaphor/gaphor#534]
It would be nice to have an Appimage for Gaphor.

**Comment by amolenaar** [comment]
Hi @freddii, welcome!

AppImage looks like a nice addition indeed. Especially for OS'es that do not ship Flatpak by default.

Just our of curiosity: what would make you prefer an AppImage over a Flatpak installation?

Do you know of any Gtk/Python applications we can look at to make one?

Can you to set up an AppImage build for Gaphor?

**Comment by freddii** [comment]
I prefer an AppImage over a Flatpak, cause it only a simple file you have to run.
Sadly i don't know how to make an Appimage for Gaphor.

**Comment by danyeaw** [comment]
I know that [Briefcase](https://github.com/beeware/briefcase) supports creating AppImages and now supports using a `pyproject.toml`. I am not sure if this would be to much overhead in order to just support an AppImage if we weren't using it for other packaging, but it might be something to look at more.

**Comment by danyeaw** [comment]
@all-contributors please add @freddii for ideas

**Comment by danyeaw** [comment]
@freddii is this something you would like to help contribute to?

**Comment by freddii** [comment]
I don't know how to add an appimge,but i think @probonopd is common with it.

**Comment by probonopd** [comment]
Check you https://github.com/niess/python-appimage#for-applications-developers

**Comment by danyeaw** [comment]
#581 is setup to automatically create AppImages for each CI run and then release them when a new version of Gaphor is released like our other packages. Currently it is building it on Ubuntu 20.04, so the AppImages will only be compatible for users using fairly new versions of Linux distributions.

In the future we could spin up a CentOS7 docker container and build the AppImages on that. This will improve compatability. [MyPaint](https://github.com/mypaint/mypaint-appimage) and [nuxeo-drive](https://github.com/nuxeo/nuxeo-drive/tree/master/tools/linux) could be used as an example, they are both building Python AppImages in a CentOS7 container. I recommend we work on this is a separate PR.

**Comment by probonopd** [comment]
> Currently it is building it on Ubuntu 20.04, so the AppImages will only be compatible for users using fairly new versions of Linux distributions.

If you are using Ubuntu, why not the oldest still-supported release, which is Xenial at this time? CentOS 7 sounds like a good choice, too.

**Comment by danyeaw** [comment]
@probonopd That is a good idea on using Xenial. I think GitHub Actions has a Ubuntu 16.04 environment, and that might prevent us from having to deal with a Docker container. Thanks!

**Comment by danyeaw** [comment]
I played with this more this afternoon. We are using features in GTK 3.24, which neither Xenial (GTK 3.18) or Bionic (GTK 3.22) have. So it looks like we would have to build using Focal (20.04) or later. That or somehow build GTK ourselves on an older distribution, but I'm not sure I want to take that on.

**Comment by probonopd** [comment]
> We are using features in GTK 3.24, which neither Xenial (GTK 3.18) or Bionic (GTK 3.22) have.

Always surprises me why application developers would want dependencies imn their applications that cannot reasonably expected to be available on all still-supported Linux distributions. Oh well.

Tools like https://github.com/AppImageCrafters/appimage-builder `appimagetool -s deploy` from go-appimage can produce AppImages that bundle everything including glibc and Gtk, but come with their own tradeoffs.

**Comment by probonopd** [comment]
Thanks for looking into this @danyeaw. Can the AppImage be downloaded somewhere?

https://gaphor.readthedocs.io/en/latest/linux.html#create-an-appimage-package only talks about _making_, not about _downloading_ an AppImage.

**Comment by amolenaar** [comment]
@probonopd  The AppImage is built and stored as build artifact. You should be able to find those in the "build" jobs. E.g. https://github.com/gaphor/gaphor/actions/runs/492571734.
