### ISSUE TITLE
Add PR and Issue Templates

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#54]
It helps and guides users to feel comfortable creating issues and pull requests if a template exists. There is a description of this feature on the GitHub blog:
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

If you do a search there is also some nice issue and pull request templates that we can start from. I would :heart: someone to create these for the project.

**Comment by tonytheleg** [comment]
If you are still looking, I wouldn't mind assisting with this. Any specific items you definitely want on there?

**Comment by danyeaw** [comment]
@tonytheleg That would be awesome 👍. Let's see what you come up with on a format and we'll go from there.

**Comment by tonytheleg** [comment]
Great, thank you! I'll see if I can get it knocked out tomorrow

**Comment by tonytheleg** [comment]
Issue templated PR submitted
https://github.com/gaphor/gaphor/pull/56
