### ISSUE TITLE
Replace ez_setup and update setup.py and setup.cfg

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#55]
ez_setup is now no longer part of the official packaging process using setuptools. It would be :sparkles:  to have someone remove this and make sure setup.py is up to date using the latest packaging guide:
https://packaging.python.org/guides/distributing-packages-using-setuptools/

You may also be able to reference the [Cookiecutter Templates](https://cookiecutter.readthedocs.io/en/latest/readme.html) to get a copy of a recent Python packaging format.

**Comment by berkaybarlas** [comment]
I can try it :D

**Comment by esantoro** [comment]
Hi, can I work on this ? Can you please assign this issue to me ?

**Comment by danyeaw** [comment]
@esantoro We would :sparkling_heart: your help on this as well!

**Comment by Pac23** [comment]
@danyeaw has this been completed ? otherwise i'll take this

**Comment by danyeaw** [comment]
@Pac23 It has not been completed, and we would really appreciate your help!

**Comment by Pac23** [comment]
@danyeaw :+1:

**Comment by Pac23** [comment]
@danyeaw this is py 2 right ? i am done with the file setup etc jsut need to bdsit_Wheel it.

**Comment by danyeaw** [comment]
Closed by commit db55ccd.
