### ISSUE TITLE
Copy Paste Issues (Xorg: AttributeError, Wayland: Non-Functional)

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#555]
**Describe the bug**
In Linux with Xorg, copy/paste is throwing an AttributeError.
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/actiongroup.py", line 142, in _action_activate
    method()
  File "/home/dan/Projects/gaphor/gaphor/services/copyservice.py", line 106, in paste_action
    view.select_item(item)
AttributeError: 'GtkView' object has no attribute 'select_item'
```
In Linux with Wayland, copy/paste is not working at all.

**To Reproduce**
1. Create a Class
2. Ctrl+C the Class
3. Ctrl+V

**Expected behavior**
Copy / Paste works.

**Screenshots**

**OS**
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows

NOTES:
Ubuntu 20.10 with GNOME DE
**Version**
Version of Gaphor:

**Additional context**

**Comment by danyeaw** [comment]
Thanks, it is working great now! :100:

**Comment by amolenaar** [comment]
I fixed most of the code, but overlooked this one :sweat_smile:
