### ISSUE TITLE
Spruce up our README

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#60]
### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [X] Documentation issue or request

We would :heart: someone to craft a new README. We need a better description of what Gaphor is and is not, a nice gif showing it in action, and details about how to install it on the different platforms.

A good starting point may be to get the sections setup first, and then we can get the information added. https://github.com/matiassingers/awesome-readme has many resources and examples showing great READMEs for other projects.

**Comment by esantoro** [comment]
Hello, can I work on this? Can you assign this issue to me ?

**Comment by danyeaw** [comment]
@esantoro Are you still interested in working on this? This is up for grabs if someone else wants to help out with sprucing up our README.
