### ISSUE TITLE
Association Multiplicity Doesn't Work for End Names with Spaces 

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#601]
**Describe the bug**
Multiplicity doesn't work if there is a space in the name of an association end. Also an extra + is added in front of the name on the diagram.

**To Reproduce**
1. Create two classes
2. Connect an association between them
3. Add a name with a space in it like `target Event` and add a multiplicity like `[1]`

**Expected behavior**
The multiplicity is recognized and the 1 is moved to the multiplicity box

**Screenshots**
With a space:
![Screenshot from 2021-01-12 20-06-20](https://user-images.githubusercontent.com/10014976/104393155-bf773e00-5511-11eb-8e23-5b77c3915bea.png)

Without a space:
![Screenshot from 2021-01-12 20-08-53](https://user-images.githubusercontent.com/10014976/104393310-2694f280-5512-11eb-93c2-e1e62a4d8302.png)

**Version**
Version of Gaphor: master

**Comment by amolenaar** [comment]
Is there a reason you want a space in the name?

**Comment by danyeaw** [comment]
@amolenaar The RAAML spec has some names with spaces in them. I thought about that as well, but I don't think the UML spec says that names can't have spaces in them. If we think it is wrong, I could try to submit an issue to the spec author.

**Comment by amolenaar** [comment]
I think it's a good thing to make the models more accessible. Sometimes a model is ment for humans, not machines :smiley:.
