### ISSUE TITLE
Support FTA in RAAML

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#606]
**Is your feature request related to a problem? Please describe.**
Gaphor currently has a Safety model based on a draft of the Safety and Reliability Profile. The OMG standard is now about to be released and has been renamed to the Risk Analysis & Assessment Modeling Language (RAAML).

I would like to add initial support for RAAML. I heard from Kyle Post who has been leading the RAAML language that there is a SAE working grouping to start exploring use of it by automotive companies. They are starting with use of Fault Tree Analysis (FTA) since it is one of the most commonly used parts of the language. Not all members of the working group have access to MagicDraw or other commercial tools, so Gaphor could help fill in that gap and be one of the first tools to support RAAML.

**Describe the solution you'd like**
Implement FTA with RAAML. Initial implementation will be qualitative only, not quantitative. To accomplish this we'll use the same general process as we used with SysML, it should be faster this time:

- [x] Update the current `Safety.gaphor` to the final version of the RAAML spec
- [ ] Update / add a data model parser for RAAML
- [ ] Add FTA icons for the different types of events (basic, external, undeveloped, etc) and gates (AND, OR, XOR, etc)
- [ ] Create a toolbar for FTA
- [ ] Create property pages

**Comment by danyeaw** [comment]
This idea originally came from @Blippost, thanks Kyle!

@all-contributors please add @Blippost for ideas

**Comment by amolenaar** [comment]
@danyeaw How can I help out with the FTA implementation?

**Comment by danyeaw** [comment]
@amolenaar I almost finished cleaning up duplicate relationships caused mostly by #648. I am still getting a lot of errors when building the RAAML model.

For each section of RAAML, there is a Profile and a Library. The Profile contains the Stereotypes, for example the definition of the <<AND>> stereotype for an AND gate. The Library contains a definition then that an AND class with the <<AND>> stereotype is a type of Gate.

The current profile coder creates a Class object from both a class and a stereotype, so we end up having duplicate classes with the same names. I could use some help thinking through what to do about this - this is the current road block I am running up against.

Another question I have for @blippost, is there some reason that the Gates need to have the <<Block>> stereotype applied to them instead of being a plain Class? It ends up making our profile coder need to depend on SysML instead of UML, and I was trying to understand if it is really needed. Most of the profile is straight UML definitions except for a few areas like the Gates.

**Comment by danyeaw** [comment]
I created a minimal FTA profile to focus on getting just the FTA portions to work. I renamed the objects in Library to be called def, for example `AND_Def`. I can feed this back to the RAAML team to ask them to make names unique. Another option is we could name our created classes with the full namespace that includes the Packages an object is in.

We these changes, it is profile coding with no errors. Tomorrow I'll start working on plumbing the coded profile to the toolbars and create the diagram shapes.

**Comment by blippost** [comment]
The elements need to be <<block>> versus <<class>> because they own SysML constraints to allow the calculation of the probabilities using SysML parametrics.  That is also why the libraries are important as value properties have to be owned by blocks.

**Comment by amolenaar** [comment]
For the current RAAML profile I see some options:

1. Make sure all element names are unique - this is in line with what we've done so far
2. Allow for namespaces in the context of a modeling language - this will be a lot of work (e.g. how to deal with imports from other packages in the same model. How to avoid cycles? Will that be up to the model builder?)
3. Split the model in it's profile and library components - we still need to address the problem with global element name uniqueness.

I think the best option for now is 1. Although the change we end up with elements in different modeling languages having the same name is increasing. I wonder how much longer we can keep this up. E.i. when to we need to "namespace" elements to their modeling language (like when saving and loading models)?

I can maybe help out with a component that "renders" SVG to Cairo. I think it will be beneficial for elements like Actors, and stereotypes in general.

**Comment by danyeaw** [comment]
> The elements need to be `<<block>>` versus `<<class>>` because they own SysML constraints to allow the calculation of the probabilities using SysML parametrics. That is also why the libraries are important as value properties have to be owned by blocks.

Thanks! I actually thought of that after I asked the question, that makes sense. I forgot about it because we don't yet support value types or parametrics. :see_no_evil:

**Comment by danyeaw** [comment]
> I can maybe help out with a component that "renders" SVG to Cairo. I think it will be beneficial for elements like Actors, and stereotypes in general.

That sounds great! I pushed the original SVGs that I extracted from the RAAML XMI. I think these will be more suitable for the diagram items instead of the toolbar icons that I created.

**Comment by amolenaar** [comment]
> That sounds great! I pushed the original SVGs that I extracted from the RAAML XMI. I think these will be more suitable for the diagram items instead of the toolbar icons that I created.

Sweet. I'll have a look.

**Comment by danyeaw** [comment]
Closed by #664
