### ISSUE TITLE
Update from LGPL 2.0 to 2.1 (or Apache)

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#61]
GitHub supports displaying the license on the [repository overview](https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/). It only supports licenses from [choose a license](https://www.choosealicense.com), which includes the LGPL 2.1, but not 2.0.

The main changes are rewording Library to Lesser, and adding another option for using a shared library mechanism:
    b) Use a suitable shared library mechanism for linking with the
    Library.  A suitable mechanism is one that (1) uses at run time a
    copy of the library already present on the user's computer system,
    rather than copying library functions into the executable, and (2)
    will operate properly with a modified version of the library, if
    the user installs one, as long as the modified version is
    interface-compatible with the version that the work was made with.

Any concerns with us migrating to the LGPL 2.1?

**Comment by amolenaar** [comment]
None at all. Even changing it to an Apache license would be fine.

**Comment by aejh** [comment]
Fine with me.

**Comment by wrobell** [comment]
Fine with me. I would even push to LGPL 3.0.

**Comment by ygormutti** [comment]
Fine with me, although I don't feel like I need to be asked, because I don't remember contributing with Gaphor, unfortunately :)

**Comment by encolpe** [comment]
With my single commit I'm agree with the upgrade to LGPL 3.0 or Apache with a little preference to Apache.

**Comment by melisdogan** [comment]
Go right ahead :)

**Comment by danyeaw** [comment]
@adamboduch, @jmallach, and @egroeper: could I please get your concurrence as well?

**Comment by jmallach** [comment]
I am happy for you to move to the lgpl 2.1. You can add (or any later version) if you like, too. Thank you.

**Comment by danyeaw** [comment]
@adamboduch and @egroeper, still looking for a response please :heart:

**Comment by amolenaar** [comment]
I'd say let's switch this code to Apache and be done with it :)
