### ISSUE TITLE
Containment Relationship Middle Handle Creates Black Polygon

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#621]
**Describe the bug**
Moving the middle handle of a containment relationship causes a black polygon to be drawn.

**To Reproduce**
1. Create two Classes
2. Create a Containment Relationship (solid diamond) between them
3. Select and move the handle in the middle of the line
4. See black polygon instead of line moved

**Expected behavior**
Line moves based on middle handle movement

**Screenshots**
![image](https://user-images.githubusercontent.com/10014976/105793783-bfd2f880-5f57-11eb-8a49-a7bd797d87d7.png)

**OS**
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: 2.2.0

**Additional context**

**Comment by amolenaar** [comment]
I think this bug is related to the highlighting introduced recently.
