### ISSUE TITLE
Use default stylesheet on screenshot

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#626]
The current appstream screenshot use a downstream stylesheet rather than the platform default (Adwaita). Since this app is in Circle now it'd be good to fix this.

**Comment by amolenaar** [comment]
I updated the screenshot link in the `appdata.xml` file to https://gaphor.org/images/screenshot.png.

**Comment by danyeaw** [comment]
@amolenaar The [freedesktop screenshot metadata](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) says that it needs to be 16:9.

**Comment by amolenaar** [comment]
Seriously? Okay. I'll attend to it.

**Comment by amolenaar** [comment]
Hmmm.. There are many apps that do not adhere to the 16:9.

**Comment by bertob** [comment]
FWIW I think those guidelines are in need of a refresh, I wouldn't worry too much about this.

**Comment by danyeaw** [comment]
Ok, fair enough, thanks for updating the screenshot @amolenaar!

**Comment by amolenaar** [comment]
I did some updates. The screenshots are now exactly 16:9. Also, I added the screenshots to our flatpak repo, so they're not accidentally removed by some website change.

**Comment by danyeaw** [comment]
Thanks @amolenaar!
