### ISSUE TITLE
Highlight (drop) and gray-out (disabled) style via CSS

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#632]
We have CSS, but we also have custom code that deals with highlighting items and grayed-out elements.

This styling should be defined via CSS as well.

We already have a `drop` pseudo selector. 
We need one for grayed-out/disabled element, still.

- [x] Set grayed out style (`:disabled`) via style sheet
- [x] Create a separate system style sheet
- [ ] Remove diagram fallback style
- [x] Remove `highlight-color` style property
- [x] Render multiple style sheets (maybe add user style sheet as well?)
- [x] Allow setting line-width for line-like elements
- [ ] Maybe we need an extra property (`opacity`) to make disabling items easier to describe.

**Comment by danyeaw** [comment]
Closed by #638
