### ISSUE TITLE
Requirement element doesn't have ID or Text - macOS

### ISSUE THREAD

**Issue by samirodj** [gaphor/gaphor#634]
**Describe the bug**
Requirement element doesn't have ID or text as options to create. 

**Expected behavior**
According to the tutorial video, should have a text field and ID field below Name (as defined by UML and SysML standards too)

**Screenshots**
<img width="436" alt="Screen Shot 2021-02-02 at 10 11 26 PM" src="https://user-images.githubusercontent.com/36422980/106693019-9c392f00-65a3-11eb-9321-a253858c6724.png">

**OS**
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: latest version as of Feb 2

**Comment by amolenaar** [comment]
Hi @samirodj,

Thanks for posting this bug report.

Indeed the option to edit text or an identifier seems to be gone. I'll have a look and see what's going on.

**Comment by amolenaar** [comment]
I checked the app, and the ui files for the requirements id and text are missing:

```
gaphor.ui.elementeditor ERROR Could not construct property page for RequirementPropertyPage
Traceback (most recent call last):
  File "gaphor/ui/elementeditor.py", line 155, in create_pages
  File "gaphor/SysML/propertypages.py", line 33, in construct
  File "gaphor/SysML/propertypages.py", line 17, in new_builder
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/Applications/Gaphor.app/Contents/MacOS/gaphor/SysML/propertypages.glade”: No such file or directory (4)
```

**Comment by amolenaar** [comment]
@samirodj You can download and install the build from https://github.com/gaphor/gaphor/actions/runs/542943511.

It contains the fix.

**Comment by danyeaw** [comment]
@all-contributorsbot please add @samirodj for bug

**Comment by danyeaw** [comment]
@all-contributors please add @samirodj for bug
