### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by Btibert3** [gaphor/gaphor#64]
### I'm submitting a...
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

Failed installation when trying to create a new environment with conda

```
conda create -n gaphor python=2.7
source activate gaphor 
pip install gaphor
```

### Expected behavior

Expect software to install.  

### Minimal reproduction of the problem with instructions

Get error for missing module `six`.  After `pip install six` and then `pip install gaphor`, get the error below.

```
Failed to build pycairo PyGObject
```

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [x] MacOS
- [ ] Windows 10
- [ ] Windows 7

**Comment by danyeaw** [comment]
Thanks so much for your contribution to the project by submitting an issue ♥️

Have you checked out the macOS install instructions? https://github.com/gaphor/gaphor/blob/master/INSTALL-MACOS.md

**Comment by Btibert3** [comment]
I didn't see those, let me poke around.  Ty.
