### ISSUE TITLE
Allow Expansion & Collapse of Namespace Tree View Using Keyboard

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#641]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to expand and collapse the namespace treeview using the left and right arrow keys. I suspect why this isn't there by default is because the Gtk TreeView can have multiple columns.

**Describe the solution you'd like**
Left and Right keys expand and collapse the namespace treeview.

**Describe alternatives you've considered**
It works to use the mouse, I'm not aware of another keyboard shortcut that allows this.

**Comment by amolenaar** [comment]
GTK uses `-` and `+` to collapse/expand tree nodes.

This is probably because a tree view can contain multiple columns. It's more intuitive to use left and right cursor keys indeed.


https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1020756

**Comment by danyeaw** [comment]
Thanks for the explanation, I didn't know about using those key bindings. Do you think we should try to add the arrow keys as a key binding as well?

**Comment by amolenaar** [comment]
I think the arrow keys are more intuitive, so yes we should 🙂

**Comment by amolenaar** [comment]
@danyeaw You'll love this solution! :smile: I did not know it was possible!
