### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by TiemenSch** [gaphor/gaphor#642]
**Is your feature request related to a problem? Please describe.**
I've tried to look for some UI-sizing related settings, but so far I haven't found any from the GUI/installed version. I work on a 4K monitor and it appears that the UI has fixed absolute scaling. This causes some trouble since most buttons get too small for comfort.

**Describe the solution you'd like**
Some form UI scaling, much like Windows does across my desktop experience. Whether this is predefined like "small/default/large" or a custom percentage depends on how easy/intuitive it might be to implement.

**Describe alternatives you've considered**
Reducing my resolution when working with Gaphor, but that's quite a tedious UX.

**Comment by amolenaar** [comment]
Hi @TiemenSch,

What system are you working on? Normally it's the desktop environment that provides scaling settings. Do you have the same problem with other GTK+ based applications, such as GIMP and Inkscape?

I work on a 4k monitor myself, using GNOME on Linux, and scaling works fine for me. I also run Gaphor on my Mac on a 4k screen with 200% scaling.

**Comment by TiemenSch** [comment]
Hi @amolenaar,

Thanks for reaching out!

I'm on Windows 10. I didn't think about adjusting my Windows UI scaling, but that in fact works and scales Gaphor, too.

However, that probably means that I disagree with Gaphor's basic scale w.r.t. my Windows UI's scale. In general, my Windows UI's navigation on 150% is quite substantially larger than Gaphor's buttons and text.

Is there any workaround possible? I tried fiddling with the Display Compatibility options in the Windows shortcut to Gaphor, but so far to no avail.

**Comment by amolenaar** [comment]
Hi @TiemenSch,

I started windows to check. For me it looks okay, but it's small indeed, on 150%.

![image](https://user-images.githubusercontent.com/96249/107685744-a2669400-6ca4-11eb-949f-d41e8707e60e.png)

But there's a solution to scale Gaphor.

Add the following variable to your environment variables (I tried with user env vars):

    GDK_SCALE=2

(GDK, not GTK).

**Comment by TiemenSch** [comment]
As I'm the first to report this, I think that's a pretty fitting workaround. Works like a charm!

Thanks for reaching out!

**Comment by amolenaar** [comment]
@TiemenSch No problem! Glad to be of help.

Happy modeling!

**Comment by danyeaw** [comment]
@all-contributors please add @TiemenSch for bug

**Comment by danyeaw** [comment]
Should we add this to the docs? On gaphor.org? @TiemenSch would you be interested in contributing by submitting a pull request to https://github.com/gaphor/gaphor.github.io

**Comment by TiemenSch** [comment]
Sure, where would you think this fits best? On the readthedocs or the gaphor.org website?

**Comment by danyeaw** [comment]
@TiemenSch Although we haven't got too many docs yet on gaphor.org, our vision is that it would be the documentation for users, while readthedocs will be the documentation for developers. I think this would fit better on the users side of things. Maybe we should link it to the Tutorials -> Problem Solving section?
