### ISSUE TITLE
Allow Reuse of Relationships

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#648]
We recently added many of the relationships to the namespace tree view, it would be nice to be able to reuse the relationships now.

For example, when updating the RAAML profile, there are multiple diagrams with the same elements and relationships on them. This currently causes multiple relationships in the model instead of reusing the ones that already exist.

![image](https://user-images.githubusercontent.com/10014976/107857337-f0da7680-6dfb-11eb-9b87-b0c942ee69ca.png)

**Describe the solution you'd like**
Drag a relationship from the namespace and it automatically connects up in the diagram. In the future we may consider wanting to allow users to right click on an element and display relationships that already exist with the element.

**Describe alternatives you've considered**
Currently recreating the same relationships multiple times.

**Additional context**

**Comment by amolenaar** [comment]
Relates to #687.

**Comment by amolenaar** [comment]
When you create a simple relation (e.g. Generalization), the relation is being reused. This does not apply to associations and connectors currently.

It should at least be possible to DnD a relation from the tree view onto a diagram. If both ends are present on the diagram, the relationship is created.

What to do if an relationship can not be fully recreated, cause the elements at one or both of the ends are not present? I think it should not put an item on the diagram then. Instead it should notify the user that a relation can only be added to the diagram if both ends are on the diagram already. Something like `Cannot create relationship on the diagram: connected elements are missing`.

**Comment by danyeaw** [comment]
> * Then the association will show in the diagram and is connected to both ends (classes)
>     * When any/both ends are not present in the diagram?
>     * When it's dragged in a diagram that already has a presentation for this Association?

I think I need to explore more how this is done with other tools. I think normally I have the tool display existing relations instead of finding and dragging relationships from the tree view.

> When an Association is presented in 2 or more diagrams, what should happen in the model

Any changes on one diagram need to propagate through the model. If a relationship did exist on another diagram, and you break the relationship, I think we should remove the hanging relationships on the diagram.

**Comment by sz332** [comment]
My way of understanding is the following. We have a model and we have a diagram. A diagram provides a constrained view of a model. It is an absolutely valid case to ask the diagram to show an assocation between model elements displayed in the diagram. Now the question is how to do that.

One solution that a good modeler tool provides to use the tree view: drag an assocation into the diagram. This I used in another tools and is a very handy solution especially when working with large models (we work with 3000+ diagrams, 600k model elements kind of large models). 

I think personally that this feature can be implemented in iterations:

When the user drags an association into a diagram

V1: if both end exists, add the association to the model, otherwise, do nothing
V2: V1 + if not exists, display an error message
V3: V1 + display a dialog where the missing ends can be added
V4: have a property to automatically add the missing ends if enabled

Corner case: we need to think about what if someone wants to display the same model element on a diagram twice by whatever reason. It is not that uncommon when for example modeling a REST interface, and you want to display both the request and response, and they are reusing a data transfer object for both request and response.

**Comment by sz332** [comment]
@amolenaar i would move the "When an Association is presented in 2 or more diagrams, what should happen in the model"
part into a separate ticket, because I feel it presents a totally different usecase. What do you think>=<

**Comment by amolenaar** [comment]
> @amolenaar i would move the "When an Association is presented in 2 or more diagrams, what should happen in the model" part into a separate ticket, because I feel it presents a totally different usecase. What do you think?

This issue has been resolved by copying relationships (on model level), instead of changing them.

**Comment by amolenaar** [comment]
# Relationships, the missing concept

Relationships are presented in diagrams by `LinePresentation` instances.

There is a relation between a line end and a relation on model level.
This can be seen in many connectors, in it's most basic form:

```python
self.line.subject = self.relationship_or_new(
    UML.Generalization, UML.Generalization.specific, UML.Generalization.general
)
```

Relationships are used in the PBT test to determine if items are connected:

```python
@check_relation.register
def _(relation: diagramitems.GeneralizationItem, head, tail):
    subject = relation.subject
    assert subject
    assert subject.specific is head.subject
    assert subject.general is tail.subject
```

Relationships also need to be available when dropping relation elements from the tree view on a diagram

```python
@drop.register
def _(element: Generalization, diagram, x, y):
    # NB. what is head and tail depends on the presentation!
    head_end, tail_end = find_ends(element)
    head = find_in_diagram(head_end, diagram)
    tail = find_in_diagram(tail_end, diagram)
    if head and tail:
        ... # create item and connect
```

There is a theme emerging here. Somehow we need to be able to retrieve the elements that a relation connects.
For starters, these relations can be determined on model level.
We need to be able to determine the relation without a presentation being present.

Relation is both read and written by `Connector`.
`Connector` connects a model element both to its peers and to a presentation.

`Connector` finds existing relations (model) based on two presentations.
`drop` works the opposite way: we know the model element and now need the presentations to connect to

We can let the Presentation (diagram item) tell which relation it represents, including a way to read/write the relationship ends.

`LinePresentation`:
* Tells about the relations from `line.subject`
* What is head and tail depends on the presentation
* We should be able to determine, without having a presentation instance (works on class level?)
* Can move logic (what end is head/tail) from connector to line presentation
* (con) It's not a presentation concept per se

`Connector` can expose this information:
* It's about connections
* (con) It would extend the `Connector` interface
* (con) Connectors are queried based on `Presentation`; in case of drop we need to know without having a `Presentation` instance yet

A separate construct:
* Easy to define on model level
* We can forget to implement
* Can be used as a "second" layer, to be used in `Connector` to connect on model level
* (con) May look quite similar to other concepts
* (con) What is head and tail depends on how the Presentation is structured

I think adding it to the presentation makes sense. Some ideas:

```python
@represents(
    UML.Generalization,
    head=UML.Generalization.specific,
    tail=UML.Generalization.general)
class GeneralizationItem(LinePresentation):
    
    def __init__(self, diagram: Diagram, id: str = None):
        super().__init__(diagram, id, style={"dash-style": ()})
```


```python
@represents(
    UML.Association,
    head=(UML.Association.memberEnd, UML.Property.type), # like this,
    tail="memberEnd.type")                               # or this: use ElementDispatcher parser (needs modeling_language!)
    UML.Association.memberEnd / "type"                   # or this
    UML.Association.memberEnd[UML.Property] / "type"     # create property paths from elements
)
class AssociationItem(LinePresentation[UML.Association], Named):
    
    def __init__(self, diagram: Diagram, id: str = None):
        super().__init__(diagram, id)
```

**Comment by amolenaar** [comment]
@danyeaw @sz332 I think that with #1421 the basics for  implemented (V2).

This mechanism, the `drop()` single dispatch function, allows us to customize the behavior where needed.
