### ISSUE TITLE
Allow Use of Stereotypes Inherited From Other Stereotypes

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#672]
**Is your feature request related to a problem? Please describe.**
While creating the FTA profile for RAAML, I realized that we don't currently support making use of a stereotype that is connected to another stereotype using a Generalization.

![image](https://user-images.githubusercontent.com/10014976/109421005-7be27180-79a3-11eb-8bc7-a01e17378db0.png)

In the example above:

1. Create a metaclass
2. Create an Extension of the metaclass and connect it to a stereotype, here called `TopStereotype`
3. Connect a `NewStereotype` to it using the Generalization relationship
4. Create a new class
5. Try to apply `NewStereotype` to the class

**Describe the solution you'd like**
Automatically make the sub-stereotype accessible as a stereotype to be used as well. It is also should have `Class` as its metaclass.

**Describe alternatives you've considered**

1. Remove the generalization and flatten it out so that each stereotype is an extension of the metaclass. This is what I am currently doing in the FTA profile, but it removes the context that the `NewStereotype` is a type of `TopStereotype`
2. Keep the generalization and explicitly make the stereotype an extension of the metaclass as well. This causes issues with Method Resolution Order when trying to autocode.

**Comment by amolenaar** [comment]
@danyeaw Is this still valid with the new coder? (I do not really understand the issue, I think :see_no_evil: )

**Comment by danyeaw** [comment]
I don't think this is fixed, we would need to have our logic that looks for stereotypes in the model check down the chain from the metaclass to stereotypes and then to lower level stereotypes through the generalization relationship.

**Comment by amolenaar** [comment]
Ah, I see. So in the case above, for a Class both `TopStereotype` and `NewStereotype` should show in the stereotype panel.

Additionally, all attributes defined on `TopStereotype` should also be displayed for `NewStereotype`.

**Comment by danyeaw** [comment]
Exactly!

**Comment by amolenaar** [comment]
Fixed by #1630.
