### ISSUE TITLE
Nest Diagrams Under Elements

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#676]
I received a somewhat anonymous emailing thanking us for our work with Gaphor and SysML, and suggesting an enhancement. I thought it would be worth discussing.

**Is your feature request related to a problem? Please describe.**

One suggestion for SysML : it would be good to put diagrams under  their associated element. It would avoid floating diagrams here and there. Since "each diagram represents a model element" and an element can have many diagrams depending on the viewpoint or else.

**Comment by amolenaar** [comment]
Hmm.. How does he/she envision this? I mean: if you right-click a popup menu appears with all related diagrams.

A diagram does not represent a model element, it is a model element. A special one. Should this change?

So far the tree view reflects the ownership relationships.

What I think we should add, is that one should be able to click through from one diagram to another.

**Comment by danyeaw** [comment]
I'm not as familiar with what UML says, but Annex A of the SysML Spec provides an overview of the diagram frame:

![image](https://user-images.githubusercontent.com/10014976/111927863-74852400-8a88-11eb-902c-2eb4227cc121.png)

The `modelElementName` is associated with the model element that the diagram is associated with. Then the diagram gets nested under the element.

- Activity diagram - activity
- Block definition diagram - block, package, or constraint block
- Internal block diagram - block or constraint block
- Package diagram - package or model
- Parametric diagram - block or constraint block
- Requirement diagram - package or requirement
- Sequence diagram - interaction
- State machine diagram - state machine
- Use case diagram - package

So for example, an Internal Block Diagram is the white box view of what is inside of a Block. The diagram is nested under the Block that it is associated with.

If we were going to support this, I think we would need to implement all of the diagram types instead of the single type we are currently using.

**Comment by amolenaar** [comment]
I think I see what you mean. It would be nice to click through on an element. E.g. on a package, which will open the diagram located inside this package.

To put it differently: currently we  only implement nesting for packages, but it would be nice if we can do that for every element.
Internal Block Diagram is one example. State Diagrams have a similar use (where a state can contain a nested state machine).

Not sure if we need diagram types, though.

**Comment by amolenaar** [comment]
By allowing all elements to (technically allow diagrams, the core model will simpler, since we do no longer have to lend `NamedElement` and `PackageableElement` from the UML model.

**Comment by danyeaw** [comment]
Does that mean we would allow any element to have a diagram?
