### ISSUE TITLE
Drop EditableText shape

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#677]
**Is your feature request related to a problem? Please describe.**
Each time when an element is selected, a small grey lines is drawn around the name of the element. This is done by the `EdtableText` shape. You can double-click anywhere on the object to edit the name though. This makes the text boundry line redundant.

Furthermore, `EditableText` is used to place the edit popup. It looks more logical to place the edit popup above the element. 

**Describe the solution you'd like**

I think EditableText is no longer needed. Replace all it's uses by Text and remove EditableText.

**Additional context**
Current:
![image](https://user-images.githubusercontent.com/96249/110038248-c6ffda00-7d3f-11eb-8093-d32b8ef5b4ed.png)

Proposed:
![image](https://user-images.githubusercontent.com/96249/110038488-19d99180-7d40-11eb-9ef9-293124a961a0.png)

**Comment by danyeaw** [comment]
Closed by #685
