### ISSUE TITLE
Allow users to provide an SVG icon for a stereotype

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#689]
## Is your feature request related to a problem?

In UML a stereotype can be represented by an icon. A classical example is the Actor, which is a classifier depicted as a straw man.

To convey an idea, sometimes it's better to use a picture instead of an abstract classifier.

## Describe the solution you'd like

When a user defines a stereotype, he/she should be able to add an icon. This icon can be used to represent a stereotyped elements.

 

## Describe alternatives you've considered

It's in the UML specs.

## Additional context

I suppose the icon should be part of the model. The icon should also adhere to the styling, as defined by the model (color, fill).

**Comment by amolenaar** [comment]
Let's reopen this when there's a need from the community.

**Comment by mvinca-bandwidth** [comment]
<jest> I guess I don't count as part of the community </jest> 😢

**Comment by mvinca-bandwidth** [comment]
😄 I knew that question was coming! Probably don't have the bandwidth for at least a few months, unfortunately.
