### ISSUE TITLE
Add containment link for the requirement diagram

### ISSUE THREAD

**Issue by freezed-or-frozen** [gaphor/gaphor#690]
**Is your feature request related to a problem? Please describe.**
I cannot find how to add a containment link between two requirements block in the requirement diagram
![Capture d’écran de 2021-03-14 10-06-16](https://user-images.githubusercontent.com/28558919/111063064-01d6e000-84ad-11eb-8a10-9e4a6f5e574c.png)

**Describe the solution you'd like**
Add a containment link after the "verifiy" link
![Capture d’écran de 2021-03-14 10-05-38](https://user-images.githubusercontent.com/28558919/111063070-0bf8de80-84ad-11eb-96bb-60226c0027d0.png)

Gaphor looks very promising. Congratulations for your work and thank you !

**Comment by danyeaw** [comment]
@all-contributors please add @freezed-or-frozen for bug

**Comment by danyeaw** [comment]
@freezed-or-frozen Thanks for the report, you are right - it looks like we are missing the containment relationship! :+1: 

This would be pretty straightforward to add I think and we are always looking for new contributors. Is this something you would be interested in helping with?

**Comment by danyeaw** [comment]
@freezed-or-frozen In #707 we have completed support for this and we should be able to release version 2.4 soon:

![image](https://user-images.githubusercontent.com/10014976/113615105-6d7e1a00-9621-11eb-866f-bd31e238a871.png)

**Comment by freezed-or-frozen** [comment]
Thank you very much for your work, it will be very useful in my school.

**Comment by danyeaw** [comment]
@freezed-or-frozen We would be very interested in how you are using Gaphor. Are you taking a class on SysML?

**Comment by freezed-or-frozen** [comment]
Yes, I use Gaphor when working on project with students. SysML requirements diagram helps to see what it is needed by the client. I use it to in UML class but just as a drawing tool. When dealing with generation/reverse code, I switch to StarUML.

**Comment by danyeaw** [comment]
@freezed-or-frozen Thanks! Are these students taking a course at a university? I am just curious on how it is being used so that we can tailor things to the users.

**Comment by freezed-or-frozen** [comment]
We used it with "A levels" and "BTEC Higher National Diploma" students.

**Comment by danyeaw** [comment]
Thanks you for sharing!
