### ISSUE TITLE
Bad selection visualisation after scroll

### ISSUE THREAD

**Issue by liferooter** [gaphor/gaphor#698]
**Describe the bug**
Gaphor draws selection without regard to the state of scrolling.

**To Reproduce**
1. Open Gaphor
2. Scroll
3. Try to select area
4. See that selection is drawn without regard to the state of scrolling

**Expected behavior**
Selection is drawn with current selection state in mind

**Screenshots**
![изображение](https://user-images.githubusercontent.com/54807745/111788794-88d2f080-88d1-11eb-847a-745f3f572594.png)

**OS**
- [x] Linux (Fedora 33)
- [ ] MacOS - **not tested**
- [ ] Windows - **not tested**

NOTES:

**Version**
Version of Gaphor: 2.2.2
Installed from: Flathub

**Additional context**
Nothing to say more

**Comment by danyeaw** [comment]
@liferooter Thanks for the bug report! :heart: I can reproduce this in 2.2.2 as well, but not in the latest master development version. We should we releasing version 2.3.0 with the fix very soon. :+1:

**Comment by danyeaw** [comment]
@dependabot please add @liferooter for bug

**Comment by danyeaw** [comment]
@all-contributors please add @liferooter for bug
