### ISSUE TITLE
Support UML Data Types and SysML Value Types

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#701]
**Is your feature request related to a problem? Please describe.**
In order to implement the rest of RAAML, for example with the ISO26262 and FMEA portions, we'll need to be able to create ValueTypes. A SysML ValueType defines values that may be used within a model. SysML value types are based on UML data types. A data type is a classifier whose instances are identified only by their value.

A data type may contain attributes and operations to support the modeling of structured data types.

A primitive type is a data type that represents atomic data values (values having no parts or structure). A primitive data type may have precise semantics and operations defined outside of UML, for example, mathematically.

Standard UML primitive types include:

- Boolean
- Integer
- UnlimitedNatural
- String
- Real

UML also contains an enumeration data type whose values are enumerated in the model as user-defined enumeration literals.

A SysML ValueType is a stereotype of UML DataType that can be used to type structural elements by their values, where these types can also include information about associated quantity kinds (via a QuantityKind tagged value) and units of measure (via a Unit tagged value). For example:

- Blocks: Value Properties, Operation parameters & return values, atomic Flow Ports
- Associations/Connectors: ItemFlows, Item properties
- Activities: ObjectNodes, Pins, Activity Parameters
- ConstraintBlocks: Constraint parameters (we don't have constraint blocks implemented yet).

**Describe the solution you'd like**
Implement support for UML data types and SysML value types.

**Describe alternatives you've considered**
Avoid adding new features that depend on using value types.

**Additional context**
An example of how a value type is used is in the creation of a Hazard Analysis situation (Hazardous Event). The situation is classified based on the severity, exposure, and controllability in order to calculate the ASIL. Value types are used for these 3 category values and for the ASIL:
![image](https://user-images.githubusercontent.com/10014976/111916513-b5157b00-8a51-11eb-8956-fa264ef7242e.png)

**Comment by amolenaar** [comment]
@danyeaw In the diagram above, the nested blocks for "hazard", "scenario", "systemLevelEffect", etc. are the ValueType's?

**Comment by danyeaw** [comment]
@amolenaar They are the Severity, Exposure, and Controllability in the values compartment.

**Comment by danyeaw** [comment]
UML Data Types, along with primatives and enumerations:

![image](https://user-images.githubusercontent.com/10014976/113491927-4d741c80-94a2-11eb-9afe-39a97886c316.png)

**Comment by danyeaw** [comment]
SysML Value Types:

![image](https://user-images.githubusercontent.com/10014976/113496641-b8851980-94c9-11eb-8f6e-40c8381c5a42.png)

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/114802332-89916200-9d6b-11eb-8004-291a4e88f0ae.png)
![image](https://user-images.githubusercontent.com/10014976/114802973-a24e4780-9d6c-11eb-8f17-2e11cd84d8a4.png)

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/115475143-02316c00-a20d-11eb-8237-b85080198fc7.png)
Initial support is now merged. I think we can close this issue once we implement the values compartment for a Block since that will unlock a lot of functionality for RAAML.

**Comment by amolenaar** [comment]
> I think we can close this issue once we implement the values compartment for a Block since that will unlock a lot of functionality for RAAML.

@danyeaw The "values compartment" will contain all linked `ValueType`'s? Or also `DataType`'s?

**Comment by danyeaw** [comment]
@amolenaar I looked in to this and with other tools it doesn't look like it is possible for a Block to have a property based on a DataType, so the values compartment should only have Value Properties.
