### ISSUE TITLE
Diagram disappear after horizontal scroll and then vertical scroll (scroll bar)

### ISSUE THREAD

**Issue by TomBous** [gaphor/gaphor#708]
**Describe the bug**

Diagram disappeared after horizontal scroll and then vertical scroll (using scroll bar)

**To Reproduce**

- 1) Open existing diagram of classes
- 2) Scroll left or right, using scroll bar (not the touch-pad)
- 3) The view does not scroll
- 4) Scroll up or down, using the scroll bar
- 5) The diagram disappear

**Expected behavior**

The view of the diagram move, and the diagram doesn't disappear.

**OS**
Ubuntu 20.04

NOTES:

**Version**
Gaphor 2.3 -> Flatpak version
I don't know if this bug affect previous version.

**Additional context**
Also, composition association doesn't show rhombus until i reapply them.
[diagram-classes.zip](https://github.com/gaphor/gaphor/files/6210696/diagram-classes.zip)

Thank you for this great peace of software !

**Comment by amolenaar** [comment]
Hi @TomBous,

Thanks for the feedback. I can reproduce the problem. I'll dive into it.

**Comment by danyeaw** [comment]
@all-contributors please add @TomBous for bug

**Comment by amolenaar** [comment]
I think https://github.com/gaphor/gaphas/pull/240 resolves this issue.

**Comment by danyeaw** [comment]
@TomBous Does this deserve a separate issue?

>  Also, composition association doesn't show rhombus until i reapply them.

**Comment by TomBous** [comment]
Wow that was a fast fix ! I didn't expect that. Thank you all.
I can confirm that the bug is fixed in last version.

> @TomBous Does this deserve a separate issue?

Totally, it should have it's own issue. I've just tested again, to confirm the issue. I'll create the issue right away.

Thank you !
