### ISSUE TITLE
Save settings per model

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#710]
## Is your feature request related to a problem?

Currently there's one settings file: `~/.local/gaphor/resources`. Whichever window has been changed last, those settings are saved.

## Describe the solution you'd like

I would like to save settings per model. So that when I reopen a model, it is shown the way I left it.

This includes:
* the selected profile/modeling language
* the diagrams opened (and their order)
* the toolbox elements that are collapsed and expanded
* width and height of the panes in the window

I think, so far, the properties do not contain any settings that are application wide. I think all settings can be categorized as user settings.

Currently, a resources file looks something like this:

```python
{'modeling-language': 'UML',
 'reset-tool-after-create': True,
 'show-tips': False,
 'toolbox-collapsed': {0: False,
                       1: False,
                       2: False,
                       3: False,
                       4: False,
                       5: False,
                       6: False,
                       7: False},
 'ui.namespace-height': 390,
 'ui.namespace-width': 239,
 'ui.window-size': (1117, 612)}
```

## Additional context

These settings are personal and per model. Therefore I think it makes no sense to add the settings to the model itself.
So where to save those? `~/.cache/gaphor`? `~/.config/gaphor`? Alongside the model (e.g. `.<modelname>.gaphorsettings`)?

This issue is related to #433.

**Comment by danyeaw** [comment]
@amolenaar This is a good idea. The [freedesktop spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says that:
$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored.
$XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored.

My vote is this is more like cache information and not settings per se.

**Comment by amolenaar** [comment]
@danyeaw I'm also in favour of the cache location. Use a hash of the full file name, then?

**Comment by danyeaw** [comment]
@amolenaar sounds good!

**Comment by danyeaw** [comment]
@amolenaar Are we ready to close this with #717 merged?
