### ISSUE TITLE
Classes associations doesn't render head/tail decoration (arrow/rhombus)

### ISSUE THREAD

**Issue by TomBous** [gaphor/gaphor#712]
**Describe the bug**
When opening file, Composite Association/Shared Association/simple Association, loose their Head/Tail decoration (arrow/rhombus).
It seems to be a rendering bug as the configuration right panel displays the correct information.

**To Reproduce**
1. Make a diagram with 2 classes linked by 3 associations : composite association, shared association and a simple association.
2. Add "navigable" to the head of the simple association to display an arrow, and save the document.
3. Re-open the document.
4. The decoration of the 3 associations have disappeared.

**Expected behavior**
I expect the associations to keep their head and tail decorations when re-opening a document.

**OS**
Ubuntu 20.04

NOTES:

**Version**
Gaphor **2.3.1** -> Flatpak version

**Comment by amolenaar** [comment]
Thanks @TomBous for spotting this.

This is a regression introduced in 2.3.

**Comment by amolenaar** [comment]
@TomBous It's fixed and 2.3.2 has been released by @danyeaw :)

**Comment by TomBous** [comment]
@amolenaar  Awesome ! I confirm that the bug is fixed in last release.

If i find other bugs I'll let you know :) 

But for the moment it's just a pleasure to use Gaphor, simple, intuitive,  beautifully designed, and much faster to use than Draw.io for example.

Thank you to all the team for such a great piece of software !
