### ISSUE TITLE
First Element Added to a Diagram Gets Stuck

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#745]
**Describe the bug**
When you add the first element to the diagram it gets placed lower than where it was dropped, and it gets stuck from moving up.

**To Reproduce**
1. Select a Box in the toolbar
2. Drop it to the top of the diagram, it will show up lower in the middle
3. Try to drag the box up to the top of the diagram, it will move up some but then prevented from moving up anymore.

If you add another element to the diagram then it unsticks the first element.

**Expected behavior**
The first element drops to the diagram on the correct drop zone. 

**OS**
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: master

**Additional context**

**Comment by amolenaar** [comment]
@danyeaw I can't seem to reproduce this behaviour.

**Comment by danyeaw** [comment]
@amolenaar Dang, I am able to in Tumbleweed with both Wayland and xorg.

**Comment by amolenaar** [comment]
@danyeaw Is this still an issue?

**Comment by danyeaw** [comment]
Yes, for me it is.

Jun 11, 2021 3:24:20 PM Arjan Molenaar ***@***.***>:

**Comment by amolenaar** [comment]
Does this also occur when you run Gaphor from Flatpak?

**Comment by danyeaw** [comment]
@amolenaar Yes with both Flatpak and the latest master version.

**Comment by danyeaw** [comment]
Issue seems to now be resolved.
