### ISSUE TITLE
Add Support for STPA from RAAML

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#748]
**Is your feature request related to a problem? Please describe.**
I would like to model System Theoretic Process Analysis (STPA) using the RAAML language. The [STPA Handbook](https://psas.scripts.mit.edu/home/get_file.php?name=STPA_handbook.pdf) and the RAAML normative examples would be the primary references.

**Describe the solution you'd like**
Add support for STPA. Since we don't currently support tables, we should be able to model it using diagrams instead. Here are the different diagrams we should be able to create based on the RAAML Examples:

![image](https://user-images.githubusercontent.com/10014976/115162575-653acb80-a072-11eb-95d1-e64139a0296a.png)
![image](https://user-images.githubusercontent.com/10014976/115162595-797ec880-a072-11eb-9901-cd67a9f138a1.png)
![image](https://user-images.githubusercontent.com/10014976/115162604-8996a800-a072-11eb-9100-550a010a0dde.png)
![image](https://user-images.githubusercontent.com/10014976/115162623-9ca97800-a072-11eb-84ed-949dae7b6fd0.png)
![image](https://user-images.githubusercontent.com/10014976/115162645-afbc4800-a072-11eb-837f-4f2da99af059.png)
![image](https://user-images.githubusercontent.com/10014976/115162658-c5ca0880-a072-11eb-8bcc-8aab61fa5186.png)
![image](https://user-images.githubusercontent.com/10014976/115162678-dbd7c900-a072-11eb-8155-e60585f5509a.png)
![image](https://user-images.githubusercontent.com/10014976/115162714-fdd14b80-a072-11eb-8450-677c0d4f8ddb.png)

**Describe alternatives you've considered**
No support for STPA.

**Additional context**

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/118382172-b29e5000-b5c0-11eb-9e4c-c05eb3f1246b.png)
First diagram in Gaphor.

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/118408988-43733b00-b656-11eb-9ad8-51337302919f.png)

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/119199570-52dcf480-ba59-11eb-931d-deab065f9a50.png)

**Comment by danyeaw** [comment]
![image](https://user-images.githubusercontent.com/10014976/119282449-b1e06c00-bc07-11eb-8fb5-371c83ae792e.png)

**Comment by danyeaw** [comment]
Closed by #781

**Comment by charlesfradley** [comment]
The online technical documentation does not cover the STPA feature, and only covers RAAML 1.0.

**Comment by danyeaw** [comment]
Hi @charlesfradley, great to hear from you and thanks for the feedback. I think you are referring to this section, right? https://gaphor.readthedocs.io/en/latest/models/raaml.html

Are you looking for technical documentation on which parts of the RAAML profile have been implemented, or are you looking for more of a how to that provides a tutorial for using STPA in Gaphor? Our user manual type documentation is lacking at the moment, but we would be glad to have some assistance making it better.
