### ISSUE TITLE
Association direction arrow is not updated

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#754]
**Describe the bug**

When moving a (connected) association, the direction arrow (if shown) is not updated.

Also the reversing button does not seem to work.

**To Reproduce**
1. Create 2 classes
2. Connect the classes with an Association
3. Toggle the option "Show direction" on
4. Move one of the classes and see the error

**Expected behavior**

Direction arrow should stay aligned with the association.

**Screenshots**

![image](https://user-images.githubusercontent.com/96249/115295170-bd003200-a159-11eb-9d35-326f82c5dfd8.png)

**OS**
- [X] Linux (Please put in notes the specific distro)
- [ ] macOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: master

**Additional context**

**Comment by danyeaw** [comment]
@amolenaar I can reproduce this one.
