### ISSUE TITLE
Flaky Test Tagged Value Upgrade Test

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#76]
When running the StorageTestCase, the test_tagged_value_upgrade test is failing when running with the full test suite, but it passes when run by itself. 

### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

```
4 != 1
Expected :
1
Actual :
4

self = <gaphor.storage.tests.test_storage.FileUpgradeTestCase testMethod=test_tagged_values_upgrade>
first = 1, second = 4, msg = None
def _patched_equals(self, first, second, msg=None):
try:
>           old(self, first, second, msg)
../../pycharm-2018.3/helpers/pycharm/teamcity/diff_tools.py:32: 
```

**Comment by amolenaar** [comment]
Fixed in #90
