### ISSUE TITLE
Reordering attributes or operation not working

### ISSUE THREAD

**Issue by icfmp** [gaphor/gaphor#777]
**Describe the bug**
When I drag and drop attributes or operations it doesn't apply to the class

**To Reproduce**
1. Open Gaphor
2. Select a class
3. Move an attribute or an operation in the edit box
4. The attribute or operator moved in the edit box but not in the view.
5. Choose another class and get back to the class you modified : modifications are lost.

**Expected behavior**
Attributes and operator order should be saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/71736258/117165644-f5dd0f80-adc5-11eb-939d-294ad16f1df7.png)

**OS**
Ubuntu 21.04 + flatpak + flathub

**Version**
Version of Gaphor: 2.4.0 from flathub

**Comment by amolenaar** [comment]
Hi @icfmp, Thanks for reporting this.

Indeed, if you reorder the attributes with drag-n-drop they are not reordered. I'll investigate this further.

As a workaround (for now), you can use <key>+</key> and <key>-</key> to reorder the elements. Then they will be updated in the diagram as well.

**Comment by danyeaw** [comment]
@all-contributors please add @icfmp for bug

**Comment by icfmp** [comment]
> Hi @icfmp, Thanks for reporting this.
> 
> Indeed, if you reorder the attributes with drag-n-drop they are not reordered. I'll investigate this further.
> 
> As a workaround (for now), you can use + and - to reorder the elements. Then they will be updated in the diagram as well.

@amolenaar Ok, I tried it. I can indeed drag a question down with =, but + isn't working.
