### ISSUE TITLE
Single letter A and S in UI is unclear

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#799]
**Describe the bug**
The column titled "A" and "S" are non-descriptive. I don't know what they mean, I have to resort to guessing.

What does "A" and "S" mean? Is it "Abstract" and "Static" ?

**To Reproduce**
1. Create a new class.
2. Click on the newly created class.
3. See error there is a column titled "A" and "S".

**Expected behavior**
There would be some tooltip or icon or other representation that is more easy to understand.

**Screenshots**
![image](https://user-images.githubusercontent.com/10222521/118048544-b5a8fe80-b37c-11eb-8ac3-3ad6c716000e.png)

NOTES:

**Version**
Version of Gaphor: 2.4.1

**Comment by amolenaar** [comment]
Hi @vanillajonathan,

Indeed this is due to space constraints. They stand for "Abstract" and "Static", as you correctly guessed.

Would it help if the "A" is in italics and the "S" is underlined? Or do you expect that to be too cryptic still?

**Comment by vanillajonathan** [comment]
No, italics and underlines does not convey the semantics in a meaningful way and would not make it any more clearer, possibly even more confusing.

What would really help is tooltips, so that when you hover over "A" it says "Abstract". The tooltip could also be on each of the checkboxes.

**Comment by amolenaar** [comment]
I added a little tooltip that shows what the letter stands for:

![image](https://user-images.githubusercontent.com/96249/118278592-71c40f80-b4ca-11eb-8838-158c73b9f7eb.png)
