### ISSUE TITLE
Use Adwaita Tabs

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#802]
There's a [new tabs widget in libhandy](https://blogs.gnome.org/alexm/2021/03/13/reinventing-tabs), which is much nicer than GtkNotebook. Switching to that would make the tabs experience much nicer :)

**Comment by amolenaar** [comment]
Thanks @bertob,

Or libhandy's GTK4 successor/counterpart [libadwaita](https://gitlab.gnome.org/GNOME/libadwaita)?

This kinda depends on the status of our GTK4 port. GTK4 is high on my list.

**Comment by bertob** [comment]
Yeah, once you port to GTK4 you'd use the same widget from libadwaita.

**Comment by danyeaw** [comment]
@all-contributors please add @bertob for idea

**Comment by danyeaw** [comment]
The draft updated HIG are here: https://teams.pages.gitlab.gnome.org/Design/hig-www/index.html

**Comment by danyeaw** [comment]
I looked in to Handy Tabs today, they are very nice. It looks like ubuntu won't have libhandy 1.2+ until version 21.10 and I think we should wait for that so that we don't have to use a PPA to setup a dev environment.

**Comment by bertob** [comment]
IIRC you can also just include Libhandy as a submodule.

**Comment by danyeaw** [comment]
Once we drop GTK3 support, we should change from using the Gtk.Notebook to use Adw.TabView and Adw.TabBar.

**Comment by amolenaar** [comment]
My idea is to improve the ui with libadwaita components (GTK4) and leave the GTK3 ui as is.

The easiest would be one we're fully on GTK4, but we may be able to implement some features earlier.
