### ISSUE TITLE
After save model and try to open I get "This file does not contain a valid Gaphor model"

### ISSUE THREAD

**Issue by carlitux** [gaphor/gaphor#828]
**Describe the bug**
Can't open the file

**To Reproduce**
1. Open Gaphor
2. Open File
3. See the error

**Expected behavior**
Open the File

**OS**
- [x ] Linux (Pop OS)
- [ ] macOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphor: 2.4.2 installed using flatpak

**Additional context**
Gaphor model compressed to be able to upload here.

[Diagrams.zip](https://github.com/gaphor/gaphor/files/6535220/Diagrams.zip)

**Comment by amolenaar** [comment]
@carlitux,

Thanks for sharing this. It appeared there was a dead reference in the model. The reference pointed to a presentation (dependency item), which was no longer in the model.

[Diagrams-fixed.zip](https://github.com/gaphor/gaphor/files/6537446/Diagrams-fixed.zip)

I noticed two more issues I want to look into:

- [ ] The stylesheet was not displayed in the editor window. Only after an edit + undo it appeared.
- [ ] C4Database items can not be styled based as one would expect. The cause for this is that the presentation item is not called `C4DatabaseItem`, but `C4ContainerDatabaseItem`. The following CSS snippet works as expected: 
```css
c4ContainerDatabase {
  background-color: #438dd5;
  color: white;
}
```
I want to change this, so `c4Database` works as well.


@danyeaw With regards to this issue: I think the distinction between model elements and diagram items should go away. With the latest changes (Gaphas 3), diagram items behave like model elements in every sense. It will also simplify the undo/redo logic.
