### ISSUE TITLE
Allow Nesting and Stereotypes for Properties

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphor#841]
**Is your feature request related to a problem? Please describe.**
With our initial SysML support we allowed for the creation of part and reference properties and then to display them as part of an Internal Block Diagram. Next it would be great if we allowed the properties to be nested. We also need to be able to display Stereotypes for Controller, Actuator, and ControlledProcess.

For example, if a Brake System Control Unit (BSCU) contains an Autobrake Controller and Hydraulic Controller:
![image](https://user-images.githubusercontent.com/10014976/120086310-4f2a1d00-c0ac-11eb-9014-a91782d01a04.png)

How I would like to be able to create a nested Internal Block Diagram that showing that the BSCU contains these things:
![image](https://user-images.githubusercontent.com/10014976/120086401-957f7c00-c0ac-11eb-8e64-fc6b6301d972.png)

Right now we can drag a property on top of another, but the relationship (composition or aggregation) isn't taken into account. Also the name of the property is centered in the property which makes this difficult. 

**Describe the solution you'd like**
When a property is selected, allow sub-properties (part or reference) to be displayed from the propertiespages.

When a sub-property is displayed, move the name and stereotype of the box back to the top and create a new compartment.

**Describe alternatives you've considered**
Move the name and stereotype to the top and keep things as they are with no nested properties.

**Additional context**

**Comment by amolenaar** [comment]
Somewhat related to #897.

**Comment by amolenaar** [comment]
@danyeaw Is this about nesting `Property`'s or `Block`'s? The first diagram shows blocks, but the text talks about properties.

We can already nest `Property` in `Block`, but not `Property` in `Property` and `Block` in `Block`.

`Block` in `Block` should be pretty straightforward. I'm not sure how `Property` in `Property` would be possible.

**Comment by danyeaw** [comment]
@amolenaar The first diagram shows that the BSCU contains an Autobrake Controller and a Brake Controller. Then in an IBD you would like to be able to show that as well without redrawing it from scratch. You would drag the BSCU to your IBD to create a part property of the BSCU (a usage of if), then you want to be able to select the BSCU and show what is inside the BSCU (the AutoBrake Controller and Brake Controller).

If the first diagram was showing aggregation instead of composition, you would still want to be able to display those in an IBD as well except as a reference property.

**Comment by amolenaar** [comment]
@danyeaw I see where I misread the diagram: "Autobrake Controller" (the block) and "autobrake Controller" (the property/association end). The latter is used in the second diagram.

**Comment by amolenaar** [comment]
This is what we can do currently:

![image](https://user-images.githubusercontent.com/96249/146428168-680151db-9f91-43c2-9f36-12d7a387e3b7.png)

Not bad, if i say so myself :smiley:. 

What I'm missing:
* Property contains name and type. Should be only name?
* Connectors and ItemFlow are not properly namespaced (they show up at toplevel)
* `ItemFlow.itemProperty` (type `Property`) can not be stereotyped through the UI. Should we do this? Isn't this too specialized?

**Comment by danyeaw** [comment]
I am fine with the properties showing the name and type.

STPA in the RAAML profile uses these ItemFlow stereotypes quite a bit. We could always make this a future enhancement as well.

**Comment by amolenaar** [comment]
@danyeaw Should the `ItemFlow` be stereotyped, or the `itemProperty`? Or both?

**Comment by danyeaw** [comment]
@amolenaar I looked at this a bit more. These Stereotypes above extend both Signal and DataType elements. The Flow Property can be typed by a Signal (or a ValueType or a Block). So we effectively have a custom signal that is typed to the flow property and then the stereotype is displayed as well.

**Comment by amolenaar** [comment]
You mean the stereotype is coming from the "allocated type"?

**Comment by danyeaw** [comment]
@amolenaar Yes

**Comment by amolenaar** [comment]
Okay, so we have to add a _type_ to our item flow, like we've done for swimlanes.
That makes this story related to #1241, I think.

Do we care about visibility and multiplicity? If not, I can change the entry field to only show the name and add a type dropdown below. Identical to swimlanes.

**Comment by amolenaar** [comment]
Voila:

![image](https://user-images.githubusercontent.com/96249/148564499-faee1255-4de1-4b1e-8620-57f09d751028.png)

**Comment by danyeaw** [comment]
Closed by #1211.
