### ISSUE TITLE
Screenshots in appdata

### ISSUE THREAD

**Issue by Alexander-Wilms** [gaphor/gaphor#88]
### I'm submitting a...
- [ ] Bug report  
- [ ] Feature request
- [x] Documentation issue or request

### Current behavior

Appdata file is missing some screenshots

### Expected behavior
Maybe show Gaphor being used to create one of each supported UML diagram types

### Minimal reproduction of the problem with instructions
Go to https://flathub.org/apps/details/org.gaphor.Gaphor, notice that there's no screenshots

### If this is a feature request please fill out the following:
<pre><code>
As a (user, developer, contributor, etc):
I want:
So that:

</code></pre>

### System Information
OS:
- [x] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:
There are some guidelines regarding the screenshots in the appdata spec: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

**Comment by danyeaw** [comment]
@Alexander-Wilms Thanks so much for submitting the issue, I really appreciate it! Is this something you would like to help us fix? ♥️

**Comment by Alexander-Wilms** [comment]
I tried opening a level from Quake II, but that didn't work, though I'm not sure if that should work. Do you have a nice level I could use?

**Comment by Alexander-Wilms** [comment]
I wanted to import Python code from some well-known projects, but didn't know which files contained some nice class structures etc. Do you have some Gaphor files I could use?

**Comment by danyeaw** [comment]
@Alexander-Wilms There are some model files in the test-diagrams folder. Also you could just create something basic which would actually probably be preferred for showing how the app works, like https://en.m.wikipedia.org/wiki/Class_diagram#/media/File%3AKP-UML-Generalization-20060325.svg or https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/UML_Use_Case_diagram.svg/1280px-UML_Use_Case_diagram.svg.png

**Comment by danyeaw** [comment]
@Alexander-Wilms Any help or guidance needed? Feel free to jump on to Gitter if you want to discuss this further. :+1:

**Comment by Alexander-Wilms** [comment]
No, I'll build the Flatpak of the version including the fix for #89 and send a PR

**Comment by danyeaw** [comment]
I think that this would be good using the latest master version that makes the background white 👍

**Comment by danyeaw** [comment]
Closed by ea934e8d44b9cc3b0eba8327591563a61abbd498
