### ISSUE TITLE
Usability request: immediately enable rename popup on entity placement

### ISSUE THREAD

**Issue by mrmonkington** [gaphor/gaphor#886]
Hello!

**Is your feature request related to a problem? Please describe.**
As a relatively new user, I am finding the workflow for sketching out my graphs in gaphor a little less fluid than it could be. In particular the cycle of 'place -> rename -> place -> rename ->...' is fiddly and requires either focusing the item editor panel and changing the name, or double clicking an entity. If I make a mistake in this process and do not correctly focus or activate the rename popup, my keystrokes are interpreted as tool shortcuts, and chaos ensues :)

**Describe the solution you'd like**
I think it would be reasonable to always immediately enable and focus the rename popup on placement of new entities (where relevant)

![image](https://user-images.githubusercontent.com/778856/125089959-bb923600-e0c6-11eb-88d4-c0c2c31aabb9.png)

**Comment by danyeaw** [comment]
Thanks @mrmonkington for the idea! We are always looking for new contributors, would you be interested in helping out with this?

@allcontributors please add @mrmonkington for idea

**Comment by mrmonkington** [comment]
Hi @danyeaw - sure I'll give it a shot! Should I be looking in gaphor itself or is the symbol pick/place in gaphas?

**Comment by amolenaar** [comment]
The code for the "InlineEditor" is all in Gaphor :).

**Comment by danyeaw** [comment]
I looked in to this yesterday. The gaphor.diagram.diagramtools.placement module is what is used to create a new item when element is dropped on the diagram. I tried instantiating a new `InlineEditor` from here, and it was working inconsistently:

- The first element I drop doesn't result in the inline editor opening
- The second one does properly, but then I get a `gtk_event_controller_get_propagation_phase: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed` CRITICAL failure
- I was also occasionally getting seg faults

I also considered using events to notify when an element was created. In the gaphor.core.modeling.event module, there is an ElementCreated event, however the event handler `_on_element_create` isn't being called, only the `EventCreated` constructor.

**Comment by sz332** [comment]
@danyeaw @mrmonkington any progress with this issue? this looked like a quick win for me.

**Comment by danyeaw** [comment]
@sz332 Not yet for me, I wasn't able to take time to look at more since my update last month.

**Comment by danyeaw** [comment]
@amolenaar When you used the `@g_async` decorator, did that allow the event loop to finish creating the element, and then open the InlineEditor? Is that why I was getting the inconsistent behavior and seg faults because the event loop was blocked?

I am just trying to learn, so I'll know what to do next time. 😅
