### ISSUE TITLE
Swap Relationship Directions from Source to Target

### ISSUE THREAD

**Issue by Gytree** [gaphor/gaphor#929]
### Is your feature request related to a problem?
When we are going to create a relation, like generalization or a class dependency, currently I need to select the target object first and then the source. but in all the previous software that I used before the behavior is on the contrary, first select the source of the relation then the target.

Example if I'm going to make a class generalization the normal thinking is the class Dog extends Animal, so the logical is select the class that is going to extend the other first (Dog) and after that the extended class (Animal)

### Describe the solution you'd like
Is possible change this behavior to a selecting the source first ? or a better solution maybe will be add a setting for this behavior.

**Comment by danyeaw** [comment]
@Gytree Thanks, I have noticed this as well, and I'm glad someone else pointed it out!

@all-contributors please add @Gytree for bug

**Comment by danyeaw** [comment]
@Gytree I created a PR to swap the generalization direction. I don't have MagicDraw available since I'm on vacation. Do you know what other relationships are backwards?

**Comment by danyeaw** [comment]
Gaphas right now defines the head end as the side of the line that is placed first. Another solution if all the relationships are backwards is to make the head and tail swappable in gaphas.

I tested things with [Papyrus](https://www.eclipse.org/papyrus/).

Class like dependencies:
- Generalization: opposite
- Dependency: opposite
- Containment: same
- Directed Association: opposite
- Extension: opposite
- Import: opposite

Others:
- Include and extend: opposite
- Transition: same
- Message: same

So what we have is inconsistent, and it wouldn't work to just allow the head and tail to be swapped in Gaphas. Should we create migrations like I did for #935 for the other relations?

**Comment by amolenaar** [comment]
@danyeaw We will probably be the most flexible if we swap which node is placed first. Make it configurable in the placement tool. We can then set the direction per item and swap them if we need to.

Are Papyrus and MagicDraw in sync with their placement behavior?

**Comment by danyeaw** [comment]
@amolenaar Yes, it looks like Papyrus and MagicDraw use the same arrow directions

**Comment by amolenaar** [comment]
- [ ]    Generalization: opposite
- [ ]    Dependency: opposite
- [ ]  Directed Association: opposite
- [ ]    Extension: opposite
- [ ]   Import: opposite
- [ ] Include and extend: opposite

**Comment by danyeaw** [comment]
@amolenaar I tested with Papyrus again. I think our directed association is backwards, did you see something different when you were testing?

We draw the arrow on the first handle, Papyrus draws the diamond on the first handle.
