### ISSUE TITLE
Translate instructions

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#937]
Can you please add how to translate your program to the [README.md](https://github.com/gaphor/gaphor/#readme) page?

We couldn't see a link Weblate or some other web-based service to translate your program.

Thank you

**Comment by danyeaw** [comment]
Hi @ovari! Thanks for the suggestion. We would like to make the translation process as easy as possible.

Right now we aren't using a web service. To update a translation you update the po file for the language in the po directory. To add a new language we need to add it to the top of the Makefile. I agree that we should add more documentation on this in CONTRIBUTING.md or at https://gaphor.readthedocs.io

Do you have experience with any of the web translation services? Maybe we should upgrade to that if it will encourage more translators to get involved.

**Comment by ovari** [comment]
Hi @danyeaw!

Thank you for your prompt response.

Please use [Weblate](https://weblate.org/) if you can. You can host your translations on their hosting service at https://hosted.weblate.org/ or you can `Self-host for complete control` which is `Gratis with paid support`.

For hosted examples, see https://hosted.weblate.org/.

For a self-hosted example, see [Linphone](https://linphone.org/)'s self-hosted instance at https://weblate.linphone.org/.

Also experienced with [Crowdin](https://crowdin.com/) and [Transifex](https://www.transifex.com/); however Weblate is the best based on the information and experiences we have gathered.

Thank you once again

**Comment by comradekingu** [comment]
Happy to contribute if the CoC/CLA is removed.

**Comment by danyeaw** [comment]
@ovari Thanks for the additional information! I have added Gaphor Weblate hosting, and you can contribute here:
https://hosted.weblate.org/projects/gaphor/gaphor

I have also updated the README with this information and added a translation status badge. :+1: 

@comradekingu Providing a welcoming and safe environment to everyone is really important to Gaphor, and we use a Code of Conduct to communicate and enforce those expectations. I'm sorry if you don't think this is important, but it is required to contribute to this project.

**Comment by danyeaw** [comment]
@all-contributors please add @ovari for idea
