### ISSUE TITLE
Make element editor more prominent

### ISSUE THREAD

**Issue by Alexander-Wilms** [gaphor/gaphor#94]
### I'm submitting a...
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

### Current behavior

Initially, I thought something was broken, since I didn't see any way of editing elements like classes etc.

### Expected behavior
When right-clicking on an UML element, it should offer to open the element editor, or it should reside in a (semi-)permanent side pane.

### Minimal reproduction of the problem with instructions
Create new diagram, add class element, try to edit it.

### If this is a feature request please fill out the following:
<pre><code>
As a (user, developer, contributor, etc): user
I want: A more obvious way of editing UML elements
So that: I can start working faster

</code></pre>

### System Information
OS:
- [x] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:
Fedora 29 KDE

**Comment by amolenaar** [comment]
In the GTK+2 version of Gaphor one could double-click on a grey box and edit it in place.

It would make sense to restore this behaviour, I think. Having the editor in a side pane would take up quite a bit of screen real estate.

**Comment by danyeaw** [comment]
Should we fix this before 1.0.0 release?

**Comment by amolenaar** [comment]
I need to allocate some time to dig into this. It should be worthwhile fixing.

**Comment by amolenaar** [comment]
Fixed by #108. You can now double click on an element and a small edit popup appears.
