### ISSUE TITLE
Please enable `The simple modeling tool` to be translated

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#941]
Please enable `The simple modeling tool`, in the System Menu, to be translated.

![image](https://user-images.githubusercontent.com/17465872/130916985-e8507399-846a-486c-897e-d84723ffc9b5.png)

Thank you

Linux Mint 20.2 Cinnamon

**Comment by ovari** [comment]
Are there code pointers in https://github.com/bottlesdevs/Bottles/issues/380#issuecomment-882123166? Thank you

**Comment by amolenaar** [comment]
@ovari The translation you refer to in the issue can be updated here: https://github.com/flathub/org.gaphor.Gaphor/blob/master/share/org.gaphor.Gaphor.desktop

A bit inconvenient, but that's how flatpaks are built :/

**Comment by danyeaw** [comment]
@ovari Thanks again for the bug report. Most of the items should now be translatable thanks to @amolenaar!

The couple of others would require editing the desktop file that is posted above.

**Comment by ovari** [comment]
Thank you @danyeaw for your message.

Thank you @amolenaar for adding the translation improvements.

Have updated Weblate so Hungarian should be at 100%

Have updated the Desktop Entry Comment with the Hungarian string. Are there any other places that need updating?

Have update your README.md file to indicate that there is also a `Desktop Entry` `Comment` that needs updating.

Thank you both once again.

**Comment by mathiascode** [comment]
> A bit inconvenient, but that's how flatpaks are built :/

Out of curiosity, is there any specific reason you handle appdata/desktop files in the Flathub repository instead of this one?

**Comment by danyeaw** [comment]
Hi @mathiascode! Having the desktop file and the manifest in the Flathub repo is the only option to get the app on Flathub that I am aware of. Do you know of another option?

**Comment by danyeaw** [comment]
@mathiascode Thanks for the info and glad to meet some other Python GTK maintainers!

I think our setup is different, we are using `pyproject.toml` instead of `setup.py` and for the most part are using pyinstaller instead of separate build scripts. Poetry doesn't support `data_files` per say, but we may be able to add an include statement in our pyproject.toml.
