### ISSUE TITLE
Should `gaphor` be `Gaphor`, i.e. with a capital letter?

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#942]
Should `gaphor` be `Gaphor`, i.e. with a capital letter?

![image](https://user-images.githubusercontent.com/17465872/130917319-27f5fa8b-1dc9-4d25-9ff1-4b047cf69c43.png)

Thank you

Linux Mint 20.2 Cinnamon

**Comment by danyeaw** [comment]
@ovari I can confirm that I see this as well in Linux. I dug around and didn't see anything obvious from where the app window name when in the activities view comes from. The official app ID is org.gaphor.Gaphor and it doesn't seem like it is pulling it from the pyproject.toml.

Anyone interested in taking a look in to this?

**Comment by ovari** [comment]
Are there code pointers in [Bottles](https://usebottles.com/) as it displays correctly for that program?

https://github.com/bottlesdevs/Bottles/issues/380#issuecomment-882186909

Thank you

**Comment by amolenaar** [comment]
I had a look, but could not find it. I thought maybe a window title is set explicitly, but that seens not be the case.

Even in (stock) GNOME, the window is named `gaphor`. It would be nice it it would contain the model name at least.

**Comment by danyeaw** [comment]
@mathiascode Awesome, thanks for the tip!

**Comment by amolenaar** [comment]
Thanks for pointing out. It shows the proper window title now.
