### ISSUE TITLE
New release with 100% Hungarian translations

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor#943]
Please release a new verison with the merged Hungarian (100%) translations.

Thank you

**Comment by ovari** [comment]
@danyeaw do you have an ETA on when a new version will be release with the Hungarian translations? Thank you

**Comment by danyeaw** [comment]
Hi @ovari, there is an issue with our macOS app signing that we need to resolve before we can cut a new release. Since we are all just volunteering our free time, I can't promise a release date, but I would like to publish a new one this weekend if possible. I'm excited for a new version as well!

**Comment by ovari** [comment]
Is there something that needs to be done for Hungarian to show throughout the whole program?

![kép](https://user-images.githubusercontent.com/17465872/133912765-b32a7bc5-b54e-43b7-994b-cfd29af4dfb2.png)

Thank you

**Comment by danyeaw** [comment]
@ovari Did you change the language of your whole desktop / system to Hungarian in the Region & Language options?

**Comment by ovari** [comment]
![kép](https://user-images.githubusercontent.com/17465872/133949009-274224e7-b406-460d-b9cc-84fca19a59b9.png)

**Comment by ovari** [comment]
![kép](https://user-images.githubusercontent.com/17465872/133949065-e521fe8d-b5c9-4ee9-a33c-4b9591db00e3.png)

Image shows Graphor with the follow 2 programs in Hungarian: [Video Downloader](https://flathub.org/apps/details/com.github.unrud.VideoDownloader) and 
[Video Trimmer](https://flathub.org/apps/details/org.gnome.gitlab.YaLTeR.VideoTrimmer). Maybe these programs can help with the cause?

Does it matter if the locale in Graphor is set to `hu` or `hu-HU`?

Is there another file in Graphor needs to be updated to enable Hungarian?

Thank you

**Comment by danyeaw** [comment]
Do you have Gaphor installed via Flatpak?

**Comment by ovari** [comment]
Yes, Gaphor is installed via Flatpak from Flathub.org using Linux Mint's Software Manager.
