### ISSUE TITLE
Re-opening editor window makes Gaphor crash

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#96]
### I'm submitting a...
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

When the editor window is opened for a second time, after it's closed, it will crash the application.

### Minimal reproduction of the problem with instructions

* Start Gaphor,
* Open the editor (Command-e)
* close the editor window
* open it again
* crash (SIGSEGV)

### System Information
OS:
- [ ] Linux (Please put in notes the specific distro)
- [X] MacOS
- [ ] Windows 10
- [ ] Windows 7

NOTES:

The Console window does not make Gaphor crash, instead the window will not show when opened for a second time.

**Comment by danyeaw** [comment]
Closed by #109. :tada:
