### ISSUE TITLE
Cannot Load File

### ISSUE THREAD

**Issue by c4tachan** [gaphor/gaphor#970]
### Describe the bug
I am unable to load the file attached to this bug report.
Upon attempting to load the file, I am presented with a blank gaphor interface, and the window title says "New Model"

### To Reproduce
1. Open the attached file

### Expected behavior
The file should load

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x] Windows

### Version
Version of Gaphor: 2.5.1
[Broken.gaphor.txt](https://github.com/gaphor/gaphor/files/7124032/Broken.gaphor.txt)

**Comment by amolenaar** [comment]
The message I see when I open the model is:

```
gaphor.storage.storage WARNING file b'/home/arjan/Downloads/Broken.gaphor' could not be loaded (Can not set <gaphor.UML.actions.activitynodes.ForkNodeItem element e29bb3df-100b-11ec-ae75-1c9957c4cf51>.parent to itself)
```

In the model, this element is indeed referencing itself:

![image](https://user-images.githubusercontent.com/96249/132542727-7c9e0831-d794-4a22-aee1-6e92cfec09ba.png)

This is a situation that should not happen.

**Comment by amolenaar** [comment]
Fixed the model. It does run into a bunch of JuggleError's when I load it. Which is also awkward, given the model is not *that* complex. 

[Broken-fixed.gaphor.txt](https://github.com/gaphor/gaphor/files/7130291/Broken-fixed.gaphor.txt)

**Comment by c4tachan** [comment]
Okay, I think I may know how this happened (from a user action standpoint).

Basically, in the navigation pane, I dragged a node into another node where it was illegal to place it. I got a warning, but the node I had tried to drag vanished from the navigation pane. This sounds like it could be somehow setting up an illegal reference chain, instead of reverting to the previous chain.

**Comment by amolenaar** [comment]
@c4tachan Thanks! That's valuable input 🙂. I'll try to reproduce it from the tree view.

**Comment by amolenaar** [comment]
I already added some extra checks in #895, so this issue should not manifest itself in Gaphor 2.6.0.

**Comment by danyeaw** [comment]
We are about to release 2.6.0 (maybe today?). If you still see issues with models not being able to run, please submit a new issue. Thanks again for the bug report @c4tachan!

@all-contributors please add @c4tachan for bug

**Comment by xurgedigital** [comment]
is there a way to repair the file? Mine does not open even after downloading latest release.

**Comment by xurgedigital** [comment]
is there a way to repair the file? Mine does not open even after downloading latest release.

**Comment by danyeaw** [comment]
@xurgedigital Could you please open a new issue if you are having issues opening a model? We would like to help resolve them, thanks!
