### ISSUE TITLE
Add Option and Dialog to Prevent Automatic Removal of Last Usage of an Element When the Diagram is Deleted

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#971]
As a user I would like to be able to create a model element in the model (by pressing a button, or right mouse click, etc. and selecting from a list), without the need of creating a new diagram.

**Comment by amolenaar** [comment]
Hi @sz332,

Thanks for the feedback. What's your case for adding such a feature? One of the goals of Gaphor is to have no "hidden" elements in your model. As stated on the https://gaphor.org:

> UML is a graphical modeling language, so all information you put in the model is visible in the diagrams. For example, stereotypes are modeled in diagrams. No hidden panels and property pages. Just diagrams!

**Comment by sz332** [comment]
It is not clear for me whether it is a drawing tool, or a modeling tool. In a modeling tool, a diagram is just a view of the system, therefore the same model element can be displayed in multiple diagrams. Therefore, creation of model elements shall be possible even outside a diagram, and then later it could be added to a diagram. This does not mean a model element is hidden, it only means, that in a particular view, you don't want to show the model element.

**Comment by sz332** [comment]
So, I would like to challenge the requirement from an advanced user point of view (we are using magicdraw, and in our current system we have around 600k model elements, and 3k diagrams). I don't see any reason what kind of benefit it would have if our current software would work this way. 

Also, for properties, if you add a class, you already have a property table, where you can add attributes and operations. As a heavy modeler, I have absolutely no problem with how the current software works, alas displaying a property table for the selected item. This is also something that shall be talked about with the target user base. If you think that having complex properties is disturbing, then you can go with some beginner, advanced, all kind of properties categorization. Otherwise, I don't really see how you could implement the uml metamodel, or even a subset of the metamodel.

**Comment by danyeaw** [comment]
Hi @sz332!

> It is not clear for me whether it is a drawing tool, or a modeling tool. In a modeling tool, a diagram is just a view of the system, therefore the same model element can be displayed in multiple diagrams.

This is a modeling tool, you can display elements on multiple diagrams. There is a UML / SysML data model implemented.

As a fellow MagicDraw user, I understand what you are saying completely. However, Gaphor isn't trying to compete with MagicDraw. We are aiming this to be fast and simple, yet powerful. One of the reasons MagicDraw is so complex is that it allows you to add or edit everything outside of diagrams. In order to accomplish that, you need many many menus and dialogs. I am not sure if that is the direction we want to head.

**Comment by sz332** [comment]
From standard point of view:

In UML/SysML (when we are talking about UML as described in OMG's UML specification) model elements exists outside the diagram, and a diagram element (the thing you see on the diagram actually references the model element). UML 2.5.1 specification, page 688.

An UMLDiagramElement is a kind of DiagramElement, and it references * modelElement (UML::CommonStructure::Element). 

I can even understand that you don't want to add the feature to add a diagram element directly to a package without adding it first to a diagram. This is something I could live with as a user now (and later, if lots of people require this, it could be improved) but I don't really see the point of removing the model elements if the last diagram is removed. Why? I don't really any advantage of this feature, but I see lots of user errors, **especially** that it does not give any kind of feedback which kind of model elements will be removed due to this action. I see it causing more problems than it solved. Alternatively, if this "feature" could be switched off, that would be a sufficient.

**Comment by danyeaw** [comment]
@sz332 Now we are getting somewhere! Would you prefer to have an option in Gaphor to turn off automatic deletion if elements when the diagram is deleted that contains the last use? Or would you prefer to have a dialog that asks you what you want to do when you delete a diagram that has the last usage of an element?

If we did add a dialog, I think we would want to ask once for all elements that have a last usage and maybe show a list of them, or possibly ask for each but have a buttons for Yes / No to All.

**Comment by sz332** [comment]
Replacing my BA/SA/Developer hat with a Product Owner :D 

Global configuration:

V1

As a user, I would like to have a configuration file, where I can disable the deletion of the model elements


V2

As a user, I would like to have a menu item somewhere in a hamburger menu for configuration. By selecting this menu item I would like to see a dialog, where I can setup:

Removal of dangling model elements:
- Always remove: always remove dangling model elements
- Never remove: never remove dangling model elements

V3

V2 + Extends the list of choices:
- Ask: display the dialog (see below)

Delete dialog:

V1

As a user, when I delete a diagram, and the diagram contains model elements that are only displayed on the diagram under deletion, I would like to see a dialog. The dialog shall ask about the deletion of the dangling? mode elements.

As a user, I shall have the following choices: 
- Remove dangling elements: will remove the diagram and the model elements only displayed on the diagram, 
- Do not remove dangling elements: will remove the diagram, but not the single model elements.
- Cancel: will cancel the deletion and close the dialog. The diagram will be unchanged, and no model elements will be deleted.

V2:

As a user, I also want to see the name (and type) of the model elements to be removed.

**Comment by amolenaar** [comment]
Looking at this after some time. I'd like to implement the dialog, and display the elements that are to be removed. At least the "toplevel" ones (e.g the Class, but not each individual attribute).

Preventing removal of elements is a little harder since that's done out of bound by a Sanitizer service. However it should be doable.

I'd like to stay away from user preferences as long as possible.
