### ISSUE TITLE
Pin support for activity diagram

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#975]
In an activity diagram, pins are often used to define object flow connection points. As a user, i would like to add pins to an existing action, either input or output pins. I would like to be able to set the multiplicity, name, and type for a pin.

**Comment by amolenaar** [comment]
Section 16.2.3.3 in the UML 2.5.1 specs.

**Comment by sz332** [comment]
- Well, normally it is nice to be able to add directly an input or an output pin, which enables fast modelling.
- Yes, it might show a little arrow, but need to check the specification
- You can add input and output pins anywhere you want connecting to an action (top, bottom, left, right, any location). The modeler shall be able to move the pins according to his wishes.
- No
