### ISSUE TITLE
Control flow support / separation from object flow

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#976]
Add support to control flow.

**Comment by amolenaar** [comment]
@danyeaw @sz332 How should this work?

**Comment by sz332** [comment]
Specification: 

https://www.omg.org/spec/UML/2.5.1/PDF

Chapter 15, Activities, a activity can have multiple activity edges, which are either an objectflow type of edge or a controlflow type of edge.

The by standard way of displaying object flow and control flow is using the same solid line. 

However, in case of SysML the control flows are differentiated visually by using a dashed line.

Relevant chapter for SysML specification (https://www.omg.org/spec/SysML/1.6/PDF)

B.2.1 SysML Activity Diagram

Description

A SysMLActivityDiagram represents an activity diagram. It extends UMLActivityDiagram.

Attributes
• isControlFlowDashed : Boolean [1] = false

Specifies whether the control flows in the activity diagram are dashed (isControlFlowDashed=true) or not (isControlFlowDashed=false).

**Comment by amolenaar** [comment]
If an ObjectFlow or ControlFlow is used depends on the objects the ActivityEdge is connecting. Gaphor dynamically uses one or the other: https://github.com/gaphor/gaphor/blob/master/gaphor/UML/actions/flowconnect.py#L64.

Are there specific properties that need to be exposed (via property pages) for Control- and ObjectFlow?

**Comment by sz332** [comment]
Is it true (according to the specification) that this kind of decision can be made always? Because they have a really-really different meaning, one is about control flow of actions, the other is about object flow (data flow) among actions.

**Comment by amolenaar** [comment]
The plan:

1. Draw Control Flow with a dashed line to distinguish it from Object Flow (probably create a separate Presentation element)
2. Add Control Flow to the toolbox
3. Create separate Connector protocols for Object Flow and Control Flow
4. Fix model loading (add migration code)

@danyeaw @sz332 Did I miss anything?

**Comment by danyeaw** [comment]
@amolenaar I like the plan!

**Comment by sz332** [comment]
@amolenaar second this, looks like a great plan!
