### ISSUE TITLE
Separate decision and merge nodes

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#977]
Decision or merge node works differently. There shall be a support to set whether a particular node is either a decision, or a merge node. They shall be rendered differently, if possible.

**Comment by amolenaar** [comment]
In gaphor, Decision and merge nodes can be merged. The type of the underlaying model element is determined by the number of incoming and outgoing edges:
1. For one incoming edges and multiple outgoing edges, it's a DecisionNode
2. For multiple incoming edges and one outgoing edge, it's a MergeNode
3. For multiple incoming and outgoing edges, it's a MergeNode connected to a DecisionNode.

This is all according to spec (UML 2.5.1, pg 392):

![image](https://user-images.githubusercontent.com/96249/133500565-61bc6de8-2334-4409-a1ee-0dce25a27e2e.png)

**Comment by sz332** [comment]
My problem is with merging decision and merge nodes, that they have rather different use. When I look at a diagram, do I really know what the intend of the modeler was? 

But, based on the folllowing, can we change how the model element is rendered BASED on the number of nodes?

**Comment by amolenaar** [comment]
I think we can do something in that area. Being explicit is a good thing. What do you have in mind? In the UML spec both Decision and Merge node are drawn in a similar fashion.

**Comment by sz332** [comment]
I just checked how various tools implement decision and merge nodes, and mostly are actually using the same element. However, we are using magicdraw, and it's using a different (but similarly looking) symbol.

https://docs.nomagic.com/display/MD190/Decision+and+Merge

**Comment by amolenaar** [comment]
Could we provide a feature where we could add custom / project level rendering for the elements? That would be rather great, like render the project like in X propertiary software.

We have a CSS engine :smiley:. By providing this level of customization, I'd say it relates to #689 and #876. 

We can provide a solid inner diamond for merge, and an open inner diamond for a combined decision/merge node.

**Comment by sz332** [comment]
Sounds really great!

**Comment by sz332** [comment]
@danyeaw @amolenaar 

Magicdraw separates decision nodes and merge nodes as a separate model element in activity diagrams. They also display it differently so that people can see that they are doing different things. 

Both Visual Paradigm and Enterprise Architect has a separate model element for decision node and merge node as well, but they look exactly the same. The problem is they are actually doing different things in the mental model (read: in the head) of the modeler and also in the specification: one is used for making a decision, the other is used to merge various object flows together.

I think from user point of view, the separation of the decision node and the merge node, also because in the metamodel they are two different things (see UML 2.5.1, 15.3.2 for metamodel, 15.3.3.5  and 15.3.3.6) and also seeing the distinction visually is a good thing.

There is a way also to merge them **visually** as @amolenaar described.

I can argue both ways for the same feature:
- strict conformance of UML specification vs
- visually helping the users to see what kind of model element they are working with (like magicdraw does)

The second could be especially important when model validation would be more advanced, e.g. you can do certain things with a decision node which you cannot do with a merge node.

Personally, I love the visual difference. 

To move things forward, could we have for features like this some kind of feature flag settable by the user? 

For this we could bring in the properties panel feature, and this kind of connect to my feature request to how Gaphor should behave when deleting an item from the diagram and the underlying model element is not displayed in any  other diagram. 

I think also that we could improve our process, involving more people in the discussion, and have some kind of go/still_discussing state for a ticket. What do you think?

**Comment by danyeaw** [comment]
As a new user to modeling, I think it is confusing to get a diamond shape on a diagram and realize you can't hook it up like you want because you didn't select the right toolbar button for the exact same visual symbol.

For this reason I kind of like that the underlying item in UML is changed as the users usage of the element on a diagram. But I could also see if a modeler is using the same decision or merge node on multiple diagrams, that this could get confusing about which is which.

We are trying to make it more apparent that Gaphor is truly a modeling tool instead of a picture drawing tool, and I think having separate buttons in the toolbox helps make that clear to the user.

I am not aligned with us creating non standard symbols that automatically change based on usage. I find this to be more confusing than making no change at all.

**Comment by danyeaw** [comment]
I would prefer that we add a label next to decision and merge nodes that can be turned on and off, rather than creating new diagram symbols. If you are a user opening a model with one of these symbols, how are you going to know what they are? Where are they going to look them up?

**Comment by amolenaar** [comment]
@danyeaw Like a stereotype you mean?

**Comment by danyeaw** [comment]
A stereotype sounds like something that would be part of the data model. I was thinking some text next to the symbol that says either Decision or Merge.

**Comment by sz332** [comment]
This label might be a good idea. Could we just use a paint application to create an example how it would look like? @danyeaw

**Comment by amolenaar** [comment]
@danyeaw @sz332 Something like this?

![image](https://user-images.githubusercontent.com/96249/142072530-8786c765-7061-4061-9213-eda782345aba.png)

**Comment by danyeaw** [comment]
@amolenaar I like this!

**Comment by sz332** [comment]
@amolenaar looks great!
