### ISSUE TITLE
Drag and drop elements does not work on diagrams

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#993]
### Describe the bug
Dragging and dropping of elements does not work.

### To Reproduce
Grab an element in the toolbar
Move it over the diagram while mouse button is pressed
An icon is displayed with a + sign indicating that drop is possible
Release the mouse button

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.5.1

**Comment by amolenaar** [comment]
Thank for reporting! Indeed this should work. I confirm that it does not work on Linux either.

**Comment by sz332** [comment]
The error is visible in the output:

TypeError: _button_drag_data_get() missing 1 required positional argument: 'action_name'

toolbox.py, button.connect("drag-data-get", _button_drag_data_get, action_name)

The method which is the target of the action seems to have an action_name field, but by whatever reason it is not used.

    def _button_drag_data_get(
        self,
        button: Gtk.Button,
        context: Gdk.DragContext,
        data: Gtk.SelectionData,
        info: int,
        time: int,
        action_name: str,
    ) -> None:

**Comment by amolenaar** [comment]
Yup. It's an function that used to be a method. I'll fix it.

**Comment by amolenaar** [comment]
Fixed :).

Thanks for reporting this.

**Comment by danyeaw** [comment]
@all-contributors please add @sz332 for bug
