### ISSUE TITLE
Fork join node - horizontal alignment strage behavior

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#995]
### Describe the bug
Adding a new fork/join node and setting horizontal alignment causes strage behavior.

### To Reproduce
1, Add a new fork/join node
2, Select the node
3, Press horizontal button on the right panel
4, The fork/join becomes horizontal
5, Click on the diagram
6, Click on the fork/join node again
7, [BUG] The node becomes vertical instead of remaining horizontal
8, Click on the diagram
9, Click on the fork/join node again
10, [BUG] The node becomes horizontal

### Expected behavior
The horizontal/vertical behaviour shall remain according to the selection.

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.5.1

**Comment by amolenaar** [comment]
Every time you deselect it and select it again, it rotates 90&deg; clockwise.

Thanks for reporting!
