### ISSUE TITLE
properties.py getAttribute() throws a huge amount of Exception

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#997]
### Describe the bug

When starting the application in debug mode, creating a new fork node, and enabling stop on uncaught/raised exceptions, a huge amount of exception is caught by VSCode. 

### To Reproduce
- Create a new diagram
- Add a new model element (i used fork node)
- Select the element or the diagram
- Watch for the errors

### Expected behavior

There should be no uncaught exceptions in the code. 

### Screenshots
![image](https://user-images.githubusercontent.com/8182138/133680085-d5f68796-c182-4416-92f9-e70dde0948c9.png)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [X] Windows

### Version
Version of Gaphor: 2.5.1

**Comment by amolenaar** [comment]
What really interests me: why did we implement it this way and not with getattr and a default parameter :). Anyhow, this calls for some improvement.

I did a little test, comparing the exception handling vs the getattr function.

Old (exception handling):

     ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     9955    0.007    0.000    0.017    0.000 properties.py:352(_get)

0,017 ÷ 9955  = 0,000001708

New (getattr with default):

     ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    14723    0.010    0.000    0.022    0.000 properties.py:348(_get)

0,022 ÷ 14723 = 0,0000014943

I'll change it to a simple `getattr`. That'll do the trick.

**Comment by amolenaar** [comment]
I pushed a fix.

I checked the other try/except blocks in `properties.py`. They all seem legit to me. In Python it's quite common to code for the general case and handle the special case in an except clause, as is done for [`derived`](https://github.com/gaphor/gaphor/blob/master/gaphor/core/modeling/properties.py#L643).
