### ISSUE TITLE
Extend the documentation with how to debug Gaphor using VSCode

### ISSUE THREAD

**Issue by sz332** [gaphor/gaphor#998]
### Is your feature request related to a problem?

The current installation manual for developers works great, even for windows users, however a couple of lines about how to debug the application in VSCode would be super helpful.

### Describe the solution you'd like

Add something like along the line:

- start a powershell console
- add gtk to the env path: $env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path
- execute the command: poetry shell
- start vscode by: code .
- put a breakpoint to __main__.py
- Start debugging -> module -> gaphor

**Comment by danyeaw** [comment]
@sz332 Thanks! Is this something you would like to contribute?

**Comment by sz332** [comment]
@danyeaw sure

**Comment by sz332** [comment]
@danyeaw I think this shall be closed....

**Comment by mengibin** [comment]
how to debug using vscode in mac?

**Comment by mengibin** [comment]
File "/Users/mengbin/Documents/study/sysml/gaphor/gaphor/__main__.py", line 8, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/mengbin/Documents/study/sysml/gaphor/gaphor/main.py", line 21, in main
    if args.profiler:
       ^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'profiler'
